### ISSUE TITLE
Failing checkin/ upload at API

### ISSUE THREAD

**Issue by andermy** [opensourceBIM/BIMserver#1009]
Bimserverversion: 1.5.147 installed by jar

Trying to upload an IFC-file through the API at the "/upload" url with a python script using the requests library. Using the following paramethers:

- token: generated from login function in API
- deserializerOid: 1048617 (Ifc2x3tc1 Step Streaming Deserializer)
- comment: "Randow text"
- poid: from GetAllProjects function in API
- merge: False
- sync: False
- topicId: from initiateCheckin function in API
- file: opening the duplexfile apartmentfile from "https://wrw.is/free-common-building-information-mode/" with python openfile. 

The request is composed with both the data and files field as viewed in the picture below.
![image](https://user-images.githubusercontent.com/1678943/61685827-1c7ba480-ad1e-11e9-8dcb-e118e72d7e7d.png)

I'm getting a 200 statuscode, but the response message is 'message': 'Unknown exception', '__type': 'ServerException'.  At the bimserver starter console I get the following message:

```
07:37:02 ERROR [qtp605686842-32]:                                                                                  (ServiceImpl.java:1078) 
java.lang.NullPointerException: null
	at org.bimserver.longaction.LongActionManager.start(LongActionManager.java:48)
	at org.bimserver.webservices.impl.ServiceImpl.checkinInternal(ServiceImpl.java:1185)
	at org.bimserver.webservices.impl.ServiceImpl.checkinInitiatedInternal(ServiceImpl.java:1063)
	at org.bimserver.webservices.impl.ServiceImpl.checkinInitiatedSync(ServiceImpl.java:1133)
	at org.bimserver.servlets.UploadServlet.service(UploadServlet.java:150)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:151)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:786)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:743)
	at java.lang.Thread.run(Unknown Source)
07:37:02 ERROR [qtp605686842-32]:                                                                                  (UploadServlet.java:183) 
org.bimserver.shared.exceptions.ServerException: null
	at org.bimserver.webservices.impl.ServiceImpl.checkinInitiatedInternal(ServiceImpl.java:1079)
	at org.bimserver.webservices.impl.ServiceImpl.checkinInitiatedSync(ServiceImpl.java:1133)
	at org.bimserver.servlets.UploadServlet.service(UploadServlet.java:150)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:151)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:786)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:743)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null
	at org.bimserver.longaction.LongActionManager.start(LongActionManager.java:48)
	at org.bimserver.webservices.impl.ServiceImpl.checkinInternal(ServiceImpl.java:1185)
	at org.bimserver.webservices.impl.ServiceImpl.checkinInitiatedInternal(ServiceImpl.java:1063)
	... 37 common frames omitted
```

Any idea for how or where to look further?

**Comment by hlg** [comment]
Maybe fixed.

https://github.com/opensourceBIM/BIMserver/blob/657c70673c39a7de658ff1d8b4a962cae427f8dc/BimServer/src/org/bimserver/longaction/LongActionManager.java#L47-L49

**Comment by hlg** [comment]
The given link to the Duplex model is not functional, but it may be found elsewhere for reproducing this issue and verifying solution.

**Comment by zaqifathis** [comment]
It fixed already.
here is the duplex link to test:
https://raw.githubusercontent.com/MadsHolten/BOT-Duplex-house/refs/heads/master/Model%20files/IFC/Duplex.ifc
