### ISSUE TITLE
Json with Geometry Serializer

### ISSUE THREAD

**Issue by RobertStancu** [opensourceBIM/BIMserver#1020]
Hi,

I've just started using the bim open source server. I am currently using the latest release (1.5.162) and I'm having trouble to obtain a similar query like in an older version (1.4.0 FINAL). Specifically when querying with the json with geometry deserializer I get null on every object (while on the 1.4.0 version i get the x,y coordinates).

**Comment by rubendel** [comment]
Assuming you mean 1.5.162. Assuming you mean geometry **serializer**. What do you mean with "you get null"? Could you please put a little more effort into your issue.

**Comment by RobertStancu** [comment]
Hi,

Please excuse me. Yes, I'm using version 1.5.162 and my problem is that, after loading an ifc file and querying from bimviews, for example, a wall object, with the json (with geometry) serializer I get this: {"_i":131663,"_u":"null","_r":0,"_t":"IfcWall","_s":0}. While doing the same query (for the same ifc file) in version 1.4.0 I get an output like this: {"_i":12807045295,"_t":"IfcCartesianPoint","_s":1,"Coordinates":[16.96599999999997,-0.2749999999999993,0.0],"CoordinatesAsString":["16.96599999999997","-0.2749999999999993","0."],"Dim":0}. 
I was interested in the coordinates information.  Please excuse me again if this feature is simply not available in this version or I'm not expressing myself correctly. 

Thank you in advance.

[Duplex_A_20110505.zip](https://github.com/opensourceBIM/BIMserver/files/3461674/Duplex_A_20110505.zip)

**Comment by RobertStancu** [comment]
Hi,

I provide more information about the error I get. On the query {
  "type": {
    "name": "IfcWall",
    "includeAllSubTypes": true
  },
  "includes": [
    "ifc4stdlib:ContainedInStructure",
    "ifc4stdlib:OwnerHistory",
    "ifc4stdlib:Representation",
    "ifc4stdlib:ObjectPlacement"
  ]
} 
The error I get is org.bimserver.BimserverDatabaseException: org.bimserver.database.queries.om.QueryException: Could not find 'ifc4stdlib' namespace in predefined queries
	at org.bimserver.database.actions.DownloadByNewJsonQueryDatabaseAction.execute(DownloadByNewJsonQueryDatabaseAction.java:308)
	at org.bimserver.database.actions.DownloadByNewJsonQueryDatabaseAction.execute(DownloadByNewJsonQueryDatabaseAction.java:73)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:743)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:735)
	at org.bimserver.longaction.LongDownloadOrCheckoutAction.executeAction(LongDownloadOrCheckoutAction.java:120)
	at org.bimserver.longaction.LongDownloadAction.execute(LongDownloadAction.java:49)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:813)
Caused by: org.bimserver.database.queries.om.QueryException: Could not find 'ifc4stdlib' namespace in predefined queries
	at org.bimserver.database.queries.om.JsonQueryObjectModelConverter.getDefineFromFile(JsonQueryObjectModelConverter.java:478)
	at org.bimserver.database.queries.om.JsonQueryObjectModelConverter.processSubInclude(JsonQueryObjectModelConverter.java:514)
	at org.bimserver.database.queries.om.JsonQueryObjectModelConverter.parseJsonQuery(JsonQueryObjectModelConverter.java:759)
	at org.bimserver.database.queries.om.JsonQueryObjectModelConverter.parseJson(JsonQueryObjectModelConverter.java:261)
	at org.bimserver.database.actions.DownloadByNewJsonQueryDatabaseAction.execute(DownloadByNewJsonQueryDatabaseAction.java:120)

**Comment by rubendel** [comment]
IFC4 std lib is called "ifc4-stdlib"

**Comment by RobertStancu** [comment]
Thank you so much, even with the stupid questions I had. If is it possible, could you explain to me how can I query  the same using java client? I've managed to connect and check in a file, but when trying to download I'm getting an error. This is the code 

``
public static void main(String[] args) throws BimServerClientException, Exception {
        try (JsonBimServerClientFactory factory = new JsonBimServerClientFactory("http://localhost:8082")){
             try (BimServerClient client = factory.create(new UsernamePasswordAuthenticationInfo("admin@localhost.com", "admin"))){
                 SProject project = client.getServiceInterface().getTopLevelProjectByName("Ultimate");
                 long roid = project.getRid();

                 SSerializerPluginConfiguration jsonSerializer = client.getServiceInterface().getSerializerByContentType("application/json");

                 Long download = client.getServiceInterface().download(Collections.singleton(roid), DefaultQueries.allAsString(), jsonSerializer.getOid(), true);
                 InputStream downloadData =  client.getDownloadData(download);
                 IOUtils.copy(downloadData, new FileOutputStream(Paths.get("C:\\Users\\robertalexandru.TRN\\Desktop\\output.json").toFile()));
             }
        }
    }
``

error I get is: 14:56:49 ERROR [ServiceInterface.download]:                                                                                  (LongAction.java:194) 
java.lang.NullPointerException: null
	at org.bimserver.longaction.LongStreamingDownloadAction.<init>(LongStreamingDownloadAction.java:118)
	at org.bimserver.webservices.impl.ServiceImpl.download(ServiceImpl.java:433)
	at org.bimserver.generated.ServiceInterfaceReflectortBYbJClvWKOd_1.callMethod(ServiceInterfaceReflectortBYbJClvWKOd_1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:223)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:77)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:66)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:868)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Thread.java:813)
