### ISSUE TITLE
bimserverjar-1.5.162.jar - Endpoint http://<bimserver>/soap12/AdminInterface?wsdl not reachable

### ISSUE THREAD

**Issue by Jo64** [opensourceBIM/BIMserver#1024]
Hi,
 I am using the 1.5.162 jar file and want to update the service references in a .NET solution.
The endpoints are not reachable.
e.q. http://<bimserver>/soap12/AdminInterface?wsdl

12:22:08 ERROR [qtp1082795132-50]:                                                                                  (RootServlet.java:214) 
java.lang.NullPointerException: null
	at org.bimserver.servlets.GenericWebServiceServlet.invoke(GenericWebServiceServlet.java:162)
	at org.bimserver.servlets.GenericWebServiceServlet.service(GenericWebServiceServlet.java:207)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:134)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
...

Thanks.

**Comment by rubendel** [comment]
SOAP support has not been tested lately. I currently see no projects in the future where I can justify spending time on this, so unless you can spend time on it yourself, you are probably better of using the JSON API.

**Comment by Jo64** [comment]
Yes you are right. It's better to use JSON API. I use the MetaInterface methods to query the structure. I use the MetaInterface methods. How can get all response types as json?

**Comment by hlg** [comment]
What do you mean by "response types"?

**Comment by hlg** [comment]
Maybe `MetaInterface.getServiceTypes` is what you are looking for. It was broken though until recently (https://github.com/opensourceBIM/BIMserver/issues/1179).
