### ISSUE TITLE
Error with checkin: java.lang.IllegalArgumentException: PlacesObject does not exist in IfcAxis2Placement3D

### ISSUE THREAD

**Issue by Moult** [opensourceBIM/BIMserver#1032]
See uploaded playground.ifc (uploaded as .txt to appease github).

[playground.txt](https://github.com/opensourceBIM/BIMserver/files/3550780/playground.txt)

I get the following error when I try to checkin this ifc:

```
java.lang.IllegalArgumentException: PlacesObject does not exist in IfcAxis2Placement3D
```

Full stack trace in log:

```
[ ... snip ...]
2019-08-28 13:49:23,515 INFO [http-nio-8080-exec-3] o.b.c.NewDiskCacheOutputStream [NewDiskCacheOutputStream.java:59] Renaming temp file a19ace6a42087343a33c2390d84da612.__tmp to a19ace6a42087343a33c2390d84da612
2019-08-28 13:49:24,224 INFO [http-nio-8080-exec-10] o.b.c.NewDiskCacheOutputStream [NewDiskCacheOutputStream.java:59] Renaming temp file c67b6f992cf781de3e7dc818cb2f5ea8.__tmp to c67b6f992cf781de3e7dc818cb2f5ea8
2019-08-28 13:49:24,234 INFO [http-nio-8080-exec-4] o.b.c.NewDiskCacheOutputStream [NewDiskCacheOutputStream.java:59] Renaming temp file e3252d925322ce9b2bf77671d6a85216.__tmp to e3252d925322ce9b2bf77671d6a85216
2019-08-28 13:49:24,938 INFO [http-nio-8080-exec-6] o.b.c.NewDiskCacheOutputStream [NewDiskCacheOutputStream.java:59] Renaming temp file 344c0a5344f9af16b03f4eeac7d9c037.__tmp to 344c0a5344f9af16b03f4eeac7d9c037
2019-08-28 13:49:24,952 INFO [http-nio-8080-exec-1] o.b.c.NewDiskCacheOutputStream [NewDiskCacheOutputStream.java:59] Renaming temp file 2ce1a1f856f230a6964e0bd68069b0f3.__tmp to 2ce1a1f856f230a6964e0bd68069b0f3
2019-08-28 13:52:25,060 ERROR [pool-1-thread-28] o.b.l.LongStreamingCheckinAction [LongStreamingCheckinAction.java:114]
org.bimserver.BimserverDatabaseException: java.lang.IllegalArgumentException: PlacesObject does not exist in IfcAxis2Placement3D
        at org.bimserver.database.queries.QueryObjectProvider.next(QueryObjectProvider.java:184)
        at org.bimserver.database.actions.GenericCheckinDatabaseAction.fixInverses(GenericCheckinDatabaseAction.java:417)
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:216)
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:83)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:743)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:720)
        at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:70)
        at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: PlacesObject does not exist in IfcAxis2Placement3D
        at org.bimserver.shared.HashMapVirtualObject.addUseForSerialization(HashMapVirtualObject.java:581)
        at org.bimserver.database.queries.FollowReferenceStackFrame.process(FollowReferenceStackFrame.java:102)
        at org.bimserver.database.queries.QueryObjectProvider.next(QueryObjectProvider.java:168)
        ... 12 common frames omitted
2019-08-28 13:52:25,060 ERROR [pool-1-thread-28] o.b.l.LongAction [LongAction.java:194]
org.bimserver.BimserverDatabaseException: java.lang.IllegalArgumentException: PlacesObject does not exist in IfcAxis2Placement3D
        at org.bimserver.database.queries.QueryObjectProvider.next(QueryObjectProvider.java:184)
        at org.bimserver.database.actions.GenericCheckinDatabaseAction.fixInverses(GenericCheckinDatabaseAction.java:417)
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:216)
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:83)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:743)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:720)
        at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:70)
        at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: PlacesObject does not exist in IfcAxis2Placement3D
        at org.bimserver.shared.HashMapVirtualObject.addUseForSerialization(HashMapVirtualObject.java:581)
        at org.bimserver.database.queries.FollowReferenceStackFrame.process(FollowReferenceStackFrame.java:102)
        at org.bimserver.database.queries.QueryObjectProvider.next(QueryObjectProvider.java:168)
        ... 12 common frames omitted
```

**Comment by rubendel** [comment]
This is simply an invalid IFC file, there is no `PlacesObject` field in `IfcAxis2Placement3D` in the Ifc2x3tc1 standard, kinda like the error message says. Please contact the developer of the software that exported this file.

Looking at the header of the IFC file, this file is created with an old version of IfcOpenShell, upgrading to a newer version _for exporting the ifc file_ will probably fix this

**Comment by hlg** [comment]
@Moult, it is about these two lines, if that helps:

    #9=IFCAXIS2PLACEMENT3D(#8,#7,#6);
    #2197=IFCANNOTATION('0k9Fa7_T17FQ1jnPXn6CdG',#5,'Line','',$,#9,#2196);

The 6th attribute in `IfcAnnotation` should be of type `IfcObjectPlacement` which would have the inverse attribute `PlacesObject`. However, `IfcAxis2Placement3D` is not a subtype of `IfcObjectPlacement` and thus can not be used in this place. As a side-effect it also does not have the expected inverse attribute.
