### ISSUE TITLE
Render is not visualized

### ISSUE THREAD

**Issue by mantinha** [opensourceBIM/BIMserver#1045]
Follows the scenario ..
Minimum arguments defined for execution by eclipse. Bimvie is required to run in development.
I am using Bimsurfer V1 as a necessity of Bimviews.
![image](https://user-images.githubusercontent.com/25441376/66948741-a68c8e00-f02b-11e9-8d84-41e1c63e998b.png)

Apparently I installed what is required to upload a .ifc file and render it and appear on the screen. The installation was done by BIMvie.ws
![image](https://user-images.githubusercontent.com/25441376/66948756-aee4c900-f02b-11e9-9c9e-ddb44d257263.png)

A test project was created and Checked out an ifc file using the "Ifc2x3tc1 (Streaming)" deserializer successfully.
I clicked the eye icon to enable 3D viewing and it appeared on the "Loading test123 ..." screen and remained so forever.
![image](https://user-images.githubusercontent.com/25441376/66948777-b6a46d80-f02b-11e9-8eb1-00c40fb49fad.png)

Apparently no errors occur in the log file.
-------------------------------------------------------------------------------
bimserver.log:
2019-10-16 15:29:34,592 INFO [main] o.b.BimServer [BimServer.java:248] Starting BIMserver (Windows 7, 1.8.0_111, 64bit, Xmx: 7,10 GB)
2019-10-16 15:29:35,879 INFO [main] o.b.BimServer [BimServer.java:251] SServiceMap Created
2019-10-16 15:29:36,662 INFO [main] o.b.BimServer [BimServer.java:254] JsonSocketReflectorFactory created
2019-10-16 15:29:36,863 INFO [main] o.b.BimServer [BimServer.java:257] ServerInfoManager created
2019-10-16 15:29:36,873 INFO [main] o.b.BimServer [BimServer.java:260] NotificationsManager created
2019-10-16 15:29:36,876 INFO [main] o.b.BimServer [BimServer.java:263] InternalServicesManager created
2019-10-16 15:29:36,877 INFO [main] o.b.BimServer [BimServer.java:266] PublicInterfaceFactory created
2019-10-16 15:29:37,313 INFO [main] o.b.BimServer [BimServer.java:295] Embedded webserver created
2019-10-16 15:29:37,313 INFO [main] o.b.BimServer [BimServer.java:298] Done with initial setup
2019-10-16 15:29:37,583 INFO [main] o.b.EmbeddedWebServer [EmbeddedWebServer.java:88] Modo Desenvolvedor: VERIFICADO
2019-10-16 15:29:37,601 INFO [main] o.b.BimServer [BimServer.java:336] Iniciando BIMserver: Version: 1.5.174-SNAPSHOT
2019-10-16 15:29:37,602 INFO [main] o.b.BimServer [BimServer.java:345] Usando "C:\Test010" como diretorio principal
2019-10-16 15:29:37,605 INFO [main] o.b.e.MetaDataManager [MetaDataManager.java:81] Metadados: nop: java.io.PrintStream@56f2bbea
2019-10-16 15:29:39,670 INFO [pool-2-thread-4] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing STORE with store
2019-10-16 15:29:39,670 INFO [pool-2-thread-3] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing GEOMETRY with geometry
2019-10-16 15:29:39,670 INFO [pool-2-thread-1] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing IFC2X3TC1 with ifc2x3tc1
2019-10-16 15:29:39,670 INFO [pool-2-thread-2] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing IFC4 with ifc4
2019-10-16 15:29:39,670 INFO [pool-2-thread-5] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing LOG with log
2019-10-16 15:29:41,347 INFO [main] o.b.d.b.BerkeleyKeyValueStore [BerkeleyKeyValueStore.java:98] No database directory found, creating "C:\Test010\database"
2019-10-16 15:29:41,348 INFO [main] o.b.d.b.BerkeleyKeyValueStore [BerkeleyKeyValueStore.java:101] Successfully created database dir "C:\Test010\database"
2019-10-16 15:29:41,937 INFO [main] o.b.BimServer [BimServer.java:693] Pasta "maven" criada
2019-10-16 15:29:41,940 INFO [main] o.b.d.Database [Database.java:106] Carregando pacotes: store
2019-10-16 15:29:41,940 INFO [main] o.b.d.Database [Database.java:108] Carregando pacotes: log
2019-10-16 15:29:41,941 INFO [main] o.b.d.Database [Database.java:110] Carregando pacotes: geometry
2019-10-16 15:29:42,005 INFO [main] o.b.d.Database [Database.java:149] Primeiro Registro no bd: CRIADO :8fc9af02-aa06-43db-8cc8-502097607a13
2019-10-16 15:30:54,398 INFO [main] o.b.d.b.BerkeleyKeyValueStore [BerkeleyKeyValueStore.java:87] Non-empty database directory found "C:\Test010\database"
2019-10-16 15:30:54,526 INFO [main] o.b.d.Database [Database.java:106] Carregando pacotes: store
2019-10-16 15:30:54,526 INFO [main] o.b.d.Database [Database.java:108] Carregando pacotes: log
2019-10-16 15:30:54,526 INFO [main] o.b.d.Database [Database.java:110] Carregando pacotes: geometry
2019-10-16 15:30:54,529 INFO [main] o.b.d.Database [Database.java:156] Registro no bd: CONSULTADO :8fc9af02-aa06-43db-8cc8-502097607a13
2019-10-16 15:30:55,101 INFO [main] o.b.BimServer [BimServer.java:729] Encriptando dados..
2019-10-16 15:30:55,102 INFO [main] o.b.BimServer [BimServer.java:822] Checking for stale records, this can take some time...
2019-10-16 15:30:55,102 INFO [main] o.b.BimServer [BimServer.java:825] Checando projetos..
2019-10-16 15:30:55,138 INFO [main] o.b.BimServer [BimServer.java:853] Done checking for stale records (35 ms)
2019-10-16 15:30:55,631 INFO [main] o.b.ServerInfoManager [ServerInfoManager.java:115] Changing server state to NOT_SETUP
2019-10-16 15:30:55,632 INFO [main] o.b.BimServer [BimServer.java:1123] Initializing database dependant logic...
2019-10-16 15:30:55,713 INFO [main] o.b.BimServer [BimServer.java:1291] Done initializing database dependant logic (80ms)
2019-10-16 15:30:57,119 INFO [main] o.b.ServerInfoManager [ServerInfoManager.java:115] Changing server state to RUNNING
2019-10-16 15:35:10,315 INFO [org.bimserver.PluginInterface.installPluginBundle] o.b.d.a.InstallPluginBundle [InstallPluginBundle.java:57] Installing plugin C:\Users\eng-5\.m2\repository (enhanced) org.opensourcebim.ifcplugins.0.0.90
2019-10-16 15:35:10,316 INFO [org.bimserver.PluginInterface.installPluginBundle] o.b.d.a.InstallPluginBundle [InstallPluginBundle.java:65] C:\Users\eng-5\.m2\repository (enhanced)
2019-10-16 15:35:10,316 INFO [org.bimserver.PluginInterface.installPluginBundle] o.b.d.a.InstallPluginBundle [InstallPluginBundle.java:70] 0.0.90
2019-10-16 15:35:41,817 INFO [org.bimserver.PluginInterface.installPluginBundle] o.b.d.a.InstallPluginBundle [InstallPluginBundle.java:57] Installing plugin C:\Users\eng-5\.m2\repository (enhanced) org.opensourcebim.ifcopenshellplugin.0.5.83
2019-10-16 15:35:41,818 INFO [org.bimserver.PluginInterface.installPluginBundle] o.b.d.a.InstallPluginBundle [InstallPluginBundle.java:65] C:\Users\eng-5\.m2\repository (enhanced)
2019-10-16 15:35:41,818 INFO [org.bimserver.PluginInterface.installPluginBundle] o.b.d.a.InstallPluginBundle [InstallPluginBundle.java:70] 0.5.83
2019-10-16 15:35:43,076 INFO [org.bimserver.PluginInterface.installPluginBundle] o.i.IfcOpenShellEnginePlugin [IfcOpenShellEnginePlugin.java:101] Using overruled system setting for commit sha
2019-10-16 15:35:43,084 INFO [org.bimserver.PluginInterface.installPluginBundle] o.i.IfcGeomServerClient [IfcGeomServerClient.java:186] Downloading from https://s3.amazonaws.com/ifcopenshell-builds/IfcGeomServer-v0.6.0-b4ce5be-win64.zip
2019-10-16 15:35:43,085 INFO [org.bimserver.PluginInterface.installPluginBundle] o.i.IfcGeomServerClient [IfcGeomServerClient.java:188] Unzipping to C:\Test010\tmp\org.opensourcebim.ifcopenshellplugin\IfcGeomServer-v0.6.0-b4ce5be-win64.exe
2019-10-16 15:35:43,811 INFO [org.bimserver.PluginInterface.installPluginBundle] o.i.IfcGeomServerClient [IfcGeomServerClient.java:195] IfcOpenShell Last Modified: Fri, 05 Jul 2019 03:01:37 GMT
2019-10-16 15:35:46,005 INFO [org.bimserver.PluginInterface.installPluginBundle] o.i.IfcOpenShellEnginePlugin [IfcOpenShellEnginePlugin.java:109] Using C:\Test010\tmp\org.opensourcebim.ifcopenshellplugin\IfcGeomServer-v0.6.0-b4ce5be-win64.exe
2019-10-16 15:35:46,352 INFO [org.bimserver.PluginInterface.installPluginBundle] o.i.IfcOpenShellEnginePlugin [IfcOpenShellEnginePlugin.java:101] Using overruled system setting for commit sha
2019-10-16 15:35:46,453 INFO [org.bimserver.PluginInterface.installPluginBundle] o.i.IfcOpenShellEnginePlugin [IfcOpenShellEnginePlugin.java:109] Using C:\Test010\tmp\org.opensourcebim.ifcopenshellplugin\IfcGeomServer-v0.6.0-b4ce5be-win64.exe
2019-10-16 15:35:46,454 INFO [org.bimserver.PluginInterface.installPluginBundle] o.b.BimServer [BimServer.java:1025] Setting default render engine for user system to IfcOpenShell
2019-10-16 15:35:46,455 INFO [org.bimserver.PluginInterface.installPluginBundle] o.b.BimServer [BimServer.java:1025] Setting default render engine for user admin@bimserver.org to IfcOpenShell
2019-10-16 15:36:06,833 INFO [org.bimserver.PluginInterface.installPluginBundle] o.b.d.a.InstallPluginBundle [InstallPluginBundle.java:57] Installing plugin C:\Users\eng-5\.m2\repository (enhanced) org.opensourcebim.binaryserializers.0.0.85
2019-10-16 15:36:06,834 INFO [org.bimserver.PluginInterface.installPluginBundle] o.b.d.a.InstallPluginBundle [InstallPluginBundle.java:65] C:\Users\eng-5\.m2\repository (enhanced)
2019-10-16 15:36:06,834 INFO [org.bimserver.PluginInterface.installPluginBundle] o.b.d.a.InstallPluginBundle [InstallPluginBundle.java:70] 0.0.85
2019-10-16 15:38:08,486 INFO [pool-1-thread-1] o.b.r.p.CommonsRenderEnginePool [CommonsRenderEnginePool.java:37] Pool size: 7
2019-10-16 15:38:13,210 INFO [pool-1-thread-1] o.b.g.StreamingGeometryGenerator [StreamingGeometryGenerator.java:640] Rendertime: 4.73s, Reused (by hash): 0 B, Reused (by transformation): 0 B, Reused (by mapping): 0 B, Total: 577,52 KB, Final: 577,52 KB

------------------------------------------------------------------------------------------
Google Chrome Version 77.0.3865.120 64 bits
------------------------------------------------------------------------------------------
Is it possible to solve this problem using Bimsurfer V1?

**Comment by rubendel** [comment]
GeometryLoader.js says: "Unimplemented version", this indicates a mismatch between BIMsurfer and BinarySerializers. If you run from git versions, make sure _all_ plugins are being run from the github versions. The plugins work together and communicatie with each other, so using "random" versions most of the time won't work.

**Comment by mantinha** [comment]
Certo. Fiz a inclusão do plugin BinarySerializers, atualizei o BIMsurfer V1 para a mais atual e alterei os arquivos do Bimviews no workspace para funcionar com o novo Bimsurfer.

![image](https://user-images.githubusercontent.com/25441376/67203727-3e023000-f3e2-11e9-9eaf-07803d97d2cf.png)

**Comment by bjsolla** [comment]
Hi, I configured BimServer following the installation instructions via wiki (https://github.com/opensourceBIM/BIMserver/wiki/Eclipse),
but when I try to visualize in 3d an ifc file on BIMvie.ws the loading remains
![BIMvie](https://user-images.githubusercontent.com/66369004/86568108-aabb5b80-bf6c-11ea-8209-3a1f9a7ef24d.jpg)
, and the eclipse console gives me this error
Logging to C:\Hbim3\BIMserver\BimServerJar\tmptestdata\home\logs\bimserver.log
09:20:38 INFO  [main]: Starting BIMserver (Windows 10, 1.8.0_191, 64bit, Xmx: 14,89 GB)                 (BimServer.java:248) 
09:20:42 INFO  [main]: Version: 1.5.183-SNAPSHOT                                                        (BimServer.java:336) 
09:20:42 INFO  [main]: Using "tmptestdata\home" as homedir                                              (BimServer.java:345) 
09:20:47 INFO  [main]: No database directory found, creating "tmptestdata\home\database"                (BerkeleyKeyValueStore.java:98) 
09:20:47 INFO  [main]: Successfully created database dir "tmptestdata\home\database"                    (BerkeleyKeyValueStore.java:101) 
09:20:56 INFO  [main]: Non-empty database directory found "tmptestdata\home\database"                   (BerkeleyKeyValueStore.java:87) 
09:20:57 INFO  [main]: Checking for stale records, this can take some time...                           (BimServer.java:813) 
09:20:57 INFO  [main]: Done checking for stale records (17 ms)                                          (BimServer.java:843) 
09:20:58 INFO  [main]: Changing server state to NOT_SETUP                                               (ServerInfoManager.java:116) 
09:20:58 INFO  [main]: Initializing database dependant logic...                                         (BimServer.java:1113) 
09:20:58 INFO  [main]: Done initializing database dependant logic (37ms)                                (BimServer.java:1284) 
09:20:59 INFO  [main]: Using overruled system setting for commit sha                                    (IfcOpenShellEnginePlugin.java:101) 
09:20:59 INFO  [main]: Downloading from https://s3.amazonaws.com/ifcopenshell-builds/IfcGeomServer-v0.6.0-b4ce5be-win64.zip (IfcGeomServerClient.java:186) 
09:20:59 INFO  [main]: Unzipping to tmptestdata\home\tmp\org.opensourcebim.ifcopenshellplugin\IfcGeomServer-v0.6.0-b4ce5be-win64.exe (IfcGeomServerClient.java:188) 
09:21:00 INFO  [main]: IfcOpenShell Last Modified: Fri, 05 Jul 2019 03:01:37 GMT                        (IfcGeomServerClient.java:195) 
09:21:02 INFO  [main]: Using tmptestdata\home\tmp\org.opensourcebim.ifcopenshellplugin\IfcGeomServer-v0.6.0-b4ce5be-win64.exe (IfcOpenShellEnginePlugin.java:109) 
09:21:02 INFO  [main]: Setting default render engine for user system to IfcOpenShell                    (BimServer.java:1015) 
09:21:03 INFO  [main]: Setting default render engine for user admin@bimserver.org to IfcOpenShell       (BimServer.java:1015) 
09:21:03 INFO  [main]: Changing server state to RUNNING                                                 (ServerInfoManager.java:116) 
09:35:32 INFO  [pool-1-thread-1]: Pool size: 4                                                                     (CommonsRenderEnginePool.java:37) 
09:35:49 INFO  [pool-1-thread-1]: Rendertime: 17.238s, Reused (by hash): 380,92 KB, Reused (by transformation): 0 B, Reused (by mapping): 0 B, Total: 1,41 MB, Final: 1,04 MB (StreamingGeometryGenerator.java:655) 
09:35:53 ERROR [pool-1-thread-2]:                                                                                  (BimServer.java:240) 
java.lang.NullPointerException: null
	at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer.writeGeometryData(BinaryGeometryMessagingStreamingSerializer.java:974)
	at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer.writeData(BinaryGeometryMessagingStreamingSerializer.java:771)
	at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer.writeMessage(BinaryGeometryMessagingStreamingSerializer.java:275)
	at org.bimserver.servlets.Streamer$1.run(Streamer.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
How can I solve the problem?
Thank you
