### ISSUE TITLE
LowLevelInterface.getDataObjectByOid really slow with BIMServer 1.5.172

### ISSUE THREAD

**Issue by GiacomoManzoli** [opensourceBIM/BIMserver#1058]
**Describe the bug**
The service `LowLevelInterface.getDataObjectByOid` became extremly slow with BIMServer 1.5.172.

**To Reproduce**
1. Open the Console application
2. Login
3. Make a call to  `LowLevelInterface.getDataObjectByOid` with any data.

**Expected behavior**
The call works, but it's slow and it logs the error:
```
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: Potential for readonly database session                                          (DatabaseSession.java:167) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: Owner: org.bimserver.database.DatabaseSession@44485e00                           (DatabaseSession.java:168) 
```

**Screenshots**
Whole log:
```
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: Potential for readonly database session                                          (DatabaseSession.java:167) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: Owner: org.bimserver.database.DatabaseSession@44485e00                           (DatabaseSession.java:168) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at java.lang.Thread.getStackTrace(Thread.java:1559)                             (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.bimserver.database.DatabaseSession.<init>(DatabaseSession.java:132)      (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.bimserver.database.Database.createSession(Database.java:379)             (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.bimserver.database.Database.createSession(Database.java:371)             (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.bimserver.webservices.impl.LowLevelServiceImpl.getDataObjectByOid(LowLevelServiceImpl.java:723) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.bimserver.generated.LowLevelInterfaceReflectorRymMUEjbhYDW_1.callMethod(LowLevelInterfaceReflectorRymMUEjbhYDW_1.java) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)                   (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)         (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.bimserver.JsonHandler.execute(JsonHandler.java:77)                       (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:66)        (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)             (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)                 (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:868)       (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)   (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)  (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)    (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.server.Server.handle(Server.java:505)                      (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)            (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)  (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)            (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)         (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917) (DatabaseSession.java:171) 
10:46:59 INFO  [LowLevelInterface.getDataObjectByOid]: 	at java.lang.Thread.run(Thread.java:748)                                        (DatabaseSession.java:171) 
```

**Additional context**
With the BIMServer 1.5.150 the call works fine. I've got an algorithm that loads serveral data with this calls and the average running time went from 200ms to 8seconds. (I know that i should use the `query` interface and i'm starting to use it, but the interface switch requires several changes).

**Comment by rubendel** [comment]
This stacktrace is not actually an error (LOG level is INFO), it's only there to remind developers that a choice has to be made for this specific use of DatabaseSession on whether it's possibly writing. I can imagine that this becomes slow because of the logging, but only when you are calling this method a gazillion times. Are you?

I'll checkin a fix that gets rid of the logging today as I am working on these calls anyways.

**Comment by rubendel** [comment]
https://github.com/opensourceBIM/BIMserver/commit/0b2490bc1077e45dc8f99b31997c5bd3ec307689

Let me know if it's still slow, then it must be something else.

**Comment by GiacomoManzoli** [comment]
> This stacktrace is not actually an error (LOG level is INFO), it's only there to remind developers that a choice has to be made for this specific use of DatabaseSession on whether it's possibly writing. I can imagine that this becomes slow because of the logging, but only when you are calling this method a gazillion times. Are you?
> 
> I'll checkin a fix that gets rid of the logging today as I am working on these calls anyways.

I'm calling it several times, the test case i'm using makes 112 calls.

> 0b2490b
> 
> Let me know if it's still slow, then it must be something else.

First i need to figure out how to build since my experience with Java and Maven is really limited

**Comment by rubendel** [comment]
Hmm 112 is not much, there is probably another reason then why it's slow. I'll have a look at that later.

I'll try to make a new build this week.

**Comment by GiacomoManzoli** [comment]
Ok thank you!
Meanwhile i'm configuring Eclipse with the Team Project file taken from the wiki. If i manage to make it work i'll update the issue.

**Comment by GiacomoManzoli** [comment]
I've tried `1.5.180` and it seems to be faster. Next week i'll do a more accurate test on other machines.
