### ISSUE TITLE
download ifc via json api

### ISSUE THREAD

**Issue by DaJansenGit** [opensourceBIM/BIMserver#1059]
I'm trying to download a ifc file from the bim server via the inbuild json api. Downloading via Bimvie.ws works fine, but downloading via api does not. I followed the tutorial in the wiki (https://github.com/opensourceBIM/BIMserver/wiki/Downloading-models) and tried both, the console app and url get via a json in python. I get the topicId but then when I do a the query with the new topicId nothing happens. The server gives the following feedback:

> org.bimserver.shared.exceptions.UserException: No data found for topicId 312
        at org.bimserver.webservices.impl.ServiceImpl.getDownloadData(ServiceImpl.java:356)
        at org.bimserver.servlets.DownloadServlet.service(DownloadServlet.java:173)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:155)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
4527995 [http-nio-8080-exec-1] ERROR org.bimserver.servlets.RootServlet -
java.lang.IllegalStateException: getOutputStream() has already been called for this response
        at org.apache.catalina.connector.Response.getWriter(Response.java:624)
        at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:211)
        at org.bimserver.servlets.DownloadServlet.service(DownloadServlet.java:279)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:155)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

The url is correct, I double counterchecked the URL with the result of what Bimvie.ws create when you do a query. Any idea why this is not working?

**Comment by rubendel** [comment]
Which call did you use to get the topicId? Which version of BIMserver are you using?

**Comment by DaJansenGit** [comment]
I'm using BIMServer version **1.5.150** .
Regarding the topicId call I tried multiple ones, because I was not sure if the query is optional or necessary. I tried:

```
{
  "token": "1021d81f92c7bf6bd2288a9fd96c70049a28f8cb5c9033f36a1337c0a266ff826a1acf7411d42df3f248cb67f053fa52",
  "request": {
    "interface": "ServiceInterface", 
    "method": "download", 
    "parameters": {
      "roids": ["11665411"],
      "query": "",
      "serializerOid": 786470,
      "sync": "false"
    }
  }
}
```
as well as

``` 
{
        "token":
            token,
        "request": {
            "interface": "ServiceInterface",
            "method": "download",
            "parameters": {
                "roids": roids,
                # "query": {
                #     "type": {
                #         "name": "IfcProduct",
                #         "includeAllSubTypes": True
                #     },
                # },
                "query":
                    'InF1ZXJ5IjogewogICAgInR5cGUiOiB7CiAgICAgICAgIm5hbWUiOiAiSWZjUHJvZHVjdCIsCiAgICAgICAgImluY2x1ZGVBbGxTdWJUeXBlcyI6IFRydWUKICAgICAgICB9LAogICAgfSwK',
                "serializerOid": serializerid,
                "sync": "false"
            }
        }
    }
```

where the query is the base64 encode for:
```
             "query": {
                    "type": {
                        "name": "IfcProduct",
                        "includeAllSubTypes": True
                    },
                },
```
I get a topicId returned which increases by one with every request but the can't download any file via this links, which is logical because the server says it's a wrong topicId but I don't get why... Thanks for any help!

**Comment by rubendel** [comment]
Hmm maybe some documentation is incorrect, but I don't think the query needs to be base64 encoded, that would only make sense for binary data. Could you try just json encoding the query?

**Comment by DaJansenGit** [comment]
ok, I tried the original query as json. I get the following error:
`ConnectionError: Missing __type field in {"type":{"name":"IfcProduct","includeAllSubTypes":true}} `
But type argument is there. 
I got the query from the implemented Bimvie.ws querys where they work fine.

**Comment by rubendel** [comment]
Please see https://github.com/opensourceBIM/BIMserver/issues/1055#issuecomment-553778949.

The query needs be a String, you'll have to JSON encode it to make sure double quotes are escaped.

**Comment by DaJansenGit** [comment]
With a string it works. The documentation seems to be incorrect at this point. Thank you for your help, you are doing great work with the BimServer!
