### ISSUE TITLE
BIMServer Starter Jar 1.5.178 fail to start the server

### ISSUE THREAD

**Issue by GiacomoManzoli** [opensourceBIM/BIMserver#1065]
**Describe the bug**
BIMServer Starter Jar 1.5.178 fail to start the server

**To Reproduce**
Start the server 1.5.178 from the jar file.

**Error log**
```
OS: Mac OS X
Main class: org.bimserver.JarBimServer

Commands:
java
-Xmx4294m
-Xss1024k
-Dorg.apache.cxf.Logger=org.apache.cxf.common.logging.Slf4jLogger
-classpath
.:lib:lib/cxf-rt-ws-addr-3.3.2.jar:lib/javax.ws.rs-api-2.1-m02.jar:lib/sdo-eclipselink-plugin-2.3.2.jar:lib/je-7.5.11.jar:lib/quartz-2.3.0.jar:lib/aether-connector-basic-1.0.2.v20150114.jar:lib/org.eclipse.core.variables-3.4.600.jar:lib/xmlbeans-2.6.0.jar:lib/jakarta.xml.bind-api-2.3.2.jar:lib/kryo-serializers-0.42.jar:lib/aether-api-1.0.2.v20150114.jar:lib/commons-logging-1.2.jar:lib/org.eclipse.equinox.registry-3.8.500.jar:lib/gmbal-4.0.0.jar:lib/javax.websocket-api-1.1.jar:lib/pfl-asm-4.0.1.jar:lib/jaxb-runtime-2.3.2.jar:lib/shared-1.5.178.jar:lib/plexus-utils-3.0.22.jar:lib/cxf-rt-frontend-simple-3.3.2.jar:lib/minlog-1.3.0.jar:lib/jetty-alpn-java-client-9.4.19.v20190610.jar:lib/ant-launcher-1.10.5.jar:lib/plexus-interpolation-1.21.jar:lib/codemodel-2.3.2.jar:lib/activation-1.1.jar:lib/slf4j-api-1.7.22.jar:lib/aether-util-1.0.2.v20150114.jar:lib/org.eclipse.persistence.core-2.7.4.jar:lib/maven-model-3.3.9.jar:lib/commons-cli-1.3.1.jar:lib/guava-26.0-jre.jar:lib/org.apache.oltu.oauth2.common-1.0.2.jar:lib/org.eclipse.core.resources-3.13.500.jar:lib/woodstox-core-5.0.3.jar:lib/aopalliance-1.0.jar:lib/cxf-rt-ws-policy-3.3.2.jar:lib/FastInfoset-1.2.16.jar:lib/org.eclipse.jdt.core-3.19.0.jar:lib/policy-2.7.6.jar:lib/org.eclipse.core.resources-3.8.101.v20130717-0806.jar:lib/maven-settings-3.3.9.jar:lib/javax.json-1.0.4.jar:lib/pfl-basic-4.0.1.jar:lib/org.eclipse.core.expressions-3.6.500.jar:lib/relaxng-datatype-2.3.2.jar:lib/jetty-jndi-9.4.19.v20190610.jar:lib/antlr4-runtime-4.7.1.jar:lib/pfl-tf-4.0.1.jar:lib/protobuf-java-2.6.1.jar:lib/jetty-alpn-client-9.4.19.v20190610.jar:lib/jersey-common-2.26-b01.jar:lib/checker-qual-2.5.2.jar:lib/logback-core-1.1.9.jar:lib/httpcore-4.4.11.jar:lib/javax-websocket-server-impl-9.4.19.v20190610.jar:lib/pfl-dynamic-4.0.1.jar:lib/maven-model-builder-3.3.9.jar:lib/org.apache.oltu.oauth2.dynamicreg.server-1.0.2.jar:lib/ant-1.10.5.jar:lib/jetty-servlet-9.4.19.v20190610.jar:lib/jetty-plus-9.4.19.v20190610.jar:lib/junit-4.12.jar:lib/json-20140107.jar:lib/plexus-cipher-1.4.jar:lib/cxf-rt-transports-http-3.3.2.jar:lib/antlr-runtime-3.5.2.jar:lib/jakarta.mail-api-1.6.3.jar:lib/kryo-5.0.0-RC1.jar:lib/jakarta.persistence-api-2.2.2.jar:lib/org.eclipse.persistence.sdo-2.7.4.jar:lib/release-documentation-2.3.2-docbook.zip:lib/websocket-server-9.4.19.v20190610.jar:lib/plexus-sec-dispatcher-1.3.jar:lib/error_prone_annotations-2.1.3.jar:lib/cdi-api-1.0.jar:lib/objenesis-2.6.jar:lib/commons-collections-20040616.jar:lib/javax.servlet-api-3.1.0.jar:lib/commons-fileupload-1.4.jar:lib/maven-core-3.3.9.jar:lib/rome-utils-1.7.1.jar:lib/aether-transport-file-1.0.2.v20150114.jar:lib/antlr-complete-3.5.2.jar:lib/jetty-security-9.4.19.v20190610.jar:lib/org.eclipse.debug.core-3.14.0.jar:lib/validation-api-1.1.0.Final.jar:lib/ST4-4.0.8.jar:lib/hk2-api-2.5.0-b31.jar:lib/cxf-rt-javascript-3.3.1.jar:lib/httpclient-4.5.7.jar:lib/guice-4.0-no_aop.jar:lib/jersey-container-servlet-core-2.26-b01.jar:lib/jackson-annotations-2.9.0.jar:lib/jettison-1.3.8.jar:lib/cors-filter-2.5.jar:lib/wsdl4j-1.6.3.jar:lib/jetty-xml-9.4.19.v20190610.jar:lib/aether-impl-1.0.2.v20150114.jar:lib/cqengine-3.0.0.jar:lib/jetty-client-9.4.19.v20190610.jar:lib/javax.annotation-api-1.2.jar:lib/stax-ex-1.8.1.jar:lib/maven-builder-support-3.3.9.jar:lib/org.eclipse.osgi-3.15.0.jar:lib/commons-codec-1.9.jar:lib/org.eclipse.emf.codegen.ecore-2.15.0.jar:lib/jaxws-ri-2.3.2.pom:lib/xmlschema-core-2.2.4.jar:lib/commonj.sdo-2.1.1.jar:lib/javax-websocket-client-impl-9.4.19.v20190610.jar:lib/java-getopt-1.0.13.jar:lib/org.eclipse.core.commands-3.9.500.jar:lib/jersey-client-2.26-b01.jar:lib/ha-api-3.1.12.jar:lib/jetty-http-9.4.19.v20190610.jar:lib/jersey-server-2.26-b01.jar:lib/org.apache.oltu.oauth2.client-1.0.2.jar:lib/jaxws-tools-2.3.2.jar:lib/bimserverclientlib-1.5.178.jar:lib/xsom-2.3.2.jar:lib/org.eclipse.emf.codegen-2.14.0.jar:lib/org.eclipse.persistence.moxy-2.7.4.jar:lib/jersey-guava-2.26-b01.jar:lib/jcl-over-slf4j-1.6.2.jar:lib/xml-resolver-1.2.jar:lib/org.eclipse.core.contenttype-3.7.400.jar:lib/mimepull-1.9.11.jar:lib/org.apache.oltu.oauth2.resourceserver-1.0.2.jar:lib/asm-7.1.jar:lib/cxf-rt-bindings-xml-3.3.2.jar:lib/websocket-api-9.4.19.v20190610.jar:lib/jakarta.activation-api-1.2.1.jar:lib/org.eclipse.text-3.9.0.jar:lib/osgi-resource-locator-1.0.1.jar:lib/stax2-api-3.1.4.jar:lib/neethi-3.1.1.jar:lib/asm-commons-7.1.jar:lib/websocket-servlet-9.4.19.v20190610.jar:lib/c3p0-0.9.5.2.jar:lib/velocity-1.7.jar:lib/hk2-utils-2.5.0-b31.jar:lib/jetty-webapp-9.4.19.v20190610.jar:lib/org.eclipse.jdt.debug-3.13.100.jar:lib/dtd-parser-1.4.1.jar:lib/management-api-3.2.1.jar:lib/cxf-core-3.3.1.jar:lib/org.eclipse.equinox.preferences-3.7.500.jar:lib/j2objc-annotations-1.1.jar:lib/jul-to-slf4j-1.7.22.jar:lib/org.apache.oltu.oauth2.dynamicreg.common-1.0.2.jar:lib/org.eclipse.emf.ecore.xmi-2.15.0.jar:lib/javax.inject-2.5.0-b31.jar:lib/javax.websocket-client-api-1.0.jar:lib/org.apache.oltu.oauth2.authzserver-1.0.2.jar:lib/bcf-0.0.35.jar:lib/bdb-1.5.178.jar:lib/commons-io-2.2.jar:lib/java-property-utils-1.9.1.jar:lib/jakarta.xml.ws-api-2.3.2.jar:lib/rngom-2.3.2.jar:lib/maven-settings-builder-3.3.9.jar:lib/asm-tree-7.1.jar:lib/org.eclipse.emf.ecore-2.15.0.jar:lib/cxf-rt-bindings-soap-3.3.1.jar:lib/hamcrest-core-1.3.jar:lib/reflectasm-1.11.7.jar:lib/rome-1.7.1.jar:lib/jakarta.annotation-api-1.3.4.jar:lib/jersey-container-servlet-2.26-b01.jar:lib/HikariCP-java6-2.3.13.jar:lib/buildingsmartlibrary-1.0.13.jar:lib/stringtemplate-3.2.1.jar:lib/cxf-rt-frontend-jaxws-3.3.2.jar:lib/aether-spi-1.0.2.v20150114.jar:lib/org.eclipse.sisu.inject-0.3.2.jar:lib/maven-plugin-api-3.3.9.jar:lib/jaxb-xjc-2.3.2.jar:lib/jetty-server-9.4.19.v20190610.jar:lib/jetty-util-9.4.19.v20190610.jar:lib/antlr-3.5.2.jar:lib/org.eclipse.equinox.common-3.10.500.jar:lib/istack-commons-runtime-3.0.8.jar:lib/org.apache.oltu.oauth2.dynamicreg.client-1.0.2.jar:lib/plexus-component-annotations-1.6.jar:lib/stax-api-1.0.1.jar:lib/jakarta.jws-api-1.1.1.jar:lib/websocket-common-9.4.19.v20190610.jar:lib/org.eclipse.jdt.core-3.14.0.v20171206-0802.jar:lib/commons-lang-2.4.jar:lib/maven-repository-metadata-3.3.9.jar:lib/hk2-locator-2.5.0-b31.jar:lib/animal-sniffer-annotations-1.14.jar:lib/asm-analysis-7.1.jar:lib/jersey-media-jaxb-2.26-b01.jar:lib/typetools-0.5.0.jar:lib/aether-transport-http-1.0.2.v20150114.jar:lib/aopalliance-repackaged-2.5.0-b31.jar:lib/org.eclipse.core.runtime-3.16.0.jar:lib/httpmime-4.5.7.jar:lib/org.eclipse.core.filesystem-1.7.500.jar:lib/concurrent-trees-2.6.1.jar:lib/org.eclipse.persistence.asm-2.7.4.jar:lib/jaxws-rt-2.3.2.jar:lib/gson-2.5.jar:lib/antlr-2.7.7.jar:lib/javassist-3.24.1-GA.jar:lib/jdom2-2.0.6.jar:lib/plexus-classworlds-2.5.2.jar:lib/org.eclipse.core.jobs-3.10.500.jar:lib/javax.mail-1.6.2.jar:lib/pluginbase-1.5.178.jar:lib/jackson-databind-2.9.7.jar:lib/jetty-annotations-9.4.19.v20190610.jar:lib/jackson-core-2.9.7.jar:lib/jsr305-3.0.2.jar:lib/org.eclipse.sisu.plexus-0.3.2.jar:lib/jaxb-jxc-2.3.2.jar:lib/gunit-3.5.2.jar:lib/sqlite-jdbc-3.23.1.jar:lib/saaj-impl-1.5.1.jar:lib/txw2-2.3.2.jar:lib/websocket-client-9.4.19.v20190610.jar:lib/jaxws-eclipselink-plugin-2.3.2.jar:lib/jakarta.xml.soap-api-1.4.1.jar:lib/bimserver-1.5.178.jar:lib/commons-lang3-3.4.jar:lib/cxf-rt-wsdl-3.3.1.jar:lib/pfl-tf-tools-4.0.1.jar:lib/javax.inject-1.jar:lib/cxf-rt-databinding-jaxb-3.3.1.jar:lib/org.eclipse.jdt.launching-3.15.0.jar:lib/maven-aether-provider-3.3.9.jar:lib/mchange-commons-java-0.2.11.jar:lib/istack-commons-tools-3.0.8.jar:lib/fastutil-8.2.3.jar:lib/streambuffer-1.5.7.jar:lib/pfl-basic-tools-4.0.1.jar:lib/jsr250-api-1.0.jar:lib/maven-artifact-3.3.9.jar:lib/samples-2.3.2.zip:lib/org.eclipse.emf.common-2.15.0.jar:lib/jetty-io-9.4.19.v20190610.jar:lib/logback-classic-1.1.9.jar:lib/org.eclipse.equinox.app-1.4.300.jar:lib/commons-pool2-2.4.2.jar
org.bimserver.JarBimServer
address=localhost
port=8082
homedir=/Users/gmanzoli/888sp/BS/server15178/home
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)
00:07:41 INFO  [main]: Starting BIMserver (Mac OS X, 1.8.0_112, 64bit, Xmx: 3,73 GB)                    (BimServer.java:248) 
Logging to /Users/gmanzoli/888sp/BS/server15178/home/logs/bimserver.log
00:07:44 INFO  [main]: Version: 1.5.178                                                                 (BimServer.java:336) 
00:07:44 INFO  [main]: Using "/Users/gmanzoli/888sp/BS/server15178/home" as homedir                     (BimServer.java:345) 
00:07:49 INFO  [main]: No database directory found, creating "/Users/gmanzoli/888sp/BS/server15178/home/database" (BerkeleyKeyValueStore.java:98) 
00:07:49 INFO  [main]: Successfully created database dir "/Users/gmanzoli/888sp/BS/server15178/home/database" (BerkeleyKeyValueStore.java:101) 
00:07:52 INFO  [main]: Non-empty database directory found "/Users/gmanzoli/888sp/BS/server15178/home/database" (BerkeleyKeyValueStore.java:87) 
00:07:53 INFO  [main]: Checking for stale records, this can take some time...                           (BimServer.java:817) 
00:07:53 INFO  [main]: Done checking for stale records (25 ms)                                          (BimServer.java:847) 
00:07:53 ERROR [main]:                                                                                  (ProtocolBuffersMetaData.java:173) 
com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:89)
	at com.google.protobuf.CodedInputStream.readTag(CodedInputStream.java:158)
	at com.google.protobuf.DescriptorProtos$FieldDescriptorProto.<init>(DescriptorProtos.java:7827)
	at com.google.protobuf.DescriptorProtos$FieldDescriptorProto.<init>(DescriptorProtos.java:7790)
	at com.google.protobuf.DescriptorProtos$FieldDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:7938)
	at com.google.protobuf.DescriptorProtos$FieldDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:7933)
	at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:495)
	at com.google.protobuf.DescriptorProtos$DescriptorProto.<init>(DescriptorProtos.java:4461)
	at com.google.protobuf.DescriptorProtos$DescriptorProto.<init>(DescriptorProtos.java:4401)
	at com.google.protobuf.DescriptorProtos$DescriptorProto$1.parsePartialFrom(DescriptorProtos.java:4565)
	at com.google.protobuf.DescriptorProtos$DescriptorProto$1.parsePartialFrom(DescriptorProtos.java:4560)
	at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:495)
	at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<init>(DescriptorProtos.java:1098)
	at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<init>(DescriptorProtos.java:1023)
	at com.google.protobuf.DescriptorProtos$FileDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:1244)
	at com.google.protobuf.DescriptorProtos$FileDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:1239)
	at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:495)
	at com.google.protobuf.DescriptorProtos$FileDescriptorSet.<init>(DescriptorProtos.java:101)
	at com.google.protobuf.DescriptorProtos$FileDescriptorSet.<init>(DescriptorProtos.java:47)
	at com.google.protobuf.DescriptorProtos$FileDescriptorSet$1.parsePartialFrom(DescriptorProtos.java:137)
	at com.google.protobuf.DescriptorProtos$FileDescriptorSet$1.parsePartialFrom(DescriptorProtos.java:132)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:192)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:215)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at com.google.protobuf.DescriptorProtos$FileDescriptorSet.parseFrom(DescriptorProtos.java:254)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:151)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:187)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:223)
	at org.bimserver.BimServer.start(BimServer.java:732)
	at org.bimserver.JarBimServer.start(JarBimServer.java:160)
	at org.bimserver.JarBimServer.main(JarBimServer.java:79)
00:07:53 ERROR [main]: Dependency ServiceInterface.proto of NewServicesInterface.proto not found        (ProtocolBuffersMetaData.java:159) 
00:07:53 ERROR [main]:                                                                                  (BimServer.java:811) 
java.lang.NullPointerException: null
	at com.google.protobuf.Descriptors$DescriptorPool.importPublicDependencies(Descriptors.java:1849)
	at com.google.protobuf.Descriptors$DescriptorPool.<init>(Descriptors.java:1832)
	at com.google.protobuf.Descriptors$FileDescriptor.buildFrom(Descriptors.java:266)
	at com.google.protobuf.Descriptors$FileDescriptor.buildFrom(Descriptors.java:235)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:163)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:187)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:223)
	at org.bimserver.BimServer.start(BimServer.java:732)
	at org.bimserver.JarBimServer.start(JarBimServer.java:160)
	at org.bimserver.JarBimServer.main(JarBimServer.java:79)
00:07:53 INFO  [main]: Server started successfully         
```

**Comment by Gorynych** [comment]
The same for me.

ProtocolBuffersMetaData fails to load ServiceInterface.desc. We just logging this error and do not stop starting process - on the next iteration of loading NewServiceInterface.desc, empty **loaded** map returns null. _And again_, we just log null value at ProtocolBuffersMetaData.java::159, so protobuf implementation gets an empty array, and throws NPE.

**Comment by Gorynych** [comment]
Looks like it is requires to rebuild proto description file.

Install protobuf using homebrew:
`brew install protobuf`

Go to the protobuffers folder: BIMserver/BimServerClientLib/src/org/bimserver/client/protocolbuffers

Compile the descriptor file:
`protoc --include_imports --descriptor_set_out=ServiceInterface.desc ServiceInterface.proto`

Now the server starts successfully - not sure if it will work properly ;) but let's figure it out.

**Comment by rubendel** [comment]
That's weird, I don't think anything related to protocol buffers has been updated lately. But I can reproduce the exact same thing here. Will have a look at this after the weekend. Thanks for posting the workaround.

**Comment by GiacomoManzoli** [comment]
Is it possible to have a new built version so i can test #1058 ?

**Comment by rubendel** [comment]
New builds are building as we speak, new version will be 1.5.179

**Comment by rubendel** [comment]
New build also does not seem to work, same error. Not entirely sure what https://github.com/opensourceBIM/BIMserver/pull/1066 is supposed to actually fix.

**Comment by Gorynych** [comment]
There was a two problems actually:
1) Server fails to start because not able to parse existing .desc file.
2) After failing to parse .desc file server do not stop the process, but send broken data to protobuf library, and then got an NPE.

#1066 fix only the 2) part. It is just a better handling of parsing problem. But not the parsing problem fix ).

**Comment by rubendel** [comment]
Ok thanks, what I would like to suggest is to disable PD completely (but not remove it yet). Even if it starts, I am pretty sure it wont work, and hasn't been working for years since I haven't been testing it, and probably no one has (JSON works fine). But since you have gone through the trouble of fixing it a bit, I can imagine the reason being that you are (trying to) use it, is that the case?

**Comment by Gorynych** [comment]
> 
> 
> is that the case?

Nope ). I just download the server, and trying to start it.

Can you please PM me?
```
new StringBuffer()
                .append("stepan.mozyra")
                .append("@")
                .append("gmail.com")
                .toString()

```

**Comment by swilim** [comment]
> 
> 
> Looks like it is requires to rebuild proto description file.
> 
> Install protobuf using homebrew:
> `brew install protobuf`
> 
> Go to the protobuffers folder: BIMserver/BimServerClientLib/src/org/bimserver/client/protocolbuffers
> 
> Compile the descriptor file:
> `protoc --include_imports --descriptor_set_out=ServiceInterface.desc ServiceInterface.proto`
> 
> Now the server starts successfully - not sure if it will work properly ;) but let's figure it out.

BIMServer Starter Jar 1.5.179 fail to start the server. ( Dependency ServiceInterface.proto of NewServicesInterface.proto not found)

**Comment by rubendel** [comment]
Sorry for the delay, new version works. https://github.com/opensourceBIM/BIMserver/releases/tag/v1.5.180.

What I did is move the initialization of Protocol Buffers in a away that it's only done when PB is actually enabled in the server (which is isn't by default). So just to be clear, PB is not working, but the build is.

**Comment by GiacomoManzoli** [comment]
It's working! Thank you!
