### ISSUE TITLE
Database error on password reset

### ISSUE THREAD

**Issue by daanvanham** [opensourceBIM/BIMserver#1073]
**Describe the bug**
Trying to reset a password by opening the link from the password reset mail triggers a "Database error" on submit.

**To Reproduce**
1. Go to 'user settings' in the Bimvie.ws
2. Click on 'Actions' -> 'Send password reset' for the user you want to reset the password from
3. Open the link in the mail
4. Enter a new password and submit

**Expected behavior**
User should have a new password now

**Additional context**
bimserver.log:
```
2019-12-17 13:03:26,229 ERROR [org.bimserver.AuthInterface.validateAccount] o.b.w.i.GenericServiceImpl [GenericServiceImpl.java:149] 
org.bimserver.BimserverDatabaseException: Cannot commit READ_ONLY DatabaseSession
	at org.bimserver.database.DatabaseSession.commit(DatabaseSession.java:200)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:777)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:767)
	at org.bimserver.webservices.impl.AuthServiceImpl.validateAccount(AuthServiceImpl.java:125)
	at org.bimserver.generated.AuthInterfaceReflectorJvXCdWXojlOQ_1.callMethod(AuthInterfaceReflectorJvXCdWXojlOQ_1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:77)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:66)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1506)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2019-12-17 13:03:26,230 INFO [http-nio-8080-exec-9] o.b.JsonHandler [JsonHandler.java:85] {"request":{"interface":"org.bimserver.AuthInterface","method":"validateAccount","parameters":{"uoid":"131074","token":"A4BD95D465AB4DCC1A5E6CB6EBE5500D","password":"test"}}}
2019-12-17 13:03:26,230 INFO [http-nio-8080-exec-9] o.b.JsonHandler [JsonHandler.java:86] 
org.bimserver.shared.exceptions.ServerException: Database error
	at org.bimserver.webservices.impl.GenericServiceImpl.handleException(GenericServiceImpl.java:150)
	at org.bimserver.webservices.impl.AuthServiceImpl.validateAccount(AuthServiceImpl.java:127)
	at org.bimserver.generated.AuthInterfaceReflectorJvXCdWXojlOQ_1.callMethod(AuthInterfaceReflectorJvXCdWXojlOQ_1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:77)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:66)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1506)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.bimserver.BimserverDatabaseException: Cannot commit READ_ONLY DatabaseSession
	at org.bimserver.database.DatabaseSession.commit(DatabaseSession.java:200)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:777)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:767)
	at org.bimserver.webservices.impl.AuthServiceImpl.validateAccount(AuthServiceImpl.java:125)
	... 29 common frames omitted```

**Comment by rubendel** [comment]
This was fixed in https://github.com/opensourceBIM/BIMserver/commit/eeacd099a343ec0f03f73a3f4c2dcce21660c9a9#diff-95b0f182fc57d05f754b4817bbedb497. Which should be in the BIMserver 1.5.180 release.
