### ISSUE TITLE
Failed redirect when logging in

### ISSUE THREAD

**Issue by yahyasaad** [opensourceBIM/BIMserver#1079]
User gets authenticated and gets a message saying login successful but the page failes to redirect and remains on the login page.
![image](https://user-images.githubusercontent.com/9978873/71241003-2cba9e80-2313-11ea-9bc9-dcf624f331d6.png)

**Comment by rubendel** [comment]
What's in the JavaScript console and in the BIMserver log file?

**Comment by yahyasaad** [comment]
> What's in the JavaScript console and in the BIMserver log file?
![Javascript console](https://user-images.githubusercontent.com/9978873/71819314-3b83ae00-3094-11ea-928a-5b656223a8ee.jpg)

Hi Rubendel,

Attached is the screen shot from the JavaScript console and below is the log records from the BIMserver log file although there is no reference to the issue encountered:

2020-01-06 13:02:28,952 INFO [main] o.b.BimServer [BimServer.java:245] Starting BIMserver (Windows Server 2016, 1.8.0_172, 64bit, Xmx: 7.11 GB)
2020-01-06 13:02:33,499 INFO [main] o.b.w.WarServerInitializer [WarServerInitializer.java:114] Servlet Context Name: BIMserver
2020-01-06 13:02:33,499 INFO [main] o.b.BimServer [BimServer.java:333] Version: 1.5.162
2020-01-06 13:02:33,499 INFO [main] o.b.BimServer [BimServer.java:342] Using "C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\bimserver15\WEB-INF" as homedir
2020-01-06 13:02:38,999 INFO [pool-5-thread-2] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing IFC4 with ifc4
2020-01-06 13:02:38,999 INFO [pool-5-thread-1] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing IFC2X3TC1 with ifc2x3tc1
2020-01-06 13:02:38,999 INFO [pool-5-thread-4] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing STORE with store
2020-01-06 13:02:38,999 INFO [pool-5-thread-3] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing GEOMETRY with geometry
2020-01-06 13:02:39,030 INFO [pool-5-thread-3] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing LOG with log
2020-01-06 13:02:41,312 INFO [main] o.b.d.b.BerkeleyKeyValueStore [BerkeleyKeyValueStore.java:85] Non-empty database directory found "C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\bimserver15\WEB-INF\database"
2020-01-06 13:02:41,530 ERROR [main] o.b.BimServer [BimServer.java:805] 
org.bimserver.database.berkeley.DatabaseInitException: Environment locked exception. Another process is using the same database, or the current user has no write access (database location: "C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\bimserver15\WEB-INF\database")
	at org.bimserver.database.berkeley.BerkeleyKeyValueStore.<init>(BerkeleyKeyValueStore.java:117)
	at org.bimserver.BimServer.start(BimServer.java:664)
	at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:117)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4643)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5109)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:742)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:718)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:986)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1858)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:772)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:426)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1585)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:308)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:966)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1427)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1417)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:943)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:682)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
2020-01-06 13:02:41,577 INFO [main] o.b.s.w.j.Jsr356Impl [Jsr356Impl.java:104] WebSocket context initialized
2020-01-06 13:09:11,201 INFO [http-nio-80-exec-26] o.b.c.NewDiskCacheOutputStream [NewDiskCacheOutputStream.java:59] Renaming temp file 5e8f37fde5632885a2da25fe74542eec.__tmp to 5e8f37fde5632885a2da25fe74542eec
2020-01-06 13:09:13,170 INFO [http-nio-80-exec-21] o.b.c.NewDiskCacheOutputStream [NewDiskCacheOutputStream.java:59] Renaming temp file 1f586a8344afa8cac7e0341d6766abb7.__tmp to 1f586a8344afa8cac7e0341d6766abb7
2020-01-06 13:09:13,310 INFO [http-nio-80-exec-22] o.b.c.NewDiskCacheOutputStream [NewDiskCacheOutputStream.java:59] Renaming temp file 0bf197e0c9b27969c4f3835b03d3156f.__tmp to 0bf197e0c9b27969c4f3835b03d3156f
2020-01-06 13:09:33,202 INFO [main] o.b.BimServer [BimServer.java:245] Starting BIMserver (Windows Server 2016, 1.8.0_172, 64bit, Xmx: 7.11 GB)
2020-01-06 13:09:36,874 INFO [main] o.b.w.WarServerInitializer [WarServerInitializer.java:114] Servlet Context Name: BIMserver
2020-01-06 13:09:36,874 INFO [main] o.b.BimServer [BimServer.java:333] Version: 1.5.162
2020-01-06 13:09:36,874 INFO [main] o.b.BimServer [BimServer.java:342] Using "C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\bimserver15\WEB-INF" as homedir
2020-01-06 13:09:42,375 INFO [pool-5-thread-1] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing IFC2X3TC1 with ifc2x3tc1
2020-01-06 13:09:42,375 INFO [pool-5-thread-4] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing STORE with store
2020-01-06 13:09:42,375 INFO [pool-5-thread-2] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing IFC4 with ifc4
2020-01-06 13:09:42,375 INFO [pool-5-thread-4] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing LOG with log
2020-01-06 13:09:42,375 INFO [pool-5-thread-3] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing GEOMETRY with geometry
2020-01-06 13:09:44,312 INFO [main] o.b.d.b.BerkeleyKeyValueStore [BerkeleyKeyValueStore.java:85] Non-empty database directory found "C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\bimserver15\WEB-INF\database"
2020-01-06 13:09:44,515 ERROR [main] o.b.BimServer [BimServer.java:805] 
org.bimserver.database.berkeley.DatabaseInitException: Environment locked exception. Another process is using the same database, or the current user has no write access (database location: "C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\bimserver15\WEB-INF\database")
	at org.bimserver.database.berkeley.BerkeleyKeyValueStore.<init>(BerkeleyKeyValueStore.java:117)
	at org.bimserver.BimServer.start(BimServer.java:664)
	at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:117)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4643)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5109)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:742)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:718)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:986)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1858)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:772)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:426)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1585)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:308)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:966)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1427)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1417)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:943)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:682)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
2020-01-06 13:09:44,547 INFO [main] o.b.s.w.j.Jsr356Impl [Jsr356Impl.java:104] WebSocket context initialized

**Comment by rubendel** [comment]
There seem to be 2 BIMservers running on the same database. Make sure you kill them all, and then start only one of them.

**Comment by yahyasaad** [comment]
> There seem to be 2 BIMservers running on the same database. Make sure you kill them all, and then start only one of them.

Applied recommended, still get the same error. Any further suggestions? Thanks

**Comment by rubendel** [comment]
You could remove the database (or if it's important, temporarily move it somewhere else) and see if that fixes it (obviously stop the server before doing so). You could remove the lock file, but that's not really recommended as it's there for a reason.
