### ISSUE TITLE
 org.bimserver.BimserverDatabaseException: Query stack size > 10000000

### ISSUE THREAD

**Issue by aurelien-gille** [opensourceBIM/BIMserver#1085]
Hello,

I received a weird .ifs I can't add on BimServer, it return : 

> `[001.5.ifc] org.bimserver.BimserverDatabaseException: Query stack size > 10000000, probably a bug, please report`

It says to repport so here I am.

At first I suspected the file wasn't good but it seems to open on DDS-CAD viewer or Areddo and looks what it's suppose to.
The file is not that big either (650Ko, 66K ifc objects) and I already try some waaaay bigger ones that worked on BimServer (152Mo, 2.7M ifc objects)

Note :  Issue #1064 works thanks again !

**Comment by rubendel** [comment]
Can you share the IFC file? Is there more info in the log file (a stacktrace would be great)?

**Comment by aurelien-gille** [comment]
The file seems to work on Areddo, BimVision, even the IfcOpenShell plugin for Blender :
[001.5.ifc.txt](https://github.com/opensourceBIM/BIMserver/files/4116696/001.5.ifc.txt)

Using the bimserverjar-1.5.180.jar version :

```
11:44:32 INFO  [pool-1-thread-5]: Top 20 stack frames                                                              (QueryObjectProvider.java:197) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacesObject: [2687335]
	PlacementRelTo: 23921545
	RelativePlacement: 39650125
 (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1876361414
               (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacesObject: [2687335]
	PlacementRelTo: 23921545
	RelativePlacement: 39650125
 (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1876361414
               (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23856009
	ReferencedByPlacements: [23987081]
	RelativePlacement: 37880653
 (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1874591942
               (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23790473
	ReferencedByPlacements: [23921545]
	RelativePlacement: 37815117
 (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1874526406
               (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23724937
	ReferencedByPlacements: [23856009]
	RelativePlacement: 37749581
 (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1874460870
               (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23659401
	ReferencedByPlacements: [23790473]
	RelativePlacement: 37684045
 (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1874395334
               (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23593865
	ReferencedByPlacements: [23724937]
	RelativePlacement: 37618509
 (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1874329798
               (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23528329
	ReferencedByPlacements: [23659401]
	RelativePlacement: 37552973
 (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1874264262
               (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23462793
	ReferencedByPlacements: [23593865]
	RelativePlacement: 37487437
 (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1874198726
               (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23397257
	ReferencedByPlacements: [23528329]
	RelativePlacement: 27591501
 (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1864302790
               (QueryObjectProvider.java:200) 
11:44:32 INFO  [pool-1-thread-5]: Last 50 frames                                                                   (QueryObjectProvider.java:205) 
11:44:32 INFO  [pool-1-thread-5]: Query dump                                                                       (QueryObjectProvider.java:207) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacesObject: [2687335]
	PlacementRelTo: 23921545
	RelativePlacement: 39650125
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1876361414
               (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacesObject: [2687335]
	PlacementRelTo: 23921545
	RelativePlacement: 39650125
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1876361414
               (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23856009
	ReferencedByPlacements: [23987081]
	RelativePlacement: 37880653
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1874591942
               (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23790473
	ReferencedByPlacements: [23921545]
	RelativePlacement: 37815117
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1874526406
               (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23724937
	ReferencedByPlacements: [23856009]
	RelativePlacement: 37749581
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1874460870
               (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23659401
	ReferencedByPlacements: [23790473]
	RelativePlacement: 37684045
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1874395334
               (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23593865
	ReferencedByPlacements: [23724937]
	RelativePlacement: 37618509
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1874329798
               (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23528329
	ReferencedByPlacements: [23659401]
	RelativePlacement: 37552973
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1874264262
               (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23462793
	ReferencedByPlacements: [23593865]
	RelativePlacement: 37487437
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1874198726
               (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23397257
	ReferencedByPlacements: [23528329]
	RelativePlacement: 27591501
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1864302790
               (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23331721
	ReferencedByPlacements: [23462793]
	RelativePlacement: 28312397
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1865023686
	RefDirection: 6423050
	Axis: 6488586
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23266185
	ReferencedByPlacements: [23397257]
	RelativePlacement: 28246861
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1864958150
               (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23200649
	ReferencedByPlacements: [23331721]
	RelativePlacement: 26215245
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1862926534
               (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23004041
	ReferencedByPlacements: [23266185]
	RelativePlacement: 26149709
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1862860998
	RefDirection: 4325898
	Axis: 4391434
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23069577
	ReferencedByPlacements: [23200649]
	RelativePlacement: 24707917
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1861419206
	RefDirection: 1835530
	Axis: 1901066
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23135113
	ReferencedByPlacements: [23004041]
	RelativePlacement: 24642381
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1861353670
	RefDirection: 1704458
	Axis: 1769994
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	ReferencedByPlacements: [23069577]
	RelativePlacement: 24576845
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1861288134
	RefDirection: 1573386
	Axis: 1638922
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	ReferencedByPlacements: [23069577]
	RelativePlacement: 24576845
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1861288134
	RefDirection: 1573386
	Axis: 1638922
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	ReferencedByPlacements: [23069577]
	RelativePlacement: 24576845
 (QueryObjectProvider.java:210) 
11:44:32 INFO11:44:32 ERROR [pool-1-thread-5]:                                                                                  (StreamingGeometryGenerator.java:672) 
org.bimserver.BimserverDatabaseException: Query stack size > 10000000, probably a bug, please report
	at org.bimserver.database.queries.QueryObjectProvider.next(QueryObjectProvider.java:156)
	at org.bimserver.geometry.StreamingGeometryGenerator.generateGeometry(StreamingGeometryGenerator.java:480)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:237)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:85)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:775)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:752)
	at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:73)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1861288134
	RefDirection: 1573386
	Axis: 1638922
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23135113
	ReferencedByPlacements: [23004041]
	RelativePlacement: 24642381
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	ReferencedByPlacements: [23069577]
	RelativePlacement: 24576845
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1861288134
	RefDirection: 1573386
	Axis: 1638922
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	ReferencedByPlacements: [23069577]
	RelativePlacement: 24576845
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1861288134
	RefDirection: 1573386
	Axis: 1638922
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1861353670
	RefDirection: 1704458
	Axis: 1769994
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	PlacementRelTo: 23135113
	ReferencedByPlacements: [23004041]
	RelativePlacement: 24642381
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1861353670
	RefDirection: 1704458
	Axis: 1769994
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	ReferencedByPlacements: [23069577]
	RelativePlacement: 24576845
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1861288134
	RefDirection: 1573386
	Axis: 1638922
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcLocalPlacement
	ReferencedByPlacements: [23069577]
	RelativePlacement: 24576845
 (QueryObjectProvider.java:210) 
11:44:32 INFO  [pool-1-thread-5]: 	QueryIncludeStackFrame IfcAxis2Placement3D
	Location: 1861288134
	RefDirection: 1573386
	Axis: 1638922
 (QueryObjectProvider.java:210) 
11:44:32 ERROR [pool-1-thread-5]: [null] [001.5.ifc] org.bimserver.BimserverDatabaseException: Query stack size > 10000000, probably a bug, please report (LongAction.java:196) 
org.bimserver.shared.exceptions.UserException: [001.5.ifc] org.bimserver.BimserverDatabaseException: Query stack size > 10000000, probably a bug, please report
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:413)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:85)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:775)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:752)
	at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:73)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.bimserver.GeometryGeneratingException: org.bimserver.BimserverDatabaseException: Query stack size > 10000000, probably a bug, please report
	at org.bimserver.geometry.StreamingGeometryGenerator.generateGeometry(StreamingGeometryGenerator.java:674)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:237)
	... 10 common frames omitted
Caused by: org.bimserver.BimserverDatabaseException: Query stack size > 10000000, probably a bug, please report
	at org.bimserver.database.queries.QueryObjectProvider.next(QueryObjectProvider.java:156)
	at org.bimserver.geometry.StreamingGeometryGenerator.generateGeometry(StreamingGeometryGenerator.java:480)
	... 11 common frames omitted

```

**Comment by rubendel** [comment]
Thanks for providing the IFC file, I fixed a bug in the default queries, this will be in the next release.
