### ISSUE TITLE
problem downloading plugins and extended dataschemas - javax.net.ssl.SSLHandshakeException

### ISSUE THREAD

**Issue by DaDup** [opensourceBIM/BIMserver#1086]
Hi all,

I am trying to setup BIMserver using  bimserverjar-1.5.180.jar.
Everything works up until trying to download either plugins or the extended data schema's:

![image](https://user-images.githubusercontent.com/50294874/71908324-0f3c6000-316e-11ea-82b6-7b1abdcbc851.png)

The BIMserver Starter shows a lot of errors starting with this one:
ERROR [ServiceInterface.getAllRepositoryExtendedDataSchemas]:                                                                                  (GenericServiceImpl.java:152) 
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)

I did not add all error messages because I think they are all caused by the same issue: a problem to connect to the internet, similar to this issue:
https://github.com/opensourceBIM/BIMserver/issues/1038

The person posting that issue solved it by opening some ports in the firewall. Could someone please tell me which port I should open for this?

Thanks a lot.

Daan

**Comment by rubendel** [comment]
Which JVM + version?

**Comment by DaDup** [comment]
Hi Ruben,

I installed Java Version 8 Update 231 and used the default JVM setting in BIMserver starter.
I'm using bimserverjar-1.5.180 to run the BIMserver itself.

**Comment by rubendel** [comment]
Ok that's reasonably recent. Usually this error indicates that you are using an older JVM that simply does not have certain root SSL certificates installed/trusted. You could try a never JVM anyways (Open JDK 11 or 12 for example).

Also manually changing certificate settings on the machine might brake things.

It's definitely not a problem to connect to "the internet", since the SSL handshake happens after at least a (or a few) packet(s) have/has successfully been transmitted. It could however be a malfunctioning proxy server, are you using a proxy server?

**Comment by DaDup** [comment]
I switched to JDK-13 but I am still getting the same error. I did not check the proxy-server checkbox inside the BIMserver starter but I am on my company's network, might that be that that is causing the certification issue?

**Comment by rubendel** [comment]
I don't think so, you are already talking to an HTTP server, so probably no proxy server is required. Can you post more of the stacktrace?

**Comment by DaDup** [comment]
Ah yes ofcourse, this is the full text output in the BIMserver:

No expanding necessary
OS: Windows 10
Main class: org.bimserver.JarBimServer

Commands:
java
-Xmx1000m
-Xss1024k
-Dorg.apache.cxf.Logger=org.apache.cxf.common.logging.Slf4jLogger
-classpath
.;lib;lib\activation-1.1.jar;lib\aether-api-1.0.2.v20150114.jar;lib\aether-connector-basic-1.0.2.v20150114.jar;lib\aether-impl-1.0.2.v20150114.jar;lib\aether-spi-1.0.2.v20150114.jar;lib\aether-transport-file-1.0.2.v20150114.jar;lib\aether-transport-http-1.0.2.v20150114.jar;lib\aether-util-1.0.2.v20150114.jar;lib\animal-sniffer-annotations-1.14.jar;lib\ant-1.10.5.jar;lib\ant-launcher-1.10.5.jar;lib\antlr-2.7.7.jar;lib\antlr-3.5.2.jar;lib\antlr-complete-3.5.2.jar;lib\antlr-runtime-3.5.2.jar;lib\antlr4-runtime-4.7.1.jar;lib\aopalliance-1.0.jar;lib\aopalliance-repackaged-2.5.0-b31.jar;lib\asm-7.1.jar;lib\asm-analysis-7.1.jar;lib\asm-commons-7.1.jar;lib\asm-tree-7.1.jar;lib\bcf-0.0.35.jar;lib\bdb-1.5.180.jar;lib\bimserver-1.5.180.jar;lib\bimserverclientlib-1.5.180.jar;lib\buildingsmartlibrary-1.0.13.jar;lib\c3p0-0.9.5.2.jar;lib\cdi-api-1.0.jar;lib\checker-qual-2.5.2.jar;lib\codemodel-2.3.2.jar;lib\commonj.sdo-2.1.1.jar;lib\commons-cli-1.3.1.jar;lib\commons-codec-1.9.jar;lib\commons-collections-20040616.jar;lib\commons-fileupload-1.4.jar;lib\commons-io-2.2.jar;lib\commons-lang-2.4.jar;lib\commons-lang3-3.4.jar;lib\commons-logging-1.2.jar;lib\commons-pool2-2.4.2.jar;lib\concurrent-trees-2.6.1.jar;lib\cors-filter-2.5.jar;lib\cqengine-3.0.0.jar;lib\cxf-core-3.3.1.jar;lib\cxf-rt-bindings-soap-3.3.1.jar;lib\cxf-rt-bindings-xml-3.3.2.jar;lib\cxf-rt-databinding-jaxb-3.3.1.jar;lib\cxf-rt-frontend-jaxws-3.3.2.jar;lib\cxf-rt-frontend-simple-3.3.2.jar;lib\cxf-rt-javascript-3.3.1.jar;lib\cxf-rt-transports-http-3.3.2.jar;lib\cxf-rt-ws-addr-3.3.2.jar;lib\cxf-rt-ws-policy-3.3.2.jar;lib\cxf-rt-wsdl-3.3.1.jar;lib\dtd-parser-1.4.1.jar;lib\error_prone_annotations-2.1.3.jar;lib\FastInfoset-1.2.16.jar;lib\fastutil-8.2.3.jar;lib\gmbal-4.0.0.jar;lib\gson-2.5.jar;lib\guava-26.0-jre.jar;lib\guice-4.0-no_aop.jar;lib\gunit-3.5.2.jar;lib\ha-api-3.1.12.jar;lib\hamcrest-core-1.3.jar;lib\HikariCP-java6-2.3.13.jar;lib\hk2-api-2.5.0-b31.jar;lib\hk2-locator-2.5.0-b31.jar;lib\hk2-utils-2.5.0-b31.jar;lib\httpclient-4.5.7.jar;lib\httpcore-4.4.11.jar;lib\httpmime-4.5.7.jar;lib\istack-commons-runtime-3.0.8.jar;lib\istack-commons-tools-3.0.8.jar;lib\j2objc-annotations-1.1.jar;lib\jackson-annotations-2.9.0.jar;lib\jackson-core-2.9.7.jar;lib\jackson-databind-2.9.7.jar;lib\jakarta.activation-api-1.2.1.jar;lib\jakarta.annotation-api-1.3.4.jar;lib\jakarta.jws-api-1.1.1.jar;lib\jakarta.mail-api-1.6.3.jar;lib\jakarta.persistence-api-2.2.2.jar;lib\jakarta.xml.bind-api-2.3.2.jar;lib\jakarta.xml.soap-api-1.4.1.jar;lib\jakarta.xml.ws-api-2.3.2.jar;lib\java-getopt-1.0.13.jar;lib\java-property-utils-1.9.1.jar;lib\javassist-3.24.1-GA.jar;lib\javax-websocket-client-impl-9.4.19.v20190610.jar;lib\javax-websocket-server-impl-9.4.19.v20190610.jar;lib\javax.annotation-api-1.2.jar;lib\javax.inject-1.jar;lib\javax.inject-2.5.0-b31.jar;lib\javax.json-1.0.4.jar;lib\javax.mail-1.6.2.jar;lib\javax.servlet-api-3.1.0.jar;lib\javax.websocket-api-1.1.jar;lib\javax.websocket-client-api-1.0.jar;lib\javax.ws.rs-api-2.1-m02.jar;lib\jaxb-jxc-2.3.2.jar;lib\jaxb-runtime-2.3.2.jar;lib\jaxb-xjc-2.3.2.jar;lib\jaxws-eclipselink-plugin-2.3.2.jar;lib\jaxws-ri-2.3.2.pom;lib\jaxws-rt-2.3.2.jar;lib\jaxws-tools-2.3.2.jar;lib\jcl-over-slf4j-1.6.2.jar;lib\jdom2-2.0.6.jar;lib\je-7.5.11.jar;lib\jersey-client-2.26-b01.jar;lib\jersey-common-2.26-b01.jar;lib\jersey-container-servlet-2.26-b01.jar;lib\jersey-container-servlet-core-2.26-b01.jar;lib\jersey-guava-2.26-b01.jar;lib\jersey-media-jaxb-2.26-b01.jar;lib\jersey-server-2.26-b01.jar;lib\jettison-1.3.8.jar;lib\jetty-alpn-client-9.4.19.v20190610.jar;lib\jetty-alpn-java-client-9.4.19.v20190610.jar;lib\jetty-annotations-9.4.19.v20190610.jar;lib\jetty-client-9.4.19.v20190610.jar;lib\jetty-http-9.4.19.v20190610.jar;lib\jetty-io-9.4.19.v20190610.jar;lib\jetty-jndi-9.4.19.v20190610.jar;lib\jetty-plus-9.4.19.v20190610.jar;lib\jetty-security-9.4.19.v20190610.jar;lib\jetty-server-9.4.19.v20190610.jar;lib\jetty-servlet-9.4.19.v20190610.jar;lib\jetty-util-9.4.19.v20190610.jar;lib\jetty-webapp-9.4.19.v20190610.jar;lib\jetty-xml-9.4.19.v20190610.jar;lib\json-20140107.jar;lib\jsr250-api-1.0.jar;lib\jsr305-3.0.2.jar;lib\jul-to-slf4j-1.7.22.jar;lib\junit-4.12.jar;lib\kryo-5.0.0-RC1.jar;lib\kryo-serializers-0.42.jar;lib\logback-classic-1.1.9.jar;lib\logback-core-1.1.9.jar;lib\management-api-3.2.1.jar;lib\maven-aether-provider-3.3.9.jar;lib\maven-artifact-3.3.9.jar;lib\maven-builder-support-3.3.9.jar;lib\maven-core-3.3.9.jar;lib\maven-model-3.3.9.jar;lib\maven-model-builder-3.3.9.jar;lib\maven-plugin-api-3.3.9.jar;lib\maven-repository-metadata-3.3.9.jar;lib\maven-settings-3.3.9.jar;lib\maven-settings-builder-3.3.9.jar;lib\mchange-commons-java-0.2.11.jar;lib\mimepull-1.9.11.jar;lib\minlog-1.3.0.jar;lib\neethi-3.1.1.jar;lib\objenesis-2.6.jar;lib\org.apache.oltu.oauth2.authzserver-1.0.2.jar;lib\org.apache.oltu.oauth2.client-1.0.2.jar;lib\org.apache.oltu.oauth2.common-1.0.2.jar;lib\org.apache.oltu.oauth2.dynamicreg.client-1.0.2.jar;lib\org.apache.oltu.oauth2.dynamicreg.common-1.0.2.jar;lib\org.apache.oltu.oauth2.dynamicreg.server-1.0.2.jar;lib\org.apache.oltu.oauth2.resourceserver-1.0.2.jar;lib\org.eclipse.core.commands-3.9.500.jar;lib\org.eclipse.core.contenttype-3.7.400.jar;lib\org.eclipse.core.expressions-3.6.500.jar;lib\org.eclipse.core.filesystem-1.7.500.jar;lib\org.eclipse.core.jobs-3.10.500.jar;lib\org.eclipse.core.resources-3.13.500.jar;lib\org.eclipse.core.resources-3.8.101.v20130717-0806.jar;lib\org.eclipse.core.runtime-3.16.0.jar;lib\org.eclipse.core.variables-3.4.600.jar;lib\org.eclipse.debug.core-3.14.0.jar;lib\org.eclipse.emf.codegen-2.14.0.jar;lib\org.eclipse.emf.codegen.ecore-2.15.0.jar;lib\org.eclipse.emf.common-2.15.0.jar;lib\org.eclipse.emf.ecore-2.15.0.jar;lib\org.eclipse.emf.ecore.xmi-2.15.0.jar;lib\org.eclipse.equinox.app-1.4.300.jar;lib\org.eclipse.equinox.common-3.10.500.jar;lib\org.eclipse.equinox.preferences-3.7.500.jar;lib\org.eclipse.equinox.registry-3.8.500.jar;lib\org.eclipse.jdt.core-3.14.0.v20171206-0802.jar;lib\org.eclipse.jdt.core-3.19.0.jar;lib\org.eclipse.jdt.debug-3.13.100.jar;lib\org.eclipse.jdt.launching-3.15.0.jar;lib\org.eclipse.osgi-3.15.0.jar;lib\org.eclipse.persistence.asm-2.7.4.jar;lib\org.eclipse.persistence.core-2.7.4.jar;lib\org.eclipse.persistence.moxy-2.7.4.jar;lib\org.eclipse.persistence.sdo-2.7.4.jar;lib\org.eclipse.sisu.inject-0.3.2.jar;lib\org.eclipse.sisu.plexus-0.3.2.jar;lib\org.eclipse.text-3.9.0.jar;lib\osgi-resource-locator-1.0.1.jar;lib\pfl-asm-4.0.1.jar;lib\pfl-basic-4.0.1.jar;lib\pfl-basic-tools-4.0.1.jar;lib\pfl-dynamic-4.0.1.jar;lib\pfl-tf-4.0.1.jar;lib\pfl-tf-tools-4.0.1.jar;lib\plexus-cipher-1.4.jar;lib\plexus-classworlds-2.5.2.jar;lib\plexus-component-annotations-1.6.jar;lib\plexus-interpolation-1.21.jar;lib\plexus-sec-dispatcher-1.3.jar;lib\plexus-utils-3.0.22.jar;lib\pluginbase-1.5.180.jar;lib\policy-2.7.6.jar;lib\protobuf-java-2.6.1.jar;lib\quartz-2.3.0.jar;lib\reflectasm-1.11.7.jar;lib\relaxng-datatype-2.3.2.jar;lib\release-documentation-2.3.2-docbook.zip;lib\rngom-2.3.2.jar;lib\rome-1.7.1.jar;lib\rome-utils-1.7.1.jar;lib\saaj-impl-1.5.1.jar;lib\samples-2.3.2.zip;lib\sdo-eclipselink-plugin-2.3.2.jar;lib\shared-1.5.180.jar;lib\slf4j-api-1.7.22.jar;lib\sqlite-jdbc-3.23.1.jar;lib\ST4-4.0.8.jar;lib\stax-api-1.0.1.jar;lib\stax-ex-1.8.1.jar;lib\stax2-api-3.1.4.jar;lib\streambuffer-1.5.7.jar;lib\stringtemplate-3.2.1.jar;lib\txw2-2.3.2.jar;lib\typetools-0.5.0.jar;lib\validation-api-1.1.0.Final.jar;lib\velocity-1.7.jar;lib\websocket-api-9.4.19.v20190610.jar;lib\websocket-client-9.4.19.v20190610.jar;lib\websocket-common-9.4.19.v20190610.jar;lib\websocket-server-9.4.19.v20190610.jar;lib\websocket-servlet-9.4.19.v20190610.jar;lib\woodstox-core-5.0.3.jar;lib\wsdl4j-1.6.3.jar;lib\xml-resolver-1.2.jar;lib\xmlbeans-2.6.0.jar;lib\xmlschema-core-2.2.4.jar;lib\xsom-2.3.2.jar
org.bimserver.JarBimServer
address=localhost
port=8082
homedir=C:\Users\daan.duppen\Documents\00 Werk\03 short assignments\03 BIMserver\home
java version "13.0.1" 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
21:39:36 INFO  [main]: Starting BIMserver (Windows 10, 13.0.1, 64bit, Xmx: 1000,00 MB)                  (BimServer.java:248) 
Logging to C:\Users\daan.duppen\Documents\00 Werk\03 short assignments\03 BIMserver\home\logs\bimserver.log
21:39:40 INFO  [main]: Version: 1.5.180                                                                 (BimServer.java:336) 
21:39:40 INFO  [main]: Using "C:\Users\daan.duppen\Documents\00 Werk\03 short assignments\03 BIMserver\home" as homedir (BimServer.java:345) 
21:39:44 INFO  [main]: No database directory found, creating "C:\Users\daan.duppen\Documents\00 Werk\03 short assignments\03 BIMserver\home\database" (BerkeleyKeyValueStore.java:98) 
21:39:44 INFO  [main]: Successfully created database dir "C:\Users\daan.duppen\Documents\00 Werk\03 short assignments\03 BIMserver\home\database" (BerkeleyKeyValueStore.java:101) 
21:40:02 INFO  [main]: Non-empty database directory found "C:\Users\daan.duppen\Documents\00 Werk\03 short assignments\03 BIMserver\home\database" (BerkeleyKeyValueStore.java:87) 
21:40:03 INFO  [main]: Checking for stale records, this can take some time...                           (BimServer.java:814) 
21:40:03 INFO  [main]: Done checking for stale records (15 ms)                                          (BimServer.java:844) 
21:40:03 INFO  [main]: Changing server state to NOT_SETUP                                               (ServerInfoManager.java:115) 
21:40:03 INFO  [main]: Initializing database dependant logic...                                         (BimServer.java:1114) 
21:40:03 INFO  [main]: Done initializing database dependant logic (66ms)                                (BimServer.java:1285) 
21:40:05 INFO  [main]: Server started successfully                                                      (JarBimServer.java:161) 
21:40:42 INFO  [AdminInterface.setup]: Changing server state to RUNNING                                                 (ServerInfoManager.java:115) 
21:40:42 ERROR [ServiceInterface.getAllRepositoryExtendedDataSchemas]:                                                                                  (GenericServiceImpl.java:152) 
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:641)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:460)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1460)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1368)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:437)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:171)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at java.base/sun.net.www.pro21:40:42 INFO  [qtp777748410-64]: {"request":{"interface":"ServiceInterface","method":"getAllRepositoryExtendedDataSchemas","parameters":{"usePre":true}},"token":"5bbf5c0f1e9e98682d12c79e6e197e940825ecdfc25143ae03b46f0d1f419e96756892f870d7462cdb83146deca1aa4c"} (JsonHandler.java:85) 
tocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at org.bimserver.utils.NetUtils.getContent(NetUtils.java:50)
	at org.bimserver.webservices.impl.ServiceImpl.getAllRepositoryExtendedDataSchemas(ServiceImpl.java:2283)
	at org.bimserver.generated.ServiceInterfaceReflectorIZbcdwQIvOBX_1.callMethod(ServiceInterfaceReflectorIZbcdwQIvOBX_1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:77)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:66)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:868)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:384)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:289)
	at java.base/sun.securit21:40:42 INFO  [qtp777748410-64]:                                                                                  (JsonHandler.java:86) 
org.bimserver.shared.exceptions.ServerException: Unhandled exception (javax.net.ssl.SSLHandshakeException): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target. See the server log for more details
	at org.bimserver.webservices.impl.GenericServiceImpl.handleException(GenericServiceImpl.java:153)
	at org.bimserver.webservices.impl.ServiceImpl.getAllRepositoryExtendedDataSchemas(ServiceImpl.java:2301)
	at org.bimserver.generated.ServiceInterfaceReflectorIZbcdwQIvOBX_1.callMethod(ServiceInterfaceReflectorIZbcdwQIvOBX_1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:77)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServy.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:625)
	... 57 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:379)
	... 62 common frames omitted
let.java:66)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:868)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:641)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:460)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1460)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1368)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:437)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:171)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at org.bimserver.utils.NetUtils.getContent(NetUtils.java:50)
	at org.bimserver.webservices.impl.ServiceImpl.getAllRepositoryExtendedDataSchemas(ServiceImpl.java:2283)
	... 40 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:384)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:289)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:625)
	... 57 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:379)
	... 62 common frames omitted

**Comment by hlg** [comment]
Is this still an issue?

**Comment by DaDup** [comment]
Hi,

This issue was never fixed but I don't need it anymore.

**Comment by zaqifathis** [comment]
I tested with BIMserver version 1.5.185 and Java versions 8, 11, 13, and 21, and I did not encounter a similar issue. Therefore, I will close this issue for now.

**Comment by hlg** [comment]
Just as a note, in case this pops up again: At this point where the error occurs, the list of extended data schemas is downloaded from the "Repository Server" where a list of initial extended data schemas is kept. By default this is configured to https://raw.githubusercontent.com/opensourceBIM/BIMserver-Repository/master. There have been errors reported in conjunction with the certificate for raw.githubusercontent.com:443 and curl access.
