### ISSUE TITLE
Required dependency commons-io:commons-io is not installed during setup

### ISSUE THREAD

**Issue by jasoncwp** [opensourceBIM/BIMserver#1101]
Hi
I am try to install BIMServer 1.5.181 on windows 2016 with Tomcat 9.0.30 and Java 1.8u241, after copy the BIMServer to tomcat wabapps directory and it extract automatically.
After go to the setup page and start to install plugin, it will show 
Installing bimviews...
		Required dependency commons-io:commons-io is not installed

and it show below error in bimserver.log

```
2020-02-03 01:49:19,639 INFO [main] o.b.BimServer [BimServer.java:248] Starting BIMserver (Windows Server 2016, 1.8.0_241, 64bit, Xmx: 228.00 MB)
2020-02-03 01:49:24,545 INFO [main] o.b.w.WarServerInitializer [WarServerInitializer.java:114] Servlet Context Name: BIMserver
2020-02-03 01:49:24,545 INFO [main] o.b.BimServer [BimServer.java:336] Version: 1.5.181
2020-02-03 01:49:24,545 INFO [main] o.b.BimServer [BimServer.java:345] Using "D:\BIM\Tomcat\webapps\bimserver\WEB-INF" as homedir
2020-02-03 01:49:30,467 INFO [pool-2-thread-1] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing IFC2X3TC1 with ifc2x3tc1
2020-02-03 01:49:30,467 INFO [pool-2-thread-2] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing IFC4 with ifc4
2020-02-03 01:49:34,295 INFO [pool-2-thread-1] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing GEOMETRY with geometry
2020-02-03 01:49:34,295 INFO [pool-2-thread-1] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing STORE with store
2020-02-03 01:49:34,295 INFO [pool-2-thread-1] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing LOG with log
2020-02-03 01:49:35,732 INFO [main] o.b.d.b.BerkeleyKeyValueStore [BerkeleyKeyValueStore.java:98] No database directory found, creating "D:\BIM\Tomcat\webapps\bimserver\WEB-INF\database"
2020-02-03 01:49:35,732 INFO [main] o.b.d.b.BerkeleyKeyValueStore [BerkeleyKeyValueStore.java:101] Successfully created database dir "D:\BIM\Tomcat\webapps\bimserver\WEB-INF\database"
2020-02-03 01:49:44,765 INFO [main] o.b.d.b.BerkeleyKeyValueStore [BerkeleyKeyValueStore.java:87] Non-empty database directory found "D:\BIM\Tomcat\webapps\bimserver\WEB-INF\database"
2020-02-03 01:49:48,437 INFO [main] o.b.BimServer [BimServer.java:814] Checking for stale records, this can take some time...
2020-02-03 01:49:48,484 INFO [main] o.b.BimServer [BimServer.java:844] Done checking for stale records (33 ms)
2020-02-03 01:49:49,015 INFO [main] o.b.ServerInfoManager [ServerInfoManager.java:116] Changing server state to NOT_SETUP
2020-02-03 01:49:49,015 INFO [main] o.b.BimServer [BimServer.java:1114] Initializing database dependant logic...
2020-02-03 01:49:49,218 INFO [main] o.b.BimServer [BimServer.java:1285] Done initializing database dependant logic (206ms)
2020-02-03 01:49:50,640 INFO [main] o.b.s.w.j.Jsr356Impl [Jsr356Impl.java:104] WebSocket context initialized
2020-02-03 01:54:52,589 INFO [AdminInterface.setup] o.b.ServerInfoManager [ServerInfoManager.java:116] Changing server state to RUNNING
2020-02-03 01:54:54,839 INFO [PluginInterface.installPluginBundle] o.b.d.a.InstallPluginBundle [InstallPluginBundle.java:57] Installing plugin central (https://repo1.maven.org/maven2/, default, releases+snapshots) org.opensourcebim.bimviews.0.0.182
2020-02-03 01:54:54,839 INFO [PluginInterface.installPluginBundle] o.b.d.a.InstallPluginBundle [InstallPluginBundle.java:65] central (https://repo1.maven.org/maven2/, default, releases+snapshots)
2020-02-03 01:54:54,839 INFO [PluginInterface.installPluginBundle] o.b.d.a.InstallPluginBundle [InstallPluginBundle.java:70] 0.0.182
2020-02-03 01:55:04,808 ERROR [PluginInterface.installPluginBundle] o.b.d.a.InstallPluginBundle [InstallPluginBundle.java:75] 
java.lang.Exception: Required dependency commons-io:commons-io is not installed
	at org.bimserver.plugins.PluginBundleManager.loadDependencies(PluginBundleManager.java:222)
	at org.bimserver.plugins.PluginBundleManager.install(PluginBundleManager.java:134)
	at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPluginBundle.java:73)
	at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPluginBundle.java:35)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:775)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:767)
	at org.bimserver.webservices.impl.PluginServiceImpl.installPluginBundle(PluginServiceImpl.java:1420)
	at org.bimserver.generated.PluginInterfaceReflectorJJGuOAzlcJrG_1.callMethod(PluginInterfaceReflectorJJGuOAzlcJrG_1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:77)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:66)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
```

Any step is missing to configure or how to fix it.

Thanks
Jason

**Comment by rubendel** [comment]
Could you try with 1.5.182?

**Comment by zaqifathis** [comment]
does this solved with latest BIMserver version 1.5.185?
