### ISSUE TITLE
BIMServer does not render IFC4 files from ARCHICAD 23

### ISSUE THREAD

**Issue by GiacomoManzoli** [opensourceBIM/BIMserver#1103]
**Describe the bug**
BIMServer can't correctly render an IFC4 project coming from ARCHICAD23 (IFC4 Reference View preset).
The same project exported in IFC2X3 is displayed correctly.

Looking at the geometry generation error there are several of this exception (one for each object)

```
java.lang.Exception: Missing objects in model (233 (329256))
	at org.bimserver.geometry.GeometryRunner.run(GeometryRunner.java:833)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
-

**Expected behavior**
-

**Screenshots**
IFC2X3 model:
<img src="https://user-images.githubusercontent.com/6218623/73768470-56237280-4779-11ea-8441-6e5bb3353e83.png">

**Additional context**

The attached ZIP contains the IFC files used and the geometry generation error for the IFC4 file.

[ac23_files.zip](https://github.com/opensourceBIM/BIMserver/files/4154830/ac23_files.zip)

**Comment by GiacomoManzoli** [comment]
Any news on this?

**Comment by rubendel** [comment]
I think this is an IfcOpenShell issue (@aothms). IfcConvert output (of the original file):
```
[Error] {2_0t5adjcdHROjPUf3_J6n} No operation defined for:
#178=IfcPolygonalFaceSet(#148,.T.,(#182,#188,#191,#194,#197,#200,#203,#206,#209,#212,#215,#218,#221,#224,#227,#230),$)
[Error] {2_0t5adjcdHROjPUf3_J6n} No operation defined for:
#272=IfcPolygonalFaceSet(#242,.T.,(#274,#279,#285,#288,#291,#294,#297,#300,#303,#306,#312,#318,#321,#324,#327,#330),$)
[Error] {0wsz9vPwCSJvku2SNOJnyW} No operation defined for:
#669=IfcPolygonalFaceSet(#655,.T.,(#671,#674,#677,#680,#683,#686,#689,#692),$)
[Error] {0wsz9vPwCSJvku2SNOJnyW} No operation defined for:
#716=IfcPolygonalFaceSet(#702,.T.,(#718,#721,#724,#727,#730,#733,#736,#739),$)
[Error] {0wsz9vPwCSJvku2SNOJnyW} No operation defined for:
#767=IfcPolygonalFaceSet(#745,.T.,(#769,#772,#775,#778,#781,#784,#787,#790,#793,#796,#799,#802),$)
[Error] {0wsz9vPwCSJvku2SNOJnyW} No operation defined for:
#830=IfcPolygonalFaceSet(#808,.T.,(#832,#835,#838,#841,#844,#847,#850,#853,#856,#859,#862,#865),$)
[Error] {0wsz9vPwCSJvku2SNOJnyW} No operation defined for:
#881=IfcPolygonalFaceSet(#871,.T.,(#883,#886,#889,#892,#895,#898),$)
[Error] {0wsz9vPwCSJvku2SNOJnyW} No operation defined for:
#914=IfcPolygonalFaceSet(#904,.T.,(#916,#919,#922,#925,#928,#931),$)
[Error] {0wsz9vPwCSJvku2SNOJnyW} No operation defined for:
#951=IfcPolygonalFaceSet(#937,.T.,(#953,#956,#959,#962,#965,#968,#971,#974),$)
[Error] {0wsz9vPwCSJvku2SNOJnyW} No operation defined for:
#994=IfcPolygonalFaceSet(#980,.T.,(#996,#999,#1002,#1005,#1008,#1011,#1014,#1017),$)
[Error] {0wsz9vPwCSJvku2SNOJnyW} No operation defined for:
#1029=IfcPolygonalFaceSet(#1023,.F.,(#1031),$)
[Error] {0wsz9vPwCSJvku2SNOJnyW} No operation defined for:
#1047=IfcPolygonalFaceSet(#1041,.F.,(#1049),$)
[Error] {0qAkItCO6dGhDqDk_D8CMi} No operation defined for:
#1134=IfcPolygonalFaceSet(#1124,.T.,(#1136,#1139,#1142,#1145,#1148,#1151),$)
[Error] {0qAkItCO6dGhDqDk_D8CMi} No operation defined for:
#1167=IfcPolygonalFaceSet(#1157,.T.,(#1169,#1172,#1175,#1178,#1181,#1184),$)
[Error] {0qAkItCO6dGhDqDk_D8CMi} No operation defined for:
#1200=IfcPolygonalFaceSet(#1190,.T.,(#1202,#1205,#1208,#1211,#1214,#1217),$)
[Error] {0qAkItCO6dGhDqDk_D8CMi} No operation defined for:
#1233=IfcPolygonalFaceSet(#1223,.T.,(#1235,#1238,#1241,#1244,#1247,#1250),$)
[Error] {0qAkItCO6dGhDqDk_D8CMi} No operation defined for:
#1266=IfcPolygonalFaceSet(#1256,.T.,(#1268,#1271,#1274,#1277,#1280,#1283),$)
[Error] {0qAkItCO6dGhDqDk_D8CMi} No operation defined for:
#1299=IfcPolygonalFaceSet(#1289,.T.,(#1301,#1304,#1307,#1310,#1313,#1316),$)
[Error] {0qAkItCO6dGhDqDk_D8CMi} No operation defined for:
#1332=IfcPolygonalFaceSet(#1322,.T.,(#1334,#1337,#1340,#1343,#1346,#1349),$)
[Error] {0qAkItCO6dGhDqDk_D8CMi} No operation defined for:
#1365=IfcPolygonalFaceSet(#1355,.T.,(#1367,#1370,#1373,#1376,#1379,#1382),$)
[Error] {0qAkItCO6dGhDqDk_D8CMi} No operation defined for:
#1398=IfcPolygonalFaceSet(#1388,.T.,(#1400,#1403,#1406,#1409,#1412,#1415),$)
[Error] {0qAkItCO6dGhDqDk_D8CMi} No operation defined for:
#1435=IfcPolygonalFaceSet(#1421,.T.,(#1437,#1440,#1443,#1446,#1449,#1452,#1455,#1458),$)
[Error] {0qAkItCO6dGhDqDk_D8CMi} No operation defined for:
#1478=IfcPolygonalFaceSet(#1464,.T.,(#1480,#1483,#1486,#1489,#1492,#1495,#1498,#1501),$)
[Error] {0qAkItCO6dGhDqDk_D8CMi} No operation defined for:
#1529=IfcPolygonalFaceSet(#1507,.T.,(#1531,#1534,#1537,#1540,#1543,#1546,#1549,#1552,#1555,#1558,#1561,#1564),$)
[Error] {0qAkItCO6dGhDqDk_D8CMi} No operation defined for:
#1580=IfcPolygonalFaceSet(#1570,.T.,(#1582,#1585,#1588,#1591,#1594,#1597),$)
[Error] {0qAkItCO6dGhDqDk_D8CMi} No operation defined for:
#1613=IfcPolygonalFaceSet(#1603,.T.,(#1615,#1618,#1621,#1624,#1627,#1630),$)
[Error] {0qAkItCO6dGhDqDk_D8CMi} No operation defined for:
#1650=IfcPolygonalFaceSet(#1636,.T.,(#1652,#1655,#1658,#1661,#1664,#1667,#1670,#1673),$)
[Error] {0qAkItCO6dGhDqDk_D8CMi} No operation defined for:
#1693=IfcPolygonalFaceSet(#1679,.T.,(#1695,#1698,#1701,#1704,#1707,#1710,#1713,#1716),$)
[Error] {0qAkItCO6dGhDqDk_D8CMi} No operation defined for:
#1728=IfcPolygonalFaceSet(#1722,.F.,(#1730),$)
[Error] {0qAkItCO6dGhDqDk_D8CMi} No operation defined for:
#1742=IfcPolygonalFaceSet(#1736,.F.,(#1744),$)
[Error] {2N307gxSslIhk9GKzxa6H1} No operation defined for:
#1866=IfcPolygonalFaceSet(#1836,.T.,(#1868,#1873,#1876,#1879,#1882,#1885,#1888,#1891,#1894,#1897,#1900,#1903,#1906,#1909,#1912,#1915),$)
[Error] {2N307gxSslIhk9GKzxa6H1} No operation defined for:
#1953=IfcPolygonalFaceSet(#1923,.T.,(#1955,#1960,#1966,#1969,#1972,#1975,#1978,#1981,#1984,#1987,#1993,#1999,#2002,#2005,#2008,#2011),$)
[Error] {165vMnbvtoIxiCEWPhJf_j} No operation defined for:
#2289=IfcPolygonalFaceSet(#2275,.T.,(#2291,#2294,#2297,#2300,#2303,#2306,#2309,#2312),$)
[Error] {165vMnbvtoIxiCEWPhJf_j} No operation defined for:
#2332=IfcPolygonalFaceSet(#2318,.T.,(#2334,#2337,#2340,#2343,#2346,#2349,#2352,#2355),$)
[Error] {165vMnbvtoIxiCEWPhJf_j} No operation defined for:
#2383=IfcPolygonalFaceSet(#2361,.T.,(#2385,#2388,#2391,#2394,#2397,#2400,#2403,#2406,#2409,#2412,#2415,#2418),$)
[Error] {165vMnbvtoIxiCEWPhJf_j} No operation defined for:
#2446=IfcPolygonalFaceSet(#2424,.T.,(#2448,#2451,#2454,#2457,#2460,#2463,#2466,#2469,#2472,#2475,#2478,#2481),$)
[Error] {165vMnbvtoIxiCEWPhJf_j} No operation defined for:
#2497=IfcPolygonalFaceSet(#2487,.T.,(#2499,#2502,#2505,#2508,#2511,#2514),$)
[Error] {165vMnbvtoIxiCEWPhJf_j} No operation defined for:
#2530=IfcPolygonalFaceSet(#2520,.T.,(#2532,#2535,#2538,#2541,#2544,#2547),$)
[Error] {165vMnbvtoIxiCEWPhJf_j} No operation defined for:
#2567=IfcPolygonalFaceSet(#2553,.T.,(#2569,#2572,#2575,#2578,#2581,#2584,#2587,#2590),$)
[Error] {165vMnbvtoIxiCEWPhJf_j} No operation defined for:
#2610=IfcPolygonalFaceSet(#2596,.T.,(#2612,#2615,#2618,#2621,#2624,#2627,#2630,#2633),$)
[Error] {165vMnbvtoIxiCEWPhJf_j} No operation defined for:
#2645=IfcPolygonalFaceSet(#2639,.F.,(#2647),$)
[Error] {165vMnbvtoIxiCEWPhJf_j} No operation defined for:
#2659=IfcPolygonalFaceSet(#2653,.F.,(#2661),$)
[Error] {3jIARH1YFlIO5Gf_AEnO63} No operation defined for:
#1134=IfcPolygonalFaceSet(#1124,.T.,(#1136,#1139,#1142,#1145,#1148,#1151),$)
[Error] {3jIARH1YFlIO5Gf_AEnO63} No operation defined for:
#1167=IfcPolygonalFaceSet(#1157,.T.,(#1169,#1172,#1175,#1178,#1181,#1184),$)
[Error] {3jIARH1YFlIO5Gf_AEnO63} No operation defined for:
#1200=IfcPolygonalFaceSet(#1190,.T.,(#1202,#1205,#1208,#1211,#1214,#1217),$)
[Error] {3jIARH1YFlIO5Gf_AEnO63} No operation defined for:
#1233=IfcPolygonalFaceSet(#1223,.T.,(#1235,#1238,#1241,#1244,#1247,#1250),$)
[Error] {3jIARH1YFlIO5Gf_AEnO63} No operation defined for:
#1266=IfcPolygonalFaceSet(#1256,.T.,(#1268,#1271,#1274,#1277,#1280,#1283),$)
[Error] {3jIARH1YFlIO5Gf_AEnO63} No operation defined for:
#1299=IfcPolygonalFaceSet(#1289,.T.,(#1301,#1304,#1307,#1310,#1313,#1316),$)
[Error] {3jIARH1YFlIO5Gf_AEnO63} No operation defined for:
#1332=IfcPolygonalFaceSet(#1322,.T.,(#1334,#1337,#1340,#1343,#1346,#1349),$)
[Error] {3jIARH1YFlIO5Gf_AEnO63} No operation defined for:
#1365=IfcPolygonalFaceSet(#1355,.T.,(#1367,#1370,#1373,#1376,#1379,#1382),$)
[Error] {3jIARH1YFlIO5Gf_AEnO63} No operation defined for:
#1398=IfcPolygonalFaceSet(#1388,.T.,(#1400,#1403,#1406,#1409,#1412,#1415),$)
[Error] {3jIARH1YFlIO5Gf_AEnO63} No operation defined for:
#1435=IfcPolygonalFaceSet(#1421,.T.,(#1437,#1440,#1443,#1446,#1449,#1452,#1455,#1458),$)
[Error] {3jIARH1YFlIO5Gf_AEnO63} No operation defined for:
#1478=IfcPolygonalFaceSet(#1464,.T.,(#1480,#1483,#1486,#1489,#1492,#1495,#1498,#1501),$)
[Error] {3jIARH1YFlIO5Gf_AEnO63} No operation defined for:
#1529=IfcPolygonalFaceSet(#1507,.T.,(#1531,#1534,#1537,#1540,#1543,#1546,#1549,#1552,#1555,#1558,#1561,#1564),$)
[Error] {3jIARH1YFlIO5Gf_AEnO63} No operation defined for:
#1580=IfcPolygonalFaceSet(#1570,.T.,(#1582,#1585,#1588,#1591,#1594,#1597),$)
[Error] {3jIARH1YFlIO5Gf_AEnO63} No operation defined for:
#1613=IfcPolygonalFaceSet(#1603,.T.,(#1615,#1618,#1621,#1624,#1627,#1630),$)
[Error] {3jIARH1YFlIO5Gf_AEnO63} No operation defined for:
#1650=IfcPolygonalFaceSet(#1636,.T.,(#1652,#1655,#1658,#1661,#1664,#1667,#1670,#1673),$)
[Error] {3jIARH1YFlIO5Gf_AEnO63} No operation defined for:
#1693=IfcPolygonalFaceSet(#1679,.T.,(#1695,#1698,#1701,#1704,#1707,#1710,#1713,#1716),$)
[Error] {3jIARH1YFlIO5Gf_AEnO63} No operation defined for:
#1728=IfcPolygonalFaceSet(#1722,.F.,(#1730),$)
[Error] {3jIARH1YFlIO5Gf_AEnO63} No operation defined for:
#1742=IfcPolygonalFaceSet(#1736,.F.,(#1744),$)
[Error] {2lIpgkfHpCIgLLygyyP4LF} No operation defined for:
#2803=IfcPolygonalFaceSet(#2793,.T.,(#2805,#2808,#2811,#2814,#2817,#2820),$)
[Error] {2lIpgkfHpCIgLLygyyP4LF} No operation defined for:
#2836=IfcPolygonalFaceSet(#2826,.T.,(#2838,#2841,#2844,#2847,#2850,#2853),$)
[Error] {0zHtz9MSHOGwll074SiXpy} No operation defined for:
#2933=IfcPolygonalFaceSet(#2919,.T.,(#2935,#2938,#2941,#2944,#2947,#2950,#2953,#2956,#2959,#2962,#2965,#2968),$)
[Error] {0zHtz9MSHOGwll074SiXpy} No operation defined for:
#2992=IfcPolygonalFaceSet(#2978,.T.,(#2994,#2997,#3000,#3003,#3006,#3009,#3012,#3015,#3018,#3021,#3024,#3027),$)
[Error] {1xkL7jagxkJvFqacrPZK7X} No operation defined for:
#3140=IfcPolygonalFaceSet(#3090,.T.,(#3142,#3145,#3154,#3157,#3166,#3169,#3172,#3175,#3178,#3181,#3184,#3187,#3190,#3193,#3196,#3199,#3202,#3205,#3208,#3211,#3214,#3217,#3220,#3223,#3226,#3229),$)
[Error] {1xkL7jagxkJvFqacrPZK7X} No operation defined for:
#3249=IfcPolygonalFaceSet(#3239,.T.,(#3251,#3254,#3257,#3260,#3263,#3266),$)
[Error] {1mYX3l_fIbJPeKCCYb_mqM} No operation defined for:
#3348=IfcPolygonalFaceSet(#3338,.T.,(#3350,#3353,#3356,#3359,#3362,#3365),$)
```

**Comment by hlg** [comment]
This issue will be resolved with the next plugin version for IfcOpenShell: https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin/commit/732da2348c6eaeda446f4d058ad5c94d4a2ce0e5. As an immediate workaround, the engine version can be changed in a running BIMserver instance through the IfcOpenShell plugin's settings. The setting _Commit Sha_ would have to be changed to "3bbdc3f".
