### ISSUE TITLE
IfcPropertySetDefinitionSet (IFC4)

### ISSUE THREAD

**Issue by hlg** [opensourceBIM/BIMserver#1109]
IfcPropertySetDefinitionSet is a new defined type in IFC4. It is part of a select type that allows either a set of property sets or a single property set (IfcPropertySetDefinition) to be referred from IfcRelDefinesByProperties . Instead of just changing the cardinality of IfcRelDefinesByProperties.RelatingPropertyDefinition to S[1:?] this select type was apparently introduced assuming that it would help with forward compatibility.

BIMserver seems not to support this type and fails with "IFCPROPERTYSETDEFINITIONSET is not an existing IFC entity". Here is a sample file: [ifcpropertysetdefinitionset.ifc.txt](https://github.com/opensourceBIM/BIMserver/files/4204434/ifcpropertysetdefinitionset.ifc.txt). Is this a known issue?

**Comment by hlg** [comment]
A similar issue, a defined type resolving to a list, is mentioned as wont-fix-issue in the [wiki](https://github.com/opensourceBIM/BIMserver/wiki/Known-Issues#user-content-other-ifc2x3-problems) (for IfcCompoundPlaneAngleMeasure). But I believe this is actually solved, isn't it?

**Comment by rubendel** [comment]
Interesting find. The IfcPropertySetDefinitionSet class is not even generated by EMF. So I am pretty sure this is missing from the BuildingSMARTLibrary [1]. I suspect it simply never happened before that a type is defined as a set of entities (or maybe not even that a type is defined as an entity). I have to say I find this a rather strange construct, but surely it should be supported by BIMserver.

Leaving this issue open, I currently don't have time to look into it.

As for the IfcCompoundPlaneAngleMeasure, I don't think that has been fixed either. If you look at the IfcCompoundPlaneAngleMeasure.java code [2] (or the IFC4 version), it only has a single `long` value where it should have a list here as well.

[1] https://github.com/opensourceBIM/BuildingSMARTLibrary
[2] https://github.com/opensourceBIM/BIMserver/blob/master/PluginBase/generated/org/bimserver/models/ifc2x3tc1/IfcCompoundPlaneAngleMeasure.java

**Comment by hlg** [comment]
Ah, I see. I had just checked the `refLatitude` and `refLongitute` attributes in `IfcSite` for some projects, because that is a prominent place where `IfcCompoundPlaneAngleMeasure` is used. That's why I thought it was fixed, but now I see that these attributes are directly represented as `EList<Long>`. The other usage is in a large value select mainly properties, where it will not work then.

**Comment by hlg** [comment]
Other IFC4 defined types similar to `IfcCompoundPlaneAngleMeasure` are `IfcLineIndex` and `IfcArcIndex` (both `IfcSegmentIndexSelect`). Those are "hacked" different from the angle measure - as wrapped values. However, they are not properly processed by the `DownloadByNewJsonQueryDatabaseAction`:

~~~
org.bimserver.BimserverDatabaseException: java.lang.NullPointerException
        at org.bimserver.database.actions.DownloadByNewJsonQueryDatabaseAction.execute(DownloadByNewJsonQueryDatabaseAction.java:306)
        at org.bimserver.database.actions.DownloadByNewJsonQueryDatabaseAction.execute(DownloadByNewJsonQueryDatabaseAction.java:73)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:775)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:767)
        at org.bimserver.longaction.LongDownloadOrCheckoutAction.executeAction(LongDownloadOrCheckoutAction.java:121)
        at org.bimserver.longaction.LongDownloadAction.execute(LongDownloadAction.java:50)
        at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:55)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: null
        at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eDerivedStructuralFeatureID(BasicEObjectImpl.java:1536)
        at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1047)
        at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1042)
        at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1037)
        at org.bimserver.database.actions.DownloadByNewJsonQueryDatabaseAction.execute(DownloadByNewJsonQueryDatabaseAction.java:260)
        ... 11 common frames omitted
~~~

It seems like they are not properly populated by the object provider. However, these constructions are working for the geometry generation queries as well as for the SharedStreamingJsonSerializer. Probably, the non-streaming download should work similar.
