### ISSUE TITLE
checkin上传ifc文件最后报java.lang.NullPointerException版本bimserverjar-1.5.88.jar

### ISSUE THREAD

**Issue by tianxiaW** [opensourceBIM/BIMserver#1119]
ERROR [pool-2-thread-2] o.b.StreamingGeometryGenerator [StreamingGeometryGenerator.java:586] 
org.bimserver.BimserverDatabaseException: org.bimserver.BimserverDatabaseException: Database session is closed
	at org.bimserver.database.queries.QueryObjectProvider.next(QueryObjectProvider.java:156)
	at org.bimserver.StreamingGeometryGenerator$Runner.run(StreamingGeometryGenerator.java:167)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by rubendel** [comment]
Closing issue as no context has been provided. Also 1.5.88 is a very old **development** version.
