### ISSUE TITLE
Geometry debug file creation fails for URL-checkins

### ISSUE THREAD

**Issue by hlg** [opensourceBIM/BIMserver#1121]
When checking in from an URL, the folder which is supposed to contain the geometry debug files, will not be created. This is probably due to invalid characters in the generated file name, maybe the slashes in the URL which appears to be included in the folder name (unescaped).

    19:51:30 ERROR [GeometryRunner]:                                                                                  (GeometryRunner.java:853) 
    java.nio.file.FileSystemException: /path/to/bimserver/home/debug/2020-03-08-19-51-15 (https:: Invalid argument
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
        at java.nio.file.Files.createDirectory(Files.java:674)
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
        at java.nio.file.Files.createDirectories(Files.java:767)
        at org.bimserver.geometry.GeometryRunner.writeDebugFile(GeometryRunner.java:1252)
        at org.bimserver.geometry.GeometryRunner.run(GeometryRunner.java:848)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by rubendel** [comment]
I think fixing this can be combined with https://github.com/opensourceBIM/BIMserver/issues/1006.

**Comment by hlg** [comment]
The following has likely happened here: the name of the directory to be created was containing the full URL, such that the OS has split it into a nested directory structure, where the outermost folder ended with "https:". Directory creation was then rejected due to the colon not allowed in directory or file names.

I can not reproduce this exact error anymore. There are serveral ways to checkin via URL: sync, async, via BIMvie.ws, via console/API. When I use console/API and explicitly put the URL into the file name (where it does not belong), the URL will end up in the directory name, creating the nested structure as seen in the original error, just that my current OS tolerates the colon in the name. My old OS back in 2020 probably did not accept this. Apart from unifying the various ways of creating incoming and debug file and directory names as mentioned in #1006, the file and directory names need proper escaping, not just of spaces.

Here is an overview of current behaviour in terms of debug directory names under Ubuntu 20.04.1 LTS, with streaming IFC4 deserializer:

* BIMviews:  `YYYY-MM-DD-HH-mm-ss (fileNameFromUrl)`
* Console/API sync, fileName empty: `YYYY-MM-DD-HH-mm-ss ()`
* Console/API sync, fileName explicit (valid): `YYYY-MM-DD-HH-mm-ss (fileName)`
* Console/API sync, fileName explicit (URL): `YYYY-MM-DD-HH-mm-ss (nested/directory/structure)`
* Console/API async, fileName empty: _fail_
* Console/API async, fileName explicit (valid): `YYYY-MM-DD-HH-mm-ss (fileName)`
* Console/API sync, fileName explicit (URL): _fail_

The failures are due to failure to create or find the file in incoming.
