### ISSUE TITLE
checkin issue

### ISSUE THREAD

**Issue by motjokk** [opensourceBIM/BIMserver#1130]
Running 1.5.182. 

NULL is returned.

`2020-03-19 21:20:21,172 INFO [pool-1-thread-18] o.b.g.StreamingGeometryGenerator [StreamingGeometryGenerator.java:655] Rendertime: 60ms, Reused (by hash): 0 B, Reused (by transformation): 0 B, Reused (by mapping): 0 B, Total: 0 B, Final: 0 B
2020-03-19 21:20:21,233 ERROR [pool-1-thread-18] o.b.l.LongAction [LongAction.java:196] [null] [AC-IFC4-DTV.ifc] null
org.bimserver.shared.exceptions.UserException: [AC-IFC4-DTV.ifc] null
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:412)
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:84)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:775)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:752)
        at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:73)
        at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:55)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: null
        at org.bimserver.database.actions.GenericCheckinDatabaseAction.generateDensityAndBounds(GenericCheckinDatabaseAction.java:354)
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:247)
        ... 10 common frames omitted
`

**Comment by rubendel** [comment]
Could you provide a bit more information? For example, are you using BIMvie.ws to upload, or using the API from your own application? Are other files working? Can you share the IFC file, or a similar file that triggers the same behavior. Was it working on a previous version?

**Comment by motjokk** [comment]
This is what im doing from my application:

1. Create Project
2. Checkin IFC4 - checkinSync success
3. Create Sub-Project
4. Checkin IFC4 - checkinSync success
5. Create Sub-Project
6. Checkin Ifc2x3tc1 - checkinFromUrl fails

After doing this, I`m not able to checkin ( from Bimvie.ws or my own application. Same error given.
Performing step 1-6 in Bimvie.ws gives no errors.

**Comment by rubendel** [comment]
That is very specific combination of functionalities. Could you please trim down the amount of variables in order to reproduce this?
- Ifc2x3tc1 and Ifc4 files
- Project structure
- checkinSync and checkinFromUrl
- Use or don't use BIMvie.ws

I can't imagine this only happens when using all of these intermingled.

**Comment by motjokk** [comment]
I forgot to mention that I also change the model, and commit those changes. This seems to be a part of the issue. Files get checked in without any problem if I don't change any of the models.

**Comment by rubendel** [comment]
Ok, so even more variables. Again, please try to come up with a minimal set of actions to reproduce the problem.

**Comment by motjokk** [comment]
It seems making changes to `AC-IFC4-DTV.ifc`  at the second level, leaves me unable to chekin `Bygg.D.ifc`. 

![image](https://user-images.githubusercontent.com/33512457/77293508-c6169980-6ce2-11ea-9006-8798396ea1be.png)

Not sure if it's useful, but here are the files:
The file I'm chekin in and making changes to - Level one and two. (change Name and LongName).
[AC-IFC4-DTV.txt](https://github.com/opensourceBIM/BIMserver/files/4367997/AC-IFC4-DTV.txt)

The file I'm chekin in at the third level
[Bygg D.txt](https://github.com/opensourceBIM/BIMserver/files/4368015/Bygg.D.txt)

**Comment by motjokk** [comment]
When trying to download sub-project on run two, I get empty serializer list. I think this may be a lead at least.


![image](https://user-images.githubusercontent.com/33512457/78333666-8aa18800-758a-11ea-88fb-5714d6e04dd6.png)

**Comment by motjokk** [comment]
This seems to be fixed in 1.5.182
