### ISSUE TITLE
Cannot install plugins for BIMserver 1.5.181-1.5.182

### ISSUE THREAD

**Issue by Jobcrazy** [opensourceBIM/BIMserver#1134]
![BIMserver](https://user-images.githubusercontent.com/4137239/79035986-24ee7500-7bf6-11ea-92b7-dbd2224f62f3.png)

It always says: "Required dependency com.fasterxml.woodstox:woodstox-core is not installed." I use java8 212 and 241 to test, everthing is the same.

And the log is as below:
13:02:23 INFO  [PluginInterface.installPluginBundle]: 0.0.184                                                                          (InstallPluginBundle.java:70) 
org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact com.fasterxml.woodstox:woodstox-core:jar:5.1.0 from/to central (https://repo1.maven.org/maven2/): status code: 416, reason phrase: Range Not Satisfiable (416)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.bimserver.plugins.MavenPluginLocation.getVersionJar(MavenPluginLocation.java:315)
	at org.bimserver.plugins.PluginBundleManager.loadDependencies(PluginBundleManager.java:214)
	at org.bimserver.plugins.PluginBundleManager.install(PluginBundleManager.java:134)
	at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPluginBundle.java:73)
	at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPluginBundle.java:35)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:775)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:767)
	at org.bimserver.webservices.impl.PluginServiceImpl.installPluginBundle(PluginServiceImpl.java:1420)
	at org.bimserver.generated.PluginInterfaceReflectoridGKrfLcVlly_1.callMethod(PluginInterfaceReflectoridGKrfLcVlly_1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:77)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:66)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:868)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact com.fasterxml.woodstox:woodstox-core:jar:5.1.0 from/to central (https://repo1.maven.org/maven2/): status code: 416, reason phrase: Range Not Satisfiable (416)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 51 more
Caused by: org.apache.http.client.HttpResponseException: status code: 416, reason phrase: Range Not Satisfiable (416)
	at org.eclipse.aether.transport.http.HttpTransporter.handleStatus(HttpTransporter.java:466)
	at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:291)
	at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:243)
	at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:59)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	... 56 more
13:02:46 ERROR [PluginInterface.installPluginBundle]:                                                                                  (InstallPluginBundle.java:75) 
java.lang.Exception: Required dependency com.fasterxml.woodstox:woodstox-core is not installed
	at org.bimserver.plugins.PluginBundleManager.loadDependencies(PluginBundleManager.java:222)
	at org.bimserver.plugins.PluginBundleManager.install(PluginBundleManager.java:134)
	at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPluginBundle.java:73)
	at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPluginBundle.java:35)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:775)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:767)
	at org.bimserver.webservices.impl.PluginServiceImpl.installPluginBundle(PluginServiceImpl.java:1420)
	at org.bimserver.generated.PluginInterfaceReflectoridGKrfLcVlly_1.callMethod(PluginInterfaceReflectoridGKrfLcVlly_1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:77)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:66)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:868)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Unknown Source)

**Comment by Jobcrazy** [comment]
My OS is Win10 LTSB

**Comment by Jobcrazy** [comment]
I test it on CentOS, it works well.
