### ISSUE TITLE
Usage of non-streaming Deserializer leads to ClassCastException

### ISSUE THREAD

**Issue by mis-nca** [opensourceBIM/BIMserver#1186]
I've been unsuccessfully trying to write and use a regular non-streaming `Deserializer`. As described on the [wiki-page here](https://github.com/opensourceBIM/BIMserver/wiki/Deserializer-Plugin), I implemented both interfaces (`Deserializer` and `DeserializerPlugin`) and was able to deploy it through the BIMvie.ws UI.
 
In order to test/use it, I did the following using the JSON-API:
1. Determined the `oid` of my `Deserializer` by using the `getAllDeserializerPluginDescriptors` method:
```
{
  "token": "bac6434f9091ca64d3ccc85900dbb8811132234411d6b5fffa8e8adfe05d22747b8e780a280e983c6eabc2effacf6caf",
  "request": {
    "interface": "PluginInterface",
    "method": "getAllDeserializerPluginDescriptors",
    "parameters": {
    }
  }
}
```

2. Then I tried to do a `checkInSync` and passed the `Deserializer's oid`:
```
{
  "token": "bac6434f9091ca64d3ccc85900dbb8811132234411d6b5fffa8e8adfe05d22747b8e780a280e983c6eabc2effacf6caf",
  "request": {
    "interface": "ServiceInterface",
    "method": "checkinSync",
    "parameters": {
        "poid" : 655361,
        "comment" : "My comment...",
        "deserializerOid" : 327734,
        "fileSize": 1,
        "fileName": "FileName",
        "data" : "IElTTy0xMDMwMy0yMTs...",
        "merge" : false
    }
  }
}
```

**->** However, this request fails due to a `ClassCastException`:
```
{
    "response": {
        "exception": {
            "__type": "ServerException",
            "message": "org.bimserver.models.store.impl.PluginDescriptorImpl cannot be cast to org.bimserver.models.store.DeserializerPluginConfiguration"
        }
    }
}
```

Here are the logs from the server:
```
2021-02-05 11:07:32,283 INFO [qtp1104654975-44] o.b.JsonHandler [JsonHandler.java:85] {"token":"bac6434f9091ca64d3ccc85900dbb8811132234411d6b5fffa8e8adfe05d22747b8e780a280e983c6eabc2effacf6caf","request":{"interface":"ServiceInterface","method":"checkinSync","parameters":{"poid":655361,"comment":"My comment...","deserializerOid":327734,"fileSize":1,"fileName":"FileName.ifc","data":"IElTTy0xMD...","merge":false}}}
2021-02-05 11:07:32,284 INFO [qtp1104654975-44] o.b.JsonHandler [JsonHandler.java:86] 
org.bimserver.shared.exceptions.ServerException: org.bimserver.models.store.impl.PluginDescriptorImpl cannot be cast to org.bimserver.models.store.DeserializerPluginConfiguration
	at org.bimserver.webservices.impl.ServiceImpl.checkinInitiatedInternal(ServiceImpl.java:1109)
	at org.bimserver.webservices.impl.ServiceImpl.checkinInitiatedSync(ServiceImpl.java:1165)
	at org.bimserver.webservices.impl.ServiceImpl.checkinSync(ServiceImpl.java:1240)
	at org.bimserver.generated.ServiceInterfaceReflectorneozmnEcKHSv_1.callMethod(ServiceInterfaceReflectorneozmnEcKHSv_1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:77)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:66)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:868)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: org.bimserver.models.store.impl.PluginDescriptorImpl cannot be cast to org.bimserver.models.store.DeserializerPluginConfiguration
	at org.bimserver.webservices.impl.ServiceImpl.checkinInternal(ServiceImpl.java:1178)
	at org.bimserver.webservices.impl.ServiceImpl.checkinInitiatedInternal(ServiceImpl.java:1094)
	... 42 common frames omitted
```

So, it seems like non of my `Deserializer` nor `DeserializerPlugin` method gets called. My implementation is largely inspired by the [IfcPlugin's JsonDeserializer](https://github.com/opensourceBIM/IfcPlugins/blob/master/IfcPlugins/src/org/bimserver/deserializers/JsonDeserializer.java) except for the `read` method which does currently nothing (therefore I won't add it here). I tried to use the `JsonDeserializer` from the IfcPlugins as well, the same exception appeared...

I noticed that there is also a `StreamingDeserializer`, are regular/non-streaming `Deserializers` no longer supported?

**Expected behavior**
What I would expect is that the `Deserializer's read` method gets called without an exception.

**Additional context**
Versions tried: [1.5.162 (latest)](https://github.com/opensourceBIM/BIMserver/releases/tag/v1.5.162) and [1.5.182 (pre-release)](https://github.com/opensourceBIM/BIMserver/releases/tag/v1.5.182)

**Comment by hlg** [comment]
For checkin, you are currently using the OID of the deserializer's plugin descriptor, not the OID of the deserializer as configured for the current user. You can get hold of the desired deserializer OID by any of the following API methods:

* `PluginInterface.getAllDeserializers`
* `PluginInterface.getAllDeserializersForProject`
* `ServiceInterface.getDeserializerById` (You would have to know the ID that your are just trying find out.)
* `ServiceInterface.getDeserializerByName`
* `ServiceInterface.getSuggestedDeserializerForExtension` (If there are multiple deserializers that can handle the particular extension and the IFC schema version of the project, this will return the first one with a preference for the streaming versions.)

For a quick test, you should also see your plugin in the list of deserializers when you attempt a checkin through BIMvie.ws.

I just realized that the method you've used, `PluginInterface.getAllDeserializerPluginDescriptors`, does not include the descriptors of streaming deserializers (same serializers), though it probably should as there is no corresponding method for the streaming version. This is a minor bug and should be easy to fix.

Non-streaming serializers and deserializers should still be working, but most implementations in IfcPlugins have already been removed from the plugin bundle and in general, the streaming versions are preferred. Do you have a case for the non-streaming version?

**Comment by michael-stadler-netcetera** [comment]
Thank you for your quick reply.

> For checkin, you are currently using the OID of the deserializer's plugin descriptor, not the OID of the deserializer as configured for a particular user.

Indeed, I was using the wrong ID. However, I'm now getting a different ClassCastException when using the JSON-API:
```
{
    "response": {
        "exception": {
            "__type": "ServerException",
            "message": "org.bimserver.interfaces.objects.SLongActionState cannot be cast to org.bimserver.interfaces.objects.SLongCheckinActionState"
        }
    }
}
```
The logs from the server are as follows:
```
2021-02-08 11:37:14,227 INFO [qtp1244263056-32] o.b.JsonHandler [JsonHandler.java:85] {"token":"015bda4ccb575ac62f2634f5490719769204061e11e0c1c614e73a4bf80376ce7b8e780a280e983c6eabc2effacf6caf","request":{"interface":"ServiceInterface","method":"checkinSync","parameters":{"poid":983041,"comment":"My comment...","deserializerOid":655401,"fileSize":1,"fileName":"FileName.json","data":"ewogICJ0eXBlIjogInR5cGUiOiAiSWZjRG9vciIsCiAgICAgICAgInJlZiI6ICIxNTdjODY2Yy05YzA4LTQzNDgtYTBlZC00ZDU3Y2Q2NmM5ZTIiCiAgICAgIH0KICAgIH0KICBdCn0=","merge":false}}}
2021-02-08 11:37:14,228 INFO [qtp1244263056-32] o.b.JsonHandler [JsonHandler.java:86] 
org.bimserver.shared.exceptions.ServerException: org.bimserver.interfaces.objects.SLongActionState cannot be cast to org.bimserver.interfaces.objects.SLongCheckinActionState
	at org.bimserver.webservices.impl.ServiceImpl.checkinInitiatedInternal(ServiceImpl.java:1109)
	at org.bimserver.webservices.impl.ServiceImpl.checkinInitiatedSync(ServiceImpl.java:1165)
	at org.bimserver.webservices.impl.ServiceImpl.checkinSync(ServiceImpl.java:1240)
	at org.bimserver.generated.ServiceInterfaceReflectoraeraktGWRyKc_1.callMethod(ServiceInterfaceReflectoraeraktGWRyKc_1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:77)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:66)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:868)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: org.bimserver.interfaces.objects.SLongActionState cannot be cast to org.bimserver.interfaces.objects.SLongCheckinActionState
	at org.bimserver.webservices.impl.ServiceImpl.checkinInternal(ServiceImpl.java:1207)
	at org.bimserver.webservices.impl.ServiceImpl.checkinInitiatedInternal(ServiceImpl.java:1094)
	... 42 common frames omitted
```

-> This seems to have been an [issue](https://github.com/opensourceBIM/BIMserver/issues/1016) in the past... Am I doing something else wrong or is this a regression?

> For a quick test, you should also see your plugin in the list of deserializers when you attempt a checkin through BIMvie.ws.

Right, my deserializer is visible there and can be used correctly.

**Comment by hlg** [comment]
This could indeed be a regression or a case never tested and reported. I will have a look at it later.

In the meantime, you can use the [upload servlet](https://github.com/opensourceBIM/BIMserver/wiki/Checkin#user-content-other-way) similar to [how the JavaScript Client does it](https://github.com/opensourceBIM/BIMserver-JavaScript-API/blob/74b42a77f264a36952e8b7ffe41af99dd0c0c4ca/bimserverclient.js#L817-L856). This method is also called from BIMvie.ws and thus it represents the most tested case (including issue #1016).
