### ISSUE TITLE
Deployed in Tomcat to report an error：Required dependency org.apache.httpcomponents:httpclient is not installed

### ISSUE THREAD

**Issue by DaLiangLee** [opensourceBIM/BIMserver#1189]
![image](https://user-images.githubusercontent.com/21189061/109623702-61152600-7b78-11eb-9654-a0840cc167c3.png)

.182
Tomcat 8
I used Tomcat to run successfully on my windows 10 before, but it failed on windows server 16. I need your help very much now, thank you

**Comment by hlg** [comment]
Make sure your system has an [outgoing internet connection](https://github.com/opensourceBIM/BIMserver/wiki/Outgoing-internet-connection), otherwise plugins with additional dependencies can not be installed even if uploaded from local. If you are sure your outgoing connection is properly working, it may be that either http://www.google.com (for the initial check) or the Maven repository (for dependencies) are temporarily not reachable. In that case, you have to repeat the whole setup procedure. There is already a feature request for a retry button to manage this case more conveniently: #942.

**Comment by DaLiangLee** [comment]
I am using a local plug-in...

> 确保您的系统具有[互联网连接](https://github.com/opensourceBIM/BIMserver/wiki/Outgoing-internet-connection)，否则，即使从本地上传，也无法安装具有其他依赖性的插件。如果您确定传出连接正常工作，则可能暂时无法访问http://www.google.com（用于初始检查）或Maven存储库（用于依赖项）。在这种情况下，您必须重复整个设置过程。已经有功能要求重试按钮以更方便地管理这种情况：[＃942](https://github.com/opensourceBIM/BIMserver/issues/942)。

![image](https://user-images.githubusercontent.com/21189061/109779247-b7e63280-7c40-11eb-9672-d5541af8affc.png)

**Comment by hlg** [comment]
Please do not post content in Chinese.

I understood that you installed the plugin from a local file. But if the plugin has additional dependencies, then it still needs an outgoing internet connection.

In the BIMvie.ws case however, there shouldn't be any additional dependencies. BIMvie.ws declares only a dependency that's in your BIMserver installation anyway and such dependencies should be skipped during plugin installation. Apparently they are not and that might be a bug due to local installations not being recommended and well-supported. In your previous setup, you may have had an internet connection at some point and those dependencies where then cached in your local Maven repository. Now you are lacking some of those dependencies.

If you can, I recommend to do the initial setup including plugin installation with an internet connection. You can work disconnected afterwards.

**Comment by DaLiangLee** [comment]
`
55300585 [org.bimserver.PluginInterface.installPluginBundleFromFile] INFO  o.i.IfcOpenShellEnginePlugin - Using overruled system setting for commit sha
55300594 [org.bimserver.PluginInterface.installPluginBundleFromFile] INFO  o.ifcopenshell.IfcGeomServerClient - Downloading from https://s3.amazonaws.com/ifcopenshell-builds/IfcGeomServer-v0.6.0-b4ce5be-win64.zip
55300595 [org.bimserver.PluginInterface.installPluginBundleFromFile] INFO  o.ifcopenshell.IfcGeomServerClient - Unzipping to C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\bimserverwar-1.5.182\WEB-INF\tmp\org.opensourcebim.ifcopenshellplugin\IfcGeomServer-v0.6.0-b4ce5be-win64.exe
55301831 [org.bimserver.PluginInterface.installPluginBundleFromFile] INFO  o.ifcopenshell.IfcGeomServerClient - IfcOpenShell Last Modified: Fri, 05 Jul 2019 03:01:37 GMT
55307059 [org.bimserver.PluginInterface.installPluginBundleFromFile] INFO  o.i.IfcOpenShellEnginePlugin - Using C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\bimserverwar-1.5.182\WEB-INF\tmp\org.opensourcebim.ifcopenshellplugin\IfcGeomServer-v0.6.0-b4ce5be-win64.exe
55307070 [org.bimserver.PluginInterface.installPluginBundleFromFile] INFO  o.i.IfcOpenShellEnginePlugin - Using overruled system setting for commit sha
55307071 [org.bimserver.PluginInterface.installPluginBundleFromFile] INFO  o.i.IfcOpenShellEnginePlugin - Using C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\bimserverwar-1.5.182\WEB-INF\tmp\org.opensourcebim.ifcopenshellplugin\IfcGeomServer-v0.6.0-b4ce5be-win64.exe
55307072 [org.bimserver.PluginInterface.installPluginBundleFromFile] INFO  org.bimserver.BimServer - Setting default render engine for user system to IfcOpenShell
55307072 [org.bimserver.PluginInterface.installPluginBundleFromFile] INFO  org.bimserver.BimServer - Setting default render engine for user admin@admin.com to IfcOpenShell
416  [localhost-startStop-1] INFO  org.bimserver.BimServer - Starting BIMserver (Windows Server 2016, 1.8.0_221, 64bit, Xmx: 3.50 GB)
2875 [localhost-startStop-1] INFO  o.b.web.WarServerInitializer - Servlet Context Name: BIMserver
2875 [localhost-startStop-1] INFO  org.bimserver.BimServer - Version: 1.5.182
2875 [localhost-startStop-1] INFO  org.bimserver.BimServer - Using "C:\Program Files\Apache Software Foundation\Tomcat 8.5\Tomcat 8.5\webapps\bimserverwar-1.5.182\WEB-INF" as homedir
5666 [pool-2-thread-3] INFO  org.bimserver.emf.PackageMetaData - Initializing GEOMETRY with geometry
5666 [pool-2-thread-1] INFO  org.bimserver.emf.PackageMetaData - Initializing IFC2X3TC1 with ifc2x3tc1
5666 [pool-2-thread-2] INFO  org.bimserver.emf.PackageMetaData - Initializing IFC4 with ifc4
5666 [pool-2-thread-4] INFO  org.bimserver.emf.PackageMetaData - Initializing STORE with store
5682 [pool-2-thread-3] INFO  org.bimserver.emf.PackageMetaData - Initializing LOG with log
7465 [localhost-startStop-1] INFO  o.b.d.b.BerkeleyKeyValueStore - Non-empty database directory found "C:\Program Files\Apache Software Foundation\Tomcat 8.5\Tomcat 8.5\webapps\bimserverwar-1.5.182\WEB-INF\database"
8666 [localhost-startStop-1] INFO  org.bimserver.BimServer - Checking for stale records, this can take some time...
8729 [localhost-startStop-1] INFO  org.bimserver.BimServer - Done checking for stale records (51 ms)
9524 [localhost-startStop-1] INFO  org.bimserver.ServerInfoManager - Changing server state to RUNNING
9524 [localhost-startStop-1] INFO  org.bimserver.BimServer - Initializing database dependant logic...
35994 [localhost-startStop-1] ERROR org.bimserver.BimServer - 
java.lang.Exception: Required dependency org.apache.httpcomponents:httpclient is not installed
	at org.bimserver.plugins.PluginBundleManager.loadDependencies(PluginBundleManager.java:222)
	at org.bimserver.plugins.PluginBundleManager.loadFromPluginDir(PluginBundleManager.java:250)
	at org.bimserver.BimServer.initDatabaseDependantItems(BimServer.java:1267)
	at org.bimserver.BimServer.start(BimServer.java:774)
	at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:117)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4705)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5171)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:938)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1784)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
37952 [localhost-startStop-1] ERROR org.bimserver.BimServer - 
java.lang.Exception: Required dependency org.apache.httpcomponents:httpclient is not installed
	at org.bimserver.plugins.PluginBundleManager.loadDependencies(PluginBundleManager.java:222)
	at org.bimserver.plugins.PluginBundleManager.loadFromPluginDir(PluginBundleManager.java:250)
	at org.bimserver.BimServer.initDatabaseDependantItems(BimServer.java:1267)
	at org.bimserver.BimServer.start(BimServer.java:774)
	at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:117)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4705)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5171)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:938)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1784)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
39692 [localhost-startStop-1] ERROR org.bimserver.BimServer - 
java.lang.Exception: Required dependency org.apache.httpcomponents:httpclient is not installed
	at org.bimserver.plugins.PluginBundleManager.loadDependencies(PluginBundleManager.java:222)
	at org.bimserver.plugins.PluginBundleManager.loadFromPluginDir(PluginBundleManager.java:250)
	at org.bimserver.BimServer.initDatabaseDependantItems(BimServer.java:1267)
	at org.bimserver.BimServer.start(BimServer.java:774)
	at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:117)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4705)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5171)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:938)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1784)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`
Our server cannot access google...
I copied the local Tomcat folder to my server, and this error occurred

**Comment by DaLiangLee** [comment]
> Please do not post content in Chinese.
> 
> I understood that you installed the plugin from a local file. But if the plugin has additional dependencies, then it still needs an outgoing internet connection.
> 
> In the BIMvie.ws case however, there shouldn't be any additional dependencies. BIMvie.ws declares only a dependency that's in your BIMserver installation anyway and such dependencies should be skipped during plugin installation. Apparently they are not and that might be a bug due to local installations not being recommended and well-supported. In your previous setup, you may have had an internet connection at some point and those dependencies where then cached in your local Maven repository. Now you are lacking some of those dependencies.
> 
> If you can, I recommend to do the initial setup including plugin installation with an internet connection. You can work disconnected afterwards.

`
2021-03-04 10:33:40,758 INFO [localhost-startStop-1] o.b.BimServer [BimServer.java:248] Starting BIMserver (Windows Server 2016, 1.8.0_221, 64bit, Xmx: 3.50 GB)
2021-03-04 10:33:43,411 INFO [localhost-startStop-1] o.b.w.WarServerInitializer [WarServerInitializer.java:114] Servlet Context Name: BIMserver
2021-03-04 10:33:43,411 INFO [localhost-startStop-1] o.b.BimServer [BimServer.java:336] Version: 1.5.182
2021-03-04 10:33:43,411 INFO [localhost-startStop-1] o.b.BimServer [BimServer.java:345] Using "C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\bimserverwar-1.5.182\WEB-INF" as homedir
2021-03-04 10:33:46,222 INFO [pool-2-thread-1] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing IFC2X3TC1 with ifc2x3tc1
2021-03-04 10:33:46,222 INFO [pool-2-thread-3] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing GEOMETRY with geometry
2021-03-04 10:33:46,230 INFO [pool-2-thread-3] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing LOG with log
2021-03-04 10:33:46,222 INFO [pool-2-thread-4] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing STORE with store
2021-03-04 10:33:46,222 INFO [pool-2-thread-2] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing IFC4 with ifc4
2021-03-04 10:33:47,810 INFO [localhost-startStop-1] o.b.d.b.BerkeleyKeyValueStore [BerkeleyKeyValueStore.java:87] Non-empty database directory found "C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\bimserverwar-1.5.182\WEB-INF\database"
2021-03-04 10:33:49,056 INFO [localhost-startStop-1] o.b.BimServer [BimServer.java:813] Checking for stale records, this can take some time...
2021-03-04 10:33:49,095 INFO [localhost-startStop-1] o.b.BimServer [BimServer.java:843] Done checking for stale records (40 ms)
2021-03-04 10:33:49,589 INFO [localhost-startStop-1] o.b.ServerInfoManager [ServerInfoManager.java:116] Changing server state to RUNNING
2021-03-04 10:33:49,589 INFO [localhost-startStop-1] o.b.BimServer [BimServer.java:1113] Initializing database dependant logic...
2021-03-04 10:33:52,478 ERROR [localhost-startStop-1] o.b.BimServer [BimServer.java:1269] 
java.lang.Exception: Required dependency org.apache.httpcomponents:httpclient is not installed
	at org.bimserver.plugins.PluginBundleManager.loadDependencies(PluginBundleManager.java:222)
	at org.bimserver.plugins.PluginBundleManager.loadFromPluginDir(PluginBundleManager.java:250)
	at org.bimserver.BimServer.initDatabaseDependantItems(BimServer.java:1267)
	at org.bimserver.BimServer.start(BimServer.java:774)
	at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:117)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4705)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5171)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:938)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1784)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-04 10:33:53,958 ERROR [localhost-startStop-1] o.b.BimServer [BimServer.java:1269] 
java.lang.Exception: Required dependency org.apache.httpcomponents:httpclient is not installed
	at org.bimserver.plugins.PluginBundleManager.loadDependencies(PluginBundleManager.java:222)
	at org.bimserver.plugins.PluginBundleManager.loadFromPluginDir(PluginBundleManager.java:250)
	at org.bimserver.BimServer.initDatabaseDependantItems(BimServer.java:1267)
	at org.bimserver.BimServer.start(BimServer.java:774)
	at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:117)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4705)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5171)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:938)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1784)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`



Our server cannot access google...
I copied the local Tomcat folder to my server, and this error occurred

**Comment by DaLiangLee** [comment]
![image](https://user-images.githubusercontent.com/21189061/109903199-74d69e80-7cd6-11eb-8c43-1724711eb857.png)
When the server can access google...

**Comment by DaLiangLee** [comment]
![image](https://user-images.githubusercontent.com/21189061/109923286-85e4d700-7cf9-11eb-87c1-a7c3e808e66e.png)

Repackage, change google.com to something else, and the progress has been like this...

**Comment by DaLiangLee** [comment]
![image](https://user-images.githubusercontent.com/21189061/109925320-8e8adc80-7cfc-11eb-8d82-59ebc9a11eb2.png)
![image](https://user-images.githubusercontent.com/21189061/109925357-98144480-7cfc-11eb-9b27-4a31d4a8c64a.png)
Half an hour after...

I think this is a very good open source project, but it is always a strange problem when installing, and each computer encounters a different problem. . .

**Comment by DaLiangLee** [comment]
Still did not succeed

**Comment by DaLiangLee** [comment]
`
2021-03-04 17:28:06,251 INFO [localhost-startStop-1] o.b.BimServer [BimServer.java:248] Starting BIMserver (Windows Server 2016, 1.8.0_281, 64bit, Xmx: 3.50 GB)
2021-03-04 17:28:08,671 INFO [localhost-startStop-1] o.b.w.WarServerInitializer [WarServerInitializer.java:114] Servlet Context Name: BIMserver
2021-03-04 17:28:08,671 INFO [localhost-startStop-1] o.b.BimServer [BimServer.java:336] Version: 1.5.182
2021-03-04 17:28:08,671 INFO [localhost-startStop-1] o.b.BimServer [BimServer.java:345] Using "C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\bimserverwar-1.5.182\WEB-INF" as homedir
2021-03-04 17:28:11,314 INFO [pool-2-thread-1] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing IFC2X3TC1 with ifc2x3tc1
2021-03-04 17:28:11,314 INFO [pool-2-thread-2] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing IFC4 with ifc4
2021-03-04 17:28:11,317 INFO [pool-2-thread-3] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing GEOMETRY with geometry
2021-03-04 17:28:11,326 INFO [pool-2-thread-3] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing LOG with log
2021-03-04 17:28:11,314 INFO [pool-2-thread-4] o.b.e.PackageMetaData [PackageMetaData.java:77] Initializing STORE with store
2021-03-04 17:28:13,367 INFO [localhost-startStop-1] o.b.d.b.BerkeleyKeyValueStore [BerkeleyKeyValueStore.java:87] Non-empty database directory found "C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\bimserverwar-1.5.182\WEB-INF\database"
2021-03-04 17:28:14,570 INFO [localhost-startStop-1] o.b.BimServer [BimServer.java:813] Checking for stale records, this can take some time...
2021-03-04 17:28:14,650 INFO [localhost-startStop-1] o.b.BimServer [BimServer.java:843] Done checking for stale records (79 ms)
2021-03-04 17:28:15,332 INFO [localhost-startStop-1] o.b.ServerInfoManager [ServerInfoManager.java:116] Changing server state to RUNNING
2021-03-04 17:28:15,333 INFO [localhost-startStop-1] o.b.BimServer [BimServer.java:1113] Initializing database dependant logic...
2021-03-04 17:28:18,888 ERROR [localhost-startStop-1] o.b.BimServer [BimServer.java:1269] 
java.lang.Exception: Required dependency org.apache.httpcomponents:httpclient is not installed
	at org.bimserver.plugins.PluginBundleManager.loadDependencies(PluginBundleManager.java:222)
	at org.bimserver.plugins.PluginBundleManager.loadFromPluginDir(PluginBundleManager.java:250)
	at org.bimserver.BimServer.initDatabaseDependantItems(BimServer.java:1267)
	at org.bimserver.BimServer.start(BimServer.java:774)
	at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:117)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4705)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5171)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1085)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1802)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-04 17:28:21,029 ERROR [localhost-startStop-1] o.b.BimServer [BimServer.java:1269] 
java.lang.Exception: Required dependency org.apache.httpcomponents:httpclient is not installed
	at org.bimserver.plugins.PluginBundleManager.loadDependencies(PluginBundleManager.java:222)
	at org.bimserver.plugins.PluginBundleManager.loadFromPluginDir(PluginBundleManager.java:250)
	at org.bimserver.BimServer.initDatabaseDependantItems(BimServer.java:1267)
	at org.bimserver.BimServer.start(BimServer.java:774)
	at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:117)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4705)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5171)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1085)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1802)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-04 17:28:22,891 ERROR [localhost-startStop-1] o.b.BimServer [BimServer.java:1269] 
java.lang.Exception: Required dependency org.apache.httpcomponents:httpclient is not installed
	at org.bimserver.plugins.PluginBundleManager.loadDependencies(PluginBundleManager.java:222)
	at org.bimserver.plugins.PluginBundleManager.loadFromPluginDir(PluginBundleManager.java:250)
	at org.bimserver.BimServer.initDatabaseDependantItems(BimServer.java:1267)
	at org.bimserver.BimServer.start(BimServer.java:774)
	at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:117)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4705)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5171)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1085)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1802)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-04 17:28:25,354 ERROR [localhost-startStop-1] o.b.BimServer [BimServer.java:1269] 
java.lang.Exception: Required dependency org.apache.httpcomponents:httpclient is not installed
	at org.bimserver.plugins.PluginBundleManager.loadDependencies(PluginBundleManager.java:222)
	at org.bimserver.plugins.PluginBundleManager.loadFromPluginDir(PluginBundleManager.java:250)
	at org.bimserver.BimServer.initDatabaseDependantItems(BimServer.java:1267)
	at org.bimserver.BimServer.start(BimServer.java:774)
	at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:117)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4705)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5171)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1085)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1802)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by DaLiangLee** [comment]
...

**Comment by hlg** [comment]
Thanks for the additional detail, though please don't use screenshots for console output, log files etc. next time.

I can't see the bottom of your last screenshot, but actually, with the error in the console, there should be an error in the setup screen in your browser as well. Definitely you should not see a message of successful setup finished? Then, subsequently, as the plugin has was not successfully installed (namely missing its dependencies), it can not be loaded, when you start the server.

There is something weird about your internet access. Don't you see 4.5.7 in the version list of [org.apache.httpcomponents:httpclient](https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient) at Maven central? Or at [repo.maven.apache.org](https://repo.maven.apache.org/maven2/org/apache/httpcomponents/httpclient/)? Maybe you are seeing outdated versions at those URLs?

I have added a check to skip Maven dependency resolution for dependencies provided by BIMserver. This will mitigate the issue for bimvie.ws which only declares a dependency on pluginbase and some other similar cases. However, once you try to install plugins with additional dependencies, such as ifcplugins without internet connection, you'll hit the same issue again.

As an enhancement, we could install all dependencies that BIMserver contains anyway into the local Maven repository on Jar expansion or War initialization. This would allow local install of all plugins that do not require additional dependencies beyond that. I'll keep this as a feature request.

As a workaround, if you have a backup of your old server setup, you could try to copy the local Maven repository to your new server.

**Comment by DaLiangLee** [comment]
After you modify the code, we immediately packaged it, and now it's successful deploed!
Thank you so much for your help!

**Comment by hlg** [comment]
Good to hear that.

The error you've shown should not have appeared with internet access enabled. To help track down the issue for future cases, can you please confirm whether you can or cannot see 4.5.7 in the version list of `org.apache.httpcomponents:httpclient` at [Maven central](https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient) and at [repo1.maven.org](https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/)  from the server where you deployed BIMserver? Thank you very much!

**Comment by hlg** [comment]
Keeping this issue open for possible enhancement:

> As an enhancement, we could install all dependencies that BIMserver contains anyway into the local Maven repository on Jar expansion or War initialization. This would allow local install of all plugins that do not require additional dependencies beyond that. I'll keep this as a feature request.
