### ISSUE TITLE
Installing ifcopenshellplugin... ...Tag mismatch

### ISSUE THREAD

**Issue by Mannshoch** [opensourceBIM/BIMserver#1192]
**Describe the bug**
I evaluate this server. I downloaded the jar and let it run. Setup stop while installing IFC OpenShell

**To Reproduce**
1. Follow the Setup until installing plugins
2. Error happened while installing the Plugin IfcOpenShell

**Expected behavior**
Successful installation

**Additional context**
on localhost:8082
```
Installing ifcopenshellplugin...
		javax.net.ssl.SSLException: javax.crypto.AEADBadTagException: Tag mismatch!

		Setup aborted
```

On BimServer Starter
```
10:33:06 INFO  [PluginInterface.installPluginBundle]: IfcOpenShell Last Modified: Fri, 05 Jul 2019 03:01:37 GMT                        (IfcGeomServerClient.java:195) 
10:33:07 ERROR [PluginInterface.installPluginBundle]:                                                                                  (InstallPluginBundle.java:75) 
org.bimserver.plugins.renderengine.RenderEngineException: javax.net.ssl.SSLException: javax.crypto.AEADBadTagException: Tag mismatch!
	at org.ifcopenshell.IfcGeomServerClient.getExecutable(IfcGeomServerClient.java:231)
	at org.ifcopenshell.IfcGeomServerClient.<init>(IfcGeomServerClient.java:158)
	at org.ifcopenshell.IfcOpenShellEnginePlugin.init(IfcOpenShellEnginePlugin.java:104)
	at org.bimserver.plugins.PluginContext.initialize(PluginContext.java:167)
	at org.bimserver.plugins.PluginBundleManager.loadPlugin(PluginBundleManager.java:770)
	at org.bimserver.plugins.PluginBundleManager.install(PluginBundleManager.java:147)
	at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPluginBundle.java:73)
	at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPluginBundle.java:35)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:775)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:767)
	at org.bimserver.webservices.impl.PluginServiceImpl.installPluginBundle(PluginServiceImpl.java:1420)
	at org.bimserver.generated.PluginInterfaceReflectoroqWUaYnjDpWT_1.callMethod(PluginInterfaceReflectoroqWUaYnjDpWT_1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:77)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:66)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:868)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLException: javax.crypto.AEADBadTagException: Tag mismatch!
	at sun.security.ssl.Alert.createSSLException(Unknown Source)
	at sun.security.ssl.TransportContext.fatal(Unknown Source)
	at sun.security.ssl.TransportContext.fatal(Unknown Source)
	at sun.security.ssl.TransportContext.fatal(Unknown Source)
	at sun.security.ssl.SSLTransport.decode(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.access$300(Unknown Source)
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:205)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at java.io.FilterInputStream.read(Unknown Source)
	at java.io.PushbackInputStream.read(Unknown Source)
	at java.util.zip.InflaterInputStream.fill(Unknown Source)
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.util.zip.ZipInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:109)
	at org.ifcopenshell.IfcGeomServerClient.getExecutable(IfcGeomServerClient.java:203)
	... 50 common frames omitted
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
	at com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:620)
	at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1116)
	at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1053)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:941)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
	at javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:779)
	at javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730)
	at javax.crypto.Cipher.doFinal(Cipher.java:2463)
	at sun.security.ssl.SSLCipher$T12GcmReadCipherGenerator$GcmReadCipher.decrypt(Unknown Source)
	at sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(Unknown Source)
	at sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
	... 68 common frames omitted

```

**Comment by Mannshoch** [comment]
I pressed Back button in and tried again, that not worked. Then I excluded it.
After that I logged into the website and tried it again on the plugin page. That worked. 
Windows 10 Enterprise (2004)
![grafik](https://user-images.githubusercontent.com/7795891/114558982-8c0c9280-9c6b-11eb-821d-edbb755a9c70.png)

**Comment by hlg** [comment]
No, the browser back button does not revert a half-succeeded setup. To initiate the setup again, you would have to stop the server, delete or change the home folder and then start over again.

You can also log in to BIMserver via BIMvie.ws and then install the remaining plugins manually from there. I assume that is what you did? Good, if that worked, then the SSL exception does not seem to be a permanent issue.

Can you perhaps try to run the setup again with a fresh home directory to confirm the issue was only temporary? Thanks a lot!

**Comment by Mannshoch** [comment]
Tested it with again a empty home. Everything worked fine. 👍
