### ISSUE TITLE
openBIMstandards/DataSetSchependomlaan has moved their repository

### ISSUE THREAD

**Issue by Mannshoch** [opensourceBIM/BIMserver#1193]
**Describe the bug**
If you try to import the demo data. The linked repository do not exist anymore.

**To Reproduce**

1. Try auto-import the demo data
2. the window do not proceed further
![grafik](https://user-images.githubusercontent.com/7795891/114561836-3ab1d280-9c6e-11eb-8cff-a7a596588d95.png)

**Expected behavior**
One of these:
- the proceed Window shows an error because he do not find the files
- No error appear and downloading the demo data work

**Additional context**

Error by BimServer Starter
```
14:45:10 ERROR [org.bimserver.ServiceInterface.checkinFromUrlSync]:                                                                                  (ServiceImpl.java:1347) 
java.io.FileNotFoundException: https://github.com/openBIMstandards/DataSetSchependomlaan/raw/master/Design%20model%20IFC%2FIFC%20Schependomlaan.ifc
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.bimserver.webservices.impl.ServiceImpl.checkinFromUrlSync(ServiceImpl.java:1317)
	at org.bimserver.generated.ServiceInterfaceReflectorKWgFgCrQZUAl_1.callMethod(ServiceInterfaceReflectorKWgFgCrQZUAl_1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:77)
	at org.bimserver.servlets.JsonApiServl14:45:10 INFO  [qtp722160979-37]: {"request":{"interface":"org.bimserver.ServiceInterface","method":"checkinFromUrlSync","parameters":{"poid":196609,"comment":"Demo Checkin","deserializerOid":524329,"fileName":"IFC Schependomlaan.ifc","url":"https://github.com/openBIMstandards/DataSetSchependomlaan/raw/master/Design%20model%20IFC%2FIFC%20Schependomlaan.ifc","merge":false}},"token":"d0524ca56761c717cf3d58e7260caf955dae9f71bdcd76629c5e833b1a36af6b6e4ac06f0e74a9592ce43d9b593a04a2"} (JsonHandler.java:85) 
et.service(JsonApiServlet.java:66)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:868)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionH14:45:10 INFO  [qtp722160979-37]:                                                                                  (JsonHandler.java:86) 
org.bimserver.shared.exceptions.ServerException: https://github.com/openBIMstandards/DataSetSchependomlaan/raw/master/Design%20model%20IFC%2FIFC%20Schependomlaan.ifc
	at org.bimserver.webservices.impl.ServiceImpl.checkinFromUrlSync(ServiceImpl.java:1348)
	at org.bimserver.generated.ServiceInterfaceReflectorKWgFgCrQZUAl_1.callMethod(ServiceInterfaceReflectorKWgFgCrQZUAl_1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:77)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:66)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:868)
	at org.eclipse.jandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.ioetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHand.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Unknown Source)
ler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: https://github.com/openBIMstandards/DataSetSchependomlaan/raw/master/Design%20model%20IFC%2FIFC%20Schependomlaan.ifc
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.bimserver.webservices.impl.ServiceImpl.checkinFromUrlSync(ServiceImpl.java:1317)
	... 40 common frames omitted

```

**Comment by machanghai502** [comment]
https://github.com/buildingSMART/Sample-Test-Files/tree/master/IFC%202x3/Schependomlaan

**Comment by hlg** [comment]
Thanks, fixed in https://github.com/opensourceBIM/bimvie.ws/commit/d80513520b7c6c63b11980ae3e98b62050491684.

**Comment by hlg** [comment]
Probably fixed.
