### ISSUE TITLE
Which sites are needed to complete to install?

### ISSUE THREAD

**Issue by planner77** [opensourceBIM/BIMserver#1200]
Hi, all.

I tried to install the bimServer 1.5.182 behind company firewall and fail it.
I guess that the cause of fail is some needed sites were denied. If you tell me which sites are needed to install plugin and demo data(The Schependomlaan project page), I'll request system admin to allow these sites.

Thanks.

**Comment by hlg** [comment]
The domains contacted are github.com and maven.org.

**Comment by planner77** [comment]
> The domains contacted are github.com and maven.org.

hi, hlg

It is enable to open both sites(https://github.com, https://maven.org). 

Thanks.

**Comment by hlg** [comment]
Is this issue solved and can be closed?

**Comment by planner77** [comment]
> Is this issue solved and can be closed?

not solved.

**Comment by hlg** [comment]
Then please post more detail about the issue. What do you mean with "install"? The BIMserver itself does not require installation. Do you mean the setup with installation of plugins during first run of BIMvie.ws? Are you using the jar or the war version? What is the error message?

**Comment by planner77** [comment]
> Then please post more detail about the issue. What do you mean with "install"? The BIMserver itself does not require installation. Do you mean the setup with installation of plugins during first run of BIMvie.ws? Are you using the jar or the war version? Where is it failing, for plugin (if so which) or for demo data installation? What is the error message?
> 
> Note that installation of the Schependomlaan dataset is currently broken (#1193) and will be fixed in next release.

Yes. I meant the setup with installation of plugins during first run of BIMvie.ws.
I used the jar version with the openjdk 14.0.2.
I got the fail for plugin.
Below is the message displayed in web browser
_**Setting up...
Setting up admin account...
Admin account successfully setup
Skipping email setup...
Checking internet connection from your BIMserver...
Internet connection OK
Not installing extended data schemas
Installing plugins...
Installing bimviews...
No plugin bundle available for your version of BIMserver: org.opensourcebim.bimviews

	Installing bimsurfer3...
	No plugin bundle available for your version of BIMserver: org.opensourcebim.bimsurfer3

	Installing ifcopenshellplugin...
	No plugin bundle available for your version of BIMserver: org.opensourcebim.ifcopenshellplugin

	Installing ifcplugins...
	No plugin bundle available for your version of BIMserver: org.opensourcebim.ifcplugins

	Installing binaryserializers...
	No plugin bundle available for your version of BIMserver: org.opensourcebim.binaryserializers

	Installing console...
	No plugin bundle available for your version of BIMserver: org.opensourcebim.console

	Installing gltf...
	No plugin bundle available for your version of BIMserver: org.opensourcebim.gltf

	Installing mergers...
	No plugin bundle available for your version of BIMserver: org.opensourcebim.mergers

	All remote plugins successfully installed
Setup successful, refresh to go to the status page**_

Below is the message displayed in the console.
**_java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:290)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1194)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1082)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:163)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1600)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at org.bimserver.utils.NetUtils.getContent(NetUtils.java:50)
	at org.bimserver.plugins.GitHubPluginRepository.listPluginLocations(GitHubPluginRepository.java:55)
	at org.bimserver.database.actions.GetInstalledPluginBundles.execute(GetInstalledPluginBundles.java:69)
	at org.bimserver.database.actions.GetInstalledPluginBundles.execute(GetInstalledPluginBundles.java:48)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:775)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:767)
	at org.bimserver.webservices.impl.PluginServiceImpl.getInstalledPluginBundles(PluginServiceImpl.java:1474)
	at org.bimserver.generated.PluginInterfaceReflectorLqrFYLyGkvJz_1.callMethod(PluginInterfaceReflectorLqrFYLyGkvJz_1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:77)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:66)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:868)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.base/java.lang.Thread.run(Thread.java:832)_**

**Comment by hlg** [comment]
At this point, the following URL is read: https://github.com/opensourceBIM/BIMserver-Repository/raw/master/plugins.json
Are you behind a proxy? In that case you would have to provide your proxy settings in the BIMserver JAR starter.

**Comment by planner77** [comment]
> At this point, the following URL is read: https://github.com/opensourceBIM/BIMserver-Repository/raw/master/plugins.json
> Are you behind a proxy? In that case you would have to provide your proxy settings in the BIMserver JAR starter.

Hi, hlg.

Yes, I am behind a proxy and provide proxy settings. And the URL you mentioned is opened in web browser after redirected to https://raw.githubusercontent.com/opensourceBIM/BIMserver-Repository/master/plugins.json.

**Comment by hlg** [comment]
Well that domain (githubusercontent.com) was off my radar - you may want to consider this in firewall settings. Can't guarantee there aren't other redirects or Github or Maven change redirect targets in the future. That's what redirects are made for after all.

**Comment by hlg** [comment]
Do you see anything after that issue in the log? There must be some failure related to Maven version resolution. This particular exception only stems from checking for already installed plugins before carrying out the actual installation. If that check fails it should proceed as if no plugins where installed yet.

When I block `raw.githubusercontent.com` in my hosts file, I can see similar exceptions for extended data schema and plugin installation (ConnectException instead of SocketTimeoutException). Due to the blocked URL, installation of extended data schemas fails, but plugin installation still goes through smoothly despite the exception.

If you allow `raw.githubusercontent.com` through the firewall, you should not see above exception anymore, but plugin installation will likely still fail and I would expect a different exception to be thrown.

**Comment by planner77** [comment]
Not solved. But close it please.

**Comment by hlg** [comment]
Could you still check whether there is anything else in the log after the exception you posted? That would be great. You'll find the logs in the BIMserver home folder you used at the time. You can also close issues yourself btw, if you're the author.

**Comment by planner77** [comment]
Not solved. But you can close it.

Thanks.
