### ISSUE TITLE
How to package the source code to run this project

### ISSUE THREAD

**Issue by 10823** [opensourceBIM/BIMserver#1212]
This is the project I pulled down. How to package Jar and run it externally using java -jar, I use Maven to package and keep reporting errors
![Uploading QQ图片20210819104251.png…]()

**Comment by 10823** [comment]
![QQ图片20210819104251](https://user-images.githubusercontent.com/62325709/129999177-0b5b0b6f-8af0-4db1-b2df-b8e0975dbaeb.png)

**Comment by 10823** [comment]
Because my github cannot send pictures, the error message is as follows：

org.bimserver.shared.exceptions.UserException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
	at org.bimserver.shared.json.JsonReflector.callMethod(JsonReflector.java:120)
	at org.bimserver.generated.AuthInterfaceImplrQJiuMoqiyQS_1.login(AuthInterfaceImplrQJiuMoqiyQS_1.java)
	at org.bimserver.client.BimServerClient.authenticate(BimServerClient.java:132)
	at org.bimserver.client.BimServerClient.connect(BimServerClient.java:124)
	at org.bimserver.client.BimServerClient.setAuthentication(BimServerClient.java:117)
	at org.bimserver.client.json.JsonBimServerClientFactory.create(JsonBimServerClientFactory.java:69)
	at org.bimserver.client.tests.TestCheckinAndGeometryDownload.test(TestCheckinAndGeometryDownload.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.bimserver.shared.reflector.ReflectorException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
	at org.bimserver.shared.json.JsonSocketReflector.call(JsonSocketReflector.java:94)
	at org.bimserver.shared.json.JsonReflector.callMethod(JsonReflector.java:64)
	... 35 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.bimserver.shared.json.JsonSocketReflector.call(JsonSocketReflector.java:72)
	... 36 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 45 more


Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project bimserverclientlib: There are test failures.

Please refer to D:\money\BIMserver-1.5.182\BimServerClientLib\target\surefire-reports for the individual test results.

**Comment by hlg** [comment]
As can be seen from the message, there are tests that fail. Some tests (for the client library) expect an active BIMserver instance which you have not running. To be honest, the test suite is currently not very evolved and in particular not made for automated testing. You are better off with tests deactivated during the build. You only need to build the parent project. For questions about Maven or your IDE consult the respective documentation.

**Comment by 10823** [comment]
I am building from the parent class of maven. I now want to type it into a jar locally and run it. However, I have been failing to package through Maven. This is the first time I use it. I want to ask how to package it, but I didn’t find it. Related documents

**Comment by hlg** [comment]
If you don't know how to work with Maven, please read some [Maven](https://maven.apache.org/) documentation. In the meantime, I suggest to use a pre-built and packaged [release](https://github.com/opensourceBIM/BIMserver/releases).

**Comment by 10823** [comment]
Thank you, I will give it a try
