### ISSUE TITLE
Problem in deploying service plugins/demo plugins on BIMSERVER

### ISSUE THREAD

**Issue by Aman-Verma-28** [opensourceBIM/BIMserver#1213]
While deploying the demo plugins on the BIMSERVER, I ran into an error which stated -

```
Could not find artifact net.sourceforge.jexcelapi:jxl:jar:2.6.10 in local (file:///home/user/.m2/repository)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.bimserver.plugins.PluginBundleManager.loadDependencies(PluginBundleManager.java:576)
	at org.bimserver.plugins.PluginBundleManager.loadJavaProject(PluginBundleManager.java:427)
	at org.bimserver.plugins.PluginBundleManager.loadPluginsFromEclipseProject(PluginBundleManager.java:497)
	at org.bimserver.LocalDevPluginLoader.loadPlugins(LocalDevPluginLoader.java:38)
	at org.bimserver.AbstractLocalDevBimServerStarter.start(AbstractLocalDevBimServerStarter.java:103)
	at org.bimserver.LocalDevBimServerStarter.main(LocalDevBimServerStarter.java:37)
```

## Attached are screenshots for the file structure and the error occurring while running the BIMSERVER.

![File Structure image](https://user-images.githubusercontent.com/66964572/131128110-0cc73395-8017-4fa8-a897-50066fe6b840.jpeg)
![Error image](https://user-images.githubusercontent.com/66964572/131128113-234f8608-2fcf-40d9-a029-a18f9fd80038.jpeg)

Is there a way to solve this issue? 
Thanks in anticipation.

**Comment by zaqifathis** [comment]
Are you still experiencing the issue, or have you found a solution?

**Comment by hlg** [comment]
This issue seems to appear in the [DemoPlugins](https://github.com/opensourceBIM/DemoPlugins) bundle. For some reason (or unintentionally), this bundle has not been updated with the release of BIMserver 1.5.182. We could try to reproduce this issue with the old version of the plugin (strict plugin-checking off) and with the default BIMserver starter (not LocalDevBimServerStarter). If this does at least install fine, we can close this issue.

Beyond that, we might check if the demo plugins still work (apart from the dependency issue) and if so update to the current release of BIMserver such that they appear again even with strict plugin checking. This is applies similarly to the following plugin bundles which have not been updated either to 1.5.182 (but before): [FixedFileService](https://github.com/opensourceBIM/FixedFileService), [IfcAnalyses](https://github.com/opensourceBIM/IfcAnalyses), [IfcAnalytics](https://github.com/opensourceBIM/IfcAnalytics), [OAuthClientTest](https://github.com/opensourceBIM/OAuthClientTest). Actually this is a different issue, but I keep it here for the time being.
