### ISSUE TITLE
Problem migrating database 1.5.101 to 1.5.182

### ISSUE THREAD

**Issue by polkuio** [opensourceBIM/BIMserver#1214]
**Describe the bug**
NullPointerException migrating database to a new BIMServer version (1.5.101 to 1.5.182). 
Tried a database with several projects and also with only one project.  Any hints what could cause this?

**To Reproduce**
1. Copied OLD version database to NEW version BIMServer HOME folder
2. Started NEW Server
3. Get below error message

**Expected behavior**
Expect seeing Migration possible or other status 

**Debug logs**
`15:25:33 INFO  [main]: Non-empty database directory found "C:\BIMserver_new182\home\database"           (BerkeleyKeyValueStore.java:87) 
15:25:34 ERROR [main]:                                                                                  (BimServer.java:807) 
org.bimserver.database.berkeley.DatabaseInitException: java.lang.NullPointerException
	at org.bimserver.database.Database.init(Database.java:217)
	at org.bimserver.BimServer.start(BimServer.java:697)
	at org.bimserver.JarBimServer.start(JarBimServer.java:160)
	at org.bimserver.JarBimServer.main(JarBimServer.java:79)
Caused by: java.lang.NullPointerException: null
	at java.lang.String.<init>(Unknown Source)
	at org.bimserver.database.Registry.readString(Registry.java:135)
	at org.bimserver.database.Database.init(Database.java:150)
	... 3 common frames omitted
15:25:34 INFO  [main]: Server started successfully                                                      (JarBimServer.java:161) `

**Comment by hlg** [comment]
Please see https://github.com/opensourceBIM/BIMserver/wiki/BIMserver-Database-Migration#current-policy.
