### ISSUE TITLE
Viewing a model in the BIMSERVER - BIMView plugin or BIMSURFER

### ISSUE THREAD

**Issue by VipulSoniGIS** [opensourceBIM/BIMserver#124]
The IFC model looks good in the IFCViewer-C++ in desktop but after upload in BIMSERVER 1.3.2 (BIMView) it never renders properly always the progress bar showing the rendering process fades away after nearing completion. Similarly the BIMSURFER shows the same issues.

08-09-2014 11:50:12 ERROR org.bimserver.serializers.binarygeometry.BinaryGeometrySerializer - 
org.eclipse.jetty.websocket.api.WebSocketException: RemoteEndpoint unavailable, current state [CLOSED], expecting [OPEN or CONNECTED]
    at org.eclipse.jetty.websocket.common.WebSocketSession.getRemote(WebSocketSession.java:245)
    at org.bimserver.servlets.StreamingSocket.send(StreamingSocket.java:68)
    at org.bimserver.servlets.Streamer$WebSocketifier.flush(Streamer.java:121)
    at java.io.DataOutputStream.flush(DataOutputStream.java:123)
    at org.bimserver.serializers.binarygeometry.BinaryGeometrySerializer.writeGeometries(BinaryGeometrySerializer.java:122)
    at org.bimserver.serializers.binarygeometry.BinaryGeometrySerializer.write(BinaryGeometrySerializer.java:82)
    at org.bimserver.plugins.serializers.EmfSerializer.writeToOutputStream(EmfSerializer.java:111)
    at org.bimserver.plugins.serializers.EmfSerializerDataSource.writeToOutputStream(EmfSerializerDataSource.java:60)
    at org.bimserver.servlets.Streamer$1.run(Streamer.java:154)
08-09-2014 11:50:12 ERROR org.bimserver.serializers.binarygeometry.BinaryGeometrySerializer - 
org.eclipse.jetty.websocket.api.WebSocketException: RemoteEndpoint unavailable, current state [CLOSED], expecting [OPEN or CONNECTED]
    at org.eclipse.jetty.websocket.common.WebSocketSession.getRemote(WebSocketSession.java:245)
    at org.bimserver.servlets.StreamingSocket.send(StreamingSocket.java:68)
    at org.bimserver.servlets.Streamer$WebSocketifier.flush(Streamer.java:121)
    at java.io.DataOutputStream.flush(DataOutputStream.java:123)
    at org.bimserver.serializers.binarygeometry.BinaryGeometrySerializer.writeGeometries(BinaryGeometrySerializer.java:122)
    at org.bimserver.serializers.binarygeometry.BinaryGeometrySerializer.write(BinaryGeometrySerializer.java:82)
    at org.bimserver.plugins.serializers.EmfSerializer.writeToOutputStream(EmfSerializer.java:111)
    at org.bimserver.plugins.serializers.EmfSerializerDataSource.writeToOutputStream(EmfSerializerDataSource.java:60)
    at org.bimserver.servlets.Streamer$1.run(Streamer.java:154)

**Comment by Raul666** [comment]
berlotti please provide link ? i cant find where is the solution posted.
