### ISSUE TITLE
The target server failed to respond

### ISSUE THREAD

**Issue by znnspace** [opensourceBIM/BIMserver#1247]
Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.bimserver.client.Channel.checkinSync(Channel.java:141)
	... 8 common frames omitted

**Comment by znnspace** [comment]
s:Generating inverses/opposites...i:-1
 s:Generating inversesi:2
 s:Generating inversesi:14
 s:Generating inversesi:18
 s:Generating inversesi:24
 s:Generating inversesi:32
 s:Generating inversesi:44
 s:Generating inversesi:48
 s:Generating inversesi:59
 s:Generating inversesi:61
 s:Generating inversesi:67
 s:Storing datai:-1
 s:Generating geometry...i:0

 org.bimserver.shared.exceptions.ServerException: The target server failed to respond
	at org.bimserver.client.Channel.checkinSync(Channel.java:173)
	at org.bimserver.client.BimServerClient.checkin(BimServerClient.java:283)

**Comment by hlg** [comment]
The issue context is completely unclear. Please submit  a proper bug report. An excerpt from a log is not sufficient to reproduce an issue.
