### ISSUE TITLE
At import time, Error : Referenced object from IfcFlowController not found

### ISSUE THREAD

**Issue by Chris-12** [opensourceBIM/BIMserver#1271]
Hi,
I am having an issue at checkin time reporting :
"Referenced object with oid 900071672 (IfcProductDefinitionShape), referenced from IfcFlowController not found."

After trying many things to work this around, we are stunk on checkin this model in.
It's size is about 55Mo.
Can someone help ?
Best regards,
Chris

**Comment by hlg** [comment]
Can you post the stacktrace, please? The BIMserver version would also be helpful to reproduce as well as a minimal sample file. I have sent you an upload link in case you like to share the data in private.

**Comment by Chris-12** [comment]
Server version is 182.
We have sent a request to the customer so that he allows us to share the model in private.
Here is the stack from log:
2022-09-12 11:01:20,524 INFO [pool-2-thread-14] o.b.d.b.BerkeleyKeyValueStore [BerkeleyKeyValueStore.java:615] writes: 2000000, 2853 ms sync
2022-09-12 11:01:25,076 ERROR [pool-2-thread-14] o.b.l.LongStreamingCheckinAction [LongStreamingCheckinAction.java:120] 
org.bimserver.BimserverDatabaseException: Referenced object with oid 947716344 (IfcProductDefinitionShape), referenced from IfcFlowController not found
	at org.bimserver.database.actions.GenericCheckinDatabaseAction.fixInverses(GenericCheckinDatabaseAction.java:433)
	at org.bimserver.database.actions.GenericCheckinDatabaseAction.fixInverses(GenericCheckinDatabaseAction.java:412)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:217)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:84)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:775)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:752)
	at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:73)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2022-09-12 11:01:25,076 ERROR [pool-2-thread-14] o.b.l.LongAction [LongAction.java:198] 
org.bimserver.BimserverDatabaseException: Referenced object with oid 947716344 (IfcProductDefinitionShape), referenced from IfcFlowController not found
	at org.bimserver.database.actions.GenericCheckinDatabaseAction.fixInverses(GenericCheckinDatabaseAction.java:433)
	at org.bimserver.database.actions.GenericCheckinDatabaseAction.fixInverses(GenericCheckinDatabaseAction.java:412)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:217)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:84)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:775)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:752)
	at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:73)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zaqifathis** [comment]
Have you found the cause of why this issue occurs? It would be helpful if you can give more information, such as BIMserver version, etc..

**Comment by Chris-12** [comment]
I do not have the model anymore. So you can close this post.

**Comment by hlg** [comment]
This looks like an invalid model with a dangling reference to a non-existing entity. The error message is pretty clear I think.
