### ISSUE TITLE
downloadQuery result no longer includes shape representations / any geometry data

### ISSUE THREAD

**Issue by mvaerle** [opensourceBIM/BIMserver#129]
I'm using downloadQuery with BimQL and when updating from bimserver 1.2 to "1.3.2-FINAL-2014-08-21" I seem to get different data from the downloadQuery call, it does not include any shape representations for example. It seems the underlying IFC data is missing, because I'm querying for IfcWindows and the window entities themselves are still in the result file.

Steps:
1) Upload duplex architecture sample model (or any other with windows)
2) use downloadQuery with the revision of the model, "BimQL Engine" as query engine and some serializers
3) observe that for Ifc2x3 serializer there are no shape representations, for the BinaryGeometry serializer that there is no geometry, and for collada that the result file does not contain geometry.

A workaround would be fine too! I can keep using 1.2 but then I can't use the binary serializer that the current 3d viewer wants, so that means no viewer, or finding a bimserver 1.2 compatible one.

Edit: the two output files can be found here:
https://gist.github.com/mvaerle/3e4fdb58a019c47ff928

**Comment by mvaerle** [comment]
FYI, I can still reproduce this using the latest release candidate. Anything that I download using the BimQL Query Engine is missing geometry in the case of a collada serializer.

**Comment by rubendel** [comment]
I am not sure how to implement this. A previous version of BIMserver apparently did something useful for your use case/models but I am pretty sure that was a coincidence. And I am also pretty sure that version did give back objects you didn't use (meaning you were filtering the results a bit more on your side). Every user will either think they are getting too much data or too little. There are many choices we have to make:
- Do we look at the data on an express-level or IFC level (at the express level we can for example make decisions about including inverse relations or not, on the IFC level we can for example decide whether to include the "Representation" reference of type "IfcProduct"
- Do we include all the queried objects + one level deep, or two levels, etc...
- Do we include the project's structure (IfcProject, IfcSite, IfcBuilding etc...)? If we do, you'll get geometry for example for IfcSite, which many people won't want. If we don't, objects that are positioned relatively to other objects will be in the wrong place.
- Should we always include the definitions of Units?

In my opinion most of these choices should be made by the user and BIMQL is not sufficient for that.

**Comment by mvaerle** [comment]
Thanks for the reply!

Makes sense, I guess the query interface in general should allow for specifying this, perhaps similar to the flag "deep" on downloadGuids, although I'm not entirely sure what that does and if that solution is general enough.

The workaround I just came up with is to serialize the queryresult to csv, extract the guids, then feed those back into a downloadGuids call, even if I don't specify deep = true it does give me geometry. However when I try to supply a larger number of guids I get the following error:

```
31-03-2015 20:54:17 ERROR                                                                                  (org.bimserver.JsonHandler.java:149) 
org.bimserver.database.UncheckedBimserverDatabaseException: org.bimserver.database.BimserverDatabaseException: Database session is closed
	at org.bimserver.database.DatabaseSession.load(DatabaseSession.java:1370)
	at org.bimserver.ServerEStore.load(ServerEStore.java:50)
	at org.bimserver.emf.IdEObjectImpl.load(IdEObjectImpl.java:141)
	at org.bimserver.emf.IdEObjectImpl.dynamicGet(IdEObjectImpl.java:74)
	at org.eclipse.emf.ecore.impl.EStructuralFeatureImpl$InternalSettingDelegateSingleData.dynamicGet(EStructuralFeatureImpl.java:2184)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1027)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1011)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1003)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:998)
	at org.bimserver.ifc.step.serializer.IfcStepSerializer.writeObject(IfcStepSerializer.java:340)
	at org.bimserver.ifc.step.serializer.IfcStepSerializer.writeEDataType(IfcStepSerializer.java:314)
	at org.bimserver.ifc.step.serializer.IfcStepSerializer.write(IfcStepSerializer.java:300)
	at org.bimserver.ifc.step.serializer.IfcStepSerializer.write(IfcStepSerializer.java:103)
	at org.bimserver.plugins.serializers.SerializerInputstream.read(SerializerInputstream.java:58)
	at java.io.InputStream.read(InputStream.java:101)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1025)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:999)
	at org.bimserver.shared.json.JsonConverter.toJson(JsonConverter.java:88)
	at org.bimserver.shared.json.JsonConverter.toJson(JsonConverter.java:67)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:139)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:60)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:98)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.bimserver.database.BimserverDatabaseException: Database session is closed
	at org.bimserver.database.DatabaseSession.checkOpen(DatabaseSession.java:713)
	at org.bimserver.database.DatabaseSession.get(DatabaseSession.java:719)
	at org.bimserver.database.DatabaseSession.lazyLoad(DatabaseSession.java:1354)
	at org.bimserver.database.DatabaseSession.load(DatabaseSession.java:1366)
	... 41 more
```

**Comment by mvaerle** [comment]
After some more testing it seems to only occur when specifying sync=false, deep=false. As soon as I change both to true it works.

The only issue is that no matter which guids I supply, it always returns the full geometry. Maybe this is caused by the deep=true parameter, but without it I get the database error above.
