### ISSUE TITLE
BimServer built error in Eclipse

### ISSUE THREAD

**Issue by t0316kcw** [opensourceBIM/BIMserver#154]
Dear all,

I tried to build the BimServer using Eclipse but it showed the following errors. I'm new to the Eclipse environment. It would be great if anyone can give me some hints.

Best regards,

Kuo-cheng

15:56:07 INFO  Starting BIMserver                                                               (org.bimserver.BimServer.java:229) 
15:56:07 INFO  Using "C:\Users\user1\git\BIMserver\BimServer\home1" as homedir              (org.bimserver.BimServer.java:231) 
15:56:08 INFO  Loading plugins from C:\Users\user1\git\BIMserver\BimServer\..               (org.bimserver.LocalDevPluginLoader.java:31) 
15:56:09 INFO  Version: 1.3.6 - Tue Jan 06 15:56:08 GMT 2015                                    (org.bimserver.BimServer.java:301) 
15:56:12 INFO  IFC-Schema successfully loaded from C:\Users\user1\git\BIMserver\BimServer\home1\tmp\IFC2X3_TC1.exp (nl.tue.buildingsmart.emf.BuildingSmartLibraryIfc2x3tc1SchemaPlugin.java:97) 
15:56:12 INFO  IFC-Schema successfully loaded from C:\Users\user1\git\BIMserver\BimServer\home1\tmp\IFC4.exp (nl.tue.buildingsmart.emf.BuildingSmartLibraryIfc4SchemaPlugin.java:97) 
15:56:12 INFO  Using "C:\Users\user1\git\BIMserver\BimServer\..\Builds\defaultsettings\shared\templates\" as template dir (org.bimserver.templating.TemplateEngine.java:64) 
15:56:13 INFO  Non-empty database directory found "C:\Users\user1\git\BIMserver\BimServer\home1\database" (org.bimserver.database.berkeley.BerkeleyKeyValueStore.java:75) 
15:56:13 ERROR                                                                                  (org.bimserver.shared.pb.ProtocolBuffersMetaData.java:173) 
com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
	at com.google.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:94)
	at com.google.protobuf.CodedInputStream.checkLastTagWas(CodedInputStream.java:124)
	at com.google.protobuf.CodedInputStream.readGroup(CodedInputStream.java:241)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:488)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:461)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:579)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:1)
	at com.google.protobuf.CodedInputStream.readGroup(CodedInputStream.java:240)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:488)
	at com.google.protobuf.GeneratedMessage.parseUnknownField(GeneratedMessage.java:193)
	at com.google.protobuf.DescriptorProtos$FileDescriptorSet.<init>(DescriptorProtos.java:89)
	at com.google.protobuf.DescriptorProtos$FileDescriptorSet.<init>(DescriptorProtos.java:72)
	at com.google.protobuf.DescriptorProtos$FileDescriptorSet$1.parsePartialFrom(DescriptorProtos.java:136)
	at com.google.protobuf.DescriptorProtos$FileDescriptorSet$1.parsePartialFrom(DescriptorProtos.java:1)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:200)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:218)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:223)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:1)
	at com.google.protobuf.DescriptorProtos$FileDescriptorSet.parseFrom(DescriptorProtos.java:253)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:151)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:187)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:223)
	at org.bimserver.BimServer.start(BimServer.java:401)
	at org.bimserver.LocalDevBimServerStarter.start(LocalDevBimServerStarter.java:62)
	at org.bimserver.LocalDevBimServerStarter.main(LocalDevBimServerStarter.java:44)
15:56:13 ERROR Dependency ServiceInterface.proto of AdminInterface.proto not found              (org.bimserver.shared.pb.ProtocolBuffersMetaData.java:159) 
15:56:13 ERROR                                                                                  (org.bimserver.BimServer.java:456) 
java.lang.NullPointerException
	at com.google.protobuf.Descriptors$DescriptorPool.importPublicDependencies(Descriptors.java:1645)
	at com.google.protobuf.Descriptors$DescriptorPool.<init>(Descriptors.java:1628)
	at com.google.protobuf.Descriptors$FileDescriptor.buildFrom(Descriptors.java:235)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:163)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:187)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:223)
	at org.bimserver.BimServer.start(BimServer.java:401)
	at org.bimserver.LocalDevBimServerStarter.start(LocalDevBimServerStarter.java:62)
	at org.bimserver.LocalDevBimServerStarter.main(LocalDevBimServerStarter.java:44)

**Comment by rubendel** [comment]
It seems to me the building went just fine. It's missing "ServiceInterface.proto", can you locate this file in your workspace? If now, try checking out again, something might have gone wrong.

**Comment by jakob-beetz** [comment]
In case somebody stumbles over this again:
Had a similar experience with a fresh clone. 
It turned out the protocolbuffer files where corrupted during checkout 

I did a "git reset --hard" on the directories on the client\protocolbuffers directory and the issue was solved

Hope this helps

**Comment by t0316kcw** [comment]
Thank you so much. That solved the problem :+1:
