### ISSUE TITLE
Getting error while downloading merged IFC file

### ISSUE THREAD

**Issue by vpanchal** [opensourceBIM/BIMserver#155]
Hi,
I am trying to download merge ifc file which has 2 ifc files uploaded as sub projects. I am trying to download main project's ifc2x3 data. I am getting error in DownloadServlet.java 274 line  in the bimserver.logs. 

Can someone look into it and suggest me the changes ?

**Comment by vpanchal** [comment]
Also if someone provides me 2 test ifc files which can be merged together.

**Comment by rubendel** [comment]
Thanks for providing the BIMserver version number, error message and log file

**Comment by vpanchal** [comment]
Hi Ruben.
Below is the exception I am getting while downloading the merge ifc file.

(org.bimserver.servlets.DownloadServlet.java:274) 
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
	at org.bimserver.ifc.step.serializer.IfcStepSerializer.writeList(IfcStepSerializer.java:461)
	at org.bimserver.ifc.step.serializer.IfcStepSerializer.writeEClass(IfcStepSerializer.java:328)
	at org.bimserver.ifc.step.serializer.IfcStepSerializer.writeObject(IfcStepSerializer.java:290)
	at org.bimserver.ifc.step.serializer.IfcStepSerializer.write(IfcStepSerializer.java:106)
	at org.bimserver.plugins.serializers.EmfSerializer.writeToOutputStream(EmfSerializer.java:113)
	at org.bimserver.plugins.serializers.EmfSerializerDataSource.writeToOutputStream(EmfSerializerDataSource.java:60)
	at org.bimserver.servlets.DownloadServlet.service(DownloadServlet.java:254)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:103)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vpanchal** [comment]
Here is the code which is causing issue in 
IfcStepSerializer.java = > 461 (writeList)

if (realVal instanceof Double) {
									Object stringVal = eObject.eGet(class1.getEStructuralFeature(structuralFeature.getName() + "AsString"));
									if (stringVal != null && model.isUseDoubleStrings()) {
										out.print(stringVal);
									} else {
										out.print(realVal);
									}

**Comment by rubendel** [comment]
Thanks, this is bug has been fixed earlier in https://github.com/opensourceBIM/BIMserver/commit/6c3e6a663f0a767e11a2d5bf216e4b7a5c3179ef

Will be in the next release.
