### ISSUE TITLE
Problem launching releases bimserver-1.3.6-FINAL-2015-01-16.jar

### ISSUE THREAD

**Issue by heseir** [opensourceBIM/BIMserver#156]
No expanding necessary
Windows Server 2008 R2
Main class: org.bimserver.JarBimServer
Running: java -Xmx1024m -Xss1024k -XX:MaxPermSize=256m -classpath lib;lib\activation.jar;lib\activemq-broker-5.8.0.jar;lib\activemq-client-5.8.0.jar;lib\activemq-openwire-legacy-5.8.0.jar;lib\antlr-2.7.7.jar;lib\antlr-3.1.1-runtime.jar;lib\antlr-3.1.1.jar;lib\aopalliance-1.0.jar;lib\asm-3.3.1.jar;lib\bimserver-1.3.6-FINAL-2015-01-16-client-lib.jar;lib\bimserver-1.3.6-FINAL-2015-01-16-ifc.jar;lib\bimserver-1.3.6-FINAL-2015-01-16-shared.jar;lib\bimserver-1.3.6-FINAL-2015-01-16-utils.jar;lib\bimserver-1.3.6-FINAL-2015-01-16-xsltserializer.jar;lib\bimserver-1.3.6-FINAL-2015-01-16.jar;lib\catalina.jar;lib\classmexer.jar;lib\commons-beanutils-1.8.3.jar;lib\commons-beanutils-bean-collections-1.8.3.jar;lib\commons-beanutils-core-1.8.3.jar;lib\commons-cli-1.2.jar;lib\commons-codec-1.9.jar;lib\commons-collections-3.2.1.jar;lib\commons-fileupload-1.2.1.jar;lib\commons-io-1.4.jar;lib\commons-lang-2.4.jar;lib\commons-lang-2.6.jar;lib\commons-logging-1.1.1.jar;lib\commons-pool-1.5.2.jar;lib\cors-filter-1.5.jar;lib\cxf-2.7.13.jar;lib\cxf-manifest.jar;lib\cxf-services-sts-core-2.7.13.jar;lib\cxf-services-ws-discovery-api-2.7.13.jar;lib\cxf-services-ws-discovery-service-2.7.13.jar;lib\cxf-services-wsn-api-2.7.13.jar;lib\cxf-services-wsn-core-2.7.13.jar;lib\cxf-xjc-boolean-3.0.2.jar;lib\cxf-xjc-bug671-3.0.2.jar;lib\cxf-xjc-dv-3.0.2.jar;lib\cxf-xjc-runtime-3.0.2.jar;lib\cxf-xjc-ts-3.0.2.jar;lib\ehcache-core-2.5.1.jar;lib\FastInfoset-1.2.13.jar;lib\geoapi-2.3-M1.jar;lib\geoapi-pending-2.3-M1.jar;lib\geronimo-j2ee-management_1.1_spec-1.0.1.jar;lib\geronimo-javamail_1.4_spec-1.7.1.jar;lib\geronimo-jaxws_2.2_spec-1.1.jar;lib\geronimo-jms_1.1_spec-1.1.1.jar;lib\geronimo-servlet_3.0_spec-1.0.jar;lib\gson-2.2.4.jar;lib\guava-18.0.jar;lib\guice-2.0.jar;lib\hawtbuf-1.9.jar;lib\httpasyncclient-4.0-beta3.jar;lib\httpclient-4.2.5.jar;lib\httpcore-4.2.4.jar;lib\httpcore-nio-4.2.4.jar;lib\httpmime-4.3.2.jar;lib\ifcNamespaces.jar;lib\isorelax-20030108.jar;lib\java-getopt-1.0.13.jar;lib\javassist.jar;lib\javax-websocket-client-impl-9.2.5.v20141112.jar;lib\javax-websocket-server-impl-9.2.5.v20141112.jar;lib\javax.websocket-api-1.0.jar;lib\javax.ws.rs-api-2.0-m10.jar;lib\jaxb-api-2.2.6.jar;lib\jaxb-impl-2.2.6.jar;lib\jaxb-xjc-2.2.6.jar;lib\jdom-1.0.jar;lib\je-6.2.31.jar;lib\jettison-1.3.6.jar;lib\jetty-alpn-client-9.2.5.v20141112.jar;lib\jetty-alpn-server-9.2.5.v20141112.jar;lib\jetty-annotations-9.2.5.v20141112.jar;lib\jetty-cdi-9.2.5.v20141112.jar;lib\jetty-client-9.2.5.v20141112.jar;lib\jetty-continuation-8.1.15.v20140411.jar;lib\jetty-continuation-9.2.5.v20141112.jar;lib\jetty-deploy-9.2.5.v20141112.jar;lib\jetty-http-8.1.15.v20140411.jar;lib\jetty-http-9.2.5.v20141112.jar;lib\jetty-io-8.1.15.v20140411.jar;lib\jetty-io-9.2.5.v20141112.jar;lib\jetty-jaas-9.2.5.v20141112.jar;lib\jetty-jaspi-9.2.5.v20141112.jar;lib\jetty-jmx-9.2.5.v20141112.jar;lib\jetty-jndi-9.2.5.v20141112.jar;lib\jetty-plus-9.2.5.v20141112.jar;lib\jetty-proxy-9.2.5.v20141112.jar;lib\jetty-quickstart-9.2.5.v20141112.jar;lib\jetty-rewrite-9.2.5.v20141112.jar;lib\jetty-schemas-3.1.jar;lib\jetty-security-8.1.15.v20140411.jar;lib\jetty-security-9.2.5.v20141112.jar;lib\jetty-server-8.1.15.v20140411.jar;lib\jetty-server-9.2.5.v20141112.jar;lib\jetty-servlet-9.2.5.v20141112.jar;lib\jetty-servlets-9.2.5.v20141112.jar;lib\jetty-util-8.1.15.v20140411.jar;lib\jetty-util-9.2.5.v20141112.jar;lib\jetty-webapp-9.2.5.v20141112.jar;lib\jetty-xml-9.2.5.v20141112.jar;lib\jna.jar;lib\joda-time-1.6.jar;lib\joda-time-2.2.jar;lib\JOpenId-1.08.jar;lib\js-1.7R2.jar;lib\jsr173_1.0_api.jar;lib\junit-4.8.2.jar;lib\jxl.jar;lib\log4j-1.2.16.jar;lib\log4j.xml;lib\mail.jar;lib\mina-core-2.0.7.jar;lib\msv-core-2011.1.jar;lib\neethi-3.0.3.jar;lib\nekohtml-1.9.14.jar;lib\oauth-20100527.jar;lib\oauth-provider-20100527.jar;lib\openid4java-0.9.8.jar;lib\openmali.jar;lib\opensaml-2.6.1.jar;lib\openws-1.5.1.jar;lib\org.eclipse.core.contenttype_3.4.200.v20120523-2004.jar;lib\org.eclipse.core.jobs_3.5.200.v20120521-2346.jar;lib\org.eclipse.core.resources_3.8.0.v20120522-2034.jar;lib\org.eclipse.core.runtime_3.8.0.v20120521-2346.jar;lib\org.eclipse.emf.codegen.ecore_2.9.1.v20130902-0605.jar;lib\org.eclipse.emf.codegen_2.9.0.v20130902-0605.jar;lib\org.eclipse.emf.common_2.9.1.v20130827-0309.jar;lib\org.eclipse.emf.ecore.xmi_2.9.1.v20130827-0309.jar;lib\org.eclipse.emf.ecore_2.9.1.v20130827-0309.jar;lib\org.eclipse.emf_2.6.0.v20130902-0605.jar;lib\org.eclipse.equinox.common_3.6.100.v20120522-1841.jar;lib\org.eclipse.equinox.preferences_3.5.0.v20120522-1841.jar;lib\org.eclipse.jdt.core_3.8.1.v20120531-0637.jar;lib\org.eclipse.osgi_3.8.0.v20120529-1548.jar;lib\protocolbuffers2.5.jar;lib\quartz-1.8.3.jar;lib\relaxngDatatype-20020414.jar;lib\resolver.jar;lib\rome-1.0.jar;lib\serializer-2.7.1.jar;lib\servlet-api-3.1.jar;lib\slf4j-api-1.6.2.jar;lib\slf4j-api-1.7.7.jar;lib\slf4j-log4j12-1.6.2.jar;lib\spring-aop-3.0.7.RELEASE.jar;lib\spring-asm-3.0.7.RELEASE.jar;lib\spring-beans-3.0.7.RELEASE.jar;lib\spring-context-3.0.7.RELEASE.jar;lib\spring-core-3.0.7.RELEASE.jar;lib\spring-expression-3.0.7.RELEASE.jar;lib\spring-jms-3.0.7.RELEASE.jar;lib\spring-tx-3.0.7.RELEASE.jar;lib\spring-web-3.0.7.RELEASE.jar;lib\stax2-api-3.1.4.jar;lib\stringtemplate-3.2.jar;lib\tar.jar;lib\tomcat-coyote.jar;lib\tomcat-juli.jar;lib\tomcat-util.jar;lib\velocity-1.7.jar;lib\websocket-api-9.2.5.v20141112.jar;lib\websocket-client-9.2.5.v20141112.jar;lib\websocket-common-9.2.5.v20141112.jar;lib\websocket-server-9.2.5.v20141112.jar;lib\websocket-servlet-9.2.5.v20141112.jar;lib\woodstox-core-asl-4.4.1.jar;lib\wsdl4j-1.6.3.jar;lib\wss4j-1.6.17.jar;lib\xbean.jar;lib\xbean_xpath.jar;lib\xercesImpl-2.8.1.jar;lib\xml-resolver-1.2.jar;lib\xmlbeans-2.6.0.jar;lib\xmlbeans-qname.jar;lib\xmlpublic.jar;lib\xmlschema-core-2.1.0.jar;lib\xmlsec-1.5.7.jar;lib\xmltooling-1.4.1.jar;lib\xsdlib-2010.1.jar org.bimserver.JarBimServer address=localhost port=8082 homedir="C:\Users\Administrator\Downloads\home"
Logging to: C:\Users\Administrator\Downloads\home\logs\bimserver.log
16-01-2015 13:27:49 INFO  org.bimserver.BimServer - Starting BIMserver
16-01-2015 13:27:49 INFO  org.bimserver.BimServer - Using "C:\Users\Administrator\Downloads\home" as homedir
16-01-2015 13:27:51 ERROR org.bimserver.BimServer - 
java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.jetty.server.ServerConnector.<init>(ServerConnector.java:96)
	at org.bimserver.EmbeddedWebServer.<init>(EmbeddedWebServer.java:39)
	at org.bimserver.BimServer.<init>(BimServer.java:265)
	at org.bimserver.JarBimServer.start(JarBimServer.java:78)
	at org.bimserver.JarBimServer.main(JarBimServer.java:53)
16-01-2015 13:27:53 ERROR org.bimserver.JarBimServer - 
java.lang.NullPointerException
	at org.bimserver.JarBimServer.start(JarBimServer.java:81)
	at org.bimserver.JarBimServer.main(JarBimServer.java:53)

Any advice?

**Comment by berlotti** [comment]
Are you using a recent Java version?

**Comment by rubendel** [comment]
This was a bug and should be fixed in https://github.com/opensourceBIM/BIMserver/releases/tag/1.3.6-FINAL-2015-01-17, which by the way is not a production release (neither is bimserver-1.3.6-FINAL-2015-01-16.jar).
