### ISSUE TITLE
Problem while checkin multiple files from different machines on same BIMServer.

### ISSUE THREAD

**Issue by vpanchal** [opensourceBIM/BIMserver#157]
Hi,
When I am trying to checkin multiple files at a time on BIMServer from different machines on same BIMServer causes a critical issue. Below are the logs

java.lang.IllegalStateException: Invalid use of BasicClientConnManager: connection still allocated.
Make sure to release the connection before allocating another one.
	at org.apache.http.impl.conn.BasicClientConnectionManager.getConnection(BasicClientConnectionManager.java:161)
	at org.apache.http.impl.conn.BasicClientConnectionManager$1.getConnection(BasicClientConnectionManager.java:138)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:455)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at org.bimserver.client.Channel.checkin(Channel.java:158)
	at org.bimserver.client.BimServerClient.checkin(BimServerClient.java:253)
	at org.bimserver.client.BimServerClient.checkin(BimServerClient.java:244)

**Comment by rubendel** [comment]
This could very well be a bug, but just to be sure, are you using 1 BimServerClient from multiple threads? Because it is not thread safe.
