### ISSUE TITLE
Issues while creating Geometry

### ISSUE THREAD

**Issue by vpanchal** [opensourceBIM/BIMserver#167]
Hi,

I am trying to generate geometry for 1 of the IFC file of 104MB which causes an issue and sends an exception in bimserver.logs

 (org.bimserver.longaction.LongAction.java:175) 
org.bimserver.database.BimserverDatabaseException: Too many conflicts, tried 10 times
at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:666)
at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:597)
at org.bimserver.longaction.LongDownloadOrCheckoutAction.executeAction(LongDownloadOrCheckoutAction.java:110)
at org.bimserver.longaction.LongDownloadAction.execute(LongDownloadAction.java:63)
at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
at java.lang.Thread.run(Thread.java:745)
31-01-2015 11:34:22 ERROR                                                                                  (org.bimserver.longaction.LongDownloadAction.java:68) 
org.bimserver.database.BimserverDatabaseException: Too many conflicts, tried 10 times
at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:666)
at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:597)
at org.bimserver.longaction.LongDownloadOrCheckoutAction.executeAction(LongDownloadOrCheckoutAction.java:110)
at org.bimserver.longaction.LongDownloadAction.execute(LongDownloadAction.java:63)
at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
at java.lang.Thread.run(Thread.java:745)
31-01-2015 11:34:22 INFO  reads: 24488351                                                                  (org.bimserver.database.berkeley.BerkeleyKeyValueStore.java:410)
31-01-2015 11:37:52 INFO  Cleaning up long running action: Download - LongDownloadAction                   (org.bimserver.longaction.LongActionManager.java:73)

**Comment by rubendel** [comment]
This error means it tried 10 times to load the model, and still there were conflicts with other transactions. What other transactions were going on at the same time?

**Comment by vpanchal** [comment]
Hi Ruben,
Thank you for your quick reply.  Interesting answer I have for your question.

We have written a JBoss scheduler which does a job of generating only geometry for list of IFC files continuously.We have mix size IFC files like from 10MB to 300MB. 
At the same time, we are trying to 3D view of IFC file in the viewer. So generating geometry and viewing task running parallel on the same BIMServer. 

But What I observe that above the exception comes while generating geometry for bigger size of IFC files.

Well, Below is the BIMServer configurations, Can I request you please review and guide me for better performance of it.
![bimserver1](https://cloud.githubusercontent.com/assets/846490/5996447/dab80f34-aacf-11e4-857f-19b1939bf209.png)

BIMServer2
![bimserver2](https://cloud.githubusercontent.com/assets/846490/5996453/e53c3dea-aacf-11e4-9928-3e409a8baaa1.png)

Thank you Ruben in Advance.

**Comment by rubendel** [comment]
There is not really a solution for this unless we change the way BIMserver handles database locks. We could increase the amount of times transactions are retried (from 10 to 20 for example), but this would not solve the underlying structural problem. In theory though the download action should not be writen to the database and thus not use any write locks, so I will look into that, might take quite a while though.

**Comment by dlabz** [comment]
@vpanchal: there;s a simple solution to your problem: generate better IFC files. IFC is designed to be extremely efficient. A 100 MB file should be able to fit a smaller town in full detail.
