### ISSUE TITLE
bimServerApi.callWs() breaks WebSocket connection

### ISSUE THREAD

**Issue by dlabz** [opensourceBIM/BIMserver#169]
Ubuntu 14.10  server
Java 1.7.0_65
Tomcat 7.0.55
BIMServer 1.3.4 (war)
Chrome 40.0.2214.94 m (64-bit)

---
When calling callWs() from a BimServerApi instance, token is automatically attached to the request. 
On the server side requests are handled by org.bimserver.servlets.Streamer, which checks if request.action is set. If not, and request.token has been set, it will than try to register endpointid.

Even if endpoint has already been set for that instance of Streamer, EndPointManager.register will blindly try to add that EndPoint to endPoints HashBiMap, resulting in an error in catalina.out:

```
Feb 03, 2015 2:28:24 AM org.apache.coyote.AbstractProtocol$AbstractConnectionHandler process
SEVERE: Error reading request, ignored
java.lang.IllegalArgumentException: value already present: 9
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:238)
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
	at com.google.common.collect.Synchronized$SynchronizedMap.put(Synchronized.java:995)
	at org.bimserver.endpoints.EndPointManager.register(EndPointManager.java:34)
	at org.bimserver.servlets.Streamer.onText(Streamer.java:178)
	at org.bimserver.servlets.TomcatStreamInbound.onTextData(TomcatStreamInbound.java:58)
	at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:191)
	at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:139)
	at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:88)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

After such error, the bimServerApi.server will drop the connection.

I've also tested this in current git version, running in Eclipse, on Win7 x64 with similar results.

**Comment by rubendel** [comment]
Just out of curiosity, why do you call "callWs"?

**Comment by dlabz** [comment]
I'm working on client-side modification of the model. For now mostly simple stuff, but I'm trying to decide on a reusable approach. BimServerApi.js is packed with a lot of cool stuff that I never used, so I decided to spend some time getting to know it, in search for inspiration. 
WS seems like just the right tool to keep the client and server in sync, and I've only been using it for notifications.
