### ISSUE TITLE
Build Error: Address already in use: bind (Eclipse Kepler, master branch)

### ISSUE THREAD

**Issue by mrca** [opensourceBIM/BIMserver#172]
Just checked in this project and tried to run the LocalDevBimServerStarter.....
I have MAMP installed but not running at the moment, could it be that this service is using the bimserver port? What am I missing? (Sorry to post here, I am having issues accessing the support.opensourcebim site)

15:59:44 INFO  Changing server state to RUNNING                                                 (org.bimserver.ServerInfoManager.java:107) 
15:59:52 ERROR                                                                                  (org.bimserver.EmbeddedWebServer.java:57) 
java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:279)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:218)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at org.eclipse.jetty.server.Server.doStart(Server.java:336)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at org.bimserver.EmbeddedWebServer.start(EmbeddedWebServer.java:55)
	at org.bimserver.BimServer.start(BimServer.java:440)
	at org.bimserver.LocalDevBimServerStarter.start(LocalDevBimServerStarter.java:62)
	at org.bimserver.LocalDevBimServerStarter.main(LocalDevBimServerStarter.java:44)

**Comment by mrca** [comment]
UPDATE: So there was a server service running in the back I tracked it down and uninstalled it, re-cloned the repo and cleared browser caches, and now the server runs from Eclipse. Still I cannot get the adminGui to open: with the 127.0.0.1:8080/admin i get a "404 - not found error"...  any suggestions?

**Comment by dlabz** [comment]
looki in to https://github.com/opensourceBIM/BIMserver/wiki/Eclipse#adding-the-plugins-property

**Comment by mrca** [comment]
That did the trick thanks, my bad. Do I need to include additional stuff so that the admin gui works? somehow it hangs and displays nothing, the api console works though...
