### ISSUE TITLE
RUN BIMServer  from  SourceCode

### ISSUE THREAD

**Issue by howlDream** [opensourceBIM/BIMserver#192]
Exception in thread "BIMserver Starter Thread" java.lang.StringIndexOutOfBoundsException: String index out of range: -4
	at java.lang.String.substring(String.java:1911)
	at org.bimserver.starter.Starter.getJarFileNameNew(Starter.java:528)
	at org.bimserver.starter.Starter.expand(Starter.java:478)
	at org.bimserver.starter.Starter.access$3(Starter.java:476)
	at org.bimserver.starter.Starter$4$1.run(Starter.java:241)
	at java.lang.Thread.run(Thread.java:722)

How to solve?

**Comment by rubendel** [comment]
That is not how you start BIMserver from code. This code is for the JAR build.
https://github.com/opensourceBIM/BIMserver/wiki/Eclipse
