### ISSUE TITLE
Upgrading BIM server from 1.3 to 1.4

### ISSUE THREAD

**Issue by jeremydenoun** [opensourceBIM/BIMserver#198]
I work on BIM Server (=>1.4.0) and I need your help about upgrading database between 1.3 and 1.4...

I follow reinstall upgrade protocol and when I try to start tomcat with new version...
I have correct log for up to database startup and I can read :

03-04-2015 16:48:58 INFO  Non-empty database directory found "/var/bimserver/home/database"                (org.bimserver.database.berkeley.BerkeleyKeyValueStore.java:76)
03-04-2015 16:49:01 ERROR                                                                                  (org.bimserver.BimServer.java:458)
org.bimserver.database.berkeley.DatabaseInitException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at org.bimserver.database.Database.init(Database.java:201)
	at org.bimserver.BimServer.start(BimServer.java:366)
	at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:84)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1911)
	at org.bimserver.database.Database.initInternalStructure(Database.java:266)
	at org.bimserver.database.Database.init(Database.java:181)
	... 11 more
03-04-2015 16:49:34 DEBUG /                                                                                (org.bimserver.servlets.RootServlet.java:71)
03-04-2015 16:49:34 INFO  No default web module                                                            (org.bimserver.servlets.RootServlet.java:108)
03-04-2015 16:49:34 ERROR                                                                                  (org.bimserver.servlets.RootServlet.java:141)
java.lang.NullPointerException
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:114)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

Do you have some idea to fix it ?
If I remove database directory, this will be recreate but I lose data...

Thanks for your help

**Comment by berlotti** [comment]
Hi Jeremy,

Have you read this post http://bimserver.org/2015/02/22/bimserver-1-4-new-core-and-database-supporting-both-ifc2x3-and-ifc4/ ?

Greetings,
Léon

**Comment by jeremydenoun** [comment]
Ok I understand... can I have a copy of your migrate script for try by myself on my installation ? 
If I can migrate only users/projects and configuration this can permit me to gain a lot of time.

Thanks

**Comment by rubendel** [comment]
Documented it here: https://github.com/opensourceBIM/BIMserver/wiki/Migrating-1.3-to-1.4

If you only want to create users/project, make sure you disable some of the code in BimServerImporter
