### ISSUE TITLE
How to add a project from a Java application?

### ISSUE THREAD

**Issue by Syvon** [opensourceBIM/BIMserver#202]
Hello, 
I have set up a bimserver ("http://localhost:8082") according to the quick setup guide from the wiki. And I can connect to the BIMserver.Now I'm trying to add a project,here is a code snippet.

		BimServerClientFactory factory = new JsonBimServerClientFactory(
				"http://localhost:8082");
		// Create a new BimServerClient with authentication
		BimServerClientInterface bimServerClient;
		try {
			bimServerClient = factory
					.create(new UsernamePasswordAuthenticationInfo(
							"admin@bimserver.com", "666666"));
			// Create a new project
			SProject newProject = bimServerClient.getBimsie1ServiceInterface()
					.addProject("secondProject");

			// This is the file we will be checking in
			File ifcFile = new File("/data/big.ifc");

			// Find a deserializer to use
			SDeserializerPluginConfiguration deserializer = bimServerClient
					.getBimsie1ServiceInterface()
					.getSuggestedDeserializerForExtension("ifc");

			// Checkin
			((BimServerClient) bimServerClient).checkin(newProject.getOid(),
					"test", deserializer.getOid(), false, true, ifcFile);
		} catch (ServiceException e) {
			// TODO 自动生成的 catch 块
			e.printStackTrace();
		} catch (ChannelConnectionException e) {
			// TODO 自动生成的 catch 块
			e.printStackTrace();
		} catch (Exception e) {
			// TODO 自动生成的 catch 块
			e.printStackTrace();
		}
but while running the program I'm getting error in server log---
25-04-2015 17:16:02 ERROR org.bimserver.JsonHandler - Missing parameters: getSuggestedDeserializerForExtension -> poid
25-04-2015 17:16:02 ERROR org.bimserver.JsonHandler - 
java.lang.NullPointerException
	at org.bimserver.generated.Bimsie1ServiceInterfaceReflector1.callMethod(Bimsie1ServiceInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:219)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:124)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:60)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:98)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
	at java.lang.Thread.run(Unknown Source)
In Eclipse the error is like that---

java.lang.NullPointerException
	at com.example.wang.BIMserver0425.main(BIMserver0425.java:55)

Please help.
Thanks in advance.

**Comment by rubendel** [comment]
You Java BIMserver client seems to be of an older version than your BIMserver because in a newer version you also have to give the "poid" argument to the call "getSuggestedDeserializerForExtension".

**Comment by Syvon** [comment]
Oh，I understand.Thank you very much.
By the way,In many cases,I found that you use the function "getFactory()",how should I use it?

**Comment by rubendel** [comment]
Can you be a bit more specific, getFactory of which class/interface?

**Comment by Syvon** [comment]
I'm sorry.
For,example:

    // Create a BimServerClientFactory, change Json to ProtocolBuffers or Soap if you like
    BimServerClientFactory factory = new JsonBimServerClientFactory("http://localhost:8080");
    // Create a new BimServerClient with authentication
    BimServerClientInterface bimServerClient = getFactory().create(new UsernamePasswordAuthenticationInfo("admin@bimserver.org", "admin"));

I see that you use the function "getFactory()" in many cases(https://github.com/opensourceBIM/BIMserver/tree/master/Tests/test/org/bimserver/tests/serviceinterface). But I can't use it in my workspace.

thank you.

**Comment by rubendel** [comment]
Those are test cases, I use getFactory so I don't have to create a factory in every single test case. If you want to use the BIMserver Java client, have a look at the documentation: https://github.com/opensourceBIM/BIMserver/wiki/BimServerClient

**Comment by Syvon** [comment]
Thank you very much.
