### ISSUE TITLE
BIMserver with OpenStudio1.7.4 NullPointerException

### ISSUE THREAD

**Issue by lbirkett** [opensourceBIM/BIMserver#212]
When I try to create a new project in OpenStudio I get this error in BIMserver...

22-05-2015 14:36:19 ERROR org.bimserver.JsonHandler - Missing parameters: addProject -> schema
22-05-2015 14:36:19 ERROR org.bimserver.JsonHandler - 
java.lang.NullPointerException
	at org.bimserver.generated.Bimsie1ServiceInterfaceReflector1.callMethod(Bimsie1ServiceInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:219)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:126)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:60)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:73)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:98)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
	at java.lang.Thread.run(Unknown Source)

How can I fix this?

**Comment by dlabz** [comment]
Since BIMserver introduced multi-schema, you need to specify the schema, when creating a project.  
I'm guessing you're using ifc2x3tc1, so the request should look like this: 
```
{
  "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "request": {
    "interface": "Bimsie1ServiceInterface", 
    "method": "addProject", 
    "parameters": {
      "projectName": "Name of the project",
      "schema": "ifc2x3tc1"
    }
  }
}
```
