### ISSUE TITLE
Null Pointer Exception when trying to make api download call

### ISSUE THREAD

**Issue by unreturnable** [opensourceBIM/BIMserver#219]
I'm calling the method 'download' from the api using a correct roid and serializerOid, When listening for progress on this I get a single response saying the download has started, then several messages saying that it is Preparing for download.

But then I get this JSON as an error:

```javascript
{
  "__type": "SLongActionState",
  "end": 1435659899493,
  "errors": [
    null
  ],
  "infos": [],
  "oid": -1,
  "progress": 0,
  "rid": 0,
  "stage": 2,
  "start": 1435659898204,
  "state": "AS_ERROR",
  "title": null,
  "warnings": []
}
```

When I look at the servers log I discover this stacktrace:

```
30-06-2015 11:34:51 ERROR org.bimserver.longaction.LongAction - 
java.lang.NullPointerException
	at org.bimserver.database.actions.AbstractDownloadDatabaseAction.checkGeometry(AbstractDownloadDatabaseAction.java:79)
	at org.bimserver.database.actions.DownloadDatabaseAction.execute(DownloadDatabaseAction.java:124)
	at org.bimserver.database.actions.DownloadDatabaseAction.execute(DownloadDatabaseAction.java:53)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:593)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:585)
	at org.bimserver.longaction.LongDownloadOrCheckoutAction.executeAction(LongDownloadOrCheckoutAction.java:118)
	at org.bimserver.longaction.LongDownloadAction.execute(LongDownloadAction.java:63)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
	at java.lang.Thread.run(Thread.java:745)
30-06-2015 11:34:51 ERROR org.bimserver.longaction.LongDownloadAction - 
java.lang.NullPointerException
	at org.bimserver.database.actions.AbstractDownloadDatabaseAction.checkGeometry(AbstractDownloadDatabaseAction.java:79)
	at org.bimserver.database.actions.DownloadDatabaseAction.execute(DownloadDatabaseAction.java:124)
	at org.bimserver.database.actions.DownloadDatabaseAction.execute(DownloadDatabaseAction.java:53)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:593)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:585)
	at org.bimserver.longaction.LongDownloadOrCheckoutAction.executeAction(LongDownloadOrCheckoutAction.java:118)
	at org.bimserver.longaction.LongDownloadAction.execute(LongDownloadAction.java:63)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
	at java.lang.Thread.run(Thread.java:745)
30-06-2015 11:34:51 INFO  org.bimserver.database.berkeley.BerkeleyKeyValueStore - reads: 266586
````

I can't find any form of documentation to describe whether I'm using the 'download' method correctly or not.

Server is running on a Ubuntu 14.04 machine, running server build: bimserver-1.4.0-FINAL-2015-05-14

**Comment by dlabz** [comment]
This looks like another instance of the phantom bug causing #207, #193 ...
  
I'm guessing there is some synchronicity issue in the 1.4.0. Seems like, in some cases, a value isn't retrieved from database at the time it's being used.

**Comment by unreturnable** [comment]
Is there any form of workaround?
