### ISSUE TITLE
Checkout CityGML 1.0.0

### ISSUE THREAD

**Issue by wuestenfux** [opensourceBIM/BIMserver#222]
when i checkout to CityGML 1.0.0, i get an empty Download file and it says "Done preparing". Do i miss something here?

**Comment by dlabz** [comment]
I tested on my setup, and get a file, though I haven't tried to open it in the viewer. Geometry seems to be defined in the .gml  
What version of BIMserver are you using

**Comment by wuestenfux** [comment]
I use Version Versiono 1.4.0 and get a File too, but it's 0 kb and doesn't contain any geometry...

**Comment by dlabz** [comment]
My files do have expectable size and a valid GML code inside them. 

You should check the BIMserver log. Also, please state the os, java version...

**Comment by wuestenfux** [comment]
<img width="1440" alt="bildschirmfoto 2015-07-07 um 13 34 11" src="https://cloud.githubusercontent.com/assets/12089603/8545247/e83cb540-24ac-11e5-966f-524367c54876.png">
OS: Windows 7 (6.1) and Java 1.8.0_45

**Comment by wuestenfux** [comment]
07-07-2015 13:33:12 INFO  org.bimserver.cache.DiskCacheManager - Reading from cache 1769475.json
07-07-2015 13:33:13 INFO  org.bimserver.servlets.Streamer - 120 messages written    348,93 KB
07-07-2015 13:33:23 INFO  org.bimserver.cache.DiskCacheManager - Start caching Test.gml
07-07-2015 13:33:25 INFO  org.bimserver.cache.DiskCacheManager - Removing cache Test.gml
07-07-2015 13:33:25 ERROR org.bimserver.servlets.DownloadServlet - 
java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Unknown Source)
	at java.nio.HeapByteBuffer.getFloat(Unknown Source)
	at org.bimserver.citygml.CityGmlSerializer.setGeometry(CityGmlSerializer.java:671)
	at org.bimserver.citygml.CityGmlSerializer.processBoundary(CityGmlSerializer.java:477)
	at org.bimserver.citygml.CityGmlSerializer.processStorey(CityGmlSerializer.java:272)
	at org.bimserver.citygml.CityGmlSerializer.processBuilding(CityGmlSerializer.java:242)
	at org.bimserver.citygml.CityGmlSerializer.write(CityGmlSerializer.java:172)
	at org.bimserver.plugins.serializers.EmfSerializer.writeToOutputStream(EmfSerializer.java:123)
	at org.bimserver.plugins.serializers.EmfSerializerDataSource.writeToOutputStream(EmfSerializerDataSource.java:60)
	at org.bimserver.plugins.serializers.CacheStoringEmfSerializerDataSource.writeToOutputStream(CacheStoringEmfSerializerDataSource.java:37)
	at org.bimserver.servlets.DownloadServlet.service(DownloadServlet.java:289)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:102)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
	at java.lang.Thread.run(Unknown Source)
07-07-2015 13:34:18 INFO  org.bimserver.longaction.LongAction - Terminating long action with id 267

**Comment by wuestenfux** [comment]
OS: Windows 7 (6.1) and Java 1.8.0_45

**Comment by wuestenfux** [comment]
Update: I get an Error on another File when i try to checkout CityGML
org.bimserver.emf.IfcModelInterfaceException: Oid already stored: 342820706 org.bimserver.models.geometry.impl.Vector3fImpl@31a6f1d2 (old: org.bimserver.models.geometry.impl.Vector3fImpl@4a3451aa

**Comment by berlotti** [comment]
turn off caching and try again. 
What render engine plugin are you using?

**Comment by wuestenfux** [comment]
I’m using the IfcOpenShell Engine
caching turned off and cleared, but still a 0 byte file.

**Comment by wuestenfux** [comment]
always stops after „Done Preparing“

**Comment by wuestenfux** [comment]
Update:  I tried it with firefox instead of safari and it loaded a file of an good size (.dat). my fzk viewer refuses to open it but at least a little step forwards.
