### ISSUE TITLE
Bimserver Problem

### ISSUE THREAD

**Issue by saras82** [opensourceBIM/BIMserver#223]
Hello,
I'm a newbie in bimserver related issues. 
I have set up a bimserver ("http://localhost:8082") according to the quick setup guide from the wiki.
 Now I'm trying to connect the bimserver from a simple java application:
This is a section of the code:

	String path="D:/Sara/Workspace/BimServer2/dirHome/home";
	// Create a config
        BimServerConfig config = new BimServerConfig();
        File home = new File(path);
        
        // Remove the home dir if it's there
        if (home.exists()) {
                try {
                        FileUtils.deleteDirectory(home);
                } catch (IOException e) {
                        e.printStackTrace();
                }
        }
        
      	config.setResourceFetcher(new LocalDevelopmentResourceFetcher(new File(path)));
      	config.setHomeDir(home);
        config.setStartEmbeddedWebServer(true);
        config.setPort(8082);
       //config.setInitialProtocolBuffersPort(8020);
        config.setClassPath(System.getProperty("java.class.path"));
           
        config.setLocalDev(true);
        config.setStartCommandLine(true);
        
        // Create a BIMserver
        BimServer bimServer = new BimServer(config);

When I run this code there is an error when I create bimServer and the logfile is:

09-07-2015 15:39:46 INFO  Starting BIMserver                                                               (org.bimserver.BimServer.java:230) 
09-07-2015 15:39:46 INFO  Using "D:\Sara\Workspace\BimServer2\dirHome\home" as homedir                     (org.bimserver.BimServer.java:232) 
09-07-2015 15:39:47 ERROR                                                                                  (org.bimserver.BimServer.java:275) 
java.lang.IllegalArgumentException
	at org.eclipse.jdt.core.dom.ASTParser.<init>(ASTParser.java:201)
	at org.eclipse.jdt.core.dom.ASTParser.newParser(ASTParser.java:109)
	at org.bimserver.shared.meta.SService.extractJavaDoc(SService.java:77)
	at org.bimserver.shared.meta.SService.processClass(SService.java:73)
	at org.bimserver.shared.meta.SService.processClass(SService.java:70)
	at org.bimserver.shared.meta.SService.init(SService.java:159)
	at org.bimserver.interfaces.SServiceInterfaceService.init(SServiceInterfaceService.java:525)
	at org.bimserver.shared.meta.SServicesMap.initialize(SServicesMap.java:256)
	at org.bimserver.shared.InterfaceList.createSServicesMap(InterfaceList.java:76)
	at org.bimserver.BimServer.<init>(BimServer.java:237)
	at tests.TestIfcEngineEmbedded.main(TestIfcEngineEmbedded.java:61)
09-07-2015 15:39:47 ERROR                                                                                  (org.bimserver.BimServer.java:222) 
java.lang.NullPointerException
	at org.bimserver.BimServer.<init>(BimServer.java:277)
	at tests.TestIfcEngineEmbedded.main(TestIfcEngineEmbedded.java:61)

Where is the problem??
Thanks in advance

**Comment by rubendel** [comment]
Not really sure what you are trying to do here, this code would start another BIMserver, is that what you want? Connecting to an already running BIMserver should be as easy as
```
BimServerClientInterface client = LocalDevSetup.setupJson("http://localhost:8082");
```

**Comment by saras82** [comment]
Hi and thanks for your help. When I run this line
BimServerClientInterface client = LocalDevSetup.setupJson("http://localhost:8082");
client is null.....
My BimServer is up at this address and port.....
why client is null?
Thanks in advance!!
