### ISSUE TITLE
Bimsie1LowLevelInterface .removeReference .removeReferenceByOid error

### ISSUE THREAD

**Issue by dlabz** [opensourceBIM/BIMserver#240]
I have an IfcGroup object, with IfcRelAssignsToGroup set as it's "IsGroupedBy" property. 
IfcRelAssignsToGroup than has a list of objects as it's "RelatedObjects" property.

If I call: 
```
"request":{
"interface":"Bimsie1LowLevelInterface",
"method":"removeReferenceByOid",
"parameters":{
"tid":"9",
"oid":"66086", //id of IfcRelAssignsToGroup
"referenceName":"RelatedObjects",
"referencedOid":"327825" //id of a related object
}}
```
and commit transaction, server returns 
```
"exception": {
      "__type": "NullPointerException",
      "message": "java.lang.NullPointerException"
    }
```
and log shows:
```
10-09-2015 22:42:29 ERROR                                                                                  (org.bimserver.JsonHandler.java:158) 
java.lang.NullPointerException
	at org.eclipse.emf.common.util.AbstractEList.getNonDuplicates(AbstractEList.java:1161)
	at org.eclipse.emf.common.util.AbstractEList.addAll(AbstractEList.java:366)
	at org.eclipse.emf.ecore.util.EcoreEList.set(EcoreEList.java:457)
	at org.eclipse.emf.ecore.impl.EStructuralFeatureImpl$InternalSettingDelegateMany.dynamicSet(EStructuralFeatureImpl.java:1729)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eDynamicSet(BasicEObjectImpl.java:1127)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eSet(BasicEObjectImpl.java:1101)
	at org.bimserver.emf.IdEObjectImpl.eSet(IdEObjectImpl.java:194)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eSet(BasicEObjectImpl.java:1071)
	at org.bimserver.emf.IdEObjectImpl.eSet(IdEObjectImpl.java:70)
	at org.bimserver.changes.RemoveReferenceChange.execute(RemoveReferenceChange.java:97)
	at org.bimserver.database.actions.CommitTransactionDatabaseAction.execute(CommitTransactionDatabaseAction.java:160)
	at org.bimserver.database.actions.CommitTransactionDatabaseAction.execute(CommitTransactionDatabaseAction.java:1)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:625)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:617)
	at org.bimserver.webservices.impl.Bimsie1LowLevelServiceImpl.commitTransaction(Bimsie1LowLevelServiceImpl.java:109)
	at org.bimserver.generated.Bimsie1LowLevelInterfaceReflector1.callMethod(Bimsie1LowLevelInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:219)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:128)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:60)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:73)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:110)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
	at java.lang.Thread.run(Thread.java:745)
```

BIMserver: master branch

**Comment by rubendel** [comment]
https://github.com/opensourceBIM/BIMserver/commit/796265bb5b4076d1bb989e160fe6742ac0c6967c

**Comment by dlabz** [comment]
The error is fixed, but the changes don't seem to be made to the model.

**Comment by dlabz** [comment]
PING!

Issue still present on 1.4.0-FINAL-2015-09-28  

Though error is gone, and new revision is created after modification, the IfcRelAssignsToGroup->RelatedObjects still shows the same list of elements, where change would be expected.
