### ISSUE TITLE
Last Release of BimServer doesnt produce any BimQL results

### ISSUE THREAD

**Issue by Jaakko** [opensourceBIM/BIMserver#243]
This issue was originally posted to bimql repo by @cancunvisual (https://github.com/opensourceBIM/bimql/issues/3). I copy-paste it here because I guess this is the correct place for this issue.

Creating a query inside bimserver gets nothing, just one blank screen. Loaded a IFC then get to the Query tab with any sample Download with JSON, IFC or wathever ... it just display a blank screen.

Even with query: Select $Var1

My setup is: Win-8 / JRE 1.8 / Tomcat 7.0 and the latest release for bimserver with tomcat in github.

Bimserver's log throws this:

java.lang.NoSuchMethodError: org.bimserver.plugins.ModelHelper.copy(Lorg/bimserver/emf/IdEObject;)Lorg/bimserver/emf/IdEObject;
at nl.wietmazairac.bimql.BimQLQueryEngine.query(BimQLQueryEngine.java:168)
at org.bimserver.database.actions.DownloadQueryDatabaseAction.execute(DownloadQueryDatabaseAction.java:76)
at org.bimserver.database.actions.DownloadQueryDatabaseAction.execute(DownloadQueryDatabaseAction.java:44)
at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:593)
at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:585)
at org.bimserver.longaction.LongDownloadOrCheckoutAction.executeAction(LongDownloadOrCheckoutAction.java:118)
at org.bimserver.longaction.LongDownloadAction.execute(LongDownloadAction.java:63)
at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
at java.lang.Thread.run(Unknown Source)
02-08-2015 01:25:57 ERROR Invalid downloadId: 79 (org.bimserver.servlets.DownloadServlet.java:226)

**Comment by rubendel** [comment]
Looks like a changed interface made the prebuilt BIMQL plugin incompatible. I've built a new version of BIMQL, the new BIMserver release will have it.

**Comment by rubendel** [comment]
Just tested the newest release, basic BIMQL is working: https://github.com/opensourceBIM/BIMserver/releases/tag/1.4.0-FINAL-2015-09-23
