### ISSUE TITLE
Using a serializer in a client app to split IFC products

### ISSUE THREAD

**Issue by mguimard** [opensourceBIM/BIMserver#255]
Hello,

I'm trying to use a serializer to generate JSON files for each product of an IFC file
This code iterates all products and tries to generate a JSON file with geometry for each product

    SSerializerPluginConfiguration s = client.getBimsie1ServiceInterface().getSerializerByName("JsonSerializerWithGeometry");
        long oid = s.getOid();

     for (IfcProduct product : ifcRelContainedInSpatialStructure.getRelatedElements()) {               
         long objectId = product.getOid();
         Set<Long> oids = new HashSet<Long>();
         oids.add(objectId);
         Long id = client.getBimsie1ServiceInterface().downloadByOids(new HashSet<Long>(project.getRevisions()), oids, oid, true, true);
         InputStream downloadData = client.getDownloadData(id, oid);
    }

Then the input stream is copied in a local file, but contains all the products of the ifc file. I think the issue comes from the usage of the downloadByOids method. What should be the right parameters to achieve this ?

**Comment by rubendel** [comment]
It's probably the result of sending true for the last parameter, "deep".

**Comment by mguimard** [comment]
Great, this works for some serializers (Json, BinaryGeometrySerializer, etc..). However, using the Ifc2x3 serializer, I'm getting this exception (parameter deep = false ) : 

Client side : 


    Exception in thread "main" org.bimserver.shared.json.ReflectorException:     com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 1 column 211
	at     org.bimserver.shared.json.JsonSocketReflector.call(JsonSocketReflector.java:93)
	at org.bimserver.shared.json.JsonReflector.callMethod(JsonReflector.java:57)
	at     org.bimserver.generated.Bimsie1ServiceInterfaceImpl1.getDownloadData(Bimsie1    ServiceInterfaceImpl1.java)
	at     com.docdoku.plugins.ifcparser.BimProjectHandler.getModelFromFile(BimProjectHandler.java:91)
	at com.docdoku.plugins.ifcparser.Main.main(Main.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at     sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at     sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
    Caused by: com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 1 column 211
	at com.google.gson.internal.Streams.parse(Streams.java:54)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at     org.bimserver.shared.json.JsonSocketReflector.call(JsonSocketReflector.java:81)
	... 9 more
    Caused by: java.io.EOFException: End of input at line 1 column 211
	at     com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1377)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:471)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403)
	at     com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:666)
	at     com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:667)
	at     com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642)
	at com.google.gson.internal.Streams.parse(Streams.java:44)
	... 12 more

Server side : 

    13-10-2015 12:47:24 INFO  org.bimserver.GeometryGenerator - Rendertime: 2621ms, Reused: 0 B, Total:    684.70 KB, Final:    684.70 KB
    13-10-2015 12:47:24 INFO  org.bimserver.cache.DiskCacheManager - Start caching 4456451-[IfcRelContainedInSpatialStructure].json
    13-10-2015 12:47:24 INFO  org.bimserver.cache.DiskCacheOutputStream - Renaming temp file 264465736.__tmp to 264465736
    13-10-2015 12:47:24 INFO  org.bimserver.cache.DiskCacheManager - Done caching 4456451-[IfcRelContainedInSpatialStructure].json
    13-10-2015 12:47:24 INFO  org.bimserver.cache.DiskCacheManager - Start caching 4456451-29229201.ifc
    13-10-2015 12:47:24 INFO  org.bimserver.cache.DiskCacheManager - Removing cache 4456451-29229201.ifc
    13-10-2015 12:47:24 ERROR org.bimserver.JsonHandler - 
    org.bimserver.database.UncheckedBimserverDatabaseException:     org.bimserver.database.BimserverDatabaseException: Database session is closed
	at     org.bimserver.database.DatabaseSession.load(DatabaseSession.java:1412)
	at org.bimserver.ServerIfcModel.load(ServerIfcModel.java:30)
	at org.bimserver.emf.IdEObjectImpl.load(IdEObjectImpl.java:123)
	at org.bimserver.emf.IdEObjectImpl.dynamicGet(IdEObjectImpl.java:55)
	at     org.eclipse.emf.ecore.impl.EStructuralFeatureImpl$InternalSettingDelegateSingleData.dynamicGet(EStructuralFeatureImpl.java:2184)
	at     org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1027)
	at     org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1011)
	at     org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1003)
	at     org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:998)
	at     org.bimserver.ifc.step.serializer.IfcStepSerializer.writeObject(IfcStepSerializer.java:340)
	at     org.bimserver.ifc.step.serializer.IfcStepSerializer.writeEDataType(IfcStepSerializer.java:314)
	at     org.bimserver.ifc.step.serializer.IfcStepSerializer.write(IfcStepSerializer.java:300)
	at     org.bimserver.ifc.step.serializer.IfcStepSerializer.write(IfcStepSerializer.java:104)
	at     org.bimserver.plugins.serializers.EmfSerializer.writeToOutputStream(EmfSerializer.java:125)
	at     org.bimserver.plugins.serializers.EmfSerializerDataSource.writeToOutputStream(EmfSerializerDataSource.java:60)
	at     org.bimserver.plugins.serializers.CacheStoringEmfSerializerDataSource.writeToOutputStream(CacheStoringEmfSerializerDataSource.java:37)
	at org.bimserver.shared.json.JsonConverter.toJson(JsonConverter.java:84)
	at org.bimserver.shared.json.JsonConverter.toJson(JsonConverter.java:67)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:146)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:60)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:73)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:110)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at     org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at     org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at     org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at     org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at     org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at     org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at     org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at     org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
	at     org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
	at java.lang.Thread.run(Thread.java:745)
    Caused by: org.bimserver.database.BimserverDatabaseException: Database session is closed
	at     org.bimserver.database.DatabaseSession.checkOpen(DatabaseSession.java:741)
	at org.bimserver.database.DatabaseSession.get(DatabaseSession.java:755)
	at     org.bimserver.database.DatabaseSession.lazyLoad(DatabaseSession.java:1396)
	at     org.bimserver.database.DatabaseSession.load(DatabaseSession.java:1408)
	... 40 more

Code used : 

    SSerializerPluginConfiguration s = client.getBimsie1ServiceInterface().getSerializerByName("Ifc2x3");
        long oid = s.getOid();
     Long id = client.getBimsie1ServiceInterface().downloadByOids(
                        Collections.singleton(project.getLastRevisionId()),
                        Collections.singleton(product.getOid()),
                        oid, true, false);

**Comment by dlabz** [comment]
Check if BIMserver has enough memory. Big projects will use up all memory, and BIMserver may crash.

**Comment by mguimard** [comment]
Tried with 8G this doesn't help. The IFC file I'm using is only 213kB.

**Comment by dlabz** [comment]
machine with 8G or -xmx8g ?

**Comment by mguimard** [comment]
On a 16G memory linux machine with the following command : 

    java -Xmx8g -Xss2048k -XX:MaxPermSize=4g

**Comment by dlabz** [comment]
Also, there's no "Ifc2x3" serializer. Only "Ifc2x3tc1"

**Comment by mguimard** [comment]
Actually there's a serializer with default name "Ifc2x3" (Ifc2x3tc1StepSerializerPlugin)

If I try

     SSerializerPluginConfiguration s = client.getBimsie1ServiceInterface().getSerializerByName("Ifc2x3tc1");

I'm getting

    Exception in thread "main" org.bimserver.shared.exceptions.UserException: No SerializerPluginConfiguration found where name = Ifc2x3tc1

which is quite normal.

**Comment by dlabz** [comment]
Ok.

Next to check is if your model is valid. JSON serializer will happily serialize whatever is thrown at it. IFC serializer will crash if model isn't valid.

**Comment by mguimard** [comment]
The JSON serializer works like a charm, and I can see the model rendered in my web browser using the default interface.

**Comment by dlabz** [comment]
From what I know, duplicate element will crash IFC serializer (due no duplicates constrain), but will work on JSON serializer which will overwrite duplicate entries without complaining.

I don't know of any particular app or method to verify the model.

**Comment by berlotti** [comment]
check if you are using the right Java version

**Comment by rubendel** [comment]
There was a bug in BIMserver causing this, it has been fixed. There is another problem though, and that is that splitting a model per IfcProduct will result in very small, invalid, and probably useles IFC files. It will include the IfcProduct + all objects directly related to it, but those will all be empty. That's just a decision, we are working on a more elaborate querying method though.

**Comment by berlotti** [comment]
hi @mguimard 
We give away BIMserver coffee mugs ('find a bug, get a mug') for people who report a bug.
If you want one, please e-mail me your postal address to leon.vanberlo@tno.nl 

PS: the new query language will be very cool!
