### ISSUE TITLE
BimQL Error

### ISSUE THREAD

**Issue by wuestenfux** [opensourceBIM/BIMserver#259]
Hi there,

I try to test the query function with the given examples, but I only get empty files and this error:

20-10-2015 14:21:21 ERROR org.bimserver.BimServer - 
java.lang.NoSuchMethodError: org.bimserver.plugins.ModelHelper.copy(Lorg/bimserver/emf/IdEObject;)Lorg/bimserver/emf/IdEObject;
	at nl.wietmazairac.bimql.BimQLQueryEngine.query(BimQLQueryEngine.java:168)
	at org.bimserver.database.actions.DownloadQueryDatabaseAction.execute(DownloadQueryDatabaseAction.java:93)
	at org.bimserver.database.actions.DownloadQueryDatabaseAction.execute(DownloadQueryDatabaseAction.java:49)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:625)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:617)
	at org.bimserver.longaction.LongDownloadOrCheckoutAction.executeAction(LongDownloadOrCheckoutAction.java:118)
	at org.bimserver.longaction.LongDownloadAction.execute(LongDownloadAction.java:63)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
	at java.lang.Thread.run(Thread.java:745)
20-10-2015 14:21:21 ERROR org.bimserver.servlets.DownloadServlet - Invalid downloadId: 30

OS X 10.11; BIMserver 1.4.0, Duplex Model

**Comment by rubendel** [comment]
Seems like the BIMQL version does not match with the BIMserver version, which version of BIMserver?

**Comment by wuestenfux** [comment]
Works fine with the newest Version
