### ISSUE TITLE
ServiceInterface.getOidByGuid - NullPointException

### ISSUE THREAD

**Issue by wuestenfux** [opensourceBIM/BIMserver#261]
Hi there,

I'm trying to test multiple API methods, such as getOidByGuid.
I got an ServerException and the Message "Unknown error: null", although i copy/pasted the GUID from a query result (.CSV) and tried multiple Roids (1,2,3..12)

25-10-2015 13:12:28 ERROR org.bimserver.webservices.impl.GenericServiceImpl - 
java.lang.NullPointerException
	at org.bimserver.database.actions.GetOidByGuidDatabaseAction.execute(GetOidByGuidDatabaseAction.java:44)
	at org.bimserver.database.actions.GetOidByGuidDatabaseAction.execute(GetOidByGuidDatabaseAction.java:29)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:625)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:617)
	at org.bimserver.webservices.impl.ServiceImpl.getOidByGuid(ServiceImpl.java:691)
	at org.bimserver.generated.ServiceInterfaceReflector1.callMethod(ServiceInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:219)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:129)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:60)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:73)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:110)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
	at java.lang.Thread.run(Thread.java:745)

Using bimserver-1.4.0-FINAL-2015-10-25.jar

**Comment by rubendel** [comment]
Why did you use 1, 2, 3...12 as roids? Those are definitely not existing roids

**Comment by wuestenfux** [comment]
Ups, thought it would be the RevisionID but i guess that's wrong. Could you tell me what the Roid is and how to get it? Thanks

**Comment by rubendel** [comment]
it's the Revision ObjectID, which of type long. You can get it from a SRevision object as the oid.

**Comment by wuestenfux** [comment]
thank you very much!
