### ISSUE TITLE
CodeMigrator.java ERROR SchemaException

### ISSUE THREAD

**Issue by bbrangeo** [opensourceBIM/BIMserver#285]
I don't understand when I execute org.bimserver.database.migrations.CodeMigrator.java I have the following error : 

someone can help me ?

17:17:45 ERROR                                                                                  (org.bimserver.emf.PackageMetaData.java:102) 
org.bimserver.plugins.schema.SchemaException: No schema plugins found
	at org.bimserver.plugins.PluginManager.requireSchemaDefinition(PluginManager.java:434)
	at org.bimserver.emf.PackageMetaData.<init>(PackageMetaData.java:100)
	at org.bimserver.emf.MetaDataManager.addEPackage(MetaDataManager.java:82)
	at org.bimserver.emf.MetaDataManager.init(MetaDataManager.java:46)
	at org.bimserver.database.migrations.CodeMigrator.start(CodeMigrator.java:110)
	at org.bimserver.database.migrations.CodeMigrator.main(CodeMigrator.java:73)
17:17:45 ERROR                                                                                  (org.bimserver.emf.PackageMetaData.java:102) 
org.bimserver.plugins.schema.SchemaException: No schema plugins found
	at org.bimserver.plugins.PluginManager.requireSchemaDefinition(PluginManager.java:434)
	at org.bimserver.emf.PackageMetaData.<init>(PackageMetaData.java:100)
	at org.bimserver.emf.MetaDataManager.addEPackage(MetaDataManager.java:82)
	at org.bimserver.emf.MetaDataManager.init(MetaDataManager.java:47)
	at org.bimserver.database.migrations.CodeMigrator.start(CodeMigrator.java:110)
	at org.bimserver.database.migrations.CodeMigrator.main(CodeMigrator.java:73)
17:17:46 ERROR                                                                                  (org.bimserver.emf.PackageMetaData.java:102) 
org.bimserver.plugins.schema.SchemaException: No schema plugins found
	at org.bimserver.plugins.PluginManager.requireSchemaDefinition(PluginManager.java:434)
	at org.bimserver.emf.PackageMetaData.<init>(PackageMetaData.java:100)
	at org.bimserver.emf.MetaDataManager.addEPackage(MetaDataManager.java:82)
	at org.bimserver.emf.MetaDataManager.init(MetaDataManager.java:46)
	at org.bimserver.tools.generators.DataObjectGeneratorWrapper.generateDataObjects(DataObjectGeneratorWrapper.java:70)
	at org.bimserver.database.migrations.CodeMigrator.start(CodeMigrator.java:120)
	at org.bimserver.database.migrations.CodeMigrator.main(CodeMigrator.java:73)
17:17:46 ERROR                                                                                  (org.bimserver.emf.PackageMetaData.java:102) 
org.bimserver.plugins.schema.SchemaException: No schema plugins found
	at org.bimserver.plugins.PluginManager.requireSchemaDefinition(PluginManager.java:434)
	at org.bimserver.emf.PackageMetaData.<init>(PackageMetaData.java:100)
	at org.bimserver.emf.MetaDataManager.addEPackage(MetaDataManager.java:82)
	at org.bimserver.emf.MetaDataManager.init(MetaDataManager.java:47)
	at org.bimserver.tools.generators.DataObjectGeneratorWrapper.generateDataObjects(DataObjectGeneratorWrapper.java:70)
	at org.bimserver.database.migrations.CodeMigrator.start(CodeMigrator.java:120)
	at org.bimserver.database.migrations.CodeMigrator.main(CodeMigrator.java:73)

**Comment by rubendel** [comment]
Hi, there was an error in the code, it was working but the error messages were confusing. Make sure you add a [plugin argument](https://github.com/opensourceBIM/BIMserver/wiki/Eclipse#adding-the-plugins-property) to your run configuration pointing to your BIMserver directory as well.

**Comment by bbrangeo** [comment]
Thanks Ruben

**Comment by bbrangeo** [comment]
Hi,

I have a problem to compile :

[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-gpg-plugin:1.5:sign (sign-artifacts) on
project PluginBase: Exit code: 127 -> [Help 1]


I added :

<plugin> <groupId>org.apache.maven.plugins</groupId> <artifactId>
maven-gpg-plugin</artifactId> <configuration> <skip>true</skip>
</configuration> </plugin>

Boris BRANGEON

Post Doctorant
APR ADEME RENOIR
Université de la Rochelle - Laboratoire LaSIE
<http://lasie.univ-larochelle.fr>


http://renoir.univ-lr.fr

2016-01-06 10:14 GMT+01:00 Ruben de Laat <notifications@github.com>:

**Comment by rubendel** [comment]
Please don't cross-post issues

**Comment by bbrangeo** [comment]
Ok sorry.

Boris

Boris BRANGEON

Post Doctorant
APR ADEME RENOIR
Université de la Rochelle - Laboratoire LaSIE
<http://lasie.univ-larochelle.fr>


http://renoir.univ-lr.fr

2016-01-13 11:23 GMT+01:00 Ruben de Laat <notifications@github.com>:
