### ISSUE TITLE
Server won't start; Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by kamelisko** [opensourceBIM/BIMserver#297]
No idea what this means... Wrong Java Version?

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/bimserver/JarBimServer : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by rubendel** [comment]
Yup, wrong Java versionm first hit on google: http://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0

**Comment by kamelisko** [comment]
Hmm. My java is the newest Java 8 update 71, but it still doesn't work. I tried both versions of 1.4.5 but the issue is same...? Am I doing something wrong?

**Comment by rubendel** [comment]
There is probably also a Java 7 version on your machine, make sure Java 8 is the default.
