### ISSUE TITLE
BimSie extended data for revision

### ISSUE THREAD

**Issue by timocontecht** [opensourceBIM/BIMserver#299]
Is extended data for revisions supported? The following does not seem to work: 

```
// Client-side, we also use a PluginManager, for example to be
                // able to use the (IFC) schemas
                PluginManager pluginManager = LocalDevPluginLoader
                        .createPluginManager(new File("home"));

                // Load all plugins available on the classpath
                pluginManager.loadPluginsFromCurrentClassloader();

                // Create a MetaDataManager, and initialize it, this code will
                // be simplified/hidden in the fut
// Client-side, we also use a PluginManager, for example to be
                // able to use the (IFC) schemas
                PluginManager pluginManager = LocalDevPluginLoader
                        .createPluginManager(new File("home"));

                // Load all plugins available on the classpath
                pluginManager.loadPluginsFromCurrentClassloader();

                // Create a MetaDataManager, and initialize it, this code will
                // be simplified/hidden in the future
                MetaDataManager metaDataManager = new MetaDataManager(
                        pluginManager);
                pluginManager.setMetaDataManager(metaDataManager);
                metaDataManager.init();

                // Initialize all loaded plugins
                pluginManager.initAllLoadedPlugins();

                // Create a factory for BimServerClients, connnect via JSON in
                // this case
                BimServerClientFactory factory = new JsonBimServerClientFactory(
                        metaDataManager, server);

                // Create a new client, with given authorization, replace this
                // with your credentials
                client = factory.create(new UsernamePasswordAuthenticationInfo(
                        name, password));



            Bimsie1ServiceInterface bimsie = client.getBimsie1ServiceInterface();
            SDeserializerPluginConfiguration deserializer = 
bimsie.getSuggestedDeserializerForExtension("ifc", project.getOid());

Long roid = bimsie.checkin(project.getOid(), user, deserializer.getOid(), 

                    file.length(), file.getName(), new DataHandler(file.toURI().toURL()), false);

            SExtendedData extData = new SExtendedData();
            extData.setAdded(new Date());
            extData.setTitle(user);
            client.getBimsie1ServiceInterface().addExtendedDataToRevision(roid, extData);

            // TEST whether this is required ...
            // refresh project
            project = client.getBimsie1ServiceInterface().getProjectByPoid(project.getOid());

            project.getConcreteRevisions();`
```

**Comment by rubendel** [comment]
Any error messages? Does it work when you try to do it manually (via BIMvie.ws?)

**Comment by timoutwente** [comment]
Ruben, 
sorry for the very late reply. I had to deliver a project, so no chance ...

Here is the console trace:

2016-02-20 15:08:45 DEBUG wire:86 - http-outgoing-0 >> "{"request":{"interface":"Bimsie1ServiceInterface","method":"addExtendedDataToRevision","parameters":{"roid":67,"extendedData":{"__type":"SExtendedData","added":1455977325470,"fileId":-1,"oid":-1,"projectId":-1,"revisionId":-1,"rid":0,"schemaId":-1,"size":0,"title":"Timo","url":null,"userId":-1}}},"token":"d4f8d8e7c41621779ee376f84eec3ca5a73166cda9bc02afb0a0bc556c18ca52a2bbda3f086b57c6cc0aa0e02da44a55"}"
2016-02-20 15:08:45 DEBUG wire:72 - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
2016-02-20 15:08:45 DEBUG wire:72 - http-outgoing-0 << "Server: Apache-Coyote/1.1[\r][\n]"
2016-02-20 15:08:45 DEBUG wire:72 - http-outgoing-0 << "Access-Control-Allow-Origin: *[\r][\n]"
2016-02-20 15:08:45 DEBUG wire:72 - http-outgoing-0 << "Access-Control-Allow-Headers: Content-Type[\r][\n]"
2016-02-20 15:08:45 DEBUG wire:72 - http-outgoing-0 << "Content-Type: application/json;charset=UTF-8[\r][\n]"
2016-02-20 15:08:45 DEBUG wire:72 - http-outgoing-0 << "Content-Length: 87[\r][\n]"
2016-02-20 15:08:45 DEBUG wire:72 - http-outgoing-0 << "Date: Sat, 20 Feb 2016 14:08:45 GMT[\r][\n]"
2016-02-20 15:08:45 DEBUG wire:72 - http-outgoing-0 << "[\r][\n]"
2016-02-20 15:08:45 DEBUG headers:113 - http-outgoing-0 << HTTP/1.1 200 OK
2016-02-20 15:08:45 DEBUG headers:116 - http-outgoing-0 << Server: Apache-Coyote/1.1
2016-02-20 15:08:45 DEBUG headers:116 - http-outgoing-0 << Access-Control-Allow-Origin: *
2016-02-20 15:08:45 DEBUG headers:116 - http-outgoing-0 << Access-Control-Allow-Headers: Content-Type
2016-02-20 15:08:45 DEBUG headers:116 - http-outgoing-0 << Content-Type: application/json;charset=UTF-8
2016-02-20 15:08:45 DEBUG headers:116 - http-outgoing-0 << Content-Length: 87
2016-02-20 15:08:45 DEBUG headers:116 - http-outgoing-0 << Date: Sat, 20 Feb 2016 14:08:45 GMT
2016-02-20 15:08:45 DEBUG MainClientExec:284 - Connection can be kept alive indefinitely
2016-02-20 15:08:45 DEBUG wire:86 - http-outgoing-0 << "{"response":{"exception":{"__type":"ServerException","message":"Unknown error: null"}}}"
2016-02-20 15:08:45 DEBUG PoolingHttpClientConnectionManager:314 - Connection [id: 0][route: {}->http://localhost:8085] can be kept alive indefinitely
2016-02-20 15:08:45 DEBUG PoolingHttpClientConnectionManager:320 - Connection released: [id: 0][route: {}->http://localhost:8085][total kept alive: 1; route allocated: 1 of 5; total allocated: 1 of 20]
2016-02-20 15:08:45 DEBUG JsonSocketReflector:80 - {"response":{"exception":{"__type":"ServerException","message":"Unknown error: null"}}}
2016-02-20 15:08:45 DEBUG MainClientExec:143 - Cancelling request execution
org.bimserver.shared.exceptions.ServerException: Unknown error: null
	at org.bimserver.shared.json.JsonReflector.callMethod(JsonReflector.java:77)
	at org.bimserver.generated.Bimsie1ServiceInterfaceImpl1.addExtendedDataToRevision(Bimsie1ServiceInterfaceImpl1.java)
	at eu.contecht.globld.BIMREST.repository.impl.BIMServerCheckinRepository.checkIn(BIMServerCheckinRepository.java:224)

To be honest, I do not get the interface on bimwie. Why should I upload a file and what schema do I need to select? Maybe I do understand the concept of extended data wrong? 

Timo

**Comment by rubendel** [comment]
This has changed quite a bit, basically as you said, there is no need to upload a schema, nothing is checked anyways. This has now evolved to simple a piece of text.
