### ISSUE TITLE
IFC won't upload

### ISSUE THREAD

**Issue by px3l** [opensourceBIM/BIMserver#310]
Hey, so still have the issue where no IFC file can be uploaded to a new project on the 1.4 latest release. I have tried with a server with 16gb ram, in case it was eating it but it still hangs. When is the 1.5 version being released as a war/jar file?

Thanks!

**Comment by px3l** [comment]
this is the error from the logs

```
27-02-2016 19:21:55 ERROR                                                                                  (org.bimserver.servlets.UploadServlet.java:146) 
org.bimserver.shared.exceptions.ServerException: Error on line 4: IFCDOC_9_2 is not supported by this deserializer (IFC4 is)
	at org.bimserver.webservices.impl.ServiceImpl.checkin(ServiceImpl.java:228)
	at org.bimserver.servlets.UploadServlet.service(UploadServlet.java:136)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.bimserver.plugins.deserializers.DeserializeException: Error on line 4: IFCDOC_9_2 is not supported by this deserializer (IFC4 is)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.processHeader(IfcStepDeserializer.java:329)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.processLine(IfcStepDeserializer.java:222)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.read(IfcStepDeserializer.java:161)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.read(IfcStepDeserializer.java:133)
	at org.bimserver.webservices.impl.ServiceImpl.checkin(ServiceImpl.java:215)
	... 24 more
```

**Comment by px3l** [comment]
so we downloaded an IFC4 but get this error

```
27-02-2016 19:21:55 ERROR                                                                                  (org.bimserver.servlets.UploadServlet.java:146) 
org.bimserver.shared.exceptions.ServerException: Error on line 4: IFCDOC_9_2 is not supported by this deserializer (IFC4 is)
	at org.bimserver.webservices.impl.ServiceImpl.checkin(ServiceImpl.java:228)
	at org.bimserver.servlets.UploadServlet.service(UploadServlet.java:136)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.bimserver.plugins.deserializers.DeserializeException: Error on line 4: IFCDOC_9_2 is not supported by this deserializer (IFC4 is)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.processHeader(IfcStepDeserializer.java:329)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.processLine(IfcStepDeserializer.java:222)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.read(IfcStepDeserializer.java:161)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.read(IfcStepDeserializer.java:133)
	at org.bimserver.webservices.impl.ServiceImpl.checkin(ServiceImpl.java:215)
	... 24 more
```

**Comment by px3l** [comment]
the same error is being thrown by using 2x3 and 2x3 serializer, or the 4 and 4 serializer... i can't win

```
27-02-2016 19:26:23 ERROR                                                                                  (org.bimserver.servlets.UploadServlet.java:146) 
org.bimserver.shared.exceptions.ServerException: Error on line 4: IFCDOC_5_2 is not supported by this deserializer (IFC2X3 is)
	at org.bimserver.webservices.impl.ServiceImpl.checkin(ServiceImpl.java:228)
	at org.bimserver.servlets.UploadServlet.service(UploadServlet.java:136)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.bimserver.plugins.deserializers.DeserializeException: Error on line 4: IFCDOC_5_2 is not supported by this deserializer (IFC2X3 is)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.processHeader(IfcStepDeserializer.java:329)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.processLine(IfcStepDeserializer.java:222)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.read(IfcStepDeserializer.java:161)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.read(IfcStepDeserializer.java:133)
	at org.bimserver.webservices.impl.ServiceImpl.checkin(ServiceImpl.java:215)
	... 24 more
```

**Comment by px3l** [comment]
So when we're using IFC4 its returning `file not supported but IFC4 is` and when we're using 2x3 its saying `file not supported but IFC2x3 is`

**Comment by px3l** [comment]
fixed - error on our behalf!!

**Comment by px3l** [comment]
issue reopened for answer on version1.5!

**Comment by rubendel** [comment]
Hi, version 1.5 has not been released yet, the builds are for testing the build system only.
