### ISSUE TITLE
Error download format CityGML 1.0.0

### ISSUE THREAD

**Issue by duduBrezic** [opensourceBIM/BIMserver#323]
I can't download my project in citygml format, I tested with multiple version of bimserver and multiple ifc file 

I have this Java exception :

java.nio.BufferUnderflowException
at java.nio.Buffer.nextGetIndex(Buffer.java:506)
at java.nio.HeapByteBuffer.getFloat(HeapByteBuffer.java:463)
at org.bimserver.citygml.CityGmlSerializer.setGeometry(CityGmlSerializer.java:671)

**Comment by rubendel** [comment]
CityGML plugin is currently not maintained, it has been moved to its own repository: https://github.com/opensourceBIM/CityGML
