### ISSUE TITLE
The memory leak issue in BIMserver-1.4.0-FINAL-2015-09-14.

### ISSUE THREAD

**Issue by garview** [opensourceBIM/BIMserver#337]
Because the BimServer average weekly collapse time, I wrote a program to reproduce the memory leak problem.

Usually the main operation is to log in and browse the 3D model, so the test method is as follows: the average every 1.6 seconds to carry on an operation, each operation only login and 3D model browsing.
15 minutes later, BimServer crashes.
Is there any way to avoid such a situation?
**Environment**:
windows 7 +jdk 8+BIMserver-1.4.0-FINAL-2015-09-14
**JVM args**:
-Xmx8562m
-Xss1024k
-XX:MaxPermSize=4096m

**jconsole snapshot**:
![qq 20160429161920](https://cloud.githubusercontent.com/assets/18555554/14911173/31d18fa6-0e26-11e6-9a19-6a633dfe1667.png)

**jvisulavm**:
![qq 20160429172436](https://cloud.githubusercontent.com/assets/18555554/14912504/4a3aa2b8-0e2f-11e6-9d33-d856d1a0cf22.png)

the log file：
[BimServer MemoryTestLog.txt](https://github.com/opensourceBIM/BIMserver/files/241975/BimServer.MemoryTestLog.txt)

I intercepted a portion of the error log as follows:

**first error trace**:
29-04-2016 15:16:16 INFO  org.bimserver.cache.DiskCacheManager - Reading from cache 65539-[IfcStructuralMember, IfcStructuralSurfaceMember, IfcStructuralPointConnection, IfcStair, IfcStairFlight, IfcPlate, IfcFeatureElementSubtraction, IfcDistributionPort, IfcStructuralReaction, IfcStructuralPointReaction, IfcStructuralSurfaceMemberVarying, IfcStructuralCurveMemberVarying, IfcWallStandardCase, IfcBuilding, IfcFlowSegment, IfcFeatureElement, IfcAnnotation, IfcProjectionElement, IfcOpeningElement, IfcVirtualElement, IfcPort, IfcFlowController, IfcTendon, IfcRampFlight, IfcElement, IfcReinforcingMesh, IfcStructuralItem, IfcProxy, IfcSpatialStructureElement, IfcRamp, IfcStructuralPlanarAction, IfcReinforcingElement, IfcDistributionControlElement, IfcEquipmentElement, IfcElementAssembly, IfcElectricDistributionPoint, IfcMechanicalFastener, IfcChamferEdgeFeature, IfcSpace, IfcStructuralConnection, IfcDistributionElement, IfcFlowStorageDevice, IfcBeam, IfcColumn, IfcDiscreteAccessory, IfcPile, IfcFastener, IfcStructuralLinearAction, IfcProduct, IfcTransportElement, IfcStructuralCurveMember, IfcFlowMovingDevice, IfcDoor, IfcFeatureElementAddition, IfcBuildingStorey, IfcBuildingElementComponent, IfcStructuralSurfaceConnection, IfcTendonAnchor, IfcWall, IfcBuildingElement, IfcCovering, IfcSite, IfcRailing, IfcWindow, IfcCurtainWall, IfcFurnishingElement, IfcReinforcingBar, IfcGrid, IfcEdgeFeature, IfcBuildingElementPart, IfcRoundedEdgeFeature, IfcMember, IfcDistributionFlowElement, IfcSlab, IfcStructuralAction, IfcEnergyConversionDevice, IfcElementComponent, IfcStructuralActivity, IfcFlowTerminal, IfcFooting, IfcRoof, IfcFlowTreatmentDevice, IfcStructuralLinearActionVarying, IfcDistributionChamberElement, IfcFlowFitting, IfcBuildingElementProxy, IfcStructuralPointAction, IfcStructuralCurveConnection, IfcStructuralPlanarActionVarying, IfcElectricalElement].json
29-04-2016 15:16:16 INFO  org.bimserver.servlets.Streamer - 2528 messages written      6.64 MB
29-04-2016 15:16:20 ERROR org.bimserver.JsonHandler - 
java.lang.NullPointerException
	at org.bimserver.webservices.impl.Bimsie1NotificationRegistryServiceImpl.registerProgressHandler(Bimsie1NotificationRegistryServiceImpl.java:60)
	at org.bimserver.generated.Bimsie1NotificationRegistryInterfaceReflector1.callMethod(Bimsie1NotificationRegistryInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:219)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:128)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:60)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:73)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:110)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
	at java.lang.Thread.run(Thread.java:745)
29-04-2016 15:16:20 INFO  org.bimserver.cache.DiskCacheManager - Reading from cache 65539-[IfcStructuralMember, IfcStructuralSurfaceMember, IfcStructuralPointConnection, IfcStair, IfcStairFlight, IfcPlate, IfcFeatureElementSubtraction, IfcDistributionPort, IfcStructuralReaction, IfcStructuralPointReaction, IfcStructuralSurfaceMemberVarying, IfcStructuralCurveMemberVarying, IfcWallStandardCase, IfcBuilding, IfcFlowSegment, IfcFeatureElement, IfcAnnotation, IfcProjectionElement, IfcOpeningElement, IfcVirtualElement, IfcPort, IfcFlowController, IfcTendon, IfcRampFlight, IfcElement, IfcReinforcingMesh, IfcStructuralItem, IfcProxy, IfcSpatialStructureElement, IfcRamp, IfcStructuralPlanarAction, IfcReinforcingElement, IfcDistributionControlElement, IfcEquipmentElement, IfcElementAssembly, IfcElectricDistributionPoint, IfcMechanicalFastener, IfcChamferEdgeFeature, IfcSpace, IfcStructuralConnection, IfcDistributionElement, IfcFlowStorageDevice, IfcBeam, IfcColumn, IfcDiscreteAccessory, IfcPile, IfcFastener, IfcStructuralLinearAction, IfcProduct, IfcTransportElement, IfcStructuralCurveMember, IfcFlowMovingDevice, IfcDoor, IfcFeatureElementAddition, IfcBuildingStorey, IfcBuildingElementComponent, IfcStructuralSurfaceConnection, IfcTendonAnchor, IfcWall, IfcBuildingElement, IfcCovering, IfcSite, IfcRailing, IfcWindow, IfcCurtainWall, IfcFurnishingElement, IfcReinforcingBar, IfcGrid, IfcEdgeFeature, IfcBuildingElementPart, IfcRoundedEdgeFeature, IfcMember, IfcDistributionFlowElement, IfcSlab, IfcStructuralAction, IfcEnergyConversionDevice, IfcElementComponent, IfcStructuralActivity, IfcFlowTerminal, IfcFooting, IfcRoof, IfcFlowTreatmentDevice, IfcStructuralLinearActionVarying, IfcDistributionChamberElement, IfcFlowFitting, IfcBuildingElementProxy, IfcStructuralPointAction, IfcStructuralCurveConnection, IfcStructuralPlanarActionVarying, IfcElectricalElement].json
29-04-2016 15:16:21 INFO  org.bimserver.cache.DiskCacheManager - Reading from cache 65539-[IfcStructuralMember, IfcStructuralSurfaceMember, IfcStructuralPointConnection, IfcStair, IfcStairFlight, IfcPlate, IfcFeatureElementSubtraction, IfcDistributionPort, IfcStructuralReaction, IfcStructuralPointReaction, IfcStructuralSurfaceMemberVarying, IfcStructuralCurveMemberVarying, IfcWallStandardCase, IfcBuilding, IfcFlowSegment, IfcFeatureElement, IfcAnnotation, IfcProjectionElement, IfcOpeningElement, IfcVirtualElement, IfcPort, IfcFlowController, IfcTendon, IfcRampFlight, IfcElement, IfcReinforcingMesh, IfcStructuralItem, IfcProxy, IfcSpatialStructureElement, IfcRamp, IfcStructuralPlanarAction, IfcReinforcingElement, IfcDistributionControlElement, IfcEquipmentElement, IfcElementAssembly, IfcElectricDistributionPoint, IfcMechanicalFastener, IfcChamferEdgeFeature, IfcSpace, IfcStructuralConnection, IfcDistributionElement, IfcFlowStorageDevice, IfcBeam, IfcColumn, IfcDiscreteAccessory, IfcPile, IfcFastener, IfcStructuralLinearAction, IfcProduct, IfcTransportElement, IfcStructuralCurveMember, IfcFlowMovingDevice, IfcDoor, IfcFeatureElementAddition, IfcBuildingStorey, IfcBuildingElementComponent, IfcStructuralSurfaceConnection, IfcTendonAnchor, IfcWall, IfcBuildingElement, IfcCovering, IfcSite, IfcRailing, IfcWindow, IfcCurtainWall, IfcFurnishingElement, IfcReinforcingBar, IfcGrid, IfcEdgeFeature, IfcBuildingElementPart, IfcRoundedEdgeFeature, IfcMember, IfcDistributionFlowElement, IfcSlab, IfcStructuralAction, IfcEnergyConversionDevice, IfcElementComponent, IfcStructuralActivity, IfcFlowTerminal, IfcFooting, IfcRoof, IfcFlowTreatmentDevice, IfcStructuralLinearActionVarying, IfcDistributionChamberElement, IfcFlowFitting, IfcBuildingElementProxy, IfcStructuralPointAction, IfcStructuralCurveConnection, IfcStructuralPlanarActionVarying, IfcElectricalElement].json
29-04-2016 15:16:21 INFO  org.bimserver.servlets.Streamer - 2528 messages written      6.64 MB

**the second error log**:
29-04-2016 15:18:50 INFO  org.bimserver.servlets.Streamer - 2528 messages written      6.64 MB
29-04-2016 15:18:50 INFO  org.bimserver.cache.DiskCacheManager - Reading from cache 65539-[IfcStructuralMember, IfcStructuralSurfaceMember, IfcStructuralPointConnection, IfcStair, IfcStairFlight, IfcPlate, IfcFeatureElementSubtraction, IfcDistributionPort, IfcStructuralReaction, IfcStructuralPointReaction, IfcStructuralSurfaceMemberVarying, IfcStructuralCurveMemberVarying, IfcWallStandardCase, IfcBuilding, IfcFlowSegment, IfcFeatureElement, IfcAnnotation, IfcProjectionElement, IfcOpeningElement, IfcVirtualElement, IfcPort, IfcFlowController, IfcTendon, IfcRampFlight, IfcElement, IfcReinforcingMesh, IfcStructuralItem, IfcProxy, IfcSpatialStructureElement, IfcRamp, IfcStructuralPlanarAction, IfcReinforcingElement, IfcDistributionControlElement, IfcEquipmentElement, IfcElementAssembly, IfcElectricDistributionPoint, IfcMechanicalFastener, IfcChamferEdgeFeature, IfcSpace, IfcStructuralConnection, IfcDistributionElement, IfcFlowStorageDevice, IfcBeam, IfcColumn, IfcDiscreteAccessory, IfcPile, IfcFastener, IfcStructuralLinearAction, IfcProduct, IfcTransportElement, IfcStructuralCurveMember, IfcFlowMovingDevice, IfcDoor, IfcFeatureElementAddition, IfcBuildingStorey, IfcBuildingElementComponent, IfcStructuralSurfaceConnection, IfcTendonAnchor, IfcWall, IfcBuildingElement, IfcCovering, IfcSite, IfcRailing, IfcWindow, IfcCurtainWall, IfcFurnishingElement, IfcReinforcingBar, IfcGrid, IfcEdgeFeature, IfcBuildingElementPart, IfcRoundedEdgeFeature, IfcMember, IfcDistributionFlowElement, IfcSlab, IfcStructuralAction, IfcEnergyConversionDevice, IfcElementComponent, IfcStructuralActivity, IfcFlowTerminal, IfcFooting, IfcRoof, IfcFlowTreatmentDevice, IfcStructuralLinearActionVarying, IfcDistributionChamberElement, IfcFlowFitting, IfcBuildingElementProxy, IfcStructuralPointAction, IfcStructuralCurveConnection, IfcStructuralPlanarActionVarying, IfcElectricalElement].json
29-04-2016 15:18:50 WARN  org.bimserver.servlets.StreamingSocket - Unhandled Error (closing connection)
java.lang.IllegalArgumentException: value already present: 102
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:238)
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
	at com.google.common.collect.Synchronized$SynchronizedMap.put(Synchronized.java:995)
	at org.bimserver.endpoints.EndPointManager.register(EndPointManager.java:34)
	at org.bimserver.servlets.Streamer.onText(Streamer.java:127)
	at org.bimserver.servlets.StreamingSocket.onWebSocketText(StreamingSocket.java:51)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:128)
	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:64)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:122)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:160)
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:613)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:468)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
	at java.lang.Thread.run(Thread.java:745)
29-04-2016 15:18:51 INFO  org.bimserver.database.berkeley.BerkeleyKeyValueStore - reads: 1101547
29-04-2016 15:18:51 INFO  org.bimserver.servlets.Streamer - 2528 messages written      6.64 MB

**the third error trace**：
29-04-2016 15:19:27 INFO  org.bimserver.database.berkeley.BerkeleyKeyValueStore - reads: 1308429
29-04-2016 15:19:27 ERROR org.bimserver.longaction.LongAction - 
org.bimserver.shared.exceptions.UserException: User has insufficient rights to download revisions from this project
	at org.bimserver.database.actions.DownloadByOidsDatabaseAction.execute(DownloadByOidsDatabaseAction.java:81)
	at org.bimserver.database.actions.DownloadByOidsDatabaseAction.execute(DownloadByOidsDatabaseAction.java:52)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:625)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:617)
	at org.bimserver.longaction.LongDownloadOrCheckoutAction.executeAction(LongDownloadOrCheckoutAction.java:118)
	at org.bimserver.longaction.LongDownloadAction.execute(LongDownloadAction.java:63)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
	at java.lang.Thread.run(Thread.java:745)
29-04-2016 15:19:27 INFO  org.bimserver.servlets.Streamer - 2528 messages written      6.64 MB

……
……
More detailed error logs are in the above log file

**Comment by rubendel** [comment]
BIMserver 1.5 has focused on memory consumption, would be great if you could do this test on that version as well.

**Comment by garview** [comment]
I'd be happy to help the test in this way. Just, when can the 1.5 version of the available release?

**Comment by garview** [comment]
i would get a try. thank you for quick reply.
