### ISSUE TITLE
3D visualization in BIMserver 1.5.48 not running

### ISSUE THREAD

**Issue by klacol** [opensourceBIM/BIMserver#349]
I have downloaded BIMserver 1.5.48 and installed it in my local Tomcat on port 8080. The database is placed in a home directory which I have configured in context,xml.

The setup is running smoothly and I can create a new project and upload a model (Ifc2x3). When I click on the eye, the model is loaded, but it is not visualized in the 3D tab.

Is there something I have to activate after the setup to get the 3D tab up and running?

**Comment by klacol** [comment]
I have checked the log; the last entry is this one:

`INFO [description] o.b.c.NewDiskCacheManager [NewDiskCacheManager.java:105] Reading from cache 6c624c79ac190cbfb67b5ed61b0ec00e`

The file 6c624c79ac190cbfb67b5ed61b0ec00e exists in the cache folder of the homedir. The file contains a json string which is valid.

The bimserver is able to load the data of the modell, since I am able to browse the modell; but the 3D-Viewer does not show up.

**Comment by mansch** [comment]
Noticed the same.
1.5.48 was working when installed several days ago but the 3D Viewer stopped working with a fresh installation from today.

**Comment by klacol** [comment]
Ok, good to know. It probably has something to do with an error related to this request:

`{
  "request": {
    "interface": "org.bimserver.ServiceInterface",
    "method": "getExtendedDataSchemaByNamespace",
    "parameters": {
      "namespace": "http://bimserver.org/3dvisualizationeffects"
    }
  },
  "token": "6ce83da00ad3876535834097f3797a5bbb21d856385df4b0898ee784eab893e7f5c3cb8780fc36b98e4e7d0816954419"
}`

It results on my machine in this response, and then the visualization stopps:

`{
  "response": {
    "exception": {
      "__type": "UserException",
      "message": "No ExtendedDataSchema found where namespace = http://bimserver.org/3dvisualizationeffects"
    }
  }
}`

**Comment by mansch** [comment]
I don't agree. This exception seems to be normal if no extended data shema has been set (see BIMvie.ws -> Server -> Extended Data Schemas).
But after this request normally the download should be the next step.. via downloadByJsonQuery, downlaodByNewJsonQuery, downloadByOids, or whatever..

Maybe I've time to look after it later - but primarily I try to get the BIMview.ws-viewer (with multiselection feature) running with the 1.5.

**Comment by klacol** [comment]
Ok, @mansch you are right. The request "getExtendedDataSchemaByNamespace" is running very often, and always runs into an error. But it is not the reason for the issue, describe here. I have a BIMserver running where I see also this request, and the 3D visualization is running.

**Comment by VladMala** [comment]
hi, same for me cannot see rendered file in 3d window.
It throws error:
13:26:48 ERROR [pool-2-thread-1]:                                                                                  (StreamingGeometryGenerator.java:374) 
java.lang.NullPointerException: null
	at org.ifcopenshell.IfcOpenShellEnginePlugin.createRenderEngine(IfcOpenShellEnginePlugin.java:68) ~[na:na]
	at org.bimserver.renderengine.RenderEnginePools$2.createRenderEngine(RenderEnginePools.java:71) ~[bimserver-1.5.48.jar:na]
	at org.bimserver.renderengine.NoPoolingRenderEnginePool.borrowObject(NoPoolingRenderEnginePool.java:16) ~[bimserver-1.5.48.jar:na]
	at org.bimserver.StreamingGeometryGenerator$Runner.run(StreamingGeometryGenerator.java:184) ~[bimserver-1.5.48.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
13:26:48 ERROR [pool-2-thread-1]:                                                                                  (StreamingGeometryGenerator.java:379) 
java.io.FileNotFoundException: debug/IfcDistributionControlElement.ifc (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method) ~[na:1.8.0_65]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[na:1.8.0_65]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[na:1.8.0_65]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[na:1.8.0_65]
	at org.bimserver.StreamingGeometryGenerator$Runner.writeDebugFile(StreamingGeometryGenerator.java:397) ~[bimserver-1.5.48.jar:na]
	at org.bimserver.StreamingGeometryGenerator$Runner.run(StreamingGeometryGenerator.java:375) ~[bimserver-1.5.48.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]

**Comment by rubendel** [comment]
The "No ExtendedDataSchema found where namespace = http://bimserver.org/3dvisualizationeffects" can be ignored, the 3D view will try and see whether this extended data schema exists, if it does exist it will check the extended data of the revision, if it does not exist (and the "error" is thrown), it won't.

This error is probably caused by a change in the binary format. I have yet to figure out a way of organizing all the different versions of all the different projects.

**Comment by rubendel** [comment]
It is working in https://github.com/opensourceBIM/BIMserver/releases/tag/parent-1.5.49 with the latest versions of BinaryGeometrySerializer and BIMvie.ws

**Comment by klacol** [comment]
Yes, it workes now; it seems to me, that the visualization ist faster than before.
Great, and many thanks!

**Comment by VladMala** [comment]
Hi Ruben!
In version 1.5.49 I got error on loading ifc files (different versions - 3,4):
ERROR [pool-2-thread-6]: Version mismatch: Plugin version IfcOpenShell-0.5.0-dev-2 does not match IfcOpenShell version IfcOpenShell-0.5.0-dev (IfcGeomServerClient.java:48) 
21:18:08 ERROR [pool-2-thread-4]:                                                                                  (StreamingGeometryGenerator.java:385) 
java.lang.NullPointerException: null
	at org.ifcopenshell.IfcGeomServerClient$Command.write(IfcGeomServerClient.java:111) ~[na:na]
	at org.ifcopenshell.IfcGeomServerClient.setDeflection(IfcGeomServerClient.java:59) ~[na:na]
	at org.ifcopenshell.IfcOpenShellEngine.init(IfcOpenShellEngine.java:57) ~[na:na]
	at org.bimserver.renderengine.NoPoolingRenderEnginePool.borrowObject(NoPoolingRenderEnginePool.java:17) ~[bimserver-1.5.49.jar:na]
	at org.bimserver.StreamingGeometryGenerator$Runner.run(StreamingGeometryGenerator.java:184) ~[bimserver-1.5.49.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]

Do you know what is the cause of the problem. Also I cannot see rendered file

**Comment by rubendel** [comment]
Please open a new issue as this has nothing to do with the original issue.
