### ISSUE TITLE
Plugin execution not covered in lifecycle configuration

### ISSUE THREAD

**Issue by oGuzee** [opensourceBIM/BIMserver#354]
Hi,

I'm very new to all this BIM and Java stuff.

I installed Eclipse and followed the instructions on the Wiki-Page.
In the Wiki-Page there is only shown the "master" repository while on my Eclipse I had 4-5 repositories. However, I just picked the "master". (I did it with all repositories either == same)
After that I got this "Plugin execution not covered in lifecycle configuration" error in the "pom.xml" file.

I had this "solution".
![bildschirmfoto 2016-06-06 um 15 07 58](https://cloud.githubusercontent.com/assets/19778298/15822885/90f15c4c-2bf8-11e6-87b4-3a93d7ab8986.png)

It tells me something about lifecycles and other witchcraft which is just melting my brain. After a few "next, next, next, finish" button hits the red X in the "pom.xml" is gone.
So I was happy and proceed the instructions in the Wiki-Page.

There was another discrepancy in the "Running BIMserver from Eclipse" on the Wiki-Page.
It says the "LocalDevBimServerStarter" Class is in "BimServer" but it is in "BimServerJar".
//Note: Don't get me wrong, I don't want to offend anybody. I just want to do it all correctly, since it's about my bachelor thesis. 

Anyway: I did the runas "Java Application" and I had a ton of errors.
![a](https://cloud.githubusercontent.com/assets/19778298/15823213/0adba3a4-2bfa-11e6-9c2b-45794caf48b4.png)

I guess it's a problem with maven. I'd be pleased if you guys could help me abit.

Best regards
oGuzee

**Comment by rubendel** [comment]
Hi, we have made a video that addresses some of these problems:

https://www.youtube.com/watch?v=Vb6gokSBA0I

**Comment by oGuzee** [comment]
thanks man! 

worked ALMOST perfect!

last problem i got: i get SNAPSHOT 1.5.50 while you get 1.5.74. This isn't that bad until it comes to the demo-plugins which are in 1.5.74. i tried to change the pom.xml from 1.5.74 to .50 but got a shitload of errors.

any ideas?

p.s.: 1000x thanks.

**Comment by rubendel** [comment]
Just changed it back to 1.5.50-SNAPSHOT, I don't get any error then, what errors are you getting?

**Comment by oGuzee** [comment]
@rubendel 

I changed the pom.xml from 1.5.74 to 1.5.50 
![bildschirmfoto 2016-06-20 um 15 40 38 2](https://cloud.githubusercontent.com/assets/19778298/16196399/0a17bf84-36fe-11e6-9f17-d85bd2d85245.png)

 --> made the runconfig ("-plugins "/Users/oGuzee/Documents/Eclipse/DemoPlugins/DemoPlugins"") and started. 

![bildschirmfoto 2016-06-20 um 15 44 38](https://cloud.githubusercontent.com/assets/19778298/16196408/1579ec6c-36fe-11e6-9773-5d61822aae5e.png)

But then, when I go to localhost:8080 this occurs:

pt1: 
![bildschirmfoto 2016-06-20 um 15 46 57 2](https://cloud.githubusercontent.com/assets/19778298/16196442/41486738-36fe-11e6-8046-a1f905ee23b8.png)
pt2: 
![bildschirmfoto 2016-06-20 um 15 47 56 2](https://cloud.githubusercontent.com/assets/19778298/16196500/8719d5da-36fe-11e6-90a3-761ffc5e9340.png)

Whole Console: `Logging to /Users/oGuzee/Documents/Eclipse/BIMserver/BimServerJar/home/logs/bimserver.log
15:41:04 INFO  [main]: Starting BIMserver                                                               (BimServer.java:213) 
15:41:04 INFO  [main]: Using "home" as homedir                                                          (BimServer.java:215) 
15:41:07 INFO  [main]: Version: 1.5.50-SNAPSHOT                                                         (BimServer.java:295) 
15:41:14 INFO  [main]: Using "Users/oGuzee/Documents/Eclipse/BIMserver/BimServerJar/../BimServer/emailtemplates/" as template dir (TemplateEngine.java:64) 
15:41:14 INFO  [main]: Non-empty database directory found "home/database"                               (BerkeleyKeyValueStore.java:85) 
15:41:16 INFO  [main]: Changing server state to RUNNING                                                 (ServerInfoManager.java:112) 
15:41:29 INFO  [main]: Skipping strict dependency checking for dependency bimserverapi                  (PluginManager.java:1277) 
15:41:29 INFO  [main]: Skipping strict dependency checking for dependency bimserverapi                  (PluginManager.java:1277) 
15:41:29 INFO  [main]: Skipping strict dependency checking for dependency bimsurfer                     (PluginManager.java:1277) 
15:41:40 WARN  [qtp239937174-28]:                                                                                  (CompressExtension.java:384) 
org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:197) ~[jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:419) ~[jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:313) ~[jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:141) [jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.io.FrameFlusher$Flusher.flush(FrameFlusher.java:152) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.io.FrameFlusher$Flusher.process(FrameFlusher.java:216) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) [jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224) [jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.io.FrameFlusher.enqueue(FrameFlusher.java:381) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.outgoingFrame(AbstractWebSocketConnection.java:610) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextOutgoingFrame(AbstractExtension.java:176) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.access$1100(CompressExtension.java:42) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension$Flusher.compress(CompressExtension.java:514) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension$Flusher.deflate(CompressExtension.java:417) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension$Flusher.process(CompressExtension.java:397) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) [jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224) [jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.outgoingFrame(CompressExtension.java:210) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack$Flusher.process(ExtensionStack.java:389) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) [jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224) [jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.outgoingFrame(ExtensionStack.java:290) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.uncheckedSendFrame(WebSocketRemoteEndpoint.java:304) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.blockingWrite(WebSocketRemoteEndpoint.java:106) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.sendString(WebSocketRemoteEndpoint.java:387) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.jsr356.JsrBasicRemote.sendText(JsrBasicRemote.java:108) [javax-websocket-client-impl-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.bimserver.servlets.websockets.jsr356.Jsr356Impl.send(Jsr356Impl.java:113) [classes/:na]
	at org.bimserver.servlets.Streamer.onOpen(Streamer.java:73) [classes/:na]
	at org.bimserver.servlets.websockets.jsr356.Jsr356Impl.onOpen(Jsr356Impl.java:68) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.jsr356.annotations.OnOpenCallable.call(OnOpenCallable.java:55) [javax-websocket-client-impl-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.jsr356.annotations.JsrEvents.callOpen(JsrEvents.java:170) [javax-websocket-client-impl-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.jsr356.endpoints.JsrAnnotatedEventDriver.onConnect(JsrAnnotatedEventDriver.java:187) [javax-websocket-client-impl-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.openSession(AbstractEventDriver.java:229) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.jsr356.endpoints.AbstractJsrEventDriver.openSession(AbstractJsrEventDriver.java:104) [javax-websocket-client-impl-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.WebSocketSession.open(WebSocketSession.java:489) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.WebSocketSession.onOpened(WebSocketSession.java:423) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.AbstractConnection.onOpen(AbstractConnection.java:198) [jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onOpen(AbstractWebSocketConnection.java:562) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:201) [jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.server.HttpConnection.onCompleted(HttpConnection.java:366) [jetty-server-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:611) [jetty-server-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:442) [jetty-server-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) [jetty-server-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) [jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) [jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.execute(ExecuteProduceConsume.java:101) [jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.ManagedSelector.run(ManagedSelector.java:136) [jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method) ~[na:1.8.0_91]
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51) ~[na:1.8.0_91]
	at sun.nio.ch.IOUtil.write(IOUtil.java:148) ~[na:1.8.0_91]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504) ~[na:1.8.0_91]
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:177) ~[jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	... 56 common frames omitted
15:41:40 ERROR [qtp239937174-28]:                                                                                  (Jsr356Impl.java:119) 
org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:197) ~[jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:419) ~[jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:313) ~[jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:141) [jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.io.FrameFlusher$Flusher.flush(FrameFlusher.java:152) ~[websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.io.FrameFlusher$Flusher.process(FrameFlusher.java:216) ~[websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) ~[jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224) ~[jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.io.FrameFlusher.enqueue(FrameFlusher.java:381) ~[websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.outgoingFrame(AbstractWebSocketConnection.java:610) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextOutgoingFrame(AbstractExtension.java:176) ~[websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.access$1100(CompressExtension.java:42) ~[websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension$Flusher.compress(CompressExtension.java:514) ~[websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension$Flusher.deflate(CompressExtension.java:417) ~[websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension$Flusher.process(CompressExtension.java:397) ~[websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) ~[jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224) ~[jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.outgoingFrame(CompressExtension.java:210) ~[websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack$Flusher.process(ExtensionStack.java:389) ~[websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) ~[jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224) ~[jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.outgoingFrame(ExtensionStack.java:290) ~[websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.uncheckedSendFrame(WebSocketRemoteEndpoint.java:304) ~[websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.blockingWrite(WebSocketRemoteEndpoint.java:106) ~[websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.sendString(WebSocketRemoteEndpoint.java:387) ~[websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.jsr356.JsrBasicRemote.sendText(JsrBasicRemote.java:108) ~[javax-websocket-client-impl-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.bimserver.servlets.websockets.jsr356.Jsr356Impl.send(Jsr356Impl.java:113) [classes/:na]
	at org.bimserver.servlets.Streamer.onOpen(Streamer.java:73) [classes/:na]
	at org.bimserver.servlets.websockets.jsr356.Jsr356Impl.onOpen(Jsr356Impl.java:68) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.jsr356.annotations.OnOpenCallable.call(OnOpenCallable.java:55) [javax-websocket-client-impl-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.jsr356.annotations.JsrEvents.callOpen(JsrEvents.java:170) [javax-websocket-client-impl-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.jsr356.endpoints.JsrAnnotatedEventDriver.onConnect(JsrAnnotatedEventDriver.java:187) [javax-websocket-client-impl-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.openSession(AbstractEventDriver.java:229) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.jsr356.endpoints.AbstractJsrEventDriver.openSession(AbstractJsrEventDriver.java:104) [javax-websocket-client-impl-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.WebSocketSession.open(WebSocketSession.java:489) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.WebSocketSession.onOpened(WebSocketSession.java:423) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.AbstractConnection.onOpen(AbstractConnection.java:198) [jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onOpen(AbstractWebSocketConnection.java:562) [websocket-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:201) [jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.server.HttpConnection.onCompleted(HttpConnection.java:366) [jetty-server-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:611) [jetty-server-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:442) [jetty-server-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) [jetty-server-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) [jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) [jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.execute(ExecuteProduceConsume.java:101) [jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.ManagedSelector.run(ManagedSelector.java:136) [jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method) ~[na:1.8.0_91]
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51) ~[na:1.8.0_91]
	at sun.nio.ch.IOUtil.write(IOUtil.java:148) ~[na:1.8.0_91]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504) ~[na:1.8.0_91]
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:177) ~[jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	... 56 common frames omitted
`

any ideas?

**Comment by rubendel** [comment]
I think this error should be suppressed as it's probably only the client's websocket disconnecting prematurely. Does this error disappear when you disable DemoPlugins again? I can't see how it can have anything to do with it. What do you see in your browser ('s javascript console)?

**Comment by oGuzee** [comment]
it seems like it works just fine.
I was about to try your suggests but the problem doesn't appear anymore.

it's just working properly..

any ideas why?

**Comment by rubendel** [comment]
Are you asking whether I have any idea why it just works?

**Comment by oGuzee** [comment]
No, ofc not.

The q ist why it did those errors, and why it stopped.
Basically, I followed your steps in "Starting a new internal BIMserver plugin". However, it seems like another error occured. 

It stays like this forever.
![bildschirmfoto 2016-06-22 um 13 05 27](https://cloud.githubusercontent.com/assets/19778298/16264486/36513418-387a-11e6-999f-6b89151f3c78.png)

I made the Runcofigs: 
![bildschirmfoto 2016-06-22 um 13 06 33](https://cloud.githubusercontent.com/assets/19778298/16264609/cb934606-387a-11e6-9ee8-817795369880.png)

-Got the repositories from GitHub. 
-Made the xml.
![bildschirmfoto 2016-06-22 um 13 13 14](https://cloud.githubusercontent.com/assets/19778298/16264667/229a8f54-387b-11e6-85ff-975fc33361a5.png)

-Killed the Homedir
-Uncommented "LocalDevBimServerStarter.java"

I don't get any errors in Eclipse, however bimvie.ws seems like it doesn't want wo work.
Any Ideas?

P.S.: I'm very greteful that you're helping me out.

**Comment by rubendel** [comment]
Not sure why you made that xml, also not sure what you mean with 'Uncommented "LocalDevBimServerStarter.java"'.

Any errors in the JavaScript console?

**Comment by oGuzee** [comment]
Hey Ruben

I got this error in Eclipse,: 
![bildschirmfoto 2016-06-27 um 17 12 48](https://cloud.githubusercontent.com/assets/19778298/16384739/68804d98-3c8a-11e6-851d-1bd826e7d179.png)

And this error in the Jscript Console.:
![bildschirmfoto 2016-06-27 um 17 16 30](https://cloud.githubusercontent.com/assets/19778298/16384889/f5c40532-3c8a-11e6-98b6-3238b530604d.png)


What should I do next?

**Comment by rubendel** [comment]
Please let me know what you commented-out in LocalDevBimServerStarter. Did it work before you started adding/changing stuff?

**Comment by oGuzee** [comment]
No no, I just uncommented out the try/catch block. For the set-up, just like you did in your video tutorial.

And no, it didn't worked at all.
