### ISSUE TITLE
3d is not rendered and throws error

### ISSUE THREAD

**Issue by VladMala** [opensourceBIM/BIMserver#361]
In version 1.5.49 I got error on loading ifc files (different versions - 3,4):

ERROR [pool-2-thread-6]: Version mismatch: Plugin version IfcOpenShell-0.5.0-dev-2 does not match IfcOpenShell version IfcOpenShell-0.5.0-dev (IfcGeomServerClient.java:48) 
21:18:08 ERROR [pool-2-thread-4]: (StreamingGeometryGenerator.java:385) 
java.lang.NullPointerException: null
at org.ifcopenshell.IfcGeomServerClient$Command.write(IfcGeomServerClient.java:111) ~[na:na]
at org.ifcopenshell.IfcGeomServerClient.setDeflection(IfcGeomServerClient.java:59) ~[na:na]
at org.ifcopenshell.IfcOpenShellEngine.init(IfcOpenShellEngine.java:57) ~[na:na]
at org.bimserver.renderengine.NoPoolingRenderEnginePool.borrowObject(NoPoolingRenderEnginePool.java:17) ~[bimserver-1.5.49.jar:na]
at org.bimserver.StreamingGeometryGenerator$Runner.run(StreamingGeometryGenerator.java:184) ~[bimserver-1.5.49.jar:na]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_65]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]

Do you know what is the cause of the problem? Also I cannot see rendered file

**Comment by bbrangeo** [comment]
Same problem

**Comment by rubendel** [comment]
Can you try a previous version of IfcOpenShell?

**Comment by rubendel** [comment]
Also, which platform is this on? Window, linux, OSX, 32 or 64 bit?

**Comment by bbrangeo** [comment]
Hi,

I use OS X 64 bit
Thanks Ruben

Le mer. 15 juin 2016 à 08:05, Ruben de Laat <notifications@github.com> a
écrit :

**Comment by bbrangeo** [comment]
Hi,

It's ok with IfcOpenShell 0.5.9.

Thanks

**Comment by aothms** [comment]
Not all binaries have been updated [1] after some recent code changes [2] in the plug-in. Honestly it will take me some time to release OS X binaries, due to the requirements apple poses on running OS X, but you can give it a shot yourself too, running a single script [3] after cloning the repo would be sufficient to get a fresh `IfcGeomServer` binary for your platform.

[1] https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin/commit/39e8382117a21ff77887ebcc688da7bddfb47c80
[2] https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin/commit/d0b1e7a00700b389b29fc38bdabd3f8597c4a3bd
[3] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/nix/build-all.sh

@rubendel for the time being we should probably make the code backwards compatible for both versions `IfcOpenShell-0.5.0-dev` and `IfcOpenShell-0.5.0-dev-2` and simply not applying any of the recently added settings in case of the former. You have time for that or shall I give it a shot?

**Comment by rubendel** [comment]
ifcopenshellplugin-0.5.14 had been built using the "settings" branch for testing purposes. A new build is underway and it will be based on GIT master again (using the old binaries). You can update the plugin with BIMvie.ws or do a fresh install.
