### ISSUE TITLE
BIMserver 1.5.55 and clashdetection 0.0.8   org.bimserver.client.GeometryException: Parts not supported

### ISSUE THREAD

**Issue by GreenUtil** [opensourceBIM/BIMserver#405]
Hello,

When running the clashdetection 0.0.8 plugin standalone in Eclipse, everything is working fine.
When calling the same clashdetection plugin from the BIMvie.ws client, started up from BIMserver 1.5.55 also running on Eclipse, gives an error : 

09:17:51 INFO  [Thread-18]: # Objects: 135858                                                                (SharedJsonDeserializer.java:121) 
org.bimserver.client.GeometryException: Parts not supported
	at org.bimserver.client.ClientIfcModel.processGeometryInputStream(ClientIfcModel.java:436)
	at org.bimserver.client.ClientIfcModel.loadGeometry(ClientIfcModel.java:343)
	at org.bimserver.client.ClientIfcModel.loadDeep(ClientIfcModel.java:300)
	at org.bimserver.client.ClientIfcModel.<init>(ClientIfcModel.java:115)
	at org.bimserver.client.BimServerClient.getModel(BimServerClient.java:196)
	at org.bimserver.client.BimServerClient.getModel(BimServerClient.java:82)
	at org.bimserver.clashdetection.ClashDetectionServiceBcfPlugin.newRevision(ClashDetectionServiceBcfPlugin.java:55)
	at org.bimserver.plugins.services.AbstractService$1.newRevision(AbstractService.java:164)
	at org.bimserver.notifications.InternalServicesManager$3$1.run(InternalServicesManager.java:212)
09:17:52 ERROR [Thread-18]:                                                                                  (AbstractService.java:176) 
java.lang.IndexOutOfBoundsException: null
	at java.nio.Buffer.checkIndex(Buffer.java:540) ~[na:1.8.0_91]
	at java.nio.ByteBufferAsFloatBufferL.get(ByteBufferAsFloatBufferL.java:115) ~[na:1.8.0_91]
	at org.bimserver.clashdetection.Triangle.<init>(Triangle.java:24) ~[na:na]
	at org.bimserver.clashdetection.ClashDetector.trianglesClash(ClashDetector.java:159) ~[na:na]
	at org.bimserver.clashdetection.ClashDetector.findClashes(ClashDetector.java:107) ~[na:na]
	at org.bimserver.clashdetection.ClashDetectionServiceBcfPlugin.newRevision(ClashDetectionServiceBcfPlugin.java:57) ~[na:na]
	at org.bimserver.plugins.services.AbstractService$1.newRevision(AbstractService.java:164) ~[classes/:na]
	at org.bimserver.notifications.InternalServicesManager$3$1.run(InternalServicesManager.java:212) [classes/:na]

**Comment by rubendel** [comment]
When models contains large geometry objects, the serialization is different. This alternative serialization is not supported by the BIMserver client at the moment. Will keep this issue open to fix later.

**Comment by GreenUtil** [comment]
The model we used for the clashdetection has been attached to this comment.
In fact it's a small building, not very complicated, modelled at LOD250.
So, there probably will be no very large geometry objects.
What is large ?

[Lindenlaan 42 (tussenwoning).zip](https://github.com/opensourceBIM/BIMserver/files/461263/Lindenlaan.42.tussenwoning.zip)

**Comment by rubendel** [comment]
In this case, large is any model containing at least one object that generates more than 5463 triangles. This limit is imposed by WebGL/OpenGL ES 2.0, but for this usecase (using the BIMserver client) it makes no sense that there is a limit, so, this issue has been fixed in https://github.com/opensourceBIM/BinarySerializers/commit/6df3e59a95c3e6f10f1b45920ab94ac10ca60282 and https://github.com/opensourceBIM/BIMserver/commit/e5d35bff20e7a0b2201c32fd7eab24ba5404bfcc
