### ISSUE TITLE
install last version - plugin doubt

### ISSUE THREAD

**Issue by oliviersaintgobain** [opensourceBIM/BIMserver#413]
Hello,
I have just installed the last version of bimserver 1.5.58.
I have a trouble on the setup page to install plugin. I think the cause is that the server can't go to internet through the proxy or something like that but I have no information in the logs. 
the only log is after close setup :
2016-09-29 12:19:52,639 INFO [localhost-startStop-1] o.b.ServerInfoManager [ServerInfoManager.java:112] Changing server state to NOT_SETUP
2016-09-29 12:19:53,067 INFO [localhost-startStop-1] o.b.s.w.j.Jsr356Impl [Jsr356Impl.java:80] WebSocket context initialized
2016-09-29 12:26:05,133 INFO [AdminInterface.setup] o.b.ServerInfoManager [ServerInfoManager.java:112] Changing server state to RUNNING

Anyway, I have made a copy of the jar plugin from my existing 1.4.final version to this version.
I have restarted my 1.5.58 server (I'm under docker) but it seems that the plugins are not taken into account.

the home page is still to show 1.5.58 running with no webmodule...no login page etc.

thanks by advance.

Olivier

**Comment by rubendel** [comment]
In 1.5 plugins cannot be installed by copying then. You need to use the API (possibly through BIMvie.ws) to install them. At the moment BIMserver cannot install plugins (or do any other connection) through a proxy.

**Comment by oliviersaintgobain** [comment]
thanks. how to deploy bimview.ws ? just unzip the content ? where ?

**Comment by rubendel** [comment]
BIMvie.ws is also a plugin, just like the others. You might want to try and delete the database or home folder and restart, that way you'll get to see the setup screen again and try to install BIMvie.ws with it in order to have a working GUI.

**Comment by oliviersaintgobain** [comment]
ok...that's what I did but I said...plugin install is not possible by this way...
message is : 
Setting up...
Setting up admin account...
Admin account successfully setup
Skipping email setup...
Installing plugins...

Plugin bundle not found
Setup aborted

But still my problem with proxy (my company is using one to connect to internet...so to download plugin).
is it possible to install it by another way ?

Olivier

**Comment by rubendel** [comment]
Yes there is the PluginInterface.installPluginBundleFromFile API method. But because you can't use BIMvie.ws, you'll have to call it manually, e.a. from some script/piece of code.

**Comment by thomasvoigt** [comment]
Hi there!

I'm still lost. How exactly do I call the "PluginInterface.installPluginBundleFromFile API method" to install a plugin?
An why doesn't bimserver respect established proxy setting methods (e.g. via -Dhttp.proxyHost and -Dhttp.proxyPort)?

Thanks and best regards,
Thomas

**Comment by rubendel** [comment]
Most of the plugin code seems to be using Files.newInputStream (part of the Java JDK). I would assume those methods to actually respect those parameters you mentioned. Not all code is using the JDK for outbound network connections though (some use apache's HTTP Client). HTTP Client can be configured to use those settings as well , so I'll keep this issue open to someday implement that.

The "PluginInterface.installPluginBundleFromFile" method you can call from your software (the software you are writing). I still think it's quite normal to expect to have working outgoing sockets in opensource software, but well that's my opinion.

**Comment by thomasvoigt** [comment]
Thanks for getting back to me so quickly.

> The "PluginInterface.installPluginBundleFromFile" method you can call from your software (the software you are writing). I still think it's quite normal to expect to have working outgoing sockets in opensource software, but well that's my opinion.

Well, proxies are quite common in enterprise environments. 

Regardless, I did not expect one has to write code to just use bimserver as a repository for IFC files. Yes, my use case would include BIMSie requests eventually. But I won't be able to load plugins this way either...

So, what can I do to get bimserver up and running in a proxy-infested enterprise environment?

Thanks and best regards,
Thomas

**Comment by rubendel** [comment]
I just setup a proxy server, but it is a bit hard to test whether it is actually working, because my regular internet connection also still works. I would have to create a separate network for it. At the moment it is too much work to support this feature with essentially just one developer. For every release we would have to check if it's still working etcetera...

Other than that, you might want to try to also set the -Dhttps.proxyHost and -Dhttps.proxyPort settings as most stuff is downloaded from HTTPS sites. Also on some OSes you can use "java.net.useSystemProxies".

**Comment by rubendel** [comment]
Another note. Installing plugins is not the only feature of BIMserver using outgoing connections. These are also used for:
- Getting the latest version info of BIMserver
- Checkin from URL
- Triggering remote services

Also on a a lot of corporate networks, the next issue you're likely to run into are websockets, not all proxy servers support them, hence my adversion.

**Comment by thomasvoigt** [comment]
> Other than that, you might want to try to also set the -Dhttps.proxyHost and -Dhttps.proxyPort settings as most stuff is downloaded from HTTPS sites. Also on some OSes you can use "java.net.useSystemProxies".

I've already tried `http[s].proxy*`, `socksProxy*`, `java.net.useSystemProxies=true`, and permutations thereof. Unfortunately, neither works:
<pre>
java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.bimserver.utils.NetUtils.getContent(NetUtils.java:48)
	at org.bimserver.plugins.GitHubPluginRepository.listPluginLocations(GitHubPluginRepository.java:55)
	at org.bimserver.database.actions.GetInstalledPluginBundles.execute(GetInstalledPluginBundles.java:65)
	at org.bimserver.database.actions.GetInstalledPluginBundles.execute(GetInstalledPluginBundles.java:44)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:698)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:690)
	at org.bimserver.webservices.impl.PluginServiceImpl.getInstalledPluginBundles(PluginServiceImpl.java:1505)
	at org.bimserver.generated.PluginInterfaceReflector1.callMethod(PluginInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:213)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:137)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:60)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:136)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:835)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:225)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
</pre>

> Also on a a lot of corporate networks, the next issue you're likely to run into are websockets, not all proxy servers support them, hence my adversion.

I'm almost certain our corporate proxy is a SOCKS proxy.

All I need at the moment is to overcome that initial plugin download problem for "BIMvie.ws" as the bimserver will only serve local intranet clients via a (yet to be developed) BIMSie-capable application. But without "BIMvie.ws" managing server permissions and debugging BIMSie request will be quite hard...

Thanks again for your time!

Best regards,
Thomas

**Comment by rubendel** [comment]
Are you using the JAR starter?

**Comment by thomasvoigt** [comment]
I've tried both, JAR and WAR (via jetty) on Java 8 on Windows Server 2012.

**Comment by rubendel** [comment]
Oke, on the JAR, how are you setting the proxy parameters?

**Comment by thomasvoigt** [comment]
Things I've tried:
- on the command line `java -DsomeProxySettings .. -jar bimserver.jar`
- Windows' Java control panel ("Get proxy settings from IE" as well as individual settings for http, https, socks etc.)
- forcing IE's proxy settings system wide via `netsh winhttp import proxy source=ie`
- some environment variables (although nobody seems to be exactly sure what variable to set

I haven't yet tinkered with Java's distribution/deploy settings.

**Comment by oliviersaintgobain** [comment]
hello, do you think new features will be manage around proxy configuration for BIMServer in the next releases ?

**Comment by rubendel** [comment]
Sorry for the late reply @thomasvoigt I think the first option should do it, but the way you (seem to) do it, it will set the proxy settings for the JAR Starter, but not for the JVM that is started by it. I'll have a look at a possibility to pass a few arguments on to the next JVM...

**Comment by rubendel** [comment]
@oliviersaintgobain If we can get it to work with not too much effort it will be included, but no guarantees

**Comment by oliviersaintgobain** [comment]
thanks
