### ISSUE TITLE
IfcxmlDeserilizer doesn't work

### ISSUE THREAD

**Issue by dominicwyf** [opensourceBIM/BIMserver#434]
Hi,

My BIMserver version is 1.5.62.

When i was trying to upload the ifcxml file to project, there are some problems in IfcXmlDeserializer.
The logs are as follows.

```
Caused by: java.lang.ClassCastException: org.eclipse.emf.ecore.impl.EDataTypeImpl cannot be cast to org.eclipse.emf.ecore.EClass
	at org.bimserver.ifc.xml.deserializer.IfcXmlDeserializer.parseField(IfcXmlDeserializer.java:345) ~[na:na]
	at org.bimserver.ifc.xml.deserializer.IfcXmlDeserializer.parseObject(IfcXmlDeserializer.java:273) ~[na:na]
	at org.bimserver.ifc.xml.deserializer.IfcXmlDeserializer.parseUos(IfcXmlDeserializer.java:231) ~[na:na]
	at org.bimserver.ifc.xml.deserializer.IfcXmlDeserializer.parseIso_10303_28(IfcXmlDeserializer.java:213) ~[na:na]
	at org.bimserver.ifc.xml.deserializer.IfcXmlDeserializer.parseDocument(IfcXmlDeserializer.java:119) ~[na:na]
	at org.bimserver.ifc.xml.deserializer.IfcXmlDeserializer.read(IfcXmlDeserializer.java:106) ~[na:na]
	at org.bimserver.ifc.xml.deserializer.IfcXmlDeserializer.read(IfcXmlDeserializer.java:98) ~[na:na]
	at org.bimserver.webservices.impl.ServiceImpl.checkinInternal(ServiceImpl.java:994) ~[bimserver-1.5.62.jar:na]
	at org.bimserver.webservices.impl.ServiceImpl.checkinInitiatedInternal(ServiceImpl.java:956) ~[bimserver-1.5.62.jar:na]
	... 29 common frames omitted
```

Regards

**Comment by dominicwyf** [comment]
Problem solved.
