### ISSUE TITLE
BIMserver service does no start anymore due to error "A database initialisation error has occured"

### ISSUE THREAD

**Issue by klacol** [opensourceBIM/BIMserver#435]
Hi, today we have a strange problem. 

We restartet the Tomcat service on windows, and after that, the BIMserver does not start anymore. We are still on 1.4.0 and are working with it for severall months now. We never saw this problem.

``` 30-11-2016 23:58:37 INFO  Using "C:\...\templates\" as template dir (org.bimserver.templating.TemplateEngine.java:64) 
30-11-2016 23:58:38 INFO  Non-empty database directory found "C:\...\database" (org.bimserver.database.berkeley.BerkeleyKeyValueStore.java:83) 
30-11-2016 23:58:38 ERROR                                                                                  (org.bimserver.BimServer.java:464) 
org.bimserver.database.berkeley.DatabaseInitException: A database initialisation error has occured ((JE 6.4.9) C:\...\database Expected log version 11 or earlier but found 12 VERSION_MISMATCH: The existing log was written with a version of JE that is later than the running version of JE, the log cannot be read. Environment is invalid and must be closed. Couldn't open file C:\...\database\00001400.jdb)
	at org.bimserver.database.berkeley.BerkeleyKeyValueStore.<init>(BerkeleyKeyValueStore.java:118)
	at org.bimserver.BimServer.start(BimServer.java:361)
	at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:95)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:586)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1777)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source) ``` 

Has anyone seen this error before and knows a possible solution?

Thanks in advance
Klaus

**Comment by rubendel** [comment]
I have not seen this before, the fact that the error message talks about version 12 (and not some random number) to me indicates that it's not a file corruption issue. Are you really sure no other versions of BIMserver were tried on the same machine?

**Comment by klacol** [comment]
ok, that was my thougt to. In fact we have a parallel running BIMserver 1.5.x in a seperate folder, on a seperate listener with a separate database. Are the know issues with such a constellation.

**Comment by klacol** [comment]
Another thougt from me: It is not immoppisble, that I accidentally startet a BIMserver 1.5.x on a database that ist still on BIMserver 1.4.  Could this lead to such a situation?

In this file I insert the path to the database folder

conf\Catalina\bimserver15\ROOT.xml

`<Context path="" docBase="ROOT">
     <Parameter name="homedir" value="C:\PathToBimserver15DataFolder" />	                         
</Context>`

I know, that I have not changed this for the BIMserver14 installation. But perhaps I have startet once the BIMserver15 without this ROOT.xml. Could there eventually be a situation, where the HOMEDIR is resolved from the ROOT.xml of BIMserver14 ?

**Comment by rubendel** [comment]
The "database-schema" on a berkeley-db level is automatically upgraded, a backwards migration is not available.

I don't know if it's possible for Tomcat to mix-up the configuration files. You can probably get more information by reading the log files. When a BIMserver starts, it always writes the path to the configured homedir in the log file.

**Comment by klacol** [comment]
I supose, I made an error in the setup procedure; one has to be very carefull with the config of the homedir BEFORE starting the BIMserver. We installed new a new database.
