### ISSUE TITLE
The remote endpoint was in state [TEXT_FULL_WRITING] which is an invalid state for called method

### ISSUE THREAD

**Issue by leohsu91** [opensourceBIM/BIMserver#436]
Hi, I deploy BIMSever(V1.5.61) with tomcat(JDK1.8 Tomcat8) on my server.
when I use bimview plugin to view the projet's 3d  view, the server appear errors. 
Here is the log:
```
2016-12-02 03:41:55,133 INFO [org.bimserver.ServiceInterface.download] o.b.c.NewDiskCacheManager [NewDiskCacheManager.java:105] Reading from cache e244d2ed58f16f4
1c8e33ee6f8cd27f6                                                                                                                                                 
2016-12-02 03:41:59,824 ERROR [Streamer 104] o.b.BimServer [BimServer.java:205]                                                                                   
java.lang.IllegalStateException: The remote endpoint was in state [TEXT_FULL_WRITING] which is an invalid state for called method                                 
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$StateMachine.checkState(WsRemoteEndpointImplBase.java:1177) ~[tomcat-websocket.jar:8.0.38]        
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$StateMachine.binaryStart(WsRemoteEndpointImplBase.java:1130) ~[tomcat-websocket.jar:8.0.38]       
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendBytes(WsRemoteEndpointImplBase.java:133) ~[tomcat-websocket.jar:8.0.38]                       
        at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendBinary(WsRemoteEndpointBasic.java:43) ~[tomcat-websocket.jar:8.0.38]                             
        at org.bimserver.servlets.websockets.jsr356.Jsr356Impl.sendBlocking(Jsr356Impl.java:133) ~[bimserver-1.5.61.jar:na]                                       
        at org.bimserver.servlets.Streamer$1.run(Streamer.java:100) ~[bimserver-1.5.61.jar:na]                                                                    
2016-12-02 03:49:59,183 INFO [org.bimserver.ServiceInterface.download] o.b.c.NewDiskCacheManager [NewDiskCacheManager.java:105] Reading from cache e244d2ed58f16f4
1c8e33ee6f8cd27f6   
```
And the loading view is stucked. 
![image_20161202131142](https://cloud.githubusercontent.com/assets/8965956/20823631/e62947cc-b890-11e6-876c-fe97643ce519.png)
So how can I solve it. Thank you very much.

**Comment by rubendel** [comment]
https://github.com/opensourceBIM/bimvie.ws/issues/73

**Comment by leohsu91** [comment]
thanks. the problem solved.

**Comment by muren400** [comment]
Hi,

I get the same Exception when loading Tiles in BimSurfer3 via websocket.

`java.lang.IllegalStateException: The remote endpoint was in state [TEXT_FULL_WRITING] which is an invalid state for called method
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$StateMachine.checkState(WsRemoteEndpointImplBase.java:1228)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$StateMachine.textStart(WsRemoteEndpointImplBase.java:1191)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendStringByCompletion(WsRemoteEndpointImplBase.java:209)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendStringByFuture(WsRemoteEndpointImplBase.java:197)
	at org.apache.tomcat.websocket.WsRemoteEndpointAsync.sendText(WsRemoteEndpointAsync.java:53)
	at org.bimserver.servlets.websockets.jsr356.Jsr356Impl.sendAsText(Jsr356Impl.java:160)
	at org.bimserver.servlets.Streamer$2.run(Streamer.java:218)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

Hapened in BIMServer version 1.5.182
