### ISSUE TITLE
Compiling failed with BIMserver 1.5.64

### ISSUE THREAD

**Issue by cbasic7** [opensourceBIM/BIMserver#437]
I use Eclipse 4.6.1 and imported the source of BIMserver 1.5.64.There were errors when I compile it.And when I run it in Eclipse it also failed.Here is the console log:

```
15:09:17 ERROR [main]:                                                                                  (BimServer.java:738) 
java.lang.NoClassDefFoundError: javax/mail/internet/AddressException
	at org.bimserver.database.actions.AddUserDatabaseAction.execute(AddUserDatabaseAction.java:98) ~[classes/:na]
	at org.bimserver.database.Database.init(Database.java:172) ~[classes/:na]
	at org.bimserver.BimServer.start(BimServer.java:606) ~[classes/:na]
	at org.bimserver.LocalDevBimServerStarter.start(LocalDevBimServerStarter.java:44) [classes/:na]
	at org.bimserver.LocalDevBimServerStarter.main(LocalDevBimServerStarter.java:26) [classes/:na]
Caused by: java.lang.ClassNotFoundException: javax.mail.internet.AddressException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_60]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_60]
	... 5 common frames omitted
```

**Comment by rubendel** [comment]
Is your workspace configured to use JDK 8?

**Comment by cbasic7** [comment]
Is that version of JRE OK?
![image](https://cloud.githubusercontent.com/assets/9390244/20876915/37f337cc-bb00-11e6-8571-c25e9ba394e8.png)

**Comment by cbasic7** [comment]
Or maybe I imported the project in a wrong way?
![image](https://cloud.githubusercontent.com/assets/9390244/20877243/3c277c2a-bb02-11e6-8953-4f3215353b5d.png)
I just imported the project by this.
@rubendel

**Comment by cbasic7** [comment]
Problem solved...I replace javax.mail 1.5.5 by javax.mail 1.5.4 and it works well.But I still don't have any idea about it.

**Comment by rubendel** [comment]
Sometimes eclipse does not get it the first time after import, usually a Project | Clean... will fix it. I think when you change back to 1.5.5 it will also work.
