### ISSUE TITLE
Import xxx cannot be solved in Demoplugin

### ISSUE THREAD

**Issue by cocarry** [opensourceBIM/BIMserver#451]
Hi rubendel,
I am testing the DemoPlugins. When I debug the OuterAreaServicePlugin.java, lots of errors such as "import org.bimserver.xxxxx cannot be solved". I try to "Add External JARs", but I cannot find the files such as "org.bimserver.jar". Is it wrong with the .jar files?
I am following the video of  "Starting a new internal BIMserver plugin.mp4" (21'41')

Followings are the error importings:

import org.bimserver.emf.IfcModelInterface;
import org.bimserver.geometry.Vector;
import org.bimserver.interfaces.objects.SObjectType;
import org.bimserver.interfaces.objects.SProject;
import org.bimserver.models.geometry.GeometryData;
import org.bimserver.models.geometry.GeometryInfo;
import org.bimserver.models.ifc2x3tc1.IfcProduct;
import org.bimserver.models.ifc2x3tc1.IfcSpace;
import org.bimserver.models.ifc2x3tc1.Tristate;
import org.bimserver.plugins.services.AbstractAddExtendedDataService;
import org.bimserver.plugins.services.BimServerClientInterface;

**Comment by cocarry** [comment]
This is the console window:
15:59:39 INFO  [main]: Changing server state to RUNNING                                                 (ServerInfoManager.java:112) 
16:00:00 INFO  [main]: Skipping strict dependency checking for dependency bimserverapi                  (PluginManager.java:1286) 
16:00:00 INFO  [main]: Skipping strict dependency checking for dependency bimserverapi                  (PluginManager.java:1286) 
16:00:01 INFO  [main]: Skipping strict dependency checking for dependency bimsurfer                     (PluginManager.java:1286) 
16:00:02 ERROR [main]:                                                                                  (LocalDevPluginLoader.java:39) 
org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.demoplugins.service.GuidFixerService' not found in file:///H:/360data/重要数据/桌面/Git/DemoPlugins/DemoPlugins/
	at org.bimserver.plugins.PluginManager.loadPlugins(PluginManager.java:534) ~[classes/:na]
	at org.bimserver.plugins.PluginManager.loadJavaProject(PluginManager.java:359) ~[classes/:na]
	at org.bimserver.plugins.PluginManager.loadPluginsFromEclipseProject(PluginManager.java:387) ~[classes/:na]
	at org.bimserver.LocalDevPluginLoader.loadPlugins(LocalDevPluginLoader.java:37) ~[classes/:na]
	at org.bimserver.LocalDevBimServerStarter.start(LocalDevBimServerStarter.java:45) [classes/:na]
	at org.bimserver.LocalDevBimServerStarter.main(LocalDevBimServerStarter.java:26) [classes/:na]
Caused by: java.lang.ClassNotFoundException: org.bimserver.demoplugins.service.GuidFixerService
	at org.bimserver.plugins.classloaders.EclipsePluginClassloader.findClass(EclipsePluginClassloader.java:107) ~[classes/:na]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_111]
	at org.bimserver.plugins.PluginManager.loadPlugins(PluginManager.java:528) ~[classes/:na]
	... 5 common frames omitted

**Comment by rubendel** [comment]
Do the other projects (like BimServer) compile correctly?

**Comment by cocarry** [comment]
when I run other project(like bimserver) there is only two problem in test, but It can run correctly. 
when I run the demoplugin , there are more errors, and it can not run it correctly.

**Comment by kenchengch** [comment]
same problem here! How to solve please.

**Comment by hyq1991** [comment]
same problem here. 
org.bimserver.demoplugins.service.GuidFixerService' not found
in fact, all the demo plugins can not be used. I download the demoplugins code from github and put in the bimserver folder. However, it is did not work. @cocarry @rubendel
