### ISSUE TITLE
When executing JarBimServer, VersionChecker checks twice the same pom.xml

### ISSUE THREAD

**Issue by sundayez** [opensourceBIM/BIMserver#457]
I am quite new trying to BIMServer, sorry if this issue has been reported previously (I didn't find it).

I have followed the instructions from the wiki to open BIMServer projects in Eclipse Neon (4.6.2). Everything is OK when launching ```LocalDevBimServer.main()```, but when trying to run the ```JarBimServer.main()``` method, I get the following exception messages in Eclipse console:

``` 11:17:20 INFO  [main]: Starting BIMserver                                                               (BimServer.java:213) 
11:17:20 INFO  [main]: Using "home" as homedir                                                          (BimServer.java:215) 
11:17:22 ERROR [main]:                                                                                  (BimServer.java:268) 
org.bimserver.version.VersionCheckException: java.lang.NullPointerException
	at org.bimserver.version.VersionChecker.<init>(VersionChecker.java:109)
	at org.bimserver.BimServer.<init>(BimServer.java:253)
	at org.bimserver.JarBimServer.start(JarBimServer.java:78)
	at org.bimserver.JarBimServer.main(JarBimServer.java:53)
Caused by: java.lang.NullPointerException: null
	at org.apache.maven.artifact.versioning.ComparableVersion.parseVersion(ComparableVersion.java:357)
	at org.apache.maven.artifact.versioning.ComparableVersion.<init>(ComparableVersion.java:348)
	at org.apache.maven.artifact.versioning.DefaultArtifactVersion.parseVersion(DefaultArtifactVersion.java:112)
	at org.apache.maven.artifact.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:48)
	at org.bimserver.version.VersionChecker.<init>(VersionChecker.java:99)
	... 3 common frames omitted
11:17:25 ERROR [main]:                                                                                  (BimServer.java:740) 
java.lang.NullPointerException: null
	at org.bimserver.BimServer.start(BimServer.java:293)
	at org.bimserver.JarBimServer.start(JarBimServer.java:84)
	at org.bimserver.JarBimServer.main(JarBimServer.java:53)
11:17:25 INFO  [main]: Server started successfully                                                      (JarBimServer.java:85) 
```
As far as I have traced the execution, I find that the problem arises when VersionChecker constructor tries to read pom.xml from a resourceFetcher that contains paths ```[home, config, .]```. First it reads BimServerJar/pom.xml, which doesn't contain any version tag (so ```model.getVersion()``` returns null); then it tries to switch to the parent dir (line 88), but the ```getFile``` method loops into the resourceFetcher, thus resolving the next path as ```home/../pom.xml``` reading the same file for the second time and getting no version.

Finally, when the server is going to be launched, it breaks since it gets a NullPointerException when accessing the version.

On the other side, if I compare these pom.xml with the pom.xml contained in bimserverjar-1.5.63.jar, these are different. The latter does contain a version number (1.5.63 in this case).

Am I doing something wrong?

Thanks in advance

**Comment by rubendel** [comment]
Why do you try to run JarBimServer.main? That one is intended to be packaged in a JAR, so that is the reason it's not working.

**Comment by sundayez** [comment]
I know that the LocalDev is the one that must be run, but I was just getting familiar with the project and I thought the JarBimServer could also be used (I was curious).

Thank you for your highly fast response!
