### ISSUE TITLE
IntelligentNameBasedModelMergerPlugin not found in BIMserver 1.5.64

### ISSUE THREAD

**Issue by penriister** [opensourceBIM/BIMserver#460]
Model download fails, because IntelligentNameBasedModelMergerPlugin  is not found. I have installed mergers plugin.
When the BIMserver starts, it gives an error message:
09:40:37 ERROR [main]:                                                                                  (BimServer.java:740) 
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[na:1.8.0_121]
	at java.util.ArrayList.get(Unknown Source) ~[na:1.8.0_121]
	at org.bimserver.plugins.PluginManager.loadFromPluginDir(PluginManager.java:1305) ~[shared-1.5.64.jar:na]
	at org.bimserver.BimServer.start(BimServer.java:732) ~[bimserver-1.5.64.jar:na]
	at org.bimserver.JarBimServer.start(JarBimServer.java:84) [bimserverjar-1.5.64/:na]
	at org.bimserver.JarBimServer.main(JarBimServer.java:53) [bimserverjar-1.5.64/:na]

Model download gives this message:
 ERROR [Download]:                                                                                  (LongAction.java:189) 
org.bimserver.shared.exceptions.UserException: No Model Merger found org.bimserver.merging.IntelligentNameBasedModelMergerPlugin
	at org.bimserver.database.actions.DownloadByNewJsonQueryDatabaseAction.execute(DownloadByNewJsonQueryDatabaseAction.java:203) ~[bimserver-1.5.64.jar:na]
	at org.bimserver.database.actions.DownloadByNewJsonQueryDatabaseAction.execute(DownloadByNewJsonQueryDatabaseAction.java:63) ~[bimserver-1.5.64.jar:na]
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:698) ~[bimserver-1.5.64.jar:na]
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:690) ~[bimserver-1.5.64.jar:na]
	at org.bimserver.longaction.LongDownloadOrCheckoutAction.executeAction(LongDownloadOrCheckoutAction.java:120) ~[bimserver-1.5.64.jar:na]
	at org.bimserver.longaction.LongDownloadAction.execute(LongDownloadAction.java:57) ~[bimserver-1.5.64.jar:na]
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43) [bimserver-1.5.64.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_121]

If I try to install mergers plugin I get this message:

 [org.bimserver.PluginInterface.installPluginBundle]:                                                                                  (InstallPluginBundle.java:46) 
org.bimserver.shared.exceptions.PluginException: This plugin has already been installed org.opensourcebim.mergers-0.0.6.jar

**Comment by berlotti** [comment]
are you still getting this issue with the most recent build?
