### ISSUE TITLE
BIMServer 1.5.63 not checkin a file (noSuchMethodError for org.bimserver.utils.StringUtils.nextField)

### ISSUE THREAD

**Issue by sundayez** [opensourceBIM/BIMserver#468]
Hello:

I'm developing a project on the basis of BIMServer and I am a little bit worried about the backward compatibility.

A few days ago I found an issue using the BIMServer version 1.5.63. It's quite strange since it worked it perfectly before. I have tested it in two different computers, using Windows 7 and Java 1.8.0_112. Apologies in advance if it is due to an incorrect operation from my side.

The steps to reproduce are:

1) I launch the file bimserverjar-1.5.63.jar. I start the server and configure it from scratch as usual (creating a user, not creating an e-mail server and installing Bimviews and IfcOpenShell modules).

2) I create a project using Ifc2x3tc1 schema and try to check in the file Duplex_A_20110907.ifc, downloaded from http://projects.buildingsmartalliance.org/files/?artifact_id=4278 (using the deserializer proposed: Ifc2x3tc1 (Streaming))

3) The file does not check in. I get the following message in the web browser: `org.bimserver.utils.StringUtils.nextField(Ljava/lang/String;I)I`

and the following messages in the BIMServer starter console:

`java.lang.NoSuchMethodError: org.bimserver.utils.StringUtils.nextField(Ljava/lang/String;I)I
	at org.bimserver.ifc.step.deserializer.StepParser.<init>(StepParser.java:16) ~[na:na]
	at org.bimserver.ifc.step.deserializer.IfcHeaderParser.parseDescription(IfcHeaderParser.java:27) ~[na:na]
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processHeader(IfcStepStreamingDeserializer.java:272) ~[na:na]
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processLine(IfcStepStreamingDeserializer.java:221) ~[na:na]
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:179) ~[na:na]
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:161) ~[na:na]
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:182) [bimserver-1.5.63.jar:na]
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:75) [bimserver-1.5.63.jar:na]
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:698) [bimserver-1.5.63.jar:na]
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:685) [bimserver-1.5.63.jar:na]
	at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:61) [bimserver-1.5.63.jar:na]
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43) [bimserver-1.5.63.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_112]
`

On the other hand, I could check in the same file correctly with the latest version of BIMServer (1.5.67).

Thank you in advance for your attention.

**Comment by raindog** [comment]
Generally speaking, I think than on the releases notes it should be specified the plugins version used in that particular release. Always downloading the latest plugin version may cause these issues. But maybe I'm wrong in this particuliar case...

**Comment by rubendel** [comment]
If we specify in the release notes with which plugin versions it will work, we could just as well merge all the plugins back into the main BIMserver project. The main reason for not doing that is that we can independently develop the different projects. As soon as there is a final release of BIMserver, we will not do any binary incompatible changes anymore like the one described in this issue.

For solving this issue, just download the latest release of BIMserver. The problem is that all versions of BIMserver download the latest versions of the selected plugins on setup. Sometimes those plugins are too new to work with that version.

**Comment by sundayez** [comment]
Thank you very much! Clear to me now.

Best regards
