### ISSUE TITLE
Bug report,org.bimserver.BimserverDatabaseException: Reading IfcPresentationStyleAssignment.Styles 7

### ISSUE THREAD

**Issue by yanzhenxing** [opensourceBIM/BIMserver#479]
Hi,Ruben,

When I checkin an ifc file, an Error occur which describe as follow:(Bimserver version:1.5.68-SNAPSHOT)

10:27:05 ERROR [pool-2-thread-1]:                                                                                  (StreamingGeometryGenerator.java:385) 
org.bimserver.BimserverDatabaseException: org.bimserver.BimserverDatabaseException: Reading IfcPresentationStyleAssignment.Styles 7
	at org.bimserver.database.queries.QueryObjectProvider.next(QueryObjectProvider.java:147)
	at org.bimserver.StreamingGeometryGenerator$Runner.run(StreamingGeometryGenerator.java:162)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.bimserver.BimserverDatabaseException: Reading IfcPresentationStyleAssignment.Styles 7
	at org.bimserver.database.queries.DatabaseReadingStackFrame.convertByteArrayToObject(DatabaseReadingStackFrame.java:240)
	at org.bimserver.database.queries.FollowReferenceStackFrame.process(FollowReferenceStackFrame.java:88)
	at org.bimserver.database.queries.QueryObjectProvider.next(QueryObjectProvider.java:134)
	... 6 common frames omitted
Caused by: java.nio.BufferUnderflowException: null
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:361)
	at org.bimserver.database.queries.DatabaseReadingStackFrame.readPrimitiveValue(DatabaseReadingStackFrame.java:323)
	at org.bimserver.database.queries.DatabaseReadingStackFrame.readWrappedValue(DatabaseReadingStackFrame.java:266)
	at org.bimserver.database.queries.DatabaseReadingStackFrame.readList(DatabaseReadingStackFrame.java:361)
	at org.bimserver.database.queries.DatabaseReadingStackFrame.convertByteArrayToObject(DatabaseReadingStackFrame.java:178)
	... 8 common frames omitted

The Ifc file is attached unsuccessfully

**Comment by rubendel** [comment]
Interesting, can you share the file via this link please?

https://www.dropbox.com/request/8eBtxj0cgMVL5r9x1Qa1

**Comment by yanzhenxing** [comment]
Yeah, I have uploaded the ifc file, Please have a check! And I also have found other failures when converting the ifc files, and will check it again, then , I will create a new issue to describe them.

**Comment by rubendel** [comment]
Thanks for reporting and for including a small example file! Will be in the new release of the IfcPlugins plugin

**Comment by yanzhenxing** [comment]
Great!
