### ISSUE TITLE
Setup fail - BIMServer15 - Plugin bundle not found

### ISSUE THREAD

**Issue by webdadag** [opensourceBIM/BIMserver#484]
>>>>>>> Browser setup screen
Click the "Setup" button to finish the setup process
Setting up...
Setting up admin account...
Admin account successfully setup
Skipping email setup...
Installing all extended data schemas...

Installing plugins...

Plugin bundle not found
Setup aborted

>>>>>>>>>> Server Command Console

15:07:28 INFO  [main]: Server started successfully                                                      (JarBimServer.java:85) 
15:09:00 INFO  [AdminInterface.setup]: Changing server state to RUNNING                                                 (ServerInfoManager.java:114) 
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.bimserver.utils.NetUtils.getContent(NetUtils.java:48)
	at org.bimserver.plugins.GitHubPluginRepository.listPluginLocations(GitHubPluginRepository.java:55)
	at org.bimserver.database.actions.GetInstalledPluginBundles.execute(GetInstalledPluginBundles.java:62)
	at org.bimserver.database.actions.GetInstalledPluginBundles.execute(GetInstalledPluginBundles.java:42)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:698)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:690)
	at org.bimserver.webservices.impl.PluginServiceImpl.getInstalledPluginBundles(PluginServiceImpl.java:1505)
	at org.bimserver.generated.PluginInterfaceReflector1.callMethod(PluginInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:213)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:137)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:60)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:136)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:835)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:225)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
15:09:02 ERROR [ServiceInterface.getAllRepositoryExtendedDataSchemas]:                                                                                  (GenericServiceImpl.java:132) 
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.bimserver.utils.NetUtils.getContent(NetUtils.java:48)
	at org.bimserver.webservices.impl.ServiceImpl.getAllRepositoryExtendedDataSchemas(ServiceImpl.java:1944)
	at org.bimserver.generated.ServiceInterfaceReflector1.callMethod(ServiceInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:213)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:137)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:60)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:136)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:835)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:225)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)

**Comment by rubendel** [comment]
I have had this today as well, I think the maven repositories have been down/slow today, might have something to do with AWS S3 problems...

**Comment by rubendel** [comment]
Apart from that, it could also be that you are running BIMserver with no internet connection, or via a proxy server. See https://github.com/opensourceBIM/BIMserver/issues/413

**Comment by webdadag** [comment]
Regarding internet connection, many of the my client environment servers
would have no outgoing internet, for security reasons. This is the basis of
a secure server environment -

What are the URLs, servers that are needed for the installation and
configuration? I could request specific URLs to be allowed.

Regards,

Sam



---------------------------------------------------------------------------
Sam Wu
U.S. General Services Administration
*Public Buildings Information Technology Services*
1800 F Street, NW
Washington, DC 20006
sam.wu@gsa.gov
202-557-4240 (Work),  703-598-2905(Mobile)
---------------------------------------------------------------------------
*Central Facility Repository (CFR): *
*CFR Support: Submit support ticket via https://gsa.service-now.com
<https://gsa.service-now.com>*
*CFR Insite: http://insite.gsa.gov/cfr <http://insite.gsa.gov/cfr>*
CFR Team Email:  pbscfrsupport@gsa.gov
Admin Email: Komi.Gnatiko@gsa.gov (CFR and PBS/NCR CMMS)
CFR URL: http://portal.pbs.gsa.gov/share
*Meeting Space:*
http://meet.gsa.gov/cfrdev USA: 1-719-325-2013
USA/Canada (toll free) 1-866-928-2008:*124208*
---------------------------------------------------------------------------

**Comment by webdadag** [comment]
I also tried this on my laptop which has internet connection. It can
complete the configuration steps but fails when I check in an IFC file.

   - Office_A_20110811.ifc

It will keep repeating the last line:
16:18:44 INFO  [LongStreamingCheckinAction]: Switching to reading from
cached file
 (RestartableInputStream.java:34)

My team would love to do a QA check for the new releases, to make sure the
new releases pass basic quality assurance checks.

For example, issue #52 mentioned a few public IFC files (I am using one of
them). My team can test every one of the IFC files, to make sure we have a
good quality pre-release and releases.
https://github.com/opensourceBIM/BIMsurfer/issues/52



---- Log file ------
INFO: Setting the server's publish address to be /soap12/OAuthInterface
16:15:23 INFO  [main]: Skipping strict dependency checking for dependency
bimserverapi                  (PluginManager.java:1273)
16:15:23 INFO  [main]: Skipping strict dependency checking for dependency
bimserverapi                  (PluginManager.java:1273)
16:15:23 INFO  [main]: Skipping strict dependency checking for dependency
bimsurfer                     (PluginManager.java:1273)
16:15:23 INFO  [main]: Server started successfully
                             (JarBimServer.java:85)
16:17:47 INFO  [LongStreamingCheckinAction]: writes: 100000

(BerkeleyKeyValueStore.java:589)
16:17:48 INFO  [LongStreamingCheckinAction]: 1018 ms sync

(BerkeleyKeyValueStore.java:596)
16:17:50 INFO  [LongStreamingCheckinAction]: writes: 200000

(BerkeleyKeyValueStore.java:589)
16:17:51 INFO  [LongStreamingCheckinAction]: 490 ms sync

 (BerkeleyKeyValueStore.java:596)
16:17:53 INFO  [LongStreamingCheckinAction]: writes: 300000

(BerkeleyKeyValueStore.java:589)
16:17:54 INFO  [LongStreamingCheckinAction]: 484 ms sync

 (BerkeleyKeyValueStore.java:596)
16:17:58 INFO  [LongStreamingCheckinAction]: writes: 400000

(BerkeleyKeyValueStore.java:589)
16:17:59 INFO  [LongStreamingCheckinAction]: 362 ms sync

 (BerkeleyKeyValueStore.java:596)
16:18:00 INFO  [LongStreamingCheckinAction]: writes: 500000

(BerkeleyKeyValueStore.java:589)
16:18:00 INFO  [LongStreamingCheckinAction]: 328 ms sync

 (BerkeleyKeyValueStore.java:596)
16:18:02 INFO  [LongStreamingCheckinAction]: writes: 600000

(BerkeleyKeyValueStore.java:589)
16:18:02 INFO  [LongStreamingCheckinAction]: 312 ms sync

 (BerkeleyKeyValueStore.java:596)
16:18:03 INFO  [LongStreamingCheckinAction]: writes: 700000

(BerkeleyKeyValueStore.java:589)
16:18:04 INFO  [LongStreamingCheckinAction]: 290 ms sync

 (BerkeleyKeyValueStore.java:596)
16:18:07 INFO  [LongStreamingCheckinAction]: writes: 800000

(BerkeleyKeyValueStore.java:589)
16:18:08 INFO  [LongStreamingCheckinAction]: 1168 ms sync

(BerkeleyKeyValueStore.java:596)
16:18:11 INFO  [LongStreamingCheckinAction]: writes: 900000

(BerkeleyKeyValueStore.java:589)
16:18:11 INFO  [LongStreamingCheckinAction]: 338 ms sync

 (BerkeleyKeyValueStore.java:596)
16:18:12 INFO  [LongStreamingCheckinAction]: writes: 1000000

 (BerkeleyKeyValueStore.java:589)
16:18:13 INFO  [LongStreamingCheckinAction]: 383 ms sync

 (BerkeleyKeyValueStore.java:596)
16:18:14 INFO  [LongStreamingCheckinAction]: writes: 1100000

 (BerkeleyKeyValueStore.java:589)
16:18:14 INFO  [LongStreamingCheckinAction]: 316 ms sync

 (BerkeleyKeyValueStore.java:596)
16:18:15 INFO  [LongStreamingCheckinAction]: writes: 1200000

 (BerkeleyKeyValueStore.java:589)
16:18:15 INFO  [LongStreamingCheckinAction]: 316 ms sync

 (BerkeleyKeyValueStore.java:596)
16:18:16 INFO  [LongStreamingCheckinAction]: writes: 1300000

 (BerkeleyKeyValueStore.java:589)
16:18:17 INFO  [LongStreamingCheckinAction]: 291 ms sync

 (BerkeleyKeyValueStore.java:596)
16:18:17 INFO  [LongStreamingCheckinAction]: writes: 1400000

 (BerkeleyKeyValueStore.java:589)
16:18:18 INFO  [LongStreamingCheckinAction]: 347 ms sync

 (BerkeleyKeyValueStore.java:596)
16:18:20 INFO  [LongStreamingCheckinAction]: writes: 1500000

 (BerkeleyKeyValueStore.java:589)
16:18:21 INFO  [LongStreamingCheckinAction]: 1141 ms sync

(BerkeleyKeyValueStore.java:596)
16:18:25 INFO  [LongStreamingCheckinAction]: writes: 1600000

 (BerkeleyKeyValueStore.java:589)
16:18:26 INFO  [LongStreamingCheckinAction]: 1458 ms sync

(BerkeleyKeyValueStore.java:596)
16:18:29 INFO  [LongStreamingCheckinAction]: writes: 1700000

 (BerkeleyKeyValueStore.java:589)
16:18:31 INFO  [LongStreamingCheckinAction]: 1245 ms sync

(BerkeleyKeyValueStore.java:596)
16:18:34 INFO  [LongStreamingCheckinAction]: writes: 1800000

 (BerkeleyKeyValueStore.java:589)
16:18:35 INFO  [LongStreamingCheckinAction]: 1028 ms sync

(BerkeleyKeyValueStore.java:596)
16:18:37 INFO  [LongStreamingCheckinAction]: Switching to reading from
cached file
 (RestartableInputStream.java:34)
16:18:39 INFO  [LongStreamingCheckinAction]: Switching to reading from
cached file
 (RestartableInputStream.java:34)
16:18:40 INFO  [LongStreamingCheckinAction]: Switching to reading from
cached file
 (RestartableInputStream.java:34)
16:18:42 INFO  [LongStreamingCheckinAction]: Switching to reading from
cached file
 (RestartableInputStream.java:34)
16:18:43 INFO  [LongStreamingCheckinAction]: Switching to reading from
cached file
 (RestartableInputStream.java:34)
16:18:44 INFO  [LongStreamingCheckinAction]: Switching to reading from
cached file
 (RestartableInputStream.java:34)






---------------------------------------------------------------------------
Sam Wu
U.S. General Services Administration
*Public Buildings Information Technology Services*
1800 F Street, NW
Washington, DC 20006
sam.wu@gsa.gov
202-557-4240 (Work),  703-598-2905(Mobile)
---------------------------------------------------------------------------
*Central Facility Repository (CFR): *
*CFR Support: Submit support ticket via https://gsa.service-now.com
<https://gsa.service-now.com>*
*CFR Insite: http://insite.gsa.gov/cfr <http://insite.gsa.gov/cfr>*
CFR Team Email:  pbscfrsupport@gsa.gov
Admin Email: Komi.Gnatiko@gsa.gov (CFR and PBS/NCR CMMS)
CFR URL: http://portal.pbs.gsa.gov/share
*Meeting Space:*
http://meet.gsa.gov/cfrdev USA: 1-719-325-2013
USA/Canada (toll free) 1-866-928-2008:*124208*
---------------------------------------------------------------------------

**Comment by webdadag** [comment]
Just a side note, just my opinion - that an enterprise application and its
installers should not require out-going internet connection. It is just a
big issue for Enterprise software security.

All the enterprise software that I ever installed (there are quite a few)
can be installed without out-going internet connection.

BIMServer 1.4 can be installed without it, BIMServer 1.5 could also be
packed that it is not required too - I know that we could not just fix it
now but just a note.

Regards,

Sam




---------------------------------------------------------------------------
Sam Wu
U.S. General Services Administration
*Public Buildings Information Technology Services*
1800 F Street, NW
Washington, DC 20006
sam.wu@gsa.gov
202-557-4240 (Work),  703-598-2905(Mobile)
---------------------------------------------------------------------------
*Central Facility Repository (CFR): *
*CFR Support: Submit support ticket via https://gsa.service-now.com
<https://gsa.service-now.com>*
*CFR Insite: http://insite.gsa.gov/cfr <http://insite.gsa.gov/cfr>*
CFR Team Email:  pbscfrsupport@gsa.gov
Admin Email: Komi.Gnatiko@gsa.gov (CFR and PBS/NCR CMMS)
CFR URL: http://portal.pbs.gsa.gov/share
*Meeting Space:*
http://meet.gsa.gov/cfrdev USA: 1-719-325-2013
USA/Canada (toll free) 1-866-928-2008:*124208*
---------------------------------------------------------------------------

**Comment by oliviersaintgobain** [comment]
Hi, in the PluginBase project, in the class:
org.bimserver.utils.Netutils
add a proxy configuration instead of direct open connection.
Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("your proxy", your port));			
HttpsURLConnection  openConnection = (HttpsURLConnection) url.openConnection(proxy);

it should works...

Olivier

**Comment by rubendel** [comment]
Please use the search function before posting new issues: https://github.com/opensourceBIM/BIMserver/issues/466

Also please create one github issue for every separate issue.

I don't see why a server system would not have an outgoing internet connection. Almost all software I use uses an outgoing internet connection to fetch updates or get license information. Also I don't see the security implications of it. I most definitely do not see how a proxy server could make things more secure than a properly configured firewall.

Due to popular demand though, functionality will be added to allow for installing plugins by uploading them.

**Comment by rubendel** [comment]
The URL that's used to get plugins is http://central.maven.org/maven2

**Comment by webdadag** [comment]
Thank you Ruben ! This is exactly what I need to ask for a whitelist
exception.

Regards,

Sam



---------------------------------------------------------------------------
Sam Wu
U.S. General Services Administration
*Public Buildings Information Technology Services*
1800 F Street, NW
Washington, DC 20006
sam.wu@gsa.gov
202-557-4240 (Work),  703-598-2905(Mobile)
---------------------------------------------------------------------------
*Central Facility Repository (CFR): *
*CFR Support: Submit support ticket via https://gsa.service-now.com
<https://gsa.service-now.com>*
*CFR Insite: http://insite.gsa.gov/cfr <http://insite.gsa.gov/cfr>*
CFR Team Email:  pbscfrsupport@gsa.gov
Admin Email: Komi.Gnatiko@gsa.gov (CFR and PBS/NCR CMMS)
CFR URL: http://portal.pbs.gsa.gov/share
*Meeting Space:*
http://meet.gsa.gov/cfrdev USA: 1-719-325-2013
USA/Canada (toll free) 1-866-928-2008:*124208*
---------------------------------------------------------------------------

**Comment by rubendel** [comment]
FYI a new developers release (1.5.69) has been published with a slightly improved setup procedure. It should work without an internet connection and allow you to install plugins by uploading files via your webbrowser. There is a little bit of documentation https://github.com/opensourceBIM/BIMserver/wiki/Installing-without-internet-connection

> Just a note, in BIMserver 1.5 you cannot just copy a plugin file to the plugins directory anymore, BIMserver is not actively monitoring this folder for new plugins and uses it to store plugins installed via the available interfaces.

**Comment by webdadag** [comment]
Thanks Ruben.

Using the internet connection workaround in BIMServer 1.5.69, I can
complete the install, but when I start check-in IFC files, the deserializer
drop down box is empty and I could not upload IFC files.

I tried a complete new install, and also using the user interface to upload
a new plug-in jar files, same result.

Please advise.

Regards,

Sam



[image: Inline image 1]



---------------------------------------------------------------------------
Sam Wu
U.S. General Services Administration
*Public Buildings Information Technology Services*
1800 F Street, NW
Washington, DC 20006
sam.wu@gsa.gov
202-557-4240 (Work),  703-598-2905(Mobile)
---------------------------------------------------------------------------
*Central Facility Repository (CFR): *
*CFR Support: Submit support ticket via https://gsa.service-now.com
<https://gsa.service-now.com>*
*CFR Insite: http://insite.gsa.gov/cfr <http://insite.gsa.gov/cfr>*
CFR Team Email:  pbscfrsupport@gsa.gov
Admin Email: Komi.Gnatiko@gsa.gov (CFR and PBS/NCR CMMS)
CFR URL: http://portal.pbs.gsa.gov/share
*Meeting Space:*
http://meet.gsa.gov/cfrdev USA: 1-719-325-2013
USA/Canada (toll free) 1-866-928-2008:*124208*
---------------------------------------------------------------------------

**Comment by rubendel** [comment]
You need the IfcPlugins plugin, that contains serializer/deserializers for IFC. Have you read the information on the Plugins tab of the Setup page? I'll quote it "Without this plugin BIMserver will not be able to read/write IFC"

**Comment by rubendel** [comment]
No need to do a complete new install to get that working BTW, you can use BIMvie.ws to install further plugins.
