### ISSUE TITLE
load ifc file in Bim server using checkin fuction error: org.bimserver.utils.StringUtils.nextField(Ljava/lang/String;I)I

### ISSUE THREAD

**Issue by grmc144** [opensourceBIM/BIMserver#496]
My error log..

13:52:18 INFO  [main]: Using "home" as homedir                                                          (BimServer.java:215) 
13:52:19 INFO  [main]: SServiceMap Created                                                              (BimServer.java:221) 
13:52:19 INFO  [main]: JsonSocketReflectorFactory created                                               (BimServer.java:224) 
13:52:20 INFO  [main]: ServerInfoManager created                                                        (BimServer.java:227) 
13:52:20 INFO  [main]: NotificationsManager created                                                     (BimServer.java:230) 
13:52:20 INFO  [main]: InternalServicesManager created                                                  (BimServer.java:233) 
13:52:20 INFO  [main]: PublicInterfaceFactory created                                                   (BimServer.java:236) 
13:52:20 INFO  [main]: PluginManager created                                                            (BimServer.java:251) 
13:52:20 INFO  [main]: Version Checker created                                                          (BimServer.java:254) 
13:52:20 INFO  [main]: Embedded webserver created                                                       (BimServer.java:260) 
13:52:20 INFO  [main]: Version: 1.5.64-SNAPSHOT                                                         (BimServer.java:296) 
13:52:30 INFO  [main]: Using "C:\Users\francis.a\git\BIMserver\BimServerJar\..\BimServer\emailtemplates\" as template dir (TemplateEngine.java:64) 
13:52:30 INFO  [main]: Non-empty database directory found "home\database"                               (BerkeleyKeyValueStore.java:85) 
13:52:33 INFO  [main]: Changing server state to RUNNING                                                 (ServerInfoManager.java:112) 
13:54:04 ERROR [LongStreamingCheckinAction]:                                                                                  (StreamingCheckinDatabaseAction.java:334) 
java.lang.NoSuchMethodError: org.bimserver.utils.StringUtils.nextField(Ljava/lang/String;I)I
	at org.bimserver.ifc.step.deserializer.StepParser.<init>(StepParser.java:16) ~[na:na]
	at org.bimserver.ifc.step.deserializer.IfcHeaderParser.parseFileName(IfcHeaderParser.java:39) ~[na:na]
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processHeader(IfcStepStreamingDeserializer.java:275) ~[na:na]
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processLine(IfcStepStreamingDeserializer.java:221) ~[na:na]
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:179) ~[na:na]
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:161) ~[na:na]
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:182) [classes/:na]
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:1) [classes/:na]
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:698) [classes/:na]
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:685) [classes/:na]
	at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:61) [classes/:na]
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43) [classes/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
13:54:04 ERROR [LongStreamingCheckinAction]:                                                                                  (LongAction.java:189) 
org.bimserver.shared.exceptions.UserException: org.bimserver.utils.StringUtils.nextField(Ljava/lang/String;I)I
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:335) ~[classes/:na]
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:1) ~[classes/:na]
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:698) ~[classes/:na]
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:685) ~[classes/:na]
	at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:61) ~[classes/:na]
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43) [classes/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.lang.NoSuchMethodError: org.bimserver.utils.StringUtils.nextField(Ljava/lang/String;I)I
	at org.bimserver.ifc.step.deserializer.StepParser.<init>(StepParser.java:16) ~[na:na]
	at org.bimserver.ifc.step.deserializer.IfcHeaderParser.parseFileName(IfcHeaderParser.java:39) ~[na:na]
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processHeader(IfcStepStreamingDeserializer.java:275) ~[na:na]
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processLine(IfcStepStreamingDeserializer.java:221) ~[na:na]
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:179) ~[na:na]
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:161) ~[na:na]
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:182) ~[classes/:na]
	... 6 common frames omitted

**Comment by rubendel** [comment]
This has been answered before, use a more recent BIMserver release
