### ISSUE TITLE
Exception java.lang.IllegalStateException: Connection pool shut down when calling getDownloadData with bimserverclient

### ISSUE THREAD

**Issue by felixh85** [opensourceBIM/BIMserver#505]
I try to download the model of a project from the bimserver with the bimserverclient. Therefore, I am using the following code:

``` IfcModelInterface model = client.getModel(project, project.getLastRevisionId(), true, false,true);```

During this call, the methode getDownloadData is invoked which results in the follwoing exception:
``` 
java.lang.IllegalStateException: Connection pool shut down
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.pool.AbstractConnPool.lease(AbstractConnPool.java:184)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:251)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:175)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.bimserver.client.Channel.getDownloadData(Channel.java:178)
	at org.bimserver.client.BimServerClient.getDownloadData(BimServerClient.java:308)
	at org.bimserver.client.ClientIfcModel.processDownload(ClientIfcModel.java:460)
	at org.bimserver.client.ClientIfcModel.loadDeep(ClientIfcModel.java:293)
	at org.bimserver.client.ClientIfcModel.<init>(ClientIfcModel.java:110)
	at org.bimserver.client.BimServerClient.getModel(BimServerClient.java:191)
	at org.bimserver.client.BimServerClient.getModel(BimServerClient.java:1)
```

When I tried to download an IFC file, I could work around this problem by using the ServiceInterface. However, this is not possible in this case.

During my research I discovered that this is probably a problem of the HTTPClient (see [here](http://stackoverflow.com/questions/25889925/apache-poolinghttpclientconnectionmanager-throwing-illegal-state-exception)). However, I double checked and I am using the following versions in the bimserver and bimserverclient application where the issue should have been fixed: httpclient-4.5.1.jar, httpcore-4.4.3.jar, httpmime-4.5.1.jar

I would appreciate your help in solving this issue. Thanks!

BTW, I am using bimserver 1.5.63.

**Comment by rubendel** [comment]
It is real hard to try and reproduce this with just one line of code. Can you come up with a minimal example that allows to reproduce this?

Are you sure you are not accidentally closing the BimServerClient (by using a try/with statement for example)?

I don't think the mentioned bug is relevant since no connection pools are shared between http clients (there is only one http client).

**Comment by felixh85** [comment]
Thank you for your answer Ruben. You were right, it was a problem with the connection. I was using a try/with statement for establishing the connection with the BimServerClient. When I changed it, the problem was gone. Thanks for your support.

**Comment by ganeshOodles** [comment]
I m using 3rd party API for currency conversion and first time when I hit the API I get the proper response but 2nd time I get this error message 

java.lang.IllegalStateException: Connection pool shut down
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.pool.AbstractConnPool.lease(AbstractConnPool.java:189)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:257)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.belfrics.service.bitcoincore.WalletManagementService.sendLiveRequest(WalletManagementService.java:518)
	at com.belfrics.service.bitcoincore.WalletManagementService.getConvertedCurrency(WalletManagementService.java:482)
	at com.belfrics.service.bitcoincore.WalletManagementService$$FastClassBySpringCGLIB$$9aab70b2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:669)
	at com.belfrics.service.bitcoincore.WalletManagementService$$EnhancerBySpringCGLIB$$14940a83.getConvertedCurrency(<generated>)
	at com.belfrics.controller.bitcoincore.WalletManagementController.getConvertedCurrency(WalletManagementController.java:122)
	at com.belfrics.controller.bitcoincore.WalletManagementController$$FastClassBySpringCGLIB$$a1ab7bde.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:669)
	at com.belfrics.controller.bitcoincore.WalletManagementController$$EnhancerBySpringCGLIB$$1ed48af2.getConvertedCurrency(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
