### ISSUE TITLE
Bugreport： Missing some parts！

### ISSUE THREAD

**Issue by yanzhenxing** [opensourceBIM/BIMserver#510]
Hi, Ruben,

I found some parts missing when view the ifc model with bimsurfer 0.0.37 and bimserver 1.5.68 as follow pictures.

<img width="365" alt="full" src="https://cloud.githubusercontent.com/assets/2803129/25366040/b04286c0-299f-11e7-91b0-26ef201deceb.png">

<img width="313" alt="partly" src="https://cloud.githubusercontent.com/assets/2803129/25366048/c0c86dde-299f-11e7-9f06-00770cac8406.png">

The first pic is the correct view when open the ifc file with Areddo, the second pic is the bimserver view and there is something missing!

The ifc file failed to upload and I think you could send me a link to upload the file.

Thank you!

best regards

**Comment by rubendel** [comment]
https://www.dropbox.com/request/rSclqw6tD4ihi8F1QaE7

**Comment by yanzhenxing** [comment]
I can not access the dropbox. Would you please use the follow link?
http://pan.baidu.com/s/1ge6pR0J

**Comment by rubendel** [comment]
Oh oh, the page you are visiting does not exist.

**Comment by yanzhenxing** [comment]
Did you access my link successfully?

**Comment by rubendel** [comment]
Second time it worked. The file looks fine in my BIMserver/BIMvie.ws setup. Can you please try the latest version?

![baidu](https://cloud.githubusercontent.com/assets/377978/25378116/b08da43e-29a9-11e7-9fa0-5fb91d9cd654.png)

**Comment by yanzhenxing** [comment]
OK , I will have a try, and what's the version of your system, include bimserver/bimvie.ws/bimsufer and other plugins? Thank you!

**Comment by rubendel** [comment]
Just the latest of everything

**Comment by yanzhenxing** [comment]
I download the 1.5.73 version war, and after I checkin the same ifc file , an exception occur when I view the 3d model. The exception is as follow:

```
17:40:16 ERROR [org.bimserver.ServiceInterface.download]:                                                                                  (LongStreamingDownloadAction.java:153) 
java.lang.NullPointerException: null
	at org.bimserver.database.queries.om.JsonQueryObjectModelConverter.parseJsonQuery(JsonQueryObjectModelConverter.java:390)
	at org.bimserver.database.queries.om.JsonQueryObjectModelConverter.parseJson(JsonQueryObjectModelConverter.java:171)
	at org.bimserver.longaction.LongStreamingDownloadAction.<init>(LongStreamingDownloadAction.java:110)
	at org.bimserver.webservices.impl.ServiceImpl.download(ServiceImpl.java:411)
	at org.bimserver.generated.ServiceInterfaceReflector1.callMethod(ServiceInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:213)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:142)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:64)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:140)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:835)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:225)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Unknown Source)
```

Could you show me the plugins versions in your home/plugins directory.
