### ISSUE TITLE
Error in 3d Model view not showing

### ISSUE THREAD

**Issue by grmc144** [opensourceBIM/BIMserver#515]
Hi,,

 i download  lastest version of bimserver .all process are fine bt click 3d model view its showing error in queriesException

17:37:31 ERROR [org.bimserver.ServiceInterface.download]:                                                                                  (LongAction.java:189) 
org.bimserver.database.queries.om.QueryException: "type" must be of type string
	at org.bimserver.database.queries.om.JsonQueryObjectModelConverter.parseJsonQuery(JsonQueryObjectModelConverter.java:369)
	at org.bimserver.database.queries.om.JsonQueryObjectModelConverter.parseJson(JsonQueryObjectModelConverter.java:151)
	at org.bimserver.longaction.LongStreamingDownloadAction.<init>(LongStreamingDownloadAction.java:108)
	at org.bimserver.webservices.impl.ServiceImpl.download(ServiceImpl.java:408)
	at org.bimserver.generated.ServiceInterfaceReflector1.callMethod(ServiceInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:213)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:142)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:64)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:140)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:835)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:225)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Unknown Source)

**Comment by rubendel** [comment]
Sorry, I forgot to make a new build for BIMserver after updating something incompatible. Can you try the new release (https://github.com/opensourceBIM/BIMserver/releases/tag/parent-1.5.73)?

**Comment by GIANCPP** [comment]
Hello, the problem continues, it is not possible to visualize the 3D model, I have already downloaded the latest version and the problem persists.

Following some old guidelines I installed Java \ jdk1.8.0_131 and directed the program to the correct address, in this case the installation indicated the following error:

homedir=D:\BIM\home
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object

**Comment by rubendel** [comment]
Setting the JVM does not work at the moment, just keep it to "default".

**Comment by GIANCPP** [comment]
Thanks for the answer.

I downloaded two sample files with .ifc extension and I was able to view it in 3D view, but I still can not see my .ifc files in 3D view, they are loaded normally and have no error report but do not show 3D. These my files open and are normally viewed in other bim viewers, eg Tekla BIMsight.

**Comment by berlotti** [comment]
any error reports?
did you click on the eye?

**Comment by grmc144** [comment]
Thanks for the answer. rubendel

I upgrade bimserver 1.5.74.. after finished github installation i upload ifc file..
 no error comes but its stuck on generated geometry value.

i attached my screenshot of that page
![untitled](https://cloud.githubusercontent.com/assets/22959292/25605925/f19f3dca-2f2b-11e7-92cc-011fc417d14c.jpg)

**Comment by berlotti** [comment]
Ah, this is during generation of the triangles and done by a plugin.
Which plugin are you using for this? The default IfcOpenShell?
Could you provide us with the original IFC file for debugging?

**Comment by grmc144** [comment]
thanks for reply berlotti,

now its working fine..
