### ISSUE TITLE
MigrateDatabase error!

### ISSUE THREAD

**Issue by yanzhenxing** [opensourceBIM/BIMserver#517]
Hi, 

I am going to upgrade bimserver from 1.5.68 to 1.5.73, and when I start the server, it tips that I should migrate the database. And then I click the migrate button and some errors occur in the console , the log is as follow:

```
12:26:54 ERROR [org.bimserver.AdminInterface.migrateDatabase]:                                                                                  (NewReferenceChange.java:107) 
org.bimserver.BimserverDatabaseException: Size to not match
	at org.bimserver.database.migrations.NewReferenceChange.change(NewReferenceChange.java:67)
	at org.bimserver.database.migrations.Schema.upgradeDatabase(Schema.java:231)
	at org.bimserver.database.migrations.Migrator.upgrade(Migrator.java:117)
	at org.bimserver.database.migrations.Migrator.migrate(Migrator.java:163)
	at org.bimserver.database.migrations.Migrator.migrate(Migrator.java:98)
	at org.bimserver.webservices.impl.AdminServiceImpl.migrateDatabase(AdminServiceImpl.java:278)
	at org.bimserver.generated.AdminInterfaceReflector1.callMethod(AdminInterfaceReflector1.java)
```

Then the server changes the state to running, and I find that my previous project could not show the 3d model. And the exception occurs : 

```
12:28:36 ERROR [Streamer 2]:                                                                                  (Streamer.java:139) 
org.bimserver.plugins.serializers.SerializerException: org.bimserver.BimserverDatabaseException: org.bimserver.BimserverDatabaseException: Reading GeometryInfo.minBoundsUntranslated 214
	at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer3.load(BinaryGeometryMessagingStreamingSerializer3.java:157)
	at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer3.writeMessage(BinaryGeometryMessagingStreamingSerializer3.java:117)
	at org.bimserver.servlets.Streamer$1.run(Streamer.java:121)
Caused by: org.bimserver.BimserverDatabaseException: org.bimserver.BimserverDatabaseException: Reading GeometryInfo.minBoundsUntranslated 214
	at org.bimserver.database.queries.QueryObjectProvider.next(QueryObjectProvider.java:148)
	at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer3.load(BinaryGeometryMessagingStreamingSerializer3.java:149)
	... 2 common frames omitted
Caused by: org.bimserver.BimserverDatabaseException: Reading GeometryInfo.minBoundsUntranslated 214
	at org.bimserver.database.queries.DatabaseReadingStackFrame.convertByteArrayToObject(DatabaseReadingStackFrame.java:249)
	at org.bimserver.database.queries.DatabaseReadingStackFrame.getMap(DatabaseReadingStackFrame.java:148)
	at org.bimserver.database.queries.QueryOidsAndTypesStackFrame.process(QueryOidsAndTypesStackFrame.java:95)
	at org.bimserver.database.queries.QueryObjectProvider.next(QueryObjectProvider.java:135)
	... 3 common frames omitted
Caused by: java.nio.BufferUnderflowException: null
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.HeapByteBuffer.getShort(HeapByteBuffer.java:310)
	at org.bimserver.database.queries.DatabaseReadingStackFrame.convertByteArrayToObject(DatabaseReadingStackFrame.java:203)
	... 6 common frames omitted

```

**Comment by rubendel** [comment]
https://github.com/opensourceBIM/BIMserver/issues/432

**Comment by xie-qianyue** [comment]
@yanzhenxing Hello zhenxing, maybe you can close this issue now? : )
