### ISSUE TITLE
Upgrading database to version 31

### ISSUE THREAD

**Issue by lordkaoz** [opensourceBIM/BIMserver#530]
hello,
im installing bim server in eclipse Neon. evrything look to go perfectly until it gets to Upgrading database to version 31 then it throws ::

15:48:54 INFO  [main]: Creating transactional table: store_NewServiceDescriptor                         (NewClassChange.java:45) 
15:48:54 INFO  [main]: Creating transactional table: store_FormatSerializerMap                          (NewClassChange.java:45) 
15:48:54 INFO  [main]: Creating transactional table: store_Action                                       (NewClassChange.java:45) 
15:48:54 INFO  [main]: Creating transactional table: store_StoreExtendedData                            (NewClassChange.java:45) 
15:48:54 INFO  [main]: Creating transactional table: store_CheckinRevision                              (NewClassChange.java:45) 
15:48:54 INFO  [main]: Creating transactional table: store_NewService                                   (NewClassChange.java:45) 
15:48:54 INFO  [main]: Upgrading database to version 26                                                 (Schema.java:227) 
15:48:55 INFO  [main]: Upgrading database to version 27                                                 (Schema.java:227) 
15:48:55 INFO  [main]: Upgrading database to version 28                                                 (Schema.java:227) 
15:48:56 INFO  [main]: Upgrading database to version 29                                                 (Schema.java:227) 
15:48:56 INFO  [main]: Upgrading database to version 30                                                 (Schema.java:227) 
15:48:57 INFO  [main]: Upgrading database to version 31                                                 (Schema.java:227) 
15:48:58 INFO  [main]: Non-empty database directory found "home\database"                               (BerkeleyKeyValueStore.java:86) 
 ERROR [main]:                                                                                  (ProtocolBuffersMetaData.java:173) 
com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
	at com.google.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:94)
	at com.google.protobuf.CodedInputStream.checkLastTagWas(CodedInputStream.java:174)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:194)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:215)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at com.google.protobuf.DescriptorProtos$FileDescriptorSet.parseFrom(DescriptorProtos.java:254)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:151)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:187)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:223)
	at org.bimserver.BimServer.start(BimServer.java:683)
	at org.bimserver.LocalDevBimServerStarter.start(LocalDevBimServerStarter.java:61)
	at org.bimserver.LocalDevBimServerStarter.main(LocalDevBimServerStarter.java:43)
15:48:58 ERROR [main]:                                                                                  (ProtocolBuffersMetaData.java:173) 
com.google.protobuf.InvalidProtocolBufferException: Protocol message tag had invalid wire type.
	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:99)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:515)
	at com.google.protobuf.GeneratedMessage.parseUnknownField(GeneratedMessage.java:205)
	at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<init>(DescriptorProtos.java:1066)
	at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<init>(DescriptorProtos.java:1023)
	at com.google.protobuf.DescriptorProtos$FileDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:1244)
	at com.google.protobuf.DescriptorProtos$FileDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:1239)
	at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:495)
	at com.google.protobuf.DescriptorProtos$FileDescriptorSet.<init>(DescriptorProtos.java:101)
	at com.google.protobuf.DescriptorProtos$FileDescriptorSet.<init>(DescriptorProtos.java:47)
	at com.google.protobuf.DescriptorProtos$FileDescriptorSet$1.parsePartialFrom(DescriptorProtos.java:137)
	at com.google.protobuf.DescriptorProtos$FileDescriptorSet$1.parsePartialFrom(DescriptorProtos.java:132)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:192)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:215)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at com.google.protobuf.DescriptorProtos$FileDescriptorSet.parseFrom(DescriptorProtos.java:254)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:151)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:187)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:223)
	at org.bimserver.BimServer.start(BimServer.java:683)
	at org.bimserver.LocalDevBimServerStarter.start(LocalDevBimServerStarter.java:61)
	at org.bimserver.LocalDevBimServerStarter.main(LocalDevBimServerStarter.java:43)
15:48:58 ERROR [main]: Dependency ServiceInterface.proto of AdminInterface.proto not found              (ProtocolBuffersMetaData.java:159) 
15:48:58 ERROR [main]: Dependency NewServicesInterface.proto of AdminInterface.proto not found          (ProtocolBuffersMetaData.java:159) 
15:48:58 ERROR [main]:                                                                                  (BimServer.java:780) 
java.lang.NullPointerException: null
	at com.google.protobuf.Descriptors$DescriptorPool.importPublicDependencies(Descriptors.java:1849)
	at com.google.protobuf.Descriptors$DescriptorPool.<init>(Descriptors.java:1832)
	at com.google.protobuf.Descriptors$FileDescriptor.buildFrom(Descriptors.java:266)
	at com.google.protobuf.Descriptors$FileDescriptor.buildFrom(Descriptors.java:235)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:163)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:187)
	at org.bimserver.shared.pb.ProtocolBuffersMetaData.load(ProtocolBuffersMetaData.java:223)
	at org.bimserver.BimServer.start(BimServer.java:683)
	at org.bimserver.LocalDevBimServerStarter.start(LocalDevBimServerStarter.java:61)
	at org.bimserver.LocalDevBimServerStarter.main(LocalDevBimServerStarter.java:43)

any help will be more than welcome.
thanks

**Comment by rubendel** [comment]
Hmm I think I have seen this before, the binary protocol buffers files were somehow corrupted in that case. Maybe refreshing in Eclipse helps? Or a new git clone.

**Comment by lordkaoz** [comment]
rudendel, 
i tried reloading the project and download it again from git.  im still getting the same error.
any idea what i can do? i need to start development with this server and im stuck.
thank you for your help.
Adrian

**Comment by lordkaoz** [comment]
also when i try to run it from Starter.java i get =
Exception in thread "BIMserver Starter Thread" java.lang.StringIndexOutOfBoundsException: String index out of range: -4
	at java.lang.String.substring(Unknown Source)
	at org.bimserver.starter.Starter.getJarFileNameNew(Starter.java:662)
	at org.bimserver.starter.Starter.expand(Starter.java:612)
	at org.bimserver.starter.Starter.access$3(Starter.java:610)
	at org.bimserver.starter.Starter$4$1.run(Starter.java:256)
	at java.lang.Thread.run(Unknown Source)

i try this same thing with others versions from the repo like 1.4.0 with the same result.

thank you
Adrian
