### ISSUE TITLE
org.bimserver.shared.exceptions.UserException: Error on line 548278: IfcPropertySingleValue expects 4 fields, but less found (String index out of range: -1)

### ISSUE THREAD

**Issue by xuys0523** [opensourceBIM/BIMserver#532]
Hi, Ruben,

When I checkin an ifc file(size:323597KB), which contain the item as follow:

**#912722= IFCPROPERTYSINGLEVALUE('magiProductCode',$,IFCTEXT('TDK/280'),$);**

an error happened.

**the log info as below：**
11:17:06 ERROR [LongStreamingCheckinAction]:                                                                                  (LongAction.java:189) 
org.bimserver.shared.exceptions.UserException: Error on line 548278: IfcPropertySingleValue expects 4 fields, but less found (String index out of range: -1)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:339)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:76)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:699)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:686)
	at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:61)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.bimserver.plugins.deserializers.DeserializeException: Error on line 548278: IfcPropertySingleValue expects 4 fields, but less found (String index out of range: -1)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processRecord(IfcStepStreamingDeserializer.java:358)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processLine(IfcStepStreamingDeserializer.java:246)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:181)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:163)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:187)
	... 6 common frames omitted

**Comment by rubendel** [comment]
I cannot reproduce this (by changing a line in another file to make it look the same as this one).

Which version of BIMserver/plugins can you reproduce this on? Can you perhaps share the file? Is this "magiProductCode" value really the value, or is perhaps the actual problem in the original value?

**Comment by xuys0523** [comment]
Thanks ! The error did not happen again by restart the server and reinstall plugins.
