### ISSUE TITLE
Download model error

### ISSUE THREAD

**Issue by xuys0523** [opensourceBIM/BIMserver#534]
I want to load the model onto cesium,but the below error hanppend.

14:36:59 ERROR [org.bimserver.ServiceInterface.download]:                                                                                  (LongStreamingDownloadAction.java:153)
java.lang.ClassCastException: org.bimserver.models.store.impl.ProjectImpl cannot be cast to org.bimserver.models.store.Revision
        at org.bimserver.longaction.LongStreamingDownloadAction.<init>(LongStreamingDownloadAction.java:90)
        at org.bimserver.webservices.impl.ServiceImpl.download(ServiceImpl.java:412)
        at org.bimserver.generated.ServiceInterfaceReflector1.callMethod(ServiceInterfaceReflector1.java)
        at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:213)
        at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:142)
        at org.bimserver.JsonHandler.execute(JsonHandler.java:64)
        at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:140)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2503)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2492)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
14:36:59 INFO  [org.bimserver.ServiceInterface.download]: Reading from cache 3b74fa46fc4e7b389bb7e7e1d7cda0f5                              (NewDiskCacheManager.java:105)
14:36:59 ERROR [org.bimserver.ServiceInterface.download]:                                                                                  (LongAction.java:189)
java.lang.ClassCastException: org.bimserver.models.store.impl.ProjectImpl cannot be cast to org.bimserver.models.store.Revision
        at org.bimserver.longaction.LongStreamingDownloadAction.<init>(LongStreamingDownloadAction.java:90)
        at org.bimserver.webservices.impl.ServiceImpl.download(ServiceImpl.java:412)
        at org.bimserver.generated.ServiceInterfaceReflector1.callMethod(ServiceInterfaceReflector1.java)
        at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:213)
        at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:142)
        at org.bimserver.JsonHandler.execute(JsonHandler.java:64)
        at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:140)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2503)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2492)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

**Comment by rubendel** [comment]
So did you pass a ProjectId or a RevisionId to BIMserver?

**Comment by xuys0523** [comment]
Yes , I got them by below code ：
			List<SProject> newProject = client.getServiceInterface().getProjectsByName("t2");
			System.out.println(newProject.get(0).getOid()+":"+newProject.get(0).getLastRevisionId());
console result:
196609:131075

and I rerun the js using the two Ids , the error log :
15:58:06 ERROR [org.bimserver.ServiceInterface.download]:                                                                                  (LongStreamingDownloadAction.java:153)
java.lang.ClassCastException: org.bimserver.models.store.impl.ProjectImpl cannot be cast to org.bimserver.models.store.Revision
        at org.bimserver.longaction.LongStreamingDownloadAction.<init>(LongStreamingDownloadAction.java:90)
        at org.bimserver.webservices.impl.ServiceImpl.download(ServiceImpl.java:412)
        at org.bimserver.generated.ServiceInterfaceReflector1.callMethod(ServiceInterfaceReflector1.java)
        at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:213)
        at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:142)
        at org.bimserver.JsonHandler.execute(JsonHandler.java:64)
        at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:140)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2503)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2492)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
15:58:06 ERROR [org.bimserver.ServiceInterface.download]:                                                                                  (LongAction.java:189)
java.lang.ClassCastException: org.bimserver.models.store.impl.ProjectImpl cannot be cast to org.bimserver.models.store.Revision
        at org.bimserver.longaction.LongStreamingDownloadAction.<init>(LongStreamingDownloadAction.java:90)
        at org.bimserver.webservices.impl.ServiceImpl.download(ServiceImpl.java:412)
        at org.bimserver.generated.ServiceInterfaceReflector1.callMethod(ServiceInterfaceReflector1.java)
        at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:213)
        at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:142)
        at org.bimserver.JsonHandler.execute(JsonHandler.java:64)
        at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:140)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2503)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2492)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
15:58:06 INFO  [http-apr-8080-exec-9]: Start caching 3d4dbe9220e77bfcd1b7e17c8b359328                                   (NewDiskCacheManager.java:117)
15:58:06 INFO  [http-apr-8080-exec-9]: Renaming temp file 3d4dbe9220e77bfcd1b7e17c8b359328.__tmp to 3d4dbe9220e77bfcd1b7e17c8b359328 (NewDiskCacheOutputStream.java:59)
15:58:06 INFO  [http-apr-8080-exec-9]: Done caching 3d4dbe9220e77bfcd1b7e17c8b359328                                    (NewDiskCacheManager.java:150)
15:58:06 INFO  [http-apr-8080-exec-9]: Renaming temp file 3d4dbe9220e77bfcd1b7e17c8b359328.__tmp to 3d4dbe9220e77bfcd1b7e17c8b359328 (NewDiskCacheOutputStream.java:59)
15:58:06 ERROR [http-apr-8080-exec-9]:                                                                                  (DownloadServlet.java:283)
java.nio.file.NoSuchFileException: D:\apache-tomcat-8.0.26\webapps\ROOT\WEB-INF\cache\3d4dbe9220e77bfcd1b7e17c8b359328.__tmp
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:318)
        at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
        at java.nio.file.Files.move(Files.java:1395)
        at org.bimserver.cache.NewDiskCacheOutputStream.close(NewDiskCacheOutputStream.java:60)
        at org.bimserver.utils.MultiplexingOutputStream.close(MultiplexingOutputStream.java:48)
        at org.bimserver.plugins.serializers.CacheStoringStreamingSerializerDataSource.writeToOutputStream(CacheStoringStreamingSerializerDataSource.java:55)
        at org.bimserver.servlets.DownloadServlet.processDataSource(DownloadServlet.java:289)
        at org.bimserver.servlets.DownloadServlet.service(DownloadServlet.java:250)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:152)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2503)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2492)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

**Comment by wq8806** [comment]
have you solved this problem?  I meet the same with yours.
![qq 1111111](https://user-images.githubusercontent.com/21306443/26860648-87598f62-4b71-11e7-91d4-83415c9566b7.png)

**Comment by rubendel** [comment]
Please post a BIMserver version number, and don't post screenshots of log files
