### ISSUE TITLE
setting attributes with LowLevelInterface stops rendering

### ISSUE THREAD

**Issue by nelsonmunoz** [opensourceBIM/BIMserver#557]
BIMserver 1.5.76

Getting this error in every time I try to render a new revision in BIMvie.ws after successfully **setting** any attribute (tested using setWrapped(Integer/Long/Boolean/String)Attribute for NominalValue or the normal variety for other attributes such as Description).

3D area stays blank with a frozen "loading..." progress bar popup (a popup at top informs of having loaded the model and then dissapears). This invariably happens in ifc2x3 and ifc4, STEP and XML and both available renderers. I've even tested with a HelloWall ifc containing a single wall, to no avail. 

![image](https://cloud.githubusercontent.com/assets/1928970/26612718/fe39489c-458c-11e7-86d0-fe7eff2ad133.png).

I can successfully explore all the properties (including the one i set) of the new commit in BIMvie.ws. I can download the .ifc and view it in any viewers, disregarding some warnings.

```
21:58:38 ERROR [Streamer 34]:                                                                                  (BimServer.java:222) 
java.lang.NullPointerException: null
	at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer3.writeStart(BinaryGeometryMessagingStreamingSerializer3.java:195)
	at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer3.writeMessage(BinaryGeometryMessagingStreamingSerializer3.java:122)
	at org.bimserver.servlets.Streamer$1.run(Streamer.java:115)
21:58:59 ERROR [Streamer 35]:                                                                                  (BimServer.java:222) 
java.lang.NullPointerException: null
	at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer3.writeStart(BinaryGeometryMessagingStreamingSerializer3.java:195)
	at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer3.writeMessage(BinaryGeometryMessagingStreamingSerializer3.java:122)
	at org.bimserver.servlets.Streamer$1.run(Streamer.java:115)
´´´

**Comment by rubendel** [comment]
Cleaning up old issues, missed this one. Just to clarify since you refer to the IFC4x1 spec, are you working with an IFC4 project/model?

**Comment by rubendel** [comment]
The specified serializer does not exist anymore, so assuming this is not a problem anymore.
