### ISSUE TITLE
ServerException while importing ifc into OpenStudio

### ISSUE THREAD

**Issue by kubawin** [opensourceBIM/BIMserver#582]
Hi everyone.
I wanted to import rather simple .ifc file into OpenStudio, but while importing file I got the error _org.bimserver.shared.exceptions.ServerException_.
However, BIMsever is up and running, and after attempt to import I got following lines in the BIMsever console:
```04-07-2017 07:44:59 ERROR org.bimserver.webservices.impl.ServiceImpl - 
java.lang.NullPointerException
	at org.bimserver.webservices.impl.ServiceImpl.checkin(ServiceImpl.java:211)
	at org.bimserver.generated.ServiceInterfaceReflector1.callMethod(ServiceInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:218)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:122)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:60)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:99)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:717)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:568)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1112)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:479)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1046)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:459)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:281)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232)
	at org.eclipse.jetty.io.AbstractConnection$1.run(AbstractConnection.java:505)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
	at java.lang.Thread.run(Thread.java:745)```
Does anyone know where should I look for the cause of it?

**Comment by rubendel** [comment]
What version of BIMserver/plugins? Had a look at OpenStudio website but I don't see any mention of it being able to connect to BIMserver.

**Comment by rubendel** [comment]
The tutorial is for a 3 year old BIMserver release, so pretty sure that's the problem.

**Comment by kubawin** [comment]
I use BIMserver-13.4.-FINAL-2014-10-17 toghether with OpenStudio 2.1.0.
So you mean it's rather weak chance to get this up and running? I wanted to use OS as import/export from .ifc to .idf.

**Comment by rubendel** [comment]
Closing as this is probably fixed by now.
