### ISSUE TITLE
Checkin an IFC file gives "NoClassDefFoundError: org/bimserver/shared/ListCapableVirtualObject"

### ISSUE THREAD

**Issue by choumanb** [opensourceBIM/BIMserver#585]
Hi, 
 I deployed bimser under Tomcat on a Ubuntu machine, all goes well.
 Then I created a test project and selected IFC4, then I tried to checkin an IFC sample file (attached) to see if its 3D model working. 
 A popup window says that the file is "Uploading" that never closes, in the bimserver.log file,  I got the following error log about a missing class

2017-07-25 19:32:27,023 ERROR [http-nio-8080-exec-9] o.b.w.i.ServiceImpl [ServiceImpl.java:1020]
java.lang.NoClassDefFoundError: org/bimserver/shared/ListCapableVirtualObject
        at org.bimserver.ifc.step.deserializer.Ifc4StepStreamingDeserializerPlugin.createDeserializer(Ifc4StepStreamingDeserializerPlugin.java:31)
        at org.bimserver.webservices.impl.ServiceImpl.checkinInternal(ServiceImpl.java:1068)
        at org.bimserver.webservices.impl.ServiceImpl.checkinInitiatedInternal(ServiceImpl.java:1015)
        at org.bimserver.webservices.impl.ServiceImpl.checkinInitiated(ServiceImpl.java:1029)
        at org.bimserver.servlets.UploadServlet.service(UploadServlet.java:139)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:146)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:475)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:498)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:796)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1366)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.bimserver.shared.ListCapableVirtualObject
        at org.bimserver.plugins.classloaders.FileJarClassLoader.findClass(FileJarClassLoader.java:175)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

Under the github repository, I found that this class is under the PluginBase, however I could not find this class or its package (org.bimserver.shared) under any of the deployed jar files.

What step am I missing? Do I need to install a special plugin?

Thanks for your help.

[example.zip](https://github.com/opensourceBIM/BIMserver/files/1174269/example.zip)

**Comment by choumanb** [comment]
BIM Server version deployed is 1.5.76

Thanks,

**Comment by Jeffix73** [comment]
I deployed BIM Server 1.5.76 (which comes together with BIMViews module v.0.0.85) the same wayon an unbutu 14 machine and get exactly the same problem. Could you please advise what would be the most appropriate action to go ahead :
1) Wait for a fix and next release?

**Comment by zhenxuans** [comment]
got the same issue. 

BimServer 1.5.76

`2017-08-17 17:24:06,594 ERROR [qtp1340051218-33] o.b.w.i.ServiceImpl [ServiceImpl.java:1020] 
java.lang.NoClassDefFoundError: org/bimserver/shared/ListCapableVirtualObject
	at org.bimserver.ifc.step.deserializer.Ifc2x3tc1StepStreamingDeserializerPlugin.createDeserializer(Ifc2x3tc1StepStreamingDeserializerPlugin.java:31)
	at org.bimserver.webservices.impl.ServiceImpl.checkinInternal(ServiceImpl.java:1068)
	at org.bimserver.webservices.impl.ServiceImpl.checkinInitiatedInternal(ServiceImpl.java:1015)
	at org.bimserver.webservices.impl.ServiceImpl.checkinInitiated(ServiceImpl.java:1029)
	at org.bimserver.servlets.UploadServlet.service(UploadServlet.java:139)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:146)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:835)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:225)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.bimserver.shared.ListCapableVirtualObject
	at org.bimserver.plugins.classloaders.FileJarClassLoader.findClass(FileJarClassLoader.java:175)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 common frames omitted
2017-08-17 17:24:06,599 ERROR [qtp1340051218-33] o.b.s.UploadServlet [UploadServlet.java:150] 
org.bimserver.shared.exceptions.ServerException: org/bimserver/shared/ListCapableVirtualObject
	at org.bimserver.webservices.impl.ServiceImpl.checkinInitiatedInternal(ServiceImpl.java:1021)
	at org.bimserver.webservices.impl.ServiceImpl.checkinInitiated(ServiceImpl.java:1029)
	at org.bimserver.servlets.UploadServlet.service(UploadServlet.java:139)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:146)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:835)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:225)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/bimserver/shared/ListCapableVirtualObject
	at org.bimserver.ifc.step.deserializer.Ifc2x3tc1StepStreamingDeserializerPlugin.createDeserializer(Ifc2x3tc1StepStreamingDeserializerPlugin.java:31)
	at org.bimserver.webservices.impl.ServiceImpl.checkinInternal(ServiceImpl.java:1068)
	at org.bimserver.webservices.impl.ServiceImpl.checkinInitiatedInternal(ServiceImpl.java:1015)
	... 29 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.bimserver.shared.ListCapableVirtualObject
	at org.bimserver.plugins.classloaders.FileJarClassLoader.findClass(FileJarClassLoader.java:175)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 common frames omitted
`

**Comment by rubendel** [comment]
I think there is some sort of version mismatch. The "ListCapableVirtualObject" class is relatively new.
There is a new build available that should fix this problem: https://github.com/opensourceBIM/BIMserver/releases/tag/parent-1.5.81
