### ISSUE TITLE
import Schependomlaan model ERROR

### ISSUE THREAD

**Issue by monadgon** [opensourceBIM/BIMserver#588]
BIMServer: bimserverjar-1.5.76.jar
OS: Windows 10 64bit
JAVA: 1.8.0_44 (x86_64)
Problem: 
URL is http://localhost:8082/apps/bimviews/?page=Projects
I clicked the "automatically" link, and my bimServer returned the below ERROR.

For a demo of BIMvie.ws/BIMserver, you can now import the freely available Schependomlaan model automatically. 

my web browser task is the below:
Checking in: IFC Schependomlaan.ifc

ERROR:
ERROR [org.bimserver.ServiceInterface.checkinFromUrl]:                                                                                  (ServiceImpl.java:1171) 
java.lang.NoClassDefFoundError: org/bimserver/shared/ListCapableVirtualObject
	at org.bimserver.ifc.step.deserializer.Ifc2x3tc1StepStreamingDeserializerPlugin.createDeserializer(Ifc2x3tc1StepStreamingDeserializerPlugin.java:31)
	at org.bimserver.webservices.impl.ServiceImpl.checkinInternal(ServiceImpl.java:1068)
	at org.bimserver.webservices.impl.ServiceImpl.checkinFromUrl(ServiceImpl.java:1144)
	at org.bimserver.generated.ServiceInterfaceReflector1.callMethod(ServiceInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:213)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:142)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:64)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:138)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:835)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:225)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.bimserver.shared.ListCapableVirtualObject
	at org.bimserver.plugins.classloaders.FileJarClassLoader.findClass(FileJarClassLoader.java:175)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 35 common frames omitted

**Comment by rubendel** [comment]
Seems to have nothing to do with Schependomlaan, any checkin on this server would generate this error. See https://github.com/opensourceBIM/BIMserver/issues/585
