### ISSUE TITLE
IFC version hardcoded in GetGeometryInfoDatabaseAction

### ISSUE THREAD

**Issue by hlg** [opensourceBIM/BIMserver#646]
IFC2x3 is hardcoded in `GetGeometryInfoDatabaseAction`, such that no geometry can be retrieved through the `ServiceInterface#getGeometryInfo` method for IFC4.  I guess this should be changed similar to how it is done in `BinaryGeometrySerializer`.

**Comment by rubendel** [comment]
Fixed it, didn't test though

**Comment by hlg** [comment]
I can't test because I am getting a null pointer when I try to check in IFC4:

```
2017-11-09 12:12:17,131 ERROR [LongStreamingCheckinAction] o.b.l.LongAction [LongAction.java:189]
org.bimserver.shared.exceptions.UserException: null
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:397)
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:88)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:727)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:704)
        at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:63)
        at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:286)
        ... 6 common frames omitted
```

I do not know exactly when this error was introduced. The last version that I am really sure it had no issues with IFC4 checkin was 1.5.88, although I think I tested later versions with IFC4 as well.

**Comment by hlg** [comment]
I have removed the IFC2x3 dependencies from the client library as well, but only tested with 1.5.85 so far. I will send you a pull request once I have tested with the latest snapshot version.

**Comment by rubendel** [comment]
Hope our efforts didn't cross each other, I just checked in a bunch of changes to make IFC4 work again in terms of generating geometry.

**Comment by hlg** [comment]
Tested with 1.5.91.
