### ISSUE TITLE
Can't render model with bimsurfer

### ISSUE THREAD

**Issue by lzhoubimfoo** [opensourceBIM/BIMserver#648]
Hi,
i upload .ifc file by Bimvie.ws and it can show in 3D viewer. But when i use bimsurfer, it has an error.
This is the log:
2017-11-09 16:22:38,264 ERROR [org.bimserver.ServiceInterface.download] o.b.l.LongAction [LongAction.java:189] 
org.bimserver.database.queries.om.QueryException: "oids"[0] must be of type number ({"_i":67416,"_t":"GeometryInfo"})
	at org.bimserver.database.queries.om.JsonQueryObjectModelConverter.parseJsonQuery(JsonQueryObjectModelConverter.java:438)
	at org.bimserver.database.queries.om.JsonQueryObjectModelConverter.parseJson(JsonQueryObjectModelConverter.java:184)
	at org.bimserver.longaction.LongStreamingDownloadAction.<init>(LongStreamingDownloadAction.java:109)
	at org.bimserver.webservices.impl.ServiceImpl.download(ServiceImpl.java:416)
	at org.bimserver.generated.ServiceInterfaceReflector1.callMethod(ServiceInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:213)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:148)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:64)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:140)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2521)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2510)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

It is OK in bimvie.we

**Comment by lzhoubimfoo** [comment]
bimserver version: 1.5.90

By the way, i found an error in https://github.com/opensourceBIM/BIMsurfer/blob/master/bimsurfer/src/BimServerModel.js
line 172: var p = instance_by_id[ps[i]];
the param 'p' will be undefined, i guess may be it is :  var p = instance_by_id[ps[i]._i]; ?
and it is the same in line 173

**Comment by rubendel** [comment]
Which version of BimServerJavaScriptApi are you using?

**Comment by rubendel** [comment]
Nevermind, V2 had to be changed because of updated JSON format, indeed the "_i" had to be added.

**Comment by lzhoubimfoo** [comment]
Thanks for reply, I update the api to the latest version and now it is OK.
