### ISSUE TITLE
bimserverjar-1.5.90.jar and Installing ifcopenshellplugin...

### ISSUE THREAD

**Issue by monadgon** [opensourceBIM/BIMserver#651]
The installing progress in the web browser:

![image](https://user-images.githubusercontent.com/511164/32705691-367c339a-c85a-11e7-9337-54632931d89a.png)

The bimserverjar-1.5.90.jar ERROR:
[PluginInterface.getPluginBundle] DEBUG org.apache.http.wire -  << "[0xb9][0xb0]x?j[0xd5][0x...[0Exception in thread "Sysin reader" java.lang.OutOfMemoryError: Java heap space
	at javax.swing.text.GapContent.allocateArray(Unknown Source)
	at javax.swing.text.GapVector.resize(Unknown Source)
	at javax.swing.text.GapVector.shiftEnd(Unknown Source)
	at javax.swing.text.GapContent.shiftEnd(Unknown Source)
	at javax.swing.text.GapVector.open(Unknown Source)
	at javax.swing.text.GapVector.replace(Unknown Source)
	at javax.swing.text.GapContent.insertString(Unknown Source)
	at javax.swing.text.AbstractDocument.handleInsertString(Unknown Source)
	at javax.swing.text.AbstractDocument.insertString(Unknown Source)
	at javax.swing.text.PlainDocument.insertString(Unknown Source)
	at javax.swing.JTextArea.append(Unknown Source)
	at org.bimserver.starter.Starter$1.write(Starter.java:116)
	at java.io.PrintStream.write(Unknown Source)
	at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(Unknown Source)

And my settings:
![image](https://user-images.githubusercontent.com/511164/32705741-909929be-c85a-11e7-9b5f-4e3af0eb6be9.png)

In the same setting, the old version "bimserverjar-1.5.88.jar" is worked perfectly.
Is there  any settings for "bimserverjar-1.5.90.jar"?

**Comment by kubawin** [comment]
I have exactly the same problem... Did anyone managed to install the BimServer from last distribution?

**Comment by tldddd** [comment]
Same problem for me as well on 1.5.90, it gets stuck on installing IfcOpenShell and never sets up properly, even after it's downloaded all the required files from Maven.

**Comment by rubendel** [comment]
This version was logging on a debug level, hence the sheer amount of log entries. This caused the JAR runner to run out of memory, not a problem in the latest builds anymore.
