### ISSUE TITLE
BimserverDatabaseException after updating from 1.5.88 to 1.5.92 

### ISSUE THREAD

**Issue by kurb70** [opensourceBIM/BIMserver#663]
I updated from 1.5.88 to 1.5.92.

In my DB there is one project with several revisions.

When I'm running version 1.5.92 and launch the webbrowser I get an `org.bimserver.BimserverDatabaseException`

```
No expanding necessary
OS: Mac OS X
Main class: org.bimserver.JarBimServer

Commands:
java
-Xmx8589m
-Xss1024k
-Dhttp.proxyHost=
-Dhttp.proxyPort=1080
-Dorg.apache.cxf.Logger=org.apache.cxf.common.logging.Slf4jLogger
-classpath
.:lib:lib/javax-websocket-server-impl-9.3.7.v20160115.jar:lib/javax.ws.rs-api-2.1-m02.jar:lib/websocket-common-9.3.7.v20160115.jar:lib/quartz-2.3.0.jar:lib/aether-connector-basic-1.0.2.v20150114.jar:lib/cxf-rt-ws-policy-3.1.11.jar:lib/xmlbeans-2.6.0.jar:lib/aether-api-1.0.2.v20150114.jar:lib/commons-logging-1.2.jar:lib/cxf-core-3.1.11.jar:lib/javax.websocket-api-1.1.jar:lib/je-7.4.5.jar:lib/plexus-utils-3.0.22.jar:lib/guava-19.0.jar:lib/jetty-util-9.3.7.v20160115.jar:lib/plexus-interpolation-1.21.jar:lib/activation-1.1.jar:lib/slf4j-api-1.7.22.jar:lib/aether-util-1.0.2.v20150114.jar:lib/maven-model-3.3.9.jar:lib/commons-cli-1.3.1.jar:lib/org.apache.oltu.oauth2.common-1.0.2.jar:lib/aopalliance-1.0.jar:lib/org.eclipse.core.resources-3.8.101.v20130717-0806.jar:lib/maven-settings-3.3.9.jar:lib/javax.json-1.0.4.jar:lib/protobuf-java-2.6.1.jar:lib/jersey-common-2.26-b01.jar:lib/logback-core-1.1.9.jar:lib/junit-4.10.jar:lib/websocket-server-9.3.7.v20160115.jar:lib/jetty-http-9.3.7.v20160115.jar:lib/jetty-xml-9.3.7.v20160115.jar:lib/maven-model-builder-3.3.9.jar:lib/org.apache.oltu.oauth2.dynamicreg.server-1.0.2.jar:lib/org.eclipse.emf.ecore-2.11.1-v20150805-0538.jar:lib/websocket-servlet-9.3.7.v20160115.jar:lib/jackson-annotations-2.8.0.jar:lib/json-20140107.jar:lib/plexus-cipher-1.4.jar:lib/jetty-plus-9.3.7.v20160115.jar:lib/antlr-runtime-3.5.2.jar:lib/websocket-api-9.3.7.v20160115.jar:lib/javassist-3.12.1.GA.jar:lib/xmlschema-core-2.2.1.jar:lib/bcf-0.0.13.jar:lib/plexus-sec-dispatcher-1.3.jar:lib/cdi-api-1.0.jar:lib/commons-collections-20040616.jar:lib/javax.servlet-api-3.1.0.jar:lib/jetty-server-9.3.7.v20160115.jar:lib/maven-core-3.3.9.jar:lib/rome-utils-1.7.1.jar:lib/aether-transport-file-1.0.2.v20150114.jar:lib/antlr-complete-3.5.2.jar:lib/jackson-databind-2.8.9.jar:lib/validation-api-1.1.0.Final.jar:lib/ST4-4.0.8.jar:lib/websocket-client-9.3.7.v20160115.jar:lib/hk2-api-2.5.0-b31.jar:lib/guice-4.0-no_aop.jar:lib/jackson-core-2.8.9.jar:lib/jersey-container-servlet-core-2.26-b01.jar:lib/jettison-1.3.8.jar:lib/cors-filter-2.5.jar:lib/wsdl4j-1.6.3.jar:lib/aether-impl-1.0.2.v20150114.jar:lib/javax.annotation-api-1.2.jar:lib/asm-commons-5.0.1.jar:lib/maven-builder-support-3.3.9.jar:lib/jaxb-core-2.2.11.jar:lib/javax-websocket-client-impl-9.3.7.v20160115.jar:lib/commons-codec-1.9.jar:lib/java-getopt-1.0.13.jar:lib/jersey-client-2.26-b01.jar:lib/org.eclipse.emf.ecore.xmi-2.11.1-v20150805-0538.jar:lib/org.eclipse.emf.codegen-2.11.0-v20150806-0404.jar:lib/jersey-server-2.26-b01.jar:lib/org.apache.oltu.oauth2.client-1.0.2.jar:lib/contenttype-3.4.200-v20140207-1251.jar:lib/httpclient-4.5.1.jar:lib/jersey-guava-2.26-b01.jar:lib/jcl-over-slf4j-1.6.2.jar:lib/xml-resolver-1.2.jar:lib/org.apache.oltu.oauth2.resourceserver-1.0.2.jar:lib/osgi-resource-locator-1.0.1.jar:lib/stax2-api-3.1.4.jar:lib/c3p0-0.9.5.2.jar:lib/velocity-1.7.jar:lib/hk2-utils-2.5.0-b31.jar:lib/javassist-3.20.0-GA.jar:lib/common-3.6.200-v20130402-1505.jar:lib/javax.mail-1.5.6.jar:lib/fastutil-7.0.13.jar:lib/commons-fileupload-1.3.2.jar:lib/jetty-io-9.3.7.v20160115.jar:lib/registry-3.5.400-v20140428-1507.jar:lib/jetty-security-9.3.7.v20160115.jar:lib/jul-to-slf4j-1.7.22.jar:lib/buildingsmartlibrary-1.0.11.jar:lib/org.apache.oltu.oauth2.dynamicreg.common-1.0.2.jar:lib/javax.inject-2.5.0-b31.jar:lib/org.apache.oltu.oauth2.authzserver-1.0.2.jar:lib/commons-io-2.2.jar:lib/java-property-utils-1.9.1.jar:lib/asm-5.0.1.jar:lib/maven-settings-builder-3.3.9.jar:lib/pluginbase-1.5.92.jar:lib/hamcrest-core-1.1.jar:lib/jaxb-impl-2.2.11.jar:lib/jetty-annotations-9.3.7.v20160115.jar:lib/rome-1.7.1.jar:lib/cxf-rt-databinding-jaxb-3.1.11.jar:lib/jobs-3.6.0-v20140424-0053.jar:lib/jersey-container-servlet-2.26-b01.jar:lib/shared-1.5.92.jar:lib/jetty-servlet-9.3.7.v20160115.jar:lib/HikariCP-java6-2.3.13.jar:lib/stringtemplate-3.2.1.jar:lib/aether-spi-1.0.2.v20150114.jar:lib/org.eclipse.sisu.inject-0.3.2.jar:lib/maven-plugin-api-3.3.9.jar:lib/cxf-rt-bindings-soap-3.1.11.jar:lib/org.eclipse.jdt.core-3.9.1.v20130905-0837.jar:lib/cxf-rt-wsdl-3.1.11.jar:lib/neethi-3.0.3.jar:lib/antlr-3.5.2.jar:lib/osgi-3.10.0-v20140606-1445.jar:lib/org.apache.oltu.oauth2.dynamicreg.client-1.0.2.jar:lib/plexus-component-annotations-1.6.jar:lib/stax-api-1.0.1.jar:lib/runtime-3.9.100-v20131218-1515.jar:lib/commons-lang-2.4.jar:lib/maven-repository-metadata-3.3.9.jar:lib/hk2-locator-2.5.0-b31.jar:lib/bimserver-1.5.92.jar:lib/jersey-media-jaxb-2.26-b01.jar:lib/aether-transport-http-1.0.2.v20150114.jar:lib/aopalliance-repackaged-2.5.0-b31.jar:lib/org.eclipse.emf.codegen.ecore-2.11.0-v20150806-0404.jar:lib/gson-2.5.jar:lib/antlr-2.7.7.jar:lib/cxf-rt-ws-addr-3.1.11.jar:lib/cxf-rt-bindings-xml-3.1.11.jar:lib/jetty-webapp-9.3.7.v20160115.jar:lib/jdom2-2.0.6.jar:lib/plexus-classworlds-2.5.2.jar:lib/asm-tree-5.0.1.jar:lib/jetty-jndi-9.3.7.v20160115.jar:lib/preferences-3.5.200-v20140224-1527.jar:lib/org.eclipse.sisu.plexus-0.3.2.jar:lib/gunit-3.5.2.jar:lib/httpcore-4.4.3.jar:lib/cxf-rt-transports-http-3.1.11.jar:lib/cxf-rt-frontend-simple-3.1.11.jar:lib/bimserverclientlib-1.5.92.jar:lib/commons-lang3-3.4.jar:lib/javax.inject-1.jar:lib/woodstox-core-asl-4.4.1.jar:lib/maven-aether-provider-3.3.9.jar:lib/httpmime-4.5.1.jar:lib/cxf-rt-frontend-jaxws-3.1.11.jar:lib/mchange-commons-java-0.2.11.jar:lib/jsr250-api-1.0.jar:lib/maven-artifact-3.3.9.jar:lib/app-1.3.200-v20130910-1609.jar:lib/org.eclipse.emf.common-2.11.0-v20150805-0538.jar:lib/cxf-rt-javascript-3.1.11.jar:lib/logback-classic-1.1.9.jar:lib/commons-pool2-2.4.2.jar
org.bimserver.JarBimServer
address=localhost
port=8082
homedir=/Users/kuba/dev/projects-bim/bimserver/home
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
16:57:40 INFO  [main]: Starting BIMserver                                                               (BimServer.java:225) 
16:57:40 INFO  [main]: Using "/Users/kuba/dev/projects-bim/bimserver/home" as homedir                   (BimServer.java:227) 
16:57:42 INFO  [main]: Adding ~/.m2 as repository                                                       (MavenPluginRepository.java:80) 
Logging to /Users/kuba/dev/projects-bim/bimserver/home/logs/bimserver.log
16:57:42 INFO  [main]: Version: 1.5.92                                                                  (BimServer.java:318) 
16:57:45 INFO  [main]: Using "Users/kuba/dev/projects-bim/bimserver/bimserverjar-1.5.92/./emailtemplates/" as template dir (TemplateEngine.java:64) 
16:57:45 INFO  [main]: Non-empty database directory found "/Users/kuba/dev/projects-bim/bimserver/home/database" (BerkeleyKeyValueStore.java:85) 
16:57:45 INFO  [main]: Adding ~/.m2/repository as repository                                            (MavenPluginRepository.java:80) 
16:57:46 INFO  [main]: Changing server state to MIGRATION_REQUIRED                                      (ServerInfoManager.java:96) 

...

16:57:55 INFO  [main]: Server started successfully                                                      (JarBimServer.java:143) 
16:58:18 ERROR [qtp893835279-32]:                                                                                  (ServerSettingsCache.java:54) 
org.bimserver.BimserverDatabaseException: Reading ServerSettings(65543).emailSenderAddress
	at org.bimserver.database.DatabaseSession.convertByteArrayToObject(DatabaseSession.java:414)
	at org.bimserver.database.DatabaseSession.getMap(DatabaseSession.java:1161)
	at org.bimserver.database.DatabaseSession.getMap(DatabaseSession.java:1208)
	at org.bimserver.database.DatabaseSession.getAllOfType(DatabaseSession.java:946)
	at org.bimserver.database.DatabaseSession.getSingle(DatabaseSession.java:2065)
	at org.bimserver.ServerSettingsCache.updateCache(ServerSettingsCache.java:45)
	at org.bimserver.ServerSettingsCache.getServerSettings(ServerSettingsCache.java:72)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:110)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:835)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:225)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 5757
	at java.lang.String.checkBounds(String.java:385)
	at java.lang.String.<init>(String.java:462)
	at org.bimserver.utils.BinUtils.readString(BinUtils.java:181)
	at org.bimserver.database.DatabaseSession.readPrimitiveValue(DatabaseSession.java:1595)
	at org.bimserver.database.DatabaseSession.convertByteArrayToObject(DatabaseSession.java:403)
	... 33 common frames omitted
16:58:18 ERROR [qtp893835279-32]:                                                                                  (RootServlet.java:209) 
java.lang.NullPointerException: null
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:110)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:835)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:225)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by rubendel** [comment]
Sorry, not all database changes can be migrated, goal is to make production releases upgradable as long as only the minor version changes. That's not the case for 1.5 as it is not released yet.

**Comment by kurb70** [comment]
I see. Thank you.
