### ISSUE TITLE
Queries involving name, guid, classification fail for IFC4

### ISSUE THREAD

**Issue by hlg** [opensourceBIM/BIMserver#667]
When running queries that involve `name`, `guid`, or `classification` on IFC4 models, they fail with the following exception:

~~~
Caused by: java.lang.UnsupportedOperationException: null
        at org.bimserver.database.queries.QueryNamesAndTypesStackFrame.getOidOfGuidAlternative(QueryNamesAndTypesStackFrame.java:95)
        at org.bimserver.database.queries.QueryNamesAndTypesStackFrame.<init>(QueryNamesAndTypesStackFrame.java:60)
        at org.bimserver.database.queries.QueryPartStackFrame.process(QueryPartStackFrame.java:124)
        at org.bimserver.database.queries.QueryObjectProvider.next(QueryObjectProvider.java:143)
        ... 33 common frames omitted
~~~

This failure is due to the missing `singleindex` annotation of the queried attributes. These annotations are added to the respective IFC2x3 elements in migrations [Step0022.java](https://github.com/opensourceBIM/BIMserver/blob/master/BimServer/src/org/bimserver/database/migrations/steps/Step0022.java) and [Step0027.java](https://github.com/opensourceBIM/BIMserver/blob/master/BimServer/src/org/bimserver/database/migrations/steps/Step0022.java). For IFC4 similar annotations would be necessary. Be aware that for `IfcClassificationReference` the attribute `ItemReference` was renamed to `Identifier` in IFC4. This can be accessed for both schemas through its position, see also f6c018247ef9014cd187ac119e3071b69ac2d740.

**Comment by rubendel** [comment]
Thanks for the clear report! Has been fixed in https://github.com/opensourceBIM/BIMserver/commit/2e4c74c94dfc47fd585b8e036e1d64285f7871d8. There are probably more places where IFC4 support lacks, keep em coming @hlg :)

**Comment by hlg** [comment]
Tested for name and classification queries as well.
