### ISSUE TITLE
Commit transaction failed

### ISSUE THREAD

**Issue by letis33** [opensourceBIM/BIMserver#676]
I have an exception when I try to commit a transaction.
=> bimserverwar-1.5.92

ie : modify description of an object from app console.

1) start transaction 
> {
  "token": "40ffb48ef8099f08b22738b01a22b5f38010e7dcbbe74b8b86cd282bd9407f985f34ebe3dbcccaebb06dba2231982256",
  "request": {
    "interface": "LowLevelInterface", 
    "method": "startTransaction", 
    "parameters": {
      "poid": 5898241
    }
  }
}
> 
=> OK (tid = 1)

2) change description
>{
  "token": "40ffb48ef8099f08b22738b01a22b5f38010e7dcbbe74b8b86cd282bd9407f985f34ebe3dbcccaebb06dba2231982256",
  "request": {
    "interface": "LowLevelInterface", 
    "method": "setStringAttribute", 
    "parameters": {
      "tid": 1,
      "oid": 294453589,
      "attributeName": "Description",
      "value": "New description"
    }
  }
}
> 
=> OK

3) commit transaction
> {
  "token": "40ffb48ef8099f08b22738b01a22b5f38010e7dcbbe74b8b86cd282bd9407f985f34ebe3dbcccaebb06dba2231982256",
  "request": {
    "interface": "LowLevelInterface", 
    "method": "commitTransaction", 
    "parameters": {
      "tid": 1,
      "comment": "New comment"
    }
  }
}
=> Failed
> 2018-01-02 16:18:52,050 INFO [http-nio-8181-exec-6] o.b.JsonHandler [JsonHandler.java:72] {"token":"40ffb48ef8099f08b22738b01a22b5f38010e7dcbbe74b8b86cd282bd9407f985f34ebe3dbcccaebb06dba2231982256","request":{"interface":"LowLevelInterface","method":"commitTransaction","parameters":{"tid":1,"comment":"New comment"}}}
2018-01-02 16:18:52,050 INFO [http-nio-8181-exec-6] o.b.JsonHandler [JsonHandler.java:73] 
java.lang.NullPointerException: null
	at org.bimserver.database.actions.CommitTransactionDatabaseAction.execute(CommitTransactionDatabaseAction.java:220)
	at org.bimserver.database.actions.CommitTransactionDatabaseAction.execute(CommitTransactionDatabaseAction.java:64)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:727)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:719)
	at org.bimserver.webservices.impl.LowLevelServiceImpl.commitTransaction(LowLevelServiceImpl.java:109)
	at org.bimserver.generated.LowLevelInterfaceReflector1.callMethod(LowLevelInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:213)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:148)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:64)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:140)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
2018-01-02 16:18:52,051 ERROR [http-nio-8181-exec-6] o.b.JsonHandler [JsonHandler.java:178] 
java.lang.NullPointerException: null
	at org.bimserver.database.actions.CommitTransactionDatabaseAction.execute(CommitTransactionDatabaseAction.java:220)
	at org.bimserver.database.actions.CommitTransactionDatabaseAction.execute(CommitTransactionDatabaseAction.java:64)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:727)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:719)
	at org.bimserver.webservices.impl.LowLevelServiceImpl.commitTransaction(LowLevelServiceImpl.java:109)
	at org.bimserver.generated.LowLevelInterfaceReflector1.callMethod(LowLevelInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:213)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:148)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:64)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:140)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

**Comment by rubendel** [comment]
This should be fixed in the mentioned commit.

**Comment by letis33** [comment]
It works again.  
Thank you very much !!!
