### ISSUE TITLE
bimserverjar-1.5.94.jar not working

### ISSUE THREAD

**Issue by letis33** [opensourceBIM/BIMserver#683]
Double click on bimserverjar-1.5.94.jar not working :

![image](https://user-images.githubusercontent.com/34182310/34914916-a680251e-f91c-11e7-830f-c733a2f4a380.png)

I think that all the libraries are not available when running the JAR.

**Comment by hlg** [comment]
I can confirm this. Here is the stacktrace:

    Exception in thread "main" java.lang.NoClassDefFoundError: org/bimserver/plugins/ResourceFetcher
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
    Caused by: java.lang.ClassNotFoundException: org.bimserver.plugins.ResourceFetcher
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

**Comment by rubendel** [comment]
I can also reproduce, but I also tried 1.5.92 (which was working before) and that one is not working either. I recently installed Java 9, I suspect that's the issue. Any chance you have installed Java 9 recently too?

**Comment by hlg** [comment]
No, just double-checked. I still use Java 8, no problems with 1.5.92.

**Comment by rubendel** [comment]
Ok thanks, Java 9 does cause a different error on all versions, just pasting it here for future reference:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at org.bimserver.starter.Starter.<init>(Starter.java:68)
        at org.bimserver.starter.Starter.main(Starter.java:85)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more
```

I think this error in 1.5.94 was caused by something I tried a while ago (adding another build), reverted that change, a new build is underway.
