### ISSUE TITLE
Streaming plugin serializers not initialized with plugin configuration

### ISSUE THREAD

**Issue by hlg** [opensourceBIM/BIMserver#693]
In a custom plugin serializer, I get a NullPointerException when accessing the plugin configuration.

```
[org.bimserver.ServiceInterface.download] ERROR org.bimserver.longaction.LongAction - java.lang.NullPointerException: null
        at sg.edu.nus.CustomSerializerPlugin.createSerializer(CustomSerializerPlugin.java:18)
        at org.bimserver.longaction.LongStreamingDownloadAction.<init>(LongStreamingDownloadAction.java:141)
        at org.bimserver.webservices.impl.ServiceImpl.download(ServiceImpl.java:416)
        at org.bimserver.generated.ServiceInterfaceReflector1.callMethod(ServiceInterfaceReflector1.java)
        at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:213)
        at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:148)
        at org.bimserver.JsonHandler.execute(JsonHandler.java:64)
        at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:140)
       ....
```

There you go: https://github.com/opensourceBIM/BIMserver/blob/2f6175a48024d145dd4555e0f95dcdb44094e3ad/BimServer/src/org/bimserver/longaction/LongStreamingDownloadAction.java#L141

**Comment by hlg** [comment]
Works as expected, thank you.
