### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by epeter-** [opensourceBIM/BIMserver#712]
today i tried to reinstall version 1.5.95
everything installs from war (debian 9, tomcat 9)
till the errormessage shows:

Installing ifcopenshellplugin...
		No executable found for the linux platorm
		Setup aborted

logfile: ......
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
org.bimserver.shared.exceptions.PluginException: No executable found for the linux platorm
        at org.ifcopenshell.IfcOpenShellEnginePlugin.init(IfcOpenShellEnginePlugin.java:139)
        at org.bimserver.plugins.PluginManager.loadPlugin(PluginManager.java:1404)
        at org.bimserver.plugins.PluginManager.install(PluginManager.java:1513)

**Comment by rubendel** [comment]
I have no idea why this would happen on a system that was working before. Can you reproduce this multiple times?

**Comment by epeter-** [comment]
ruben, sorry took a time to reinstall everything.
first of all i could not install the plugin by any means again. 
so bimserver never ran again.
what did i do?
i provided an out of the box system (as close as possible)
installed a brand new version of debian9 + java8 + tomcat9
setup server.xml for bimserver
started bimserver
installed till the openshellplugin

this is the relevant entries in the logfile:

....
2018-03-09 14:29:38,249 INFO [PluginInterface.installPluginBundle] o.b.d.a.Insta
llPluginBundle [InstallPluginBundle.java:70] 0.0.105
2018-03-09 14:31:34,591 INFO [PluginInterface.installPluginBundle] o.b.d.a.Insta
llPluginBundle [InstallPluginBundle.java:57] Installing plugin central (http://c
entral.maven.org/maven2, default, releases+snapshots) org.opensourcebim.ifcopens
hellplugin.0.5.25
2018-03-09 14:31:34,592 INFO [PluginInterface.installPluginBundle] o.b.d.a.Insta
llPluginBundle [InstallPluginBundle.java:65] central (http://central.maven.org/m
aven2, default, releases+snapshots)
2018-03-09 14:31:34,592 INFO [PluginInterface.installPluginBundle] o.b.d.a.Insta
llPluginBundle [InstallPluginBundle.java:70] 0.5.25
2018-03-09 14:31:35,151 ERROR [PluginInterface.installPluginBundle] o.b.p.Plugin
Manager [PluginManager.java:1416]
org.bimserver.shared.exceptions.PluginException: No executable found for the lin
ux platorm
        at org.ifcopenshell.IfcOpenShellEnginePlugin.init(IfcOpenShellEnginePlug
in.java:139)
        at org.bimserver.plugins.PluginManager.loadPlugin(PluginManager.java:140
4)
        at org.bimserver.plugins.PluginManager.install(PluginManager.java:1513)
        at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPlu
ginBundle.java:73)
        at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPlu
ginBundle.java:35)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(Databas
eSession.java:726)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(Databas
eSession.java:718)
        at org.bimserver.webservices.impl.PluginServiceImpl.installPluginBundle(
PluginServiceImpl.java:1472)
        at org.bimserver.generated.PluginInterfaceReflector1.callMethod(PluginIn
terfaceReflector1.java)
        at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:213)
        at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:148)
        at org.bimserver.JsonHandler.execute(JsonHandler.java:64)
        at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:409)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1376)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
2018-03-09 14:31:35,152 ERROR [PluginInterface.installPluginBundle] o.b.d.a.InstallPluginBundle [InstallPluginBundle.java:75]
org.bimserver.shared.exceptions.PluginException: No executable found for the linux platorm
        at org.ifcopenshell.IfcOpenShellEnginePlugin.init(IfcOpenShellEnginePlugin.java:139)
        at org.bimserver.plugins.PluginManager.loadPlugin(PluginManager.java:1404)
        at org.bimserver.plugins.PluginManager.install(PluginManager.java:1513)
        at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPluginBundle.java:73)
        at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPluginBundle.java:35)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:726)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:718)
        at org.bimserver.webservices.impl.PluginServiceImpl.installPluginBundle(PluginServiceImpl.java:1472)
        at org.bimserver.generated.PluginInterfaceReflector1.callMethod(PluginInterfaceReflector1.java)
        at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:213)
        at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:148)
        at org.bimserver.JsonHandler.execute(JsonHandler.java:64)
        at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
