### ISSUE TITLE
Error:Debug LocalDevBimServerStarter

### ISSUE THREAD

**Issue by Zhouyiduo** [opensourceBIM/BIMserver#717]
Logging to D:\MyDir\Unity_Manage\Project\BimPlatform\OpenBIMServer\src\BIMserver-parent-1.5.92\BimServerJar\home\logs\bimserver.log
19:22:38 WARN  [main]: ..\BimServer                                                                     (ResourceFetcher.java:57) 
19:22:38 WARN  [main]: ..\BimServerClientLib\src\org\bimserver\client\protocolbuffers                   (ResourceFetcher.java:57) 
19:22:38 WARN  [main]: ..\BimServer                                                                     (ResourceFetcher.java:57) 
19:22:38 WARN  [main]: ..\BimServerClientLib\src\org\bimserver\client\protocolbuffers                   (ResourceFetcher.java:57) 
19:22:38 WARN  [main]: ..\BimServer                                                                     (ResourceFetcher.java:57) 
19:22:38 WARN  [main]: ..\BimServerClientLib\src\org\bimserver\client\protocolbuffers                   (ResourceFetcher.java:57) 
19:22:38 WARN  [main]: ..\BimServer                                                                     (ResourceFetcher.java:57) 
19:22:38 INFO  [main]: Starting BIMserver                                                               (BimServer.java:225) 
19:22:38 INFO  [main]: Using "home" as homedir                                                          (BimServer.java:227) 
19:22:50 ERROR [main]:                                                                                  (BimServer.java:284) 
java.lang.NoSuchMethodError: org.eclipse.jdt.internal.compiler.impl.CompilerOptions.versionToJdkLevel(Ljava/lang/Object;)J
	at org.eclipse.jdt.core.dom.ASTConverter.<init>(ASTConverter.java:82)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.convert(CompilationUnitResolver.java:281)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1207)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:807)
	at org.bimserver.shared.meta.SService.extractJavaDoc(SService.java:80)
	at org.bimserver.shared.meta.SService.processClass(SService.java:73)
	at org.bimserver.shared.meta.SService.processClass(SService.java:70)
	at org.bimserver.shared.meta.SService.init(SService.java:159)
	at org.bimserver.interfaces.SServiceInterfaceService.init(SServiceInterfaceService.java:567)
	at org.bimserver.shared.meta.SServicesMap.initialize(SServicesMap.java:255)
	at org.bimserver.shared.InterfaceList.createSServicesMap(InterfaceList.java:68)
	at org.bimserver.BimServer.<init>(BimServer.java:232)
	at org.bimserver.LocalDevBimServerStarter.start(LocalDevBimServerStarter.java:77)
	at org.bimserver.LocalDevBimServerStarter.main(LocalDevBimServerStarter.java:52)

ASTParser parser = ASTParser.newParser(AST.JLS4);
parser.setSource(sourceCodeFetcher.get(clazz).toCharArray());
parser.setKind(ASTParser.K_COMPILATION_UNIT);
final CompilationUnit cu = (CompilationUnit) parser.createAST(null);

This is ok in other Project that I create.

**Comment by Zhouyiduo** [comment]
![default](https://user-images.githubusercontent.com/29697734/36941177-3430aa02-1f90-11e8-80b7-6c219c17ad5b.png)

**Comment by rubendel** [comment]
As you noted yourself, there seems to be a conflict of version. The included version in BIMserver is of a different version than the one introduced by yourself in your own application. Doesn't seem to be a BIMserver issue.
