### ISSUE TITLE
Connect to Local BIM-server from a java application

### ISSUE THREAD

**Issue by nazmul-prince** [opensourceBIM/BIMserver#73]
Hello, 
I'm a newbie in bimserver related issues. I have set up a bimserver ("http://localhost:8082") according to the quick setup guide from the wiki. Now I'm trying to connect the bimserver from a simple java application wher the code snippet is---

```
  BimServerClientFactory bscf = new JsonBimServerClientFactory("http://localhost:8082");

  BimServerClient bimServerClient;
  try {
      bimServerClient = (BimServerClient) bscf.create(new UsernamePasswordAuthenticationInfo("nazmul.prince@cubicasa.fi", "bimserver"));
      List<SProject> allProjects = bimServerClient .getBimsie1ServiceInterface().getAllProjects(true, true);
      int i = 1;
      for(SProject sp : allProjects){
          System.out.println("project no "+i+" "+sp.getName());
      }
  }catch (ServiceException ex) {
      System.out.println("ServiceException: "+ex.toString());
  } catch (ChannelConnectionException ex) {
      System.out.println("ChannelConnectionException: "+ex.toString());
  } catch (PublicInterfaceNotFoundException ex) {
      System.out.println("PublicInterfaceNotFoundException: "+ex.toString());
  }
```

but while running the program I'm getting error in server log---
2014-03-12 18:55:40,878 ERROR org.bimserver.servlets.JsonServlet - 
org.codehaus.jettison.json.JSONException: JSONObject["action"] not found.
    at org.codehaus.jettison.json.JSONObject.get(JSONObject.java:360)
    at org.codehaus.jettison.json.JSONObject.getString(JSONObject.java:487)
    at org.bimserver.servlets.JsonServlet.service(JsonServlet.java:49)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:538)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:478)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:517)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:937)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:871)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
    at org.eclipse.jetty.server.Server.handle(Server.java:346)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:438)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:921)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:780)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:220)
    at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:55)
    at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:242)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:529)
    at java.lang.Thread.run(Unknown Source)

I'm using netbeans where it indicating the error in line---

bimServerClient = (BimServerClient) bscf.create(new UsernamePasswordAuthenticationInfo("nazmul.prince@cubicasa.fi", "bimserver"));

and in netbeans the error is like that---

Exception in thread "main" org.bimserver.shared.json.ReflectorException: java.lang.ClassCastException: com.google.gson.JsonNull cannot be cast to com.google.gson.JsonObject

I'm just trying to get connected of my local bimserver an get access of the ifc files in the projects of bimserver which are being uploaded from the bimserver manually ("localhost:8082/admin/Console.html")

Please help.
Thanks in advance.

**Comment by vikaskallidantheyil** [comment]
hi i am new to bim server, my requirement is i need to write programme to connect to bim server , create a project and upload ifc file and above code looks perfect but the problem is i am not to run the code

**Comment by rubendel** [comment]
Well if you are not going to run the code, you probably won't get far
