### ISSUE TITLE
Cand start BIMserver 1.5.96 on Tomcat8.0.50

### ISSUE THREAD

**Issue by Knut33** [opensourceBIM/BIMserver#730]
In the log i get this error:
2018-03-22 13:45:40,001 INFO [localhost-startStop-1] o.b.BimServer [BimServer.java:232] Starting BIMserver
2018-03-22 13:45:40,021 INFO [localhost-startStop-1] o.b.BimServer [BimServer.java:234] Using "/opt/tomcat/webapps/bimserver-lt-1/WEB-INF" as homedir
2018-03-22 13:45:47,371 INFO [localhost-startStop-1] o.b.p.MavenPluginRepository [MavenPluginRepository.java:80] Adding ~/.m2 as repository
2018-03-22 13:45:47,573 INFO [localhost-startStop-1] o.b.w.WarServerInitializer [WarServerInitializer.java:113] Servlet Context Name: BIMserver
2018-03-22 13:45:47,575 INFO [localhost-startStop-1] o.b.BimServer [BimServer.java:325] Version: 1.5.96
2018-03-22 13:46:00,969 INFO [localhost-startStop-1] o.b.t.TemplateEngine [TemplateEngine.java:64] Using "opt/tomcat/webapps/bimserver-lt-1/WEB-INF/emailtemplates/" as template dir
2018-03-22 13:46:01,414 INFO [localhost-startStop-1] o.b.d.b.BerkeleyKeyValueStore [BerkeleyKeyValueStore.java:85] Non-empty database directory found "/opt/tomcat/webapps/bimserver-lt-1/WEB-INF/database"
2018-03-22 13:46:02,815 INFO [localhost-startStop-1] o.b.p.MavenPluginRepository [MavenPluginRepository.java:80] Adding ~/.m2/repository as repository
2018-03-22 13:46:04,968 ERROR [localhost-startStop-1] o.b.d.Database [Database.java:202] 
org.bimserver.BimserverDatabaseException: Table store_User_username not found
	at org.bimserver.database.berkeley.BerkeleyKeyValueStore.getTableWrapper(BerkeleyKeyValueStore.java:240)
	at org.bimserver.database.berkeley.BerkeleyKeyValueStore.get(BerkeleyKeyValueStore.java:301)
	at org.bimserver.database.DatabaseSession.querySingle(DatabaseSession.java:2136)
	at org.bimserver.database.actions.BimDatabaseAction.getUserByUserName(BimDatabaseAction.java:98)
	at org.bimserver.database.actions.AddUserDatabaseAction.execute(AddUserDatabaseAction.java:104)
	at org.bimserver.database.Database.init(Database.java:172)
	at org.bimserver.BimServer.start(BimServer.java:657)
	at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:116)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4861)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5322)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:974)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1850)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-03-22 13:46:05,045 ERROR [localhost-startStop-1] o.b.BimServer [BimServer.java:758] 
java.lang.IllegalStateException: There is 1 existing transaction opened against the Environment.
Aborting open transactions ...
aborting <Transaction id="1911">
	at com.sleepycat.je.Environment.close(Environment.java:440)
	at org.bimserver.database.berkeley.BerkeleyKeyValueStore.close(BerkeleyKeyValueStore.java:265)
	at org.bimserver.database.Database.close(Database.java:346)
	at org.bimserver.database.Database.init(Database.java:203)
	at org.bimserver.BimServer.start(BimServer.java:657)
	at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:116)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4861)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5322)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:974)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1850)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-03-22 13:46:05,046 INFO [localhost-startStop-1] o.b.s.w.j.Jsr356Impl [Jsr356Impl.java:94] WebSocket context initialized
2018-03-22 13:52:20,271 ERROR [http-nio-8080-exec-4] o.b.s.RootServlet [RootServlet.java:210] 
java.lang.NullPointerException: null
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:111)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rubendel** [comment]
Have you tried to start multiple instances on the same database? Or did it crash during startup? Can you try again after removing the database?

**Comment by Knut33** [comment]
Hi!

Its seems it was to short time between deploying and configurating, the script needed a long time to deploy.

After letting the deployment run for 5-10 min it worked!

Is not so for 1.5.95 that deploys at once.

 

 

 

Fra: Ruben de Laat [mailto:notifications@github.com] 
Sendt: fredag 30. mars 2018 10:48
Til: opensourceBIM/BIMserver <BIMserver@noreply.github.com>
Kopi: Knut33 <post@onsker.no>; Author <author@noreply.github.com>
Emne: Re: [opensourceBIM/BIMserver] Cand start BIMserver 1.5.96 on Tomcat8.0.50 (#730)

 

Have you tried to start multiple instances on the same database? Or did it crash during startup? Can you try again after removing the database?
