### ISSUE TITLE
IfcStairFlight not possible to check in since IFC4 ADD2 introduction

### ISSUE THREAD

**Issue by hlg** [opensourceBIM/BIMserver#746]
Trying to checkin an entity of type `IfcStairFlight` (sample [IfcStairFlight.ifc.txt](https://github.com/opensourceBIM/BIMserver/files/1919797/IfcStairFlight.ifc.txt)) yields the following error:

```
8168051 [LongStreamingCheckinAction] ERROR org.bimserver.longaction.LongAction -
org.bimserver.shared.exceptions.UserException: Error on line 116870: Unimplemented class org.bimserver.models.ifc4.IfcStairFlightTypeEnum
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:397)
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:85)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:726)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:703)
        at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:63)
        at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.bimserver.plugins.deserializers.DeserializeException: Error on line 116870: Unimplemented class org.bimserver.models.ifc4.IfcStairFlightTypeEnum
        at org.bimserver.ifc.step.deserializer.IfcParserWriterUtils.convertSimpleValue(IfcParserWriterUtils.java:106)
        at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.convert(IfcStepStreamingDeserializer.java:555)
        at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processRecord(IfcStepStreamingDeserializer.java:384)
        at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processLine(IfcStepStreamingDeserializer.java:248)
        at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:183)
        at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:165)
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:208)
        ... 6 common frames omitted
```

The same file can be checked in without error up to BIMserver version 1.5.95. The offending attribute `IfcStairFlight.PredefinedType` of type `IfcStairFlightTypeEnum` was added in IFC4 FINAL.

The attribute `IfcStairFlightType.PredefinedType` is of the same enum type and was introduced in IFC2x2. `IfcStairFlightType` entities can be checked in without problems in BIMserver 1.5.100 (sample [IfcStairFlightType.ifc.txt](https://github.com/opensourceBIM/BIMserver/files/1919831/IfcStairFlightType.ifc.txt)).

**Comment by rubendel** [comment]
Hi Helga, I tried to checkin both files, and both went OK here (101-SNAPSHOT). Not sure if I accidentally fixed these problems last week when fixing the other IFC4 issues. Could you try again?

**Comment by hlg** [comment]
Yes, seems to be fine now. Also, opensourcebim/ifcplugins#12 can be marked resolved.
