### ISSUE TITLE
Eclipse -  org.bimserver.shared.exceptions.PluginException 

### ISSUE THREAD

**Issue by veerakumarasamyv** [opensourceBIM/BIMserver#784]
Hi all, Good well..

I am new to BimServer. i imported the Bimserver1.5.101 source code to my local eclipse neon.  when starting local client, which throws exception mentioned as bellow,

```
Logging to C:\Users\we\git\BIMserver\BimServerJar\tmptestdata\home\logs\bimserver.log
23:43:08 INFO  [main]: Starting BIMserver                                                               (BimServer.java:234) 
23:43:08 INFO  [main]: Using "tmptestdata\home" as homedir                                              (BimServer.java:236) 
23:43:16 INFO  [main]: Adding ~/.m2 as repository                                                       (MavenPluginRepository.java:80) 
23:43:17 INFO  [main]: Version: 1.5.103-SNAPSHOT                                                        (BimServer.java:327) 
23:43:30 INFO  [main]: Using "C:\Users\we\git\BIMserver\BimServerJar\..\BimServer\emailtemplates\" as template dir (TemplateEngine.java:64) 
23:43:31 INFO  [main]: Non-empty database directory found "tmptestdata\home\database"                   (BerkeleyKeyValueStore.java:85) 
23:43:32 INFO  [main]: Adding ~/.m2/repository as repository                                            (MavenPluginRepository.java:80) 
23:43:32 INFO  [main]: Checking for stale records, this can take some time...                           (BimServer.java:770) 
23:43:32 INFO  [main]: Checking for stale records took 86 ms                                            (BimServer.java:800) 
23:43:33 INFO  [main]: Changing server state to RUNNING                                                 (ServerInfoManager.java:113) 
23:45:29 ERROR [main]:                                                                                  (LocalDevPluginLoader.java:39) 
org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.demoplugins.bimbotdemo.BimBotDemoService' not found in file:///C:/Users/we/git/DemoPlugins/DemoPlugins/
	at org.bimserver.plugins.PluginManager.loadPlugins(PluginManager.java:611)
	at org.bimserver.plugins.PluginManager.loadJavaProject(PluginManager.java:430)
	at org.bimserver.plugins.PluginManager.loadPluginsFromEclipseProject(PluginManager.java:460)
	at org.bimserver.LocalDevPluginLoader.loadPlugins(LocalDevPluginLoader.java:37)
	at org.bimserver.LocalDevBimServerStarter.start(LocalDevBimServerStarter.java:114)
	at org.bimserver.LocalDevBimServerStarter.main(LocalDevBimServerStarter.java:69)
Caused by: java.lang.ClassNotFoundException: org.bimserver.demoplugins.bimbotdemo.BimBotDemoService
	at org.bimserver.plugins.classloaders.EclipsePluginClassloader.findClass(EclipsePluginClassloader.java:107)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.bimserver.plugins.PluginManager.loadPlugins(PluginManager.java:605)
	... 5 common frames omitted

```

Kindly help or give some suggestions to proceed next step. Thanks in Advance.!

**Comment by rubendel** [comment]
Does the DemoPlugins project compile without errors?
