### ISSUE TITLE
trouble with bimserver on Mac

### ISSUE THREAD

**Issue by brunoribeirodasilva** [opensourceBIM/BIMserver#787]
I am trying to set up BIMserver (https://github.com/opensourceBIM/BIMserver/releases) on my Mac with a JAR file. I had trouble opening it, but after trying java --add-modules=java.xml.ws -jar /Users/BIMMS/Downloads/bimserverjar-1.5.101.jar I got it finally running. The trouble is that after I setup the server, this error pops up.

```
No expanding necessary
OS: Mac OS X
Main class: org.bimserver.JarBimServer

Commands:
java
-Xmx4000m
-Xss1024m
-Dorg.apache.cxf.Logger=org.apache.cxf.common.logging.Slf4jLogger
-classpath
.:lib:lib/activation-1.1.jar:lib/aether-api-1.0.2.v20150114.jar:lib/aether-connector-basic-1.0.2.v20150114.jar:lib/aether-impl-1.0.2.v20150114.jar:lib/aether-spi-1.0.2.v20150114.jar:lib/aether-transport-file-1.0.2.v20150114.jar:lib/aether-transport-http-1.0.2.v20150114.jar:lib/aether-util-1.0.2.v20150114.jar:lib/antlr-2.7.7.jar:lib/antlr-3.5.2.jar:lib/antlr-complete-3.5.2.jar:lib/antlr-runtime-3.5.2.jar:lib/aopalliance-1.0.jar:lib/aopalliance-repackaged-2.5.0-b31.jar:lib/app-1.3.200-v20130910-1609.jar:lib/asm-6.0.jar:lib/asm-commons-6.0.jar:lib/asm-tree-6.0.jar:lib/bcf-0.0.13.jar:lib/bimserver-1.5.101.jar:lib/bimserverclientlib-1.5.101.jar:lib/buildingsmartlibrary-1.0.13.jar:lib/c3p0-0.9.5.2.jar:lib/cdi-api-1.0.jar:lib/common-3.6.200-v20130402-1505.jar:lib/commons-cli-1.3.1.jar:lib/commons-codec-1.9.jar:lib/commons-collections-20040616.jar:lib/commons-fileupload-1.3.2.jar:lib/commons-io-2.2.jar:lib/commons-lang-2.4.jar:lib/commons-lang3-3.4.jar:lib/commons-logging-1.2.jar:lib/commons-pool2-2.4.2.jar:lib/contenttype-3.4.200-v20140207-1251.jar:lib/cors-filter-2.5.jar:lib/cxf-core-3.1.11.jar:lib/cxf-rt-bindings-soap-3.1.11.jar:lib/cxf-rt-bindings-xml-3.1.11.jar:lib/cxf-rt-databinding-jaxb-3.1.11.jar:lib/cxf-rt-frontend-jaxws-3.1.11.jar:lib/cxf-rt-frontend-simple-3.1.11.jar:lib/cxf-rt-javascript-3.1.11.jar:lib/cxf-rt-transports-http-3.1.11.jar:lib/cxf-rt-ws-addr-3.1.11.jar:lib/cxf-rt-ws-policy-3.1.11.jar:lib/cxf-rt-wsdl-3.1.11.jar:lib/fastutil-7.0.13.jar:lib/gson-2.5.jar:lib/guava-19.0.jar:lib/guice-4.0-no_aop.jar:lib/gunit-3.5.2.jar:lib/hamcrest-core-1.1.jar:lib/HikariCP-java6-2.3.13.jar:lib/hk2-api-2.5.0-b31.jar:lib/hk2-locator-2.5.0-b31.jar:lib/hk2-utils-2.5.0-b31.jar:lib/httpclient-4.5.1.jar:lib/httpcore-4.4.3.jar:lib/httpmime-4.5.1.jar:lib/jackson-annotations-2.8.0.jar:lib/jackson-core-2.8.9.jar:lib/jackson-databind-2.8.9.jar:lib/java-getopt-1.0.13.jar:lib/java-property-utils-1.9.1.jar:lib/javassist-3.12.1.GA.jar:lib/javassist-3.20.0-GA.jar:lib/javax-websocket-client-impl-9.4.9.v20180320.jar:lib/javax-websocket-server-impl-9.4.9.v20180320.jar:lib/javax.annotation-api-1.2.jar:lib/javax.inject-1.jar:lib/javax.inject-2.5.0-b31.jar:lib/javax.json-1.0.4.jar:lib/javax.mail-1.5.6.jar:lib/javax.servlet-api-3.1.0.jar:lib/javax.websocket-api-1.1.jar:lib/javax.websocket-client-api-1.0.jar:lib/javax.ws.rs-api-2.1-m02.jar:lib/jaxb-core-2.2.11.jar:lib/jaxb-impl-2.2.11.jar:lib/jcl-over-slf4j-1.6.2.jar:lib/jdom2-2.0.6.jar:lib/je-7.4.5.jar:lib/jersey-client-2.26-b01.jar:lib/jersey-common-2.26-b01.jar:lib/jersey-container-servlet-2.26-b01.jar:lib/jersey-container-servlet-core-2.26-b01.jar:lib/jersey-guava-2.26-b01.jar:lib/jersey-media-jaxb-2.26-b01.jar:lib/jersey-server-2.26-b01.jar:lib/jettison-1.3.8.jar:lib/jetty-annotations-9.4.9.v20180320.jar:lib/jetty-client-9.4.9.v20180320.jar:lib/jetty-http-9.4.9.v20180320.jar:lib/jetty-io-9.4.9.v20180320.jar:lib/jetty-jndi-9.4.9.v20180320.jar:lib/jetty-plus-9.4.9.v20180320.jar:lib/jetty-security-9.4.9.v20180320.jar:lib/jetty-server-9.4.9.v20180320.jar:lib/jetty-servlet-9.4.9.v20180320.jar:lib/jetty-util-9.4.9.v20180320.jar:lib/jetty-webapp-9.4.9.v20180320.jar:lib/jetty-xml-9.4.9.v20180320.jar:lib/jobs-3.6.0-v20140424-0053.jar:lib/json-20140107.jar:lib/jsr250-api-1.0.jar:lib/jul-to-slf4j-1.7.22.jar:lib/junit-4.10.jar:lib/logback-classic-1.1.9.jar:lib/logback-core-1.1.9.jar:lib/maven-aether-provider-3.3.9.jar:lib/maven-artifact-3.3.9.jar:lib/maven-builder-support-3.3.9.jar:lib/maven-core-3.3.9.jar:lib/maven-model-3.3.9.jar:lib/maven-model-builder-3.3.9.jar:lib/maven-plugin-api-3.3.9.jar:lib/maven-repository-metadata-3.3.9.jar:lib/maven-settings-3.3.9.jar:lib/maven-settings-builder-3.3.9.jar:lib/mchange-commons-java-0.2.11.jar:lib/neethi-3.0.3.jar:lib/org.apache.oltu.oauth2.authzserver-1.0.2.jar:lib/org.apache.oltu.oauth2.client-1.0.2.jar:lib/org.apache.oltu.oauth2.common-1.0.2.jar:lib/org.apache.oltu.oauth2.dynamicreg.client-1.0.2.jar:lib/org.apache.oltu.oauth2.dynamicreg.common-1.0.2.jar:lib/org.apache.oltu.oauth2.dynamicreg.server-1.0.2.jar:lib/org.apache.oltu.oauth2.resourceserver-1.0.2.jar:lib/org.eclipse.core.resources-3.8.101.v20130717-0806.jar:lib/org.eclipse.emf.codegen-2.11.0-v20150806-0404.jar:lib/org.eclipse.emf.codegen.ecore-2.11.0-v20150806-0404.jar:lib/org.eclipse.emf.common-2.11.0-v20150805-0538.jar:lib/org.eclipse.emf.ecore-2.11.1-v20150805-0538.jar:lib/org.eclipse.emf.ecore.xmi-2.11.1-v20150805-0538.jar:lib/org.eclipse.jdt.core-3.9.1.v20130905-0837.jar:lib/org.eclipse.sisu.inject-0.3.2.jar:lib/org.eclipse.sisu.plexus-0.3.2.jar:lib/osgi-3.10.0-v20140606-1445.jar:lib/osgi-resource-locator-1.0.1.jar:lib/plexus-cipher-1.4.jar:lib/plexus-classworlds-2.5.2.jar:lib/plexus-component-annotations-1.6.jar:lib/plexus-interpolation-1.21.jar:lib/plexus-sec-dispatcher-1.3.jar:lib/plexus-utils-3.0.22.jar:lib/pluginbase-1.5.101.jar:lib/preferences-3.5.200-v20140224-1527.jar:lib/protobuf-java-2.6.1.jar:lib/quartz-2.3.0.jar:lib/registry-3.5.400-v20140428-1507.jar:lib/rome-1.7.1.jar:lib/rome-utils-1.7.1.jar:lib/runtime-3.9.100-v20131218-1515.jar:lib/shared-1.5.101.jar:lib/slf4j-api-1.7.22.jar:lib/ST4-4.0.8.jar:lib/stax-api-1.0.1.jar:lib/stax2-api-3.1.4.jar:lib/stringtemplate-3.2.1.jar:lib/validation-api-1.1.0.Final.jar:lib/velocity-1.7.jar:lib/websocket-api-9.4.9.v20180320.jar:lib/websocket-client-9.4.9.v20180320.jar:lib/websocket-common-9.4.9.v20180320.jar:lib/websocket-server-9.4.9.v20180320.jar:lib/websocket-servlet-9.4.9.v20180320.jar:lib/woodstox-core-asl-4.4.1.jar:lib/wsdl4j-1.6.3.jar:lib/xml-resolver-1.2.jar:lib/xmlbeans-2.6.0.jar:lib/xmlschema-core-2.2.1.jar
org.bimserver.JarBimServer
address=localhost
port=8080
homedir=/Users/BIMMS/./Desktop/home
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
10:48:47 INFO  [main]: Starting BIMserver                                                               (BimServer.java:232) 
10:48:47 INFO  [main]: Using "/Users/BIMMS/./Desktop/home" as homedir                                   (BimServer.java:234) 
10:48:48 ERROR [main]:                                                                                  (BimServer.java:291) 
java.lang.NoClassDefFoundError: javax/jws/WebService
    at org.bimserver.shared.meta.SService.<init>(SService.java:60)
    at org.bimserver.interfaces.SServiceInterfaceService.<init>(SServiceInterfaceService.java:31)
    at org.bimserver.shared.InterfaceList.createSServicesMap(InterfaceList.java:61)
    at org.bimserver.BimServer.<init>(BimServer.java:239)
    at org.bimserver.JarBimServer.start(JarBimServer.java:146)
    at org.bimserver.JarBimServer.main(JarBimServer.java:79)
Caused by: java.lang.ClassNotFoundException: javax.jws.WebService
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
    ... 6 common frames omitted
Logging to /Users/BIMMS/./Desktop/home/logs/bimserver.log
10:48:48 INFO  [main]: Unknown version                                                                  (BimServer.java:330) 
10:48:48 ERROR [main]:                                                                                  (BimServer.java:616) 
java.lang.NullPointerException: null
    at org.bimserver.BimServer.start(BimServer.java:334)
    at org.bimserver.JarBimServer.start(JarBimServer.java:159)
    at org.bimserver.JarBimServer.main(JarBimServer.java:79)
10:48:48 ERROR [main]:                                                                                  (BimServer.java:758) 
java.lang.NullPointerException: null
    at org.bimserver.BimServer.start(BimServer.java:620)
    at org.bimserver.JarBimServer.start(JarBimServer.java:159)
    at org.bimserver.JarBimServer.main(JarBimServer.java:79)
10:48:48 ERROR [main]:                                                                                  (JarBimServer.java:162) 
java.lang.NullPointerException: null
    at org.bimserver.BimServer.start(BimServer.java:759)
    at org.bimserver.JarBimServer.start(JarBimServer.java:159)
    at org.bimserver.JarBimServer.main(JarBimServer.java:79)

```
my java version is:

```
java 10.0.2 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

if anyone could help I would be glad

**Comment by rubendel** [comment]
Java 10 is not supported on any of the platforms for BIMserver. The Oracle roadmap says it won't be supported anymore after September 2018, so makes no sense to go through the effort.

http://www.oracle.com/technetwork/java/javase/eol-135779.html

**Comment by rubendel** [comment]
BTW, also Java 9 is not supported, Java 8 is the only version that has support until 2020

**Comment by brunoribeirodasilva** [comment]
@rubendel Thanks, it worked!
