### ISSUE TITLE
Java ClassNotFoundException: javax.jws.WebService

### ISSUE THREAD

**Issue by CrossfireAUT** [opensourceBIM/BIMserver#796]
Hello team,

I am trying to set up a BIMServer on a java-11-openjdk-amd64, Tomcat v9.0.10 on Ubuntu 18.04.
Following Exception occurs in my /var/bimserver/home/logs/bimserver.log:
``
07-08-2018 09:35:36 INFO  Starting BIMserver                                                               (org.bimserver.BimServer.java:218)
07-08-2018 09:35:36 INFO  Using "/var/bimserver/home" as homedir                                           (org.bimserver.BimServer.java:220)
07-08-2018 09:35:36 ERROR                                                                                  (org.bimserver.BimServer.java:261)
java.lang.NoClassDefFoundError: javax/jws/WebService
        at org.bimserver.shared.meta.SService.<init>(SService.java:60)
        at org.bimserver.interfaces.SServiceInterfaceService.<init>(SServiceInterfaceService.java:31)
        at org.bimserver.shared.InterfaceList.createSServicesMap(InterfaceList.java:107)
        at org.bimserver.BimServer.<init>(BimServer.java:225)
        at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:73)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4643)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5109)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1427)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1417)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:943)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1427)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1417)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:943)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:682)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
Caused by: java.lang.ClassNotFoundException: javax.jws.WebService
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1309)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1138)
        ... 35 more``

Is there a unsupported Version I'm using or a mistake on my part?
Sorry for the trouble and thanks.

**Comment by CrossfireAUT** [comment]
Fixed it.
I made a new VM, installed tomcat via apt and installed java-8-openjdk-amd64 and openjdk-11-jre-headless. Seemed like a missing or unreadable library.

Then:
``2018-08-07 12:05:17,570 ERROR [passit-bim01.l.x-startStop-1] o.b.d.Database [Database.java:202]
org.bimserver.BimserverDatabaseException: Table store_User_username not found
        at org.bimserver.database.berkeley.BerkeleyKeyValueStore.getTableWrapper(BerkeleyKeyValueStore.java:240)
        at org.bimserver.database.berkeley.BerkeleyKeyValueStore.get(BerkeleyKeyValueStore.java:301)
        at org.bimserver.database.DatabaseSession.querySingle(DatabaseSession.java:2136)
        at org.bimserver.database.actions.BimDatabaseAction.getUserByUserName(BimDatabaseAction.java:115)
        at org.bimserver.database.actions.AddUserDatabaseAction.execute(AddUserDatabaseAction.java:104)
        at org.bimserver.database.Database.init(Database.java:172)
        at org.bimserver.BimServer.start(BimServer.java:657)
        at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:116)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4776)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5240)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
``
Like in https://github.com/opensourceBIM/BIMserver/issues/730, I removed the database directory and restarted tomcat, he then recreates the tables and it worked.
I now have a Tomcat 8.5.30 with openjdk 8 and 11 on Ubuntu 18.04.

**Comment by rubendel** [comment]
OpenJDK 11 is not supported, only version 8.
