### ISSUE TITLE
multiple users checkin ifc Exception:ConcurrentModificationException

### ISSUE THREAD

**Issue by steven0718** [opensourceBIM/BIMserver#803]
hi rubendel, bimserver version:1.5.101.    multiple users checkin ifc exception occurred：
org.bimserver.BimserverDatabaseException: java.util.ConcurrentModificationException
	at org.bimserver.database.queries.QueryObjectProvider.next(QueryObjectProvider.java:156)
	at org.bimserver.geometry.StreamingGeometryGenerator.generateGeometry(StreamingGeometryGenerator.java:384)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:257)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:85)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:726)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:703)
	at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:63)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at org.bimserver.database.queries.DatabaseReadingStackFrame.processPossibleInclude(DatabaseReadingStackFrame.java:125)
	at org.bimserver.database.queries.DatabaseReadingStackFrame.processPossibleIncludes(DatabaseReadingStackFrame.java:92)
	at org.bimserver.database.queries.DatabaseReadingStackFrame.processPossibleInclude(DatabaseReadingStackFrame.java:137)
	at org.bimserver.database.queries.DatabaseReadingStackFrame.processPossibleIncludes(DatabaseReadingStackFrame.java:97)
	at org.bimserver.database.queries.QueryTypeStackFrame.process(QueryTypeStackFrame.java:91)
	at org.bimserver.database.queries.QueryObjectProvider.next(QueryObjectProvider.java:143)
	... 8 common frames omitted
2018-08-13 10:41:09,964 ERROR [LongStreamingCheckinAction] o.b.l.LongAction [LongAction.java:189] 
org.bimserver.shared.exceptions.UserException: org.bimserver.BimserverDatabaseException: java.util.ConcurrentModificationException
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:397)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:85)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:726)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:703)
	at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:63)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.bimserver.GeometryGeneratingException: org.bimserver.BimserverDatabaseException: java.util.ConcurrentModificationException
	at org.bimserver.geometry.StreamingGeometryGenerator.generateGeometry(StreamingGeometryGenerator.java:492)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:257)
	... 6 common frames omitted
Caused by: org.bimserver.BimserverDatabaseException: java.util.ConcurrentModificationException
	at org.bimserver.database.queries.QueryObjectProvider.next(QueryObjectProvider.java:156)
	at org.bimserver.geometry.StreamingGeometryGenerator.generateGeometry(StreamingGeometryGenerator.java:384)
	... 7 common frames omitted
Caused by: java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at org.bimserver.database.queries.DatabaseReadingStackFrame.processPossibleInclude(DatabaseReadingStackFrame.java:125)
	at org.bimserver.database.queries.DatabaseReadingStackFrame.processPossibleIncludes(DatabaseReadingStackFrame.java:92)
	at org.bimserver.database.queries.DatabaseReadingStackFrame.processPossibleInclude(DatabaseReadingStackFrame.java:137)
	at org.bimserver.database.queries.DatabaseReadingStackFrame.processPossibleIncludes(DatabaseReadingStackFrame.java:97)
	at org.bimserver.database.queries.QueryTypeStackFrame.process(QueryTypeStackFrame.java:91)
	at org.bimserver.database.queries.QueryObjectProvider.next(QueryObjectProvider.java:143)
	... 8 common frames omitted

**Comment by rubendel** [comment]
Most of these types of issues have been solved in https://github.com/opensourceBIM/BIMserver/releases/tag/v1.5.108, please re-open if this still happens.
