### ISSUE TITLE
Couldn't Run LocalDevBimServerStarter

### ISSUE THREAD

**Issue by Inuyashahan** [opensourceBIM/BIMserver#814]
Exception in thread "main" java.lang.NoClassDefFoundError: BimServer
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.getMethod(Unknown Source)
	at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: BimServer
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more

I see in pom.xml 
<dependency>
			<groupId>org.opensourcebim</groupId>
			<artifactId>bimserver</artifactId>
			<version>1.5.103-SNAPSHOT</version>
</dependency> is missing, How can I fix it?

**Comment by Inuyashahan** [comment]
The above is the Console Result when I try to run LocalDevBimServerStarter.
Thanks very much for help!!!

**Comment by rubendel** [comment]
Is it compiling?
