### ISSUE TITLE
Persistent  database for docker-containers

### ISSUE THREAD

**Issue by sigurdne** [opensourceBIM/BIMserver#816]
Would it be possible to configure the database to be moved from `WEB-INF` into a place where it can be mapped in from the outside of the container?

Regards

**Comment by sigurdne** [comment]
I tried to update the war-file by adding `context.xml` to `META-INF`

`<?xml version="1.0" encoding="UTF-8"?>`
`<Context path="/BIMserver" docBase="/opt/tomcat/webapps/BIMserver.war" antiJARLocking="true" attiResourceLocking="true">`
	`<Parameter name="homedir" value="/var/bimserver/home"/>`
`</Context>`

But then I got an error on start:

> 06-Sep-2018 18:14:08.308 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.bimserver.web.WarServerInitializer]
> java.lang.NullPointerException
>	at org.bimserver.BimServer.start(BimServer.java:758)
>	at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:116)
>	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4792)
>	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5256)
>	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
>	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
>	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
>	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
>	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:985)
>	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
>	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>	at java.lang.Thread.run(Thread.java:748)

Any advice?

Regards

**Comment by sigurdne** [comment]
Well, it is working for local install, like this on ubuntu 18.04:
```
$ sudo apt-get install libecj-java libtomcat8-java tomcat8-common

$ sudo mkdir mkdir /var/www/localhost -p
$ sudo chown -R tomcat8 /var/www/localhost
 
$ sudo mkdir /var/bimserver/home -p
$ sudo chown -R tomcat8 /var/bimserver

$ sudo nano /etc/tomcat8/policy.d/default.policy
```
paste:
>grant {
>  permission java.security.AllPermission;
>};

`$ sudo chown tomcat8 /etc/tomcat8/policy.d/default.policy`

edit: /etc/tomcat8/server.xml

```
<Host name="localhost" appBase="/var/www/localhost" unpackWARs="true" autoDeploy="true" xmlValidation="false" xmlNamespaceAware="false">
	<Context path="" docBase="/var/www/localhost/ROOT.war">
		<Parameter name="homedir" value="/var/bimserver/home"/>
	</Context>
</Host>
```

Place war-file
`$ sudo cp ~/Downloads/bimserverwar-1.5.101.war  /var/www/localhost/ROOT.war`

Restart tomcat
`$ sudo service tomcat8 restart`

And it works for `http://localhost:8080/`

I will give the docker-container another try

Regards

**Comment by sigurdne** [comment]
And there it works.
My mistake was to install the wrong openjdk. It has to be the jre-headless.
i.e.: `openjdk-8-jre-headless`

Regards
