### ISSUE TITLE
Can not install IfcOpenShellPlugin on ubuntu 16.04 server

### ISSUE THREAD

**Issue by rickwang0929** [opensourceBIM/BIMserver#834]
Server OS: Ubuntu 16.04
Tomcat Version: 8.5.34
BIMserver Version: 1.5.108
Java Version: 8

Hi. I deployed the BIMserver.jar on my ubuntu server. Everything is fine until the installation of IfcOpenShellPlugin. Error occurs like this.
`java.io.FileNotFoundException: /home/tomcat8/.ifcopenshell/IfcGeomServer-v0.6.0-5526f42-linux64 (No such file or directory)`

I checked the log file. Here it is.
`2018-09-26 00:24:53,886 ERROR [org.bimserver.PluginInterface.installPluginBundle] o.b.d.a.InstallPluginBundle [InstallPluginBundle.java:75]
org.bimserver.plugins.renderengine.RenderEngineException: java.io.FileNotFoundException: /home/tomcat8/.ifcopenshell/IfcGeomServer-v0.6.0-5526f42-linux64 (No such file or directory)
        at org.ifcopenshell.IfcGeomServerClient.<init>(IfcGeomServerClient.java:201)
        at org.ifcopenshell.IfcOpenShellEnginePlugin.init(IfcOpenShellEnginePlugin.java:74)
        at org.bimserver.plugins.PluginManager.loadPlugin(PluginManager.java:1404)
        at org.bimserver.plugins.PluginManager.install(PluginManager.java:1524)
        at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPluginBundle.java:73)
        at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPluginBundle.java:35)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:734)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:726)
        at org.bimserver.webservices.impl.PluginServiceImpl.installPluginBundle(PluginServiceImpl.java:1476)
        at org.bimserver.generated.PluginInterfaceReflector1.callMethod(PluginInterfaceReflector1.java)
        at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
        at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:154)
        at org.bimserver.JsonHandler.execute(JsonHandler.java:70)
        at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /home/tomcat8/.ifcopenshell/IfcGeomServer-v0.6.0-5526f42-linux64 (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at org.ifcopenshell.IfcGeomServerClient.<init>(IfcGeomServerClient.java:177)
        ... 36 common frames omitted
`
Also attach the tutorial about how to install bimserver on ubuntu server
https://fumblehool.wordpress.com/2017/06/17/install-bim-server-on-ubuntu-server/

**Comment by rubendel** [comment]
This has been fixed in https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin/commit/e3eeac404aaedabc32d81a2a6d73d7e358dc3f10. A new release of the IfcOpenShell plugin is underway, please upgrade to 0.5.30.

**Comment by rickwang0929** [comment]
Problem solved. Thank you!

PS: For those who want to install the latest plugin but can not find the latest version, restart server first.

**Comment by rubendel** [comment]
Actually no restart is required, it simply takes 1 hour for BIMserver to refresh the maven repository, also it takes a bit of time for maven artifacts to propagate through the maven "network". Good that it works, thanks for the feedback.
