### ISSUE TITLE
Missing objects in model in IFC2X3

### ISSUE THREAD

**Issue by albertomusetti** [opensourceBIM/BIMserver#839]
Hi, I have a problem with geometry generation in a IFC2X3 model.

In the geometry generation report, it says:

`java.lang.Exception: Missing objects in model (19889, 19892, 19881)
	at org.bimserver.geometry.GeometryRunner.run(GeometryRunner.java:583)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

`java.lang.Exception: Missing objects in model (133191, 133188, 133194)
	at org.bimserver.geometry.GeometryRunner.run(GeometryRunner.java:583)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

The model renders correctly with solibri model viewer as well as other IFC viewer.
The IFC model iwas generated by the Naviswork - Codemill IFC Exporter.

I've attached the Geometry Generation report and the IFC file that generate the error: 
[2018-10-08-08-53-50.zip](https://github.com/opensourceBIM/BIMserver/files/2455349/2018-10-08-08-53-50.zip)

Many thanks!

**Comment by rubendel** [comment]
Have you tried this in the latest release? I just did and it's not missing any geometry. BTW I had to change the GUIDs in this file because they are not valid.

**Comment by albertomusetti** [comment]
I did not tested the file in the last version because I had the invalid GUID error.
Now I have manually changed the GUIDs and it works in the last version.

There is a command/script to change the GUIDs automatically?

many thanks

**Comment by rubendel** [comment]
Not that I know of, but please do contact the developer of the software you use to have them fix it.
