### ISSUE TITLE
Unable to read getModel(): malformed input around byte 0

### ISSUE THREAD

**Issue by Dakki97** [opensourceBIM/BIMserver#846]
Hello, when starting to parse the IFC this error occurs

```
org.bimserver.client.GeometryException: Protocol != BGS (L2F )
	at org.bimserver.client.ClientIfcModel.processGeometryInputStream(ClientIfcModel.java:408)
	at org.bimserver.client.ClientIfcModel.loadGeometry(ClientIfcModel.java:369)
	at org.bimserver.client.ClientIfcModel.loadDeep(ClientIfcModel.java:304)
	at org.bimserver.client.ClientIfcModel.<init>(ClientIfcModel.java:116)
	at org.bimserver.client.BimServerClient.getModel(BimServerClient.java:202)
	at IFC.initialize(IFC.java:103)
	at IFCFacade.queryStoreys(IFCFacade.java:11)
	at BIM.setup(BIM.java:9)
	at GenericDemoClient.start(GenericDemoClient.java:12)
	at BIM.main(BIM.java:5)

```
Another error occured on the same getModel() function:
    Malformed input around byte 0.

I initialize my model like this

```
    public ClientIfcModel initialize(BimServerClient client) {
        try {
            final String PROJECT_NAME = "IFCParser";
            final List<SProject> PROJECTS = client.getServiceInterface().getAllProjects(true, true);
            SProject project = null;
            Iterator<SProject> projectIterator = PROJECTS.iterator();
            while (projectIterator.hasNext()) {
                final SProject S_PROJECT = projectIterator.next();
                if (S_PROJECT.getName().equals(PROJECT_NAME)) {
                    project = S_PROJECT;
                    break;
                }
            }
            assert project != null;
            final long POID = project.getOid();
            SDeserializerPluginConfiguration deserializer = client.getServiceInterface().getSuggestedDeserializerForExtension("ifc", POID);
            final Path IFC_FILE = Paths.get(this.FILE);
            client.checkin(POID, "", deserializer.getOid(), false, Flow.SYNC, IFC_FILE);
            project = client.getServiceInterface().getProjectByPoid(project.getOid());
            return client.getModel(project, project.getLastRevisionId(), true, false, true);
        } catch (org.bimserver.shared.exceptions.ServerException | IOException | UserException e) {
            e.printStackTrace();
        }
        return null;
    }

```
This approach worked on 1.5.101 but sadly I cannot go back because of InvalidGuidException error

How can I solve this ?

**Comment by rubendel** [comment]
Have you updated the BimServerJava client version as well?

**Comment by Dakki97** [comment]
Do you mean the Jar file? If yes, then yes I use that one.
I also rewrote all the dependencies to 1.5.109.

**Comment by rubendel** [comment]
1.5.101 is not released yet. The error has nothing to do with checkin in (since it's happening in getModel, which happens _after_ checkin). Are the binary serializer also updated to the latest version?

**Comment by Dakki97** [comment]
I deleted the home folder,  so that I can reinstall everything twice and there i successfully installed all plugins including the BinarySerializer

**Comment by Dakki97** [comment]
It still throws geometry errors
