### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by navneetccna** [opensourceBIM/BIMserver#85]
I am trying to checkin a file and getting this error

t org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
07-04-2014 16:47:33 ERROR org.bimserver.webservices.impl.ServiceImpl - 
java.lang.OutOfMemoryError: GC overhead limit exceeded
    at java.util.Arrays.copyOfRange(Arrays.java:2694)
    at java.lang.String.<init>(String.java:203)
    at java.lang.String.substring(String.java:1877)
    at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.readList(IfcStepDeserializer.java:467)
    at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.processRecord(IfcStepDeserializer.java:416)
    at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.processLine(IfcStepDeserializer.java:251)
    at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.read(IfcStepDeserializer.java:166)
    at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.read(IfcStepDeserializer.java:142)
    at org.bimserver.webservices.impl.ServiceImpl.checkin(ServiceImpl.java:220)
    at org.bimserver.servlets.UploadServlet.service(UploadServlet.java:145)
    at org.bimserver.servlets.RootServlet.service(RootServlet.java:98)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:564)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:446)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:445)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:269)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
    at java.lang.Thread.run(Thread.java:744)

**Comment by sanjeevghimire** [comment]
Question: whats the memory required for uploading and viewing 500mb of IFC file?

**Comment by coryasilva** [comment]
I have had success with giving bimserver a 16GB heap.

**Comment by rubendel** [comment]
It depends on the IFC file and how many triangles it's geometry generate.
