### ISSUE TITLE
Errors importing IFC4 models

### ISSUE THREAD

**Issue by RyanHow** [opensourceBIM/BIMserver#852]
Hi,

I've been having trouble importing IFC4 models.

I'm getting the following error on check-in.

I'm using BIM Server v109. I've also tried v100 with the same error.

The files are opening fine in other viewers.

Any help would be appreciated.

Thanks!

```
16:12:32 ERROR [LongStreamingCheckinAction]:                                                                                  (LongAction.java:189) 
org.bimserver.shared.exceptions.UserException: Error on line 3560: Field not found: ListAsString
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:400)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:84)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:734)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:711)
	at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:66)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.bimserver.plugins.deserializers.DeserializeException: Error on line 3560: Field not found: ListAsString
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.readList(IfcStepStreamingDeserializer.java:455)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.readList(IfcStepStreamingDeserializer.java:490)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processRecord(IfcStepStreamingDeserializer.java:387)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processLine(IfcStepStreamingDeserializer.java:252)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:187)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:169)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:196)
	... 6 common frames omitted
```

**Comment by rubendel** [comment]
Can you share the IFC file or a similar one that results in the same error message?

**Comment by RyanHow** [comment]
Sure. Have you got a private channel I can send it on?

**Comment by rubendel** [comment]
ruben@logic-labs.nl

**Comment by RyanHow** [comment]
Thanks. I've emailed a file.

**Comment by RyanHow** [comment]
Thank you so much :)
