### ISSUE TITLE
error installing ifc plugins

### ISSUE THREAD

**Issue by epeter-** [opensourceBIM/BIMserver#856]
during installation i receive following error message:
error valid for both linux and windows10 release 108 and 109 but working with 111
this is a new error raised with the release of 111. before (2 days ago) installation was possible.

Installing ifcplugins...
org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.ifc.step.deserializer.Ifc4StepDeserializerPlugin' not found

Setup aborted

startuplog:
19:08:31 ERROR [PluginInterface.installPluginBundle]:                                                                                  (PluginManager.java:1416) 
org.bimserver.shared.exceptions.PluginException: org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.ifc.step.deserializer.Ifc4StepDeserializerPlugin' not found
	at org.bimserver.plugins.PluginManager.loadPluginsFromJar(PluginManager.java:778)
	at org.bimserver.plugins.PluginManager.loadPlugin(PluginManager.java:1394)
	at org.bimserver.plugins.PluginManager.install(PluginManager.java:1524)
	at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPluginBundle.java:73)
	at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPluginBundle.java:35)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:734)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:726)
	at org.bimserver.webservices.impl.PluginServiceImpl.installPluginBundle(PluginServiceImpl.java:1476)
	at org.bimserver.generated.PluginInterfaceReflector1.callMethod(PluginInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:154)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:70)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.ifc.step.deserializer.Ifc4StepDeserializerPlugin' not found
	at org.bimserver.plugins.PluginManager.loadPlugins(PluginManager.java:609)
	at org.bimserver.plugins.PluginManager.loadPluginsFromJar(PluginManager.java:768)
	... 47 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/bimserver/plugins/deserializers/IfcSchemaDeterminer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at org.bimserver.plugins.classloaders.FileJarClassLoader.findClass(FileJarClassLoader.java:184)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at org.bimserver.plugins.classloaders.FileJarClassLoader.findClass(FileJarClassLoader.java:184)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.bimserver.plugins.PluginManager.loadPlugins(PluginManager.java:605)
	... 48 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.bimserver.plugins.deserializers.IfcSchemaDeterminer
	at org.bimserver.plugins.classloaders.FileJarClassLoader.findClass(FileJarClassLoader.java:175)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 61 common frames omitted
19:08:31 ERROR [PluginInterface.installPluginBundle]:                                                                                  (InstallPluginBundle.java:75) 
org.bimserver.shared.exceptions.PluginException: org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.ifc.step.deserializer.Ifc4StepDeserializerPlugin' not found
	at org.bimserver.plugins.PluginManager.loadPluginsFromJar(PluginManager.java:778)
	at org.bimserver.plugins.PluginManager.loadPlugin(PluginManager.java:1394)
	at org.bimserver.plugins.PluginManager.install(PluginManager.java:1524)
	at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPluginBundle.java:73)
	at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPluginBundle.java:35)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:734)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:726)
	at org.bimserver.webservices.impl.PluginServiceImpl.installPluginBundle(PluginServiceImpl.java:1476)
	at org.bimserver.generated.PluginInterfaceReflector1.callMethod(PluginInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:154)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:70)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.ifc.step.deserializer.Ifc4StepDeserializerPlugin' not found
	at org.bimserver.plugins.PluginManager.loadPlugins(PluginManager.java:609)
	at org.bimserver.plugins.PluginManager.loadPluginsFromJar(PluginManager.java:768)
	... 47 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/bimserver/plugins/deserializers/IfcSchemaDeterminer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at org.bimserver.plugins.classloaders.FileJarClassLoader.findClass(FileJarClassLoader.java:184)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at org.bimserver.plugins.classloaders.FileJarClassLoader.findClass(FileJarClassLoader.java:184)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.bimserver.plugins.PluginManager.loadPlugins(PluginManager.java:605)
	... 48 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.bimserver.plugins.deserializers.IfcSchemaDeterminer
	at org.bimserver.plugins.classloaders.FileJarClassLoader.findClass(FileJarClassLoader.java:175)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 61 common frames omitted

**Comment by rubendel** [comment]
Can you please clarify the following two sentences:

> error valid for both linux and windows10 release 108 and 109 but working with 111
> this is a new error raised with the release of 111. before (2 days ago) installation was possible.

They seem contradictory to me.

If what you are saying is this:
When I try to install 108 or 109 "today" (e.a. not when they were released), I get this error. This I would expect because the `IfcSchemaDeterminer` class was only introduced in 1.5.111, hence the `java.lang.ClassNotFoundException: org.bimserver.plugins.deserializers.IfcSchemaDeterminer`.

Also all releases before 1.5.111 try to simply install the latest version of all plugins, which would then lead to exactly these types of errors. This has actually been fixed in 1.5.111, this version will only install plugins that are built specifically for that version, see also: https://github.com/opensourceBIM/BIMserver/wiki/Plugin-problems

**Comment by shubhambansal500** [comment]
somehow i got this same issue in 1.5.109 but later when i updated to 1.5.111 the issue seems to be resolved

**Comment by sellingsolutions** [comment]
I'm getting a similar issue in **1.5.113**

`org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.ifc.step.deserializer.Ifc4StepDeserializerPlugin' not found
		Setup aborted`

**Comment by rubendel** [comment]
@sellingsolutions  Is this a clean install?

**Comment by sellingsolutions** [comment]
False alarm! I copy pasted the wrong link it was actually an older version. My bad.

**Comment by sellingsolutions** [comment]
What does it mean that no plugin bundle was found? Seems like quite a few plugins weren't installed?

`Installing plugins...
		Installing bimsurfer...
		No plugin bundle available for your version of BIMserver: org.opensourcebim.bimsurfer

		Installing bimviews...
		No plugin bundle available for your version of BIMserver: org.opensourcebim.bimviews

		Installing ifcopenshellplugin...
		Successfully installed IfcOpenShellPlugin (org.opensourcebim:ifcopenshellplugin:0.5.35)

		Installing ifcplugins...
		Successfully installed IfcPlugins (org.opensourcebim:ifcplugins:0.0.41)

		Installing binaryserializers...
		Successfully installed BinarySerializers (org.opensourcebim:binaryserializers:0.0.41)

		Installing bimserverapi...
		No plugin bundle available for your version of BIMserver: org.opensourcebim.bimserverapi

		Installing console...
		Successfully installed Console (org.opensourcebim:console:0.0.16)

		Installing gltf...
		No plugin bundle available for your version of BIMserver: org.opensourcebim.gltf

		Installing mergers...
		Successfully installed Mergers (org.opensourcebim:mergers:0.0.17)

		All remote plugins successfully installed`
