### ISSUE TITLE
Running Jar on Ubuntu 18.04

### ISSUE THREAD

**Issue by pierrejoye** [opensourceBIM/BIMserver#899]
The following error happens while running java -jar bimserver-1.5.117.jar 
``` 
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.bimserver.starter.Starter.<init>(Starter.java:68)
	at org.bimserver.starter.Starter.main(Starter.java:85)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 2 more
``` 
java version on 18.04:
```openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
```

Is it known? Or do I need another Java version?

**Comment by rubendel** [comment]
You need Java 8, Java > 8 is not supported currently

**Comment by pierrejoye** [comment]
ah ok. My mistake. Thanks :)
