### ISSUE TITLE
standalone jar not starting on Java 9+

### ISSUE THREAD

**Issue by jakob-beetz** [opensourceBIM/BIMserver#909]
the required `java.xml.bind` is disabled in JRE 9 by default 
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j 

to successfully start the standalone .jar I had to manually reenable it via the command line calling 

`java --add-modules java.xml.bind -jar "bimserverjar-1.5.120.jar"

an elegant solution without a startup script seems to come only from JRE 11 onwards.

added a small paragraph with the workaround on the installation wiki 

EDIT: Ok, there seems to be much more going on in the dependency breaking department when tryting to run on Java >8:

> 
<pre>
java.lang.NoClassDefFoundError: javax/jws/WebService
        at org.bimserver.shared.meta.SService.<init>(SService.java:60)
        at org.bimserver.interfaces.SServiceInterfaceService.<init>(SServiceInterfaceService.java:31)
        at org.bimserver.shared.InterfaceList.createSServicesMap(InterfaceList.java:61)
        at org.bimserver.BimServer.<init>(BimServer.java:248)
        at org.bimserver.JarBimServer.start(JarBimServer.java:147)
        at org.bimserver.JarBimServer.main(JarBimServer.java:79)
Caused by: java.lang.ClassNotFoundException: javax.jws.WebService
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 6 common frames omitted
Logging to c:\bimserver\home\logs\bimserver.log
18:39:34 INFO  [main]: Unknown version                                                                  (BimServer.java:339)
18:39:34 ERROR [main]:                                                                                  (BimServer.java:631)
java.lang.NullPointerException: null
        at org.bimserver.BimServer.start(BimServer.java:343)
        at org.bimserver.JarBimServer.start(JarBimServer.java:160)
        at org.bimserver.JarBimServer.main(JarBimServer.java:79)
18:39:34 ERROR [main]:                                                                                  (BimServer.java:792)
java.lang.NullPointerException: null
        at org.bimserver.BimServer.start(BimServer.java:635)
        at org.bimserver.JarBimServer.start(JarBimServer.java:160)
        at org.bimserver.JarBimServer.main(JarBimServer.java:79)
18:39:34 ERROR [main]:                                                                                  (JarBimServer.java:163)
java.lang.NullPointerException: null
        at org.bimserver.BimServer.start(BimServer.java:793)
        at org.bimserver.JarBimServer.start(JarBimServer.java:160)
        at org.bimserver.JarBimServer.main(JarBimServer.java:79)
`
</pre>

**Comment by rubendel** [comment]
Yes I have had a look at this earlier, no easy fix so it seems, for now:
- Only Java 8 is supported
- Java 9 and 10 will be skipped (both are not supported by Oracle anymore)
- Java 11 has LTS (Long Term Support, up until 2022 I think) will be supported, either by:
  - Having 2 builds, one for Java 8, one for Java 11
  - Doing a final release of 1.5 on Java 8, and then continue development for BIMserver 1.6 only for Java 11
  - Try to find a way to do a release for that works on both Java 8 and Java 11

**Comment by rubendel** [comment]
The newest release works on Java 8 and 11 (and probably 9 and 10 too, but those have not been tested).
