### ISSUE TITLE
 ERROR org.bimserver.BimServer -  java.nio.file.FileSystemException: E:\eTASK\BIMserver\Database\plugins\org.opensourcebim.ifcopenshellplugin-0.5.38.jar: The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by stegh** [opensourceBIM/BIMserver#914]
Hello,

we've had issues with installing BIMserver on machines without internet connection, maybe it's "our fault", - I'm not sure if installing on machines without internet connection is supported by BIMserver. 
(and to be honest; we're not entirely sure if the behaviour is related to missing internet connection).

On machines **with internet connection** some downloads start after this line...

`[BimServer.java:1091] Initializing database dependant logic...`

ifcopenshellplugin is downloaded from AWS, e.g. this line:

`INFO [PluginInterface.installPluginBundle] o.i.IfcGeomServerClient [IfcGeomServerClient.java:193] Downloading from https://s3.amazonaws.com/ifcopenshell-builds/IfcGeomServer-v0.6.0-4f8b430-win64.zip`

On machines **without internet connection** we get this error:

` ERROR org.bimserver.BimServer -  java.nio.file.FileSystemException: E:\eTASK\BIMserver\Database\plugins\org.opensourcebim.ifcopenshellplugin-0.5.38.jar: The process cannot access the file because it is being used by another process.`

...here in German (and long version ;)):

`ERROR [main] o.b.BimServer [BimServer.java:1228] 
java.nio.file.FileSystemException: C:\Program Files (x86)\eTASK\BIMserver\Database\plugins\org.opensourcebim.ifcopenshellplugin-0.5.38.jar: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
	at java.nio.file.Files.delete(Unknown Source)
	at org.bimserver.plugins.PluginManager.loadPlugin(PluginManager.java:1428)
	at org.bimserver.plugins.PluginManager.loadFromPluginDir(PluginManager.java:1398)
	at org.bimserver.BimServer.initDatabaseDependantItems(BimServer.java:1226)
	at org.bimserver.BimServer.start(BimServer.java:755)
	at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:116)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4643)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5105)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1425)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1415)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:941)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1425)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1415)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:941)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:671)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:355)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:495)`

I tried to find out about the lock / sharing using https://live.sysinternals.com/Procmon.exe

Filtering PATH ends with org.opensourcebim.ifcopenshellplugin-0.5.38.jar

The error occurs at every (re)start of the BIMserver service / Tomcat service.

You can see a SHARING VIOLATION, - but I don't know why...

> --------------------------------------------------------------------------
Event Class:	File System
Operation:	CreateFile
Result:	SHARING VIOLATION
Path:	E:\eTASK\BIMserver\Database\plugins\org.opensourcebim.ifcopenshellplugin-0.5.38.jar
TID:	6464
Duration:	0.0000367
Desired Access:	Read Attributes, Delete
Disposition:	Open
Options:	Non-Directory File, Open Reparse Point
Attributes:	n/a
ShareMode:	Read, Write, Delete
AllocationSize:	n/a
--------------------------------------------------------------------------

Any help/suggestions appreciated ;)

Regards,
  Thomas

**Comment by stegh** [comment]
I guess the issue is related to the following code:

https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin/blob/master/src/org/ifcopenshell/IfcGeomServerClient.java#L156

**Comment by stegh** [comment]
To reproduce this issue on our servers I started with a new virtual machine using VM

Diesmal von Remotedesktop auf PLUTO mit VMware vSphere Client 
über PLUTO zu Server auf JUPITER: qm27159.zentrale.etask.de

Netzwerkverbindung getrennt, keine Netzwerkkarte in virtueller Maschine
mehr aktiv, dann hosts-Datei-Eintrag:

127.0.0.1 qm27159.zentrale.etask.de

Der Server hat dann gar kein Netz mehr, kein DNS, kein Internetzugriff
(und noch nicht mal eine "richtige IP-Adresse", sondern nur localhost)


Details SetupBIMserver_1.5.117.exe:
-------------------------------------------------------------------------

Hostname: bimserver-1-5-117.etask.de

Verfügbare IPs: 127.0.0.1

Zertifikat (PFX-Datei): C:\Users\Stegh\Desktop\wildcard.etask.de.pfx

Kennwort der PFX-Datei: https://pm.etask.de/neon/App.Etask/d6429cb6-6cba-45a8-b2be-0645d9476449/edit775.aspx

Standardspeicher GB: 2

Maximale Speicher GB: 8

Shutdown Port: 8105

-------------------------------------------------------------------------


Ergebnis: Verrückt, der BIMserver FUNKTIONIERT danach!!

Siehe Screenshot anbei.

Im C:\Program Files (x86)\eTASK\BIMserver\logs\bimserver.log
steht trotzdem 2x der Fehler:
java.nio.file.FileSystemException: C:\Program Files (x86)\eTASK\BIMserver\Database\plugins\org.opensourcebim.ifcopenshellplugin-0.5.38.jar: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

Das Verhalten möchte ich dann nun auf dem Live-Server von PROM
