### ISSUE TITLE
Ifc files are not checked in when a string contains text '/*'

### ISSUE THREAD

**Issue by Jo64** [opensourceBIM/BIMserver#920]
Hi,
I use Revit to model and generate the IFC file.
However, if a text property e.g. for an object model code contains the characters '/*', the exported IFC file can no longer be checked in.

The Revit IFC Export creates the lines
...
Line195 - #275= IFCPROPERTYSINGLEVALUE('Volumen',$,IFCVOLUMEMEASURE(10.8),$);
Line196 - #276= IFCPROPERTYSINGLEVALUE('Kennzeichen',$,IFCTEXT('/*'),$);
...

The characters '/*' does not need to be encoded. Everything is fine.

Now I check in the file. The IfcStepStreamingDeserializer evaluates the string incorrectly and generates an error message.

Error on line 195: IfcPropertySingleValue expects 4 fields, but less found (String index out of range: -1)

The error message in the BIMserver log file.

161483579 [pool-1-thread-46] ERROR org.bimserver.longaction.LongAction - 
org.bimserver.shared.exceptions.UserException: Error on line 195: IfcPropertySingleValue expects 4 fields, but less found (String index out of range: -1)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:426)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:85)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:735)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:712)
	at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:66)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.bimserver.plugins.deserializers.DeserializeException: Error on line 195: IfcPropertySingleValue expects 4 fields, but less found (String index out of range: -1)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processRecord(IfcStepStreamingDeserializer.java:371)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processLine(IfcStepStreamingDeserializer.java:253)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:188)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:170)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:197)
	... 10 common frames omitted
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processRecord(IfcStepStreamingDeserializer.java:363)
	... 14 common frames omitted
	
	
Can you please check this?
Thanks.

Regards,
Jo
![stringencoding](https://user-images.githubusercontent.com/16973608/52167565-2df3d480-271d-11e9-8d34-2a74f5d29a55.PNG)
[StringEncoding.zip](https://github.com/opensourceBIM/BIMserver/files/2824685/StringEncoding.zip)

**Comment by stegh** [comment]
The "real life example" that leads to this error originated in Autodesk Revit 2017, here's a screenshot:

![qm_27240_revit_screenshot_mit_fehler_verursachenden_daten](https://user-images.githubusercontent.com/545308/52232142-0be48880-28bc-11e9-8704-701446982c58.png)

Exported with https://sourceforge.net/projects/ifcexporter/files/2017/ ist looks like this in IFC:

`#6011721= IFCPROPERTYSINGLEVALUE('magiProductFamilyId',$,IFCTEXT('VSD35-*-*-AS-*-*/*X*X*/*'),$);`

This should not cause an error when checking in this file to BIMserver.

**Comment by rubendel** [comment]
This is now fixed in https://github.com/opensourceBIM/BIMserver/commit/7d7f88b08d7fea3425906929ffc2280b75a7d6e0, unit tests updated in https://github.com/opensourceBIM/IfcPlugins/commit/e09da25654b402641b32bdc55802e4da1ec4f2aa
