### ISSUE TITLE
JSON serialization of two-dimensional arrays (IfcCartesianPointList)

### ISSUE THREAD

**Issue by hlg** [opensourceBIM/BIMserver#922]
When serializing IfcCartesianPointList with the streaming Json serializer, the two-dimensional array `coordList` is not properly resolved, resulting in invalid JSON as below.

```
{"_i":340330252,"_t":"IfcCartesianPointList2D","_s":1,"_eCoordList":[[
  {"_t":"IfcLengthMeasure","_r":org.bimserver.shared.HashMapWrappedVirtualObject@5a717be2},  
  {"_t":"IfcLengthMeasure","_r":org.bimserver.shared.HashMapWrappedVirtualObject@5a717be2}
],[
  {"_t":"IfcLengthMeasure","_r":org.bimserver.shared.HashMapWrappedVirtualObject@67b70973}, 
  {"_t":"IfcLengthMeasure","_r":org.bimserver.shared.HashMapWrappedVirtualObject@5a717be2}
], ... ]}
```

Can be reproduced with [IFC4Add2TC1 slab standard case example](http://www.buildingsmart-tech.org/ifc/IFC4/Add2TC1/html/link/slab-standard-case.htm) and BIMserver 1.5.123 or 1.5.124.

Probably as a consequence, IfcCartesianPointLists do not show up in BIMvie.ws entity browser, although I had seen that working in 1.5.117, where they where serialized as 

```
{"_i":58066349,"_t":"IfcCartesianPointList2D","_s":1,"_eCoordList":[[
  {"_t":"IfcLengthMeasure","_v":0.0},
  {"_t":"IfcLengthMeasure","_v":0.0}
],[
  {"_t":"IfcLengthMeasure","_v":1000.0},
  {"_t":"IfcLengthMeasure","_v":0.0}
], ... ]}
```

That is weird, because the JSON serializers don't seem to have changed between 1.5.117 and 1.5.123.

Moreover, I would assume they should be represented as lists of lists of primitives like this?

```
{"_i":340330252,"_t":"IfcCartesianPointList2D","_s":1,"CoordList":[[0,0],[1000,0], ... ]}
```

That would be similar to IfcCartesianPoint coordinates, which are one-dimensional lists of IfcLengthMeasure and are represented in JSON without the DefinedType explicitely included.

```
{"_i":15221196075,"_t":"IfcCartesianPoint","_s":1,"Coordinates":[0.0,0.0,0.0],"CoordinatesAsString":["0.0","0.0","0.0"]}
```

Did not test how JSON deserializers handle any of these. 

Not sure if this is related: Non-streaming JSON serializer and JSON serializer with geometry provoke NPE's for this example.

```
org.bimserver.BimserverDatabaseException: java.lang.NullPointerException
	at org.bimserver.database.actions.DownloadByNewJsonQueryDatabaseAction.execute(DownloadByNewJsonQueryDatabaseAction.java:258)
	at org.bimserver.database.actions.DownloadByNewJsonQueryDatabaseAction.execute(DownloadByNewJsonQueryDatabaseAction.java:73)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:735)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:727)
	at org.bimserver.longaction.LongDownloadOrCheckoutAction.executeAction(LongDownloadOrCheckoutAction.java:120)
	at org.bimserver.longaction.LongDownloadAction.execute(LongDownloadAction.java:57)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eDerivedStructuralFeatureID(BasicEObjectImpl.java:1497)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1008)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1003)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:998)
	at org.bimserver.database.actions.DownloadByNewJsonQueryDatabaseAction.execute(DownloadByNewJsonQueryDatabaseAction.java:218)
	... 11 common frames omitted
```

**Comment by hlg** [comment]
It is now producing something  like this:

    {"_i":58066349,"_t":"IfcCartesianPointList2D","_s":1,"_eCoordList":[[
      {"_t":"IfcLengthMeasure","wrappedValue":0.0,"wrappedValueAsString":"0.0"},
      {"_t":"IfcLengthMeasure","wrappedValue":0.0,"wrappedValueAsString":"0.0"}
    ],[
      {"_t":"IfcLengthMeasure","wrappedValue":1000.0,"wrappedValueAsString":"1000.0"},
      {"_t":"IfcLengthMeasure","wrappedValue":0.0,"wrappedValueAsString":"0.0"}
    ], ... ]}

And SharedJsonDeserializer fails. Does it expect the wrapped value in a `_v` attribute?

```
Caused by: java.lang.IllegalStateException: Expected END_OBJECT but was NUMBER at line .. column .. path $.objects[0]._eCoordList[0][0].wrappedValue
	at com.google.gson.stream.JsonReader.endObject(JsonReader.java:404)
	at org.bimserver.emf.SharedJsonDeserializer.processObject(SharedJsonDeserializer.java:285)
	at org.bimserver.emf.SharedJsonDeserializer.read(SharedJsonDeserializer.java:125)
	at org.bimserver.client.ClientIfcModel.processDownload(ClientIfcModel.java:599)
	... 40 more
```
