### ISSUE TITLE
Crashes during IFC file checkin

### ISSUE THREAD

**Issue by tchegito** [opensourceBIM/BIMserver#932]
When I try to checkin a specific IFC file from BimCollab's examples (here: https://www.bimcollab.com/en/Support/Support/Downloads/Examples-templates ) I got errors.

There's 2 different cases.

1) 08_BIMcollab_Example_Ventilation.ifczip

```
org.bimserver.shared.exceptions.UserException: [08_BIMcollab_Example_Ventilation.ifczip] Error on line 7: Field OwningUser of IfcOwnerHistory cannot contain a IfcOwnerHistory/110560110
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:412)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:1)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:735)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:712)
	at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:70)
	at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.bimserver.plugins.deserializers.DeserializeException: Error on line 7: Field OwningUser of IfcOwnerHistory cannot contain a IfcOwnerHistory/110560110
	at org.bimserver.shared.WaitingListVirtualObject.updateNode(WaitingListVirtualObject.java:102)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processRecord(IfcStepStreamingDeserializer.java:440)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processLine(IfcStepStreamingDeserializer.java:256)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:191)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:155)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:195)
	... 10 common frames omitted
```

File is the one written in the stacktrace (in Design folder)

2) 05_BIMcollab_Example_Hollow_core_slabs
```
Caused by: org.bimserver.plugins.deserializers.DeserializeException: Error on line 110026: Enum type IfcSlabTypeEnum has no literal value 'FLOORING'
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.readEnum(IfcStepStreamingDeserializer.java:680)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processRecord(IfcStepStreamingDeserializer.java:394)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processLine(IfcStepStreamingDeserializer.java:256)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:191)
	at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:155)
	at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:195)
	... 10 common frames omitted
```

All the other files from the package are working well.

**Comment by hlg** [comment]
BIMserver expects valid IFC files, your example files are not.

###  08_BIMcollab_Example_Ventilation

The first attribute of `IfcOwnerHistory#OwningUser` should be of type `IfcPersonAndOrganization`. It can not refer to another instance of [IfcOwnerHistory](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcutilityresource/lexical/ifcownerhistory.htm). In the following excerpt from the example file, `#1` is faulty, while `#2` and `#273` seem ok in this regard.

    #1=IFCOWNERHISTORY(#273,#34358,$,.ADDED.,$,$,$,1389887074);
    #2=IFCOWNERHISTORY(#47134,#34358,$,.NOCHANGE.,$,$,$,1387542570);
    #273=IFCOWNERHISTORY(#47134,#34358,$,.NOCHANGE.,$,$,$,1387542567);
    #47134=IFCPERSONANDORGANIZATION(#120138,#41076,$);


###   05_BIMcollab_Example_Hollow_core_slabs

The last attribute of `IfcSlabType#PredefinedType` should be of type [IfcSlabTypeEnum](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcsharedbldgelements/lexical/ifcslabtypeenum.htm), which can not have a value of `FLOORING`. There is [IfcCoveringTypeEnum](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcproductextension/lexical/ifccoveringtypeenum.htm) where this value would be valid, but this enum is only allowed as `PredefinedType` of `IfcCovering` or `IfcCoveringType`, not of `IfcSlab` or `IfcSlabType`. These are some lines from the example file, where the first two are right, but the last two are wrong.

    #110018=IFCSLABTYPE('2bhUyBgh91BBN6kOPkKD__',#1,'Precast concrete',$,$,$,$,$,$,.FLOOR.);
    #110019=IFCSLABTYPE('2Wd6rsD2D0M8PE7P0z1mN8',#1,'Cast in place concrete',$,$,$,$,$,$,.FLOOR.);
    #110020=IFCSLABTYPE('2gV5uuA4f27PJY4pUoeElB',#1,'Precast concrete',$,$,$,$,$,$,.FLOORING.);
    #110021=IFCSLABTYPE('14zW1fu8zDJhojQWASp_7B',#1,'Cast in place concrete',$,$,$,$,$,$,.FLOORING.);

**Comment by tchegito** [comment]
Thank you for your answer. In the file, we can see that it has been generated by Solibri in 2013. We may conclude that this software wasn't able to produce valid file at this time ? I'm a little bit confused because these are examples provided by BimCollab right now.

Sorry but I'm quite new to this IFC world. Shouldn't parser be less strict to this kind of error ? I ask that because in BIMServer code, I saw that some exceptions are caught to let the process continue (EntityNotFound for example).

In any case, I can use some other files, but I was concerned of the usability of BIMServer.

**Comment by hlg** [comment]
As far as I can see, Solibri was only used to optimize the IFC file size. The algorithm mainly removes duplicates and replaces groups of duplicates by a unique version. It should not (and in my experience does not) change the validity of the files. One file seems to be generated with DDS CAD and then received some editing from SimpleBIM and the other claims to be generated with AutoCAD Architecture 2012 and processed with the EuroSTEP toolbox. Both the originating applications are certified for IFC2x3 CV export, but the subsequent processing applications are not. It is hard to tell where the invalid parts where introduced, but I would suggest to report this to BIMcollab, so that they can clean up their examples.

To which extent erroneous files or not should be tolerated, I would say most important is to not reject valid IFC files. For invalid files, as a user I would not appreciate errors to be silently swallowed, e.g. if some entities are just skipped by the parser and not end up in the database.

**Comment by rubendel** [comment]
Completely agree with @hlg. Closing this issue as these are serious problems in the IFC files that cannot be automatically resolved, in my opinion the error message is also pretty clear.
