### ISSUE TITLE
LowLevelCall getIntegerAttribute returns java.lang.NullPointerException

### ISSUE THREAD

**Issue by motjokk** [opensourceBIM/BIMserver#952]
**Description of the bug**
Bimserver 1.5.125 tosses ServerException: Unhandled exception (java.lang.NullPointerException). See the server log for more details. (JSON API)

`getIntegerAttribute `

I pass the objectId (of a column), and ask for "OverallWidth".

```
2019-03-22 09:14:11,543 ERROR [LowLevelInterface.getIntegerAttribute] o.b.w.i.GenericServiceImpl [GenericServiceImpl.java:134] 
java.lang.NullPointerException: null
2019-03-22 09:14:11,543 INFO [http-nio-8090-exec-9] o.b.JsonHandler [JsonHandler.java:84] {"request":{"interface":"LowLevelInterface","method":"getIntegerAttribute","parameters":{"attributeName":"OverallWidth","oid":2905867013,"tid":177}},"token":"1e20960002af38a00ebba14513877c67eefad78ef718001a2db42939dc7abf9889893be9714149414a319f8372740d4a"}
2019-03-22 09:14:11,543 INFO [http-nio-8090-exec-9] o.b.JsonHandler [JsonHandler.java:85] 
org.bimserver.shared.exceptions.ServerException: Unhandled exception (java.lang.NullPointerException). See the server log for more details
        at org.bimserver.webservices.impl.GenericServiceImpl.handleException(GenericServiceImpl.java:135)
        at org.bimserver.webservices.impl.LowLevelServiceImpl.getAttribute(LowLevelServiceImpl.java:546)
        at org.bimserver.webservices.impl.LowLevelServiceImpl.getIntegerAttribute(LowLevelServiceImpl.java:424)
        at org.bimserver.generated.LowLevelInterfaceReflector1.callMethod(LowLevelInterfaceReflector1.java)
        at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
        at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:160)
        at org.bimserver.JsonHandler.execute(JsonHandler.java:76)
        at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:67)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null

```

**Comment by rubendel** [comment]
Not saying the error message couldn't be clearer, but IfcColumn does not have a field called "OverallWidth"

http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcsharedbldgelements/lexical/ifccolumn.htm

**Comment by motjokk** [comment]
That was my suspicion! thank you.

**Comment by rubendel** [comment]
I'll leave this issue open, to implement a more clear error message
