### ISSUE TITLE
getStringAttribute "Type" returns not found

### ISSUE THREAD

**Issue by motjokk** [opensourceBIM/BIMserver#956]
**Description of the issue**
Requesting `getStringAttribute` "Type" on Bimserver 1.5.125 Gives "not found". Success requesting "Name" and "GlobalId". 

![image](https://user-images.githubusercontent.com/33512457/54881857-c1f83780-4e54-11e9-8b83-a343a5c0f07d.png)

```
2019-03-24 16:44:57,220 ERROR [LowLevelInterface.getStringAttribute] o.b.w.i.GenericServiceImpl [GenericServiceImpl.java:134] 
java.lang.NullPointerException: null
2019-03-24 16:44:57,221 INFO [http-nio-8080-exec-3] o.b.JsonHandler [JsonHandler.java:84] {"request":{"interface":"LowLevelInterface","method":"getStringAttribute","parameters":{"attributeName":"Type","oid":296419746,"tid":66}},"token":"7e716f4c6c09e8daaf8d3b96e84e0f88d13877745c7ff9881ce506a5e32eed3a35f66a73501cd588c017717c58198ae7"}
2019-03-24 16:44:57,221 INFO [http-nio-8080-exec-3] o.b.JsonHandler [JsonHandler.java:85] 
org.bimserver.shared.exceptions.ServerException: Unhandled exception (java.lang.NullPointerException). See the server log for more details
        at org.bimserver.webservices.impl.GenericServiceImpl.handleException(GenericServiceImpl.java:135)
        at org.bimserver.webservices.impl.LowLevelServiceImpl.getAttribute(LowLevelServiceImpl.java:546)
        at org.bimserver.webservices.impl.LowLevelServiceImpl.getStringAttribute(LowLevelServiceImpl.java:360)
        at org.bimserver.generated.LowLevelInterfaceReflector1.callMethod(LowLevelInterfaceReflector1.java)
        at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
        at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:160)
        at org.bimserver.JsonHandler.execute(JsonHandler.java:76)
        at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:67)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1463)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
```

**Comment by rubendel** [comment]
Type is not a field of IfcProject, it's just something BIMvie.ws adds to this view for convenience. Please consult the documentation more often, this can easily be found in the IFC spec.

http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifckernel/lexical/ifcproject.htm
