### ISSUE TITLE
Checkin of large IFC2x3 files taking ages or won't finish

### ISSUE THREAD

**Issue by mansch** [opensourceBIM/BIMserver#960]
BIMserver 1.5.125

We've tried to checkin (via BIMvie.ws) a large model - ifc2x3 file (Revit export) is around 347MB.
It is running for ages now on a Intel I7 with 8 threads at 3.6 GHz.
Started at Friday 12:20, the CPU usage is now, monday morning still at 75%. Additionally the server is no longer responsive but the checkin seems to be still in progress.
On sunday night (38 hours after checkin has been started) a database exception was logged. Nothing else..

A desktop viewer parses the file and renders the model in less than one minute.
We actually don't see how constructers should be able to work with BIMserver if the checkin takes that unbelievable long or is unstable.

Any recommendations?

2019-04-05 12:21:18,048 INFO [pool-1-thread-1] o.b.d.b.BerkeleyKeyValueStore [BerkeleyKeyValueStore.java:604] writes: 1000000, 1272 ms sync
2019-04-05 12:21:25,940 INFO [pool-1-thread-1] o.b.d.b.BerkeleyKeyValueStore [BerkeleyKeyValueStore.java:604] writes: 2000000, 2950 ms sync
2019-04-05 12:21:47,575 INFO [pool-1-thread-1] o.b.d.b.BerkeleyKeyValueStore [BerkeleyKeyValueStore.java:604] writes: 3000000, 5373 ms sync
2019-04-05 12:22:29,285 INFO [pool-1-thread-1] o.b.d.b.BerkeleyKeyValueStore [BerkeleyKeyValueStore.java:604] writes: 4000000, 10798 ms sync
2019-04-05 12:23:36,688 INFO [pool-1-thread-1] o.b.d.b.BerkeleyKeyValueStore [BerkeleyKeyValueStore.java:604] writes: 5000000, 10033 ms sync
2019-04-07 02:00:36,291 ERROR [GeometryRunner] o.b.g.StreamingGeometryGenerator [GeometryRunner.java:590] 
org.bimserver.database.berkeley.BimserverConcurrentModificationDatabaseException: Key exists: pid: 17, oid: 39257964, rid: 1
	at org.bimserver.database.berkeley.BerkeleyKeyValueStore.storeNoOverwrite(BerkeleyKeyValueStore.java:549)
	at org.bimserver.database.DatabaseSession.save(DatabaseSession.java:2277)
	at org.bimserver.database.DatabaseSession.save(DatabaseSession.java:2270)
	at org.bimserver.shared.HashMapVirtualObject.save(HashMapVirtualObject.java:501)
	at org.bimserver.geometry.GeometryRunner.run(GeometryRunner.java:533)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2019-04-07 05:58:38,051 INFO [pool-1-thread-1] o.b.g.StreamingGeometryGenerator [StreamingGeometryGenerator.java:588] Rendertime: 1d 59998553h, Reused (by hash):      2,88 MB, Reused (by transformation): 0 B, Reused (by mapping):     13,19 MB, Total:     30,31 MB, Final:     14,24 MB
2019-04-07 17:01:33,717 ERROR [GeometryRunner] o.b.g.StreamingGeometryGenerator [GeometryRunner.java:802] 
java.lang.IllegalArgumentException: Transaction 8565 has been closed and is no longer usable.
	at com.sleepycat.je.Transaction.getLocker(Transaction.java:864)
	at com.sleepycat.je.DbInternal.getLocker(DbInternal.java:568)
	at com.sleepycat.je.txn.LockerFactory.getWritableLocker(LockerFactory.java:113)
	at com.sleepycat.je.txn.LockerFactory.getWritableLocker(LockerFactory.java:40)
	at com.sleepycat.je.Database.put(Database.java:1564)
	at com.sleepycat.je.Database.putNoOverwrite(Database.java:1676)
	at org.bimserver.database.berkeley.BerkeleyKeyValueStore.storeNoOverwrite(BerkeleyKeyValueStore.java:539)
	at org.bimserver.database.DatabaseSession.save(DatabaseSession.java:2277)
	at org.bimserver.database.DatabaseSession.save(DatabaseSession.java:2270)
	at org.bimserver.shared.HashMapVirtualObject.save(HashMapVirtualObject.java:501)
	at org.bimserver.geometry.GeometryRunner.run(GeometryRunner.java:331)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mansch** [comment]
I cancelled the progress and found the model only partially visible via BIMvie.ws.

**Comment by mansch** [comment]
I did a complete reinstall, provided more RAM to the server and the checkin progress finished within 20 minutes, i think this will be acceptable.
