### ISSUE TITLE
Error on checkin

### ISSUE THREAD

**Issue by tchegito** [opensourceBIM/BIMserver#964]
When checkin an IFC file, I got following error:

```
org.bimserver.shared.exceptions.UserException: [175-batifile.ifc] Error on line 49433: IfcRamp expects 9 fields, but less found (String index out of range: -1)
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:395)
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:83)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:735)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:712)
        at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:70)
        at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```
Looking in the IFC, I see this around the given line:

```
#49426= IFCRELDEFINESBYPROPERTIES('2YkBzUCg5FrR41WwJ_tTly',#2,$,$,(#49339),#49422);
#49427= IFCRAMP('3JA8rwHZ95M98SPOIaVWY9',#2,'Rampe d__acc\X2\00E8\X0\s:Rampe d__acc\X2\00E8\X0\s B\X2\00E9\X0\ton - 150 mm - 5%:2127452 <Rampe d__acc\X2\00E8\X0\s:Rampe d__acc\X2\00E8\X0\s B\X2\00E9\X0\ton - 150 mm - 5%:2127452 #296658>',$,$,#49428,$,$);
#49428= IFCLOCALPLACEMENT(#66,#49429);
#49429= IFCAXIS2PLACEMENT3D(#49430,#49431,#49432);
#49430= IFCCARTESIANPOINT((0.0000000000,0.0000000000,0.0000000000));
#49431= IFCDIRECTION((0.0000000000,0.0000000000,1.000000000));
#49432= IFCDIRECTION((1.000000000,0.0000000000,0.0000000000));
#49433= IFCPROPERTYSET('14zCWJHqP3zxKSomonNI5O',#2,'Pset_RampCommon',$,(#49434,#49435));

```

I paste a big block because I'm not sure if 49433 is the real line number, or the line tagged with sharp.

The file is made with TopSolid.

**Comment by rubendel** [comment]
Assuming the file is Ifc2x3tc1.

The IFC file is invalid, IfcRamp should have 9 fields, it only has 8 in this file, basically what the error message says. By the looks of it, it is missing the last field, which is also non-optional:
```
ShapeType: IfcRampTypeEnum
```

What makes it a bit tricky to count the number of fields here is the mess called express string encoding, but I double checked and there are only 8.

Please contact your software provider and have them fix their export.

[1] http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcsharedbldgelements/lexical/ifcramp.htm

**Comment by tchegito** [comment]
Thank you for your analysis. I transmitted it to my customer, and I'll check again with an updated file, if that's possible.
