### ISSUE TITLE
BIMserver jar does not run in Azul's Zulu JVM

### ISSUE THREAD

**Issue by hlg** [opensourceBIM/BIMserver#965]
Trying to run BIMserver (latest release, 1.5.125) in [Zulu JVM](https://www.azul.com/downloads/zulu/), results in the following error thrown from the Berkeley DB:

```
java.lang.IllegalStateException: Could not access Zing management bean. Make sure -XX:+UseZingMXBeans was specified.
        at com.sleepycat.je.utilint.JVMSystemUtils.getRuntimeMaxMemory(JVMSystemUtils.java:95)
        at com.sleepycat.je.dbi.MemoryBudget.calcMaxMemory(MemoryBudget.java:765)
        at com.sleepycat.je.dbi.MemoryBudget.<init>(MemoryBudget.java:716)
        at com.sleepycat.je.dbi.EnvironmentImpl.<init>(EnvironmentImpl.java:598)
        at com.sleepycat.je.dbi.EnvironmentImpl.<init>(EnvironmentImpl.java:487)
        at com.sleepycat.je.dbi.DbEnvPool.getEnvironment(DbEnvPool.java:192)
        at com.sleepycat.je.Environment.makeEnvironmentImpl(Environment.java:267)
        at com.sleepycat.je.Environment.<init>(Environment.java:252)
        at com.sleepycat.je.Environment.<init>(Environment.java:222)
        at org.bimserver.database.berkeley.BerkeleyKeyValueStore.<init>(BerkeleyKeyValueStore.java:113)
        at org.bimserver.BimServer.start(BimServer.java:655)
        at org.bimserver.JarBimServer.start(JarBimServer.java:160)
        at org.bimserver.JarBimServer.main(JarBimServer.java:79)
Caused by: java.lang.ClassNotFoundException: com.azul.zing.management.ManagementFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.sleepycat.je.utilint.JVMSystemUtils.getRuntimeMaxMemory(JVMSystemUtils.java:81)
        ... 12 common frames omitted
```
Subsequently BIMserver reports to have successfully started, but apparently is not operational.

This seems to be due to an error reported in [Oracle's BDB JE forum](https://community.oracle.com/thread/4040318), where Zulu JVM is mistakenly recognized as Zing, because both have the same vendor identifier. The thread mentions that the fix made it into 7.6, but 7.6 was never released.

I tried to upgrade the com.sleepycat.je dependency to the latest BDB version 18.3.12 for BIMserver 1.5.117: https://github.com/hlg/BIMserver/commit/a6d3753509dfe27efd75a8ecddf3df253cb4f961. This seems to work well so far, but is not thoroughly tested. It seems that Oracle has not officially released the Java Edition for 18.1.32 and nothing for 18.3.12 at all on [their website](https://www.oracle.com/technetwork/database/database-technologies/berkeleydb/downloads/index.html), but there is an [18.3.12 artifact in Maven central](https://search.maven.org/artifact/com.sleepycat/je). Is this a deal-breaker for the dependency upgrade?

**Comment by rubendel** [comment]
Berkeley DB and Berkeley BD Java edition are not related, except that their names look alike. Linked maven artifact must be a mistake (https://search.maven.org/artifact/com.sleepycat/je/18.3.12/jar).

I just updated BIMserver to use 7.5.11 (latest release) instead of 7.4.5, maybe that helps. The only other thing we can do is wait for 7.6 to be released.

It's kind of a difficult situation because Oracle has changed licensing, pushing people to use Azul, but then there is this bug where it doesn't run on Azul. Looks like we might need to look for another key/value store anyways.

**Comment by hlg** [comment]
Thanks for clarifying the independence of the two Berkeley DB "editions". Very confusing otherwise.

I just checked the 7.5.11 sources and the respective change is in fact already in that release.
Will try to run BIMserver with this dependency in Zulu and close this issue if successful.

With regard to further updates: Oracle's communication [about that](https://community.oracle.com/thread/4187428) does not look very promising.

**Comment by rubendel** [comment]
Good that the fix is in that release, I am planning to do another release of BIMserver this week.

That indeed does not look very promising. I haven't found an open source database that can replace BDB, any suggestions are welcome.
