### ISSUE TITLE
Enum type IfcBuildingElementProxyTypeEnum has no literal value 'FLOOR'

### ISSUE THREAD

**Issue by noblej** [opensourceBIM/BIMserver#967]
Hi ,
i have this issue when checkin ifc (IFC2X3) in on Bimserver 125 running an o CentOS7 Server. The same 

2019-04-18 15:39:38,089 ERROR [pool-1-thread-1] o.b.l.LongAction [LongAction.java:194]
org.bimserver.shared.exceptions.UserException: [8454145.ifc] Error on line 153829: Enum type IfcBuildingElementProxyTypeEnum has no literal value 'FLOOR'
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:411)
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:83)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:735)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:712)
        at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:70)
        at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.bimserver.plugins.deserializers.DeserializeException: Error on line 153829: Enum type IfcBuildingElementProxyTypeEnum has no literal value 'FLOOR'
        at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.readEnum(IfcStepStreamingDeserializer.java:680)
        at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processRecord(IfcStepStreamingDeserializer.java:394)
        at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.processLine(IfcStepStreamingDeserializer.java:256)
        at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:191)
        at org.bimserver.ifc.step.deserializer.IfcStepStreamingDeserializer.read(IfcStepStreamingDeserializer.java:173)
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:195)
        ... 10 common frames omitted
2019-04-18 16:42:57,389 ERROR [pool-1-thread-4] o.b.l.LongAction [LongAction.java:194]
org.bimserver.shared.exceptions.UserException: [LOUVRES_POC_PRO_AB_ARC+GOE_R19.ifc] Error on line 23: IFC2X3 is not supported by this deserializer (IFC4 is)
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:411)
        at org.bimserver.database.actions.StreamingCheckinDatabaseAction.execute(StreamingCheckinDatabaseAction.java:83)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:735)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:712)
        at org.bimserver.longaction.LongStreamingCheckinAction.execute(LongStreamingCheckinAction.java:70)
        at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748

thanks for your help

**Comment by hlg** [comment]
The error message tells you that your IFC file is invalid. It contains values that are not allowed in that place - here the value `FLOOR`, where only values of `IfcBuildingElementProxyTypeEnum` would be acceptable. Please note the list of enums (and their values) for [IFC2x3](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/alphabeticalorder_enumtype.htm) and for [IFC4](http://www.buildingsmart-tech.org/ifc/IFC4/Add2TC1/html/link/alphabeticalorder-enumeration-types.htm).

This has been asked [a couple of times](https://github.com/opensourceBIM/BIMserver/search?q=has+no+literal+value&type=Issues) already. In the future, please check whether your issue is already covered before opening a new one.
