### ISSUE TITLE
can't access bimserver installation page

### ISSUE THREAD

**Issue by davidaj90** [opensourceBIM/BIMserver#970]
I have installed BIM server via WAR file. I have Ubuntu 18.04.2 and Apache Tomcat 9. I have followed the instructions  on this page:
https://fumblehool.wordpress.com/2017/06/17/install-bim-server-on-ubuntu-server/
I have successfully unpacked the WAR file. But when I go to my web browser and type http://myipaddress:8080 it shows me Tomcat home page, and not bimserver installation page, can someone help me please?

**Comment by motjokk** [comment]
Please share your catalina.out and bimserver.log output.

**Comment by davidaj90** [comment]
root@cloud03:~# cat /opt/tomcat/logs/catalina.out | tail -n 50
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)

10:55:03.958 [main] INFO org.bimserver.servlets.websockets.jsr356.Jsr356Impl - WebSocket context initialized
24-Apr-2019 10:55:03.959 GRAVE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
24-Apr-2019 10:55:03.960 GRAVE [main] org.apache.catalina.core.StandardContext.startInternal Falló en arranque del Contexto [] debido a errores previos
10:55:03.966 [main] INFO org.bimserver.servlets.websockets.jsr356.Jsr356Impl - WebSocket context destroyed
10:55:03.966 [main] INFO org.bimserver.BimServer - Stopping BIMserver
24-Apr-2019 10:55:03.967 GRAVE [main] org.apache.catalina.core.StandardContext.listenerStop Excepción enviando evento de contexto destruído a instancia de escuchador de clase [org.bimserver.web.WarServerInitializer]
 java.lang.NullPointerException
        at org.bimserver.BimServer.stop(BimServer.java:1341)
        at org.bimserver.web.WarServerInitializer.contextDestroyed(WarServerInitializer.java:127)
        at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4729)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5388)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:187)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1377)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1367)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:902)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:831)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1377)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1367)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:902)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:423)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:932)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)

24-Apr-2019 10:55:03.984 INFORMACIÓN [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
24-Apr-2019 10:55:03.993 INFORMACIÓN [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
24-Apr-2019 10:55:03.999 INFORMACIÓN [main] org.apache.catalina.startup.Catalina.start Server startup in [5.983] milliseconds




root@cloud03:~# cat /var/bimserver/home/logs/bimserver.log | tail -n 50
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:423)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:932)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
2019-04-24 10:55:03,955 ERROR [main] o.b.BimServer [BimServer.java:758]
java.lang.NullPointerException: null
        at org.bimserver.BimServer.start(BimServer.java:619)
        at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:91)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4682)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5150)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1377)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1367)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:902)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:831)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1377)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1367)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:902)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:423)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:932)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
2019-04-24 10:55:03,958 INFO [main] o.b.s.w.j.Jsr356Impl [Jsr356Impl.java:80] WebSocket context initialized
2019-04-24 10:55:03,966 INFO [main] o.b.s.w.j.Jsr356Impl [Jsr356Impl.java:86] WebSocket context destroyed
2019-04-24 10:55:03,966 INFO [main] o.b.BimServer [BimServer.java:1315] Stopping BIMserver

**Comment by motjokk** [comment]
Try changing the port for your Bimserver in `/opt/tomcat/conf/server.xml` ie. to 8090
Also, Installing tomcat-manager might be helpful when deploying.

**Comment by davidaj90** [comment]
I changed the port number and my problem is the same: I type myipaddress:8090 and I'm redirected to Tomcat home page

**Comment by motjokk** [comment]
so you get redirected to `http://tomcat.apache.org/`?

**Comment by davidaj90** [comment]
Sorry, my bad, not Tomcat home page, I meant the page that says: If you're seeing this, you've successfully installed Tomcat. Congratulations!

**Comment by motjokk** [comment]
Have you set user tomcat to be owner of the bimserver folder?

**Comment by davidaj90** [comment]
Good morning. Yes, tomcat is the owner of the ROOT folder. I also installed Manager/Host-Manager like you suggested. When I try to deploy the WAR file from the Tomcat Manager App, it does something weird: Sometimes it gives me 403 access denied page, and at other times an err_connection_reset page (this is when I click the "deploy" button).

**Comment by davidaj90** [comment]
Also, this message:

FALLO - Falló Carga de Despliegue, Excepción: [org.apache.tomcat.util.http.fileupload.FileUploadBase$SizeLimitExceededException: the request was rejected because its size (75754588) exceeds the configured maximum (52428800)]
--

**Comment by motjokk** [comment]
Good morning, 

I install everyting via apt, and that works well. I have had the same issue, but not sure how I fixed it.  You are getting the tomcat status page because the bimserver is not running. Seems like a permission issue. Either on file level or in the configuration of tomcat.  Starting from scratch using apt would be my best suggestion. Sorry i couldn't be more helpful.

**Comment by davidaj90** [comment]
No problem, thank you anyways. You mean installing bimserver using apt-get install command? Is that possible? What is the name of the package?

**Comment by motjokk** [comment]
I install tomcat and openjdk-headless using apt-get. Bimserver is downloaded with wget as the tutorial states. If you install using apt-get everything is configured  out-of-the-box, but regardless of that, there is no need for the init.d script as I see it.

**Comment by davidaj90** [comment]
Thats exactly what I did: Install tomcat and openjdk-headless using apt-get. Bimserver downloaded with wget as the tutorial states.

When you change server.xml and put this (tutorial):

<Host name="[Domain]" appBase="/var/www/[Domain]" unpackWARs="true" autoDeploy="true" xmlValidation="false" xmlNamespaceAware="false">
    <Context path="" docBase="/var/www/[Domain]/ROOT.war">
        <Parameter name="homedir" value="/var/bimserver/home"/>
    </Context>
</Host>

[Domain] can be whatever i want it to be? or does it have to be something else?
Also, do I need to put something in Context path=""?
Thanks for your patience

**Comment by motjokk** [comment]
Domain needs to be either localhost or your ip-address (or a domain name if you have that). The word domain is used misleading I would argue. All paths needs to be valid 

docBase="/path/to/ROOT.was" and homedir value = "/path/to/ROOT"

**Comment by davidaj90** [comment]
I'm not sure if I get it. This is the exact content of the server.xml file

> 

   <Host name="domain" appBase="/var/www/domain" unpackWARs="true" autoDeploy="true" xmlValidation="false" xmlNamespaceAware="false">
    <Context path="" docBase="/var/www/domain/ROOT.war">
        <Parameter name="homedir" value="/var/bimserver/home"/>
    </Context>
</Host>
>
I just used the word "domain"

**Comment by motjokk** [comment]
Context path should be the path to your ROOT.war. IP-address should be your private (not public) address handed to you by your dhcp or simply localhost. appBase should be `/var/bimserver/home` in your case it seems.

**Comment by davidaj90** [comment]
Tried it like that but didn't fix the problem. I'll keep trying different combinations on server.xml which seems to be the problem. Thank you for your insight.

**Comment by epeter-** [comment]
i installed a bimserver just recently from war.
for the host section in server.xml you will need something like:
(localhost shall be replaced with the actual domain of your server)
(the path to the dirctory where your bimserver.war file resides as ROOT.war)

 <Host name="localhost"  appBase="/var/www/myBimServerWarDirectory"
            unpackWARs="true" autoDeploy="true">
            <Context path="" docBase="/ROOT.war">
                <Parameter name="homedir" value="/var/bimserver/home"/>
            </Context>
      </Host>     


if that is not working: on your system there will be a catalina.log file.
if tomcat is running: stop it
delete the catalina log file(s) (just to keep things simple) 
restart tomcat
and read the log. there will be an answer to your question why bimserver is not starting as expected.

keep in mind that for each tomcat application you will need a service with own port definition

**Comment by davidaj90** [comment]
Here's the  output of catalina log file:

26-Apr-2019 06:07:40.332 INFORMACIÓN [http-nio-8090-exec-5] org.apache.jasper.servlet.TldScanner.scanJars Al menos un JAR, que se ha explorado buscando TLDs, aún no contenía TLDs. Activar historial de depuración para este historiador para una completa lista de los JARs que fueron explorados y de los que nos se halló TLDs. Saltarse JARs no necesarios durante la exploración puede dar lugar a una mejora de tiempo significativa en el arranque y compilación de JSP .
Logging to /opt/tomcat/webapps/bimserverwar-1.5.76/WEB-INF/logs/bimserver.log
06:07:40 INFO  [http-nio-8090-exec-5]: Starting BIMserver                                                               (BimServer.java:230)
06:07:40 INFO  [http-nio-8090-exec-5]: Using "/opt/tomcat/webapps/bimserverwar-1.5.76/WEB-INF" as homedir               (BimServer.java:232)
06:07:40 ERROR [http-nio-8090-exec-5]:                                                                                  (BimServer.java:289)
java.lang.NoClassDefFoundError: javax/jws/WebService
        at org.bimserver.shared.meta.SService.<init>(SService.java:60)
        at org.bimserver.interfaces.SServiceInterfaceService.<init>(SServiceInterfaceService.java:31)
        at org.bimserver.shared.InterfaceList.createSServicesMap(InterfaceList.java:61)
        at org.bimserver.BimServer.<init>(BimServer.java:237)
        at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:85)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4682)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5150)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.manager.ManagerServlet.start(ManagerServlet.java:1409)
        at org.apache.catalina.manager.HTMLManagerServlet.start(HTMLManagerServlet.java:700)
        at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:223)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:136)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:607)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.jws.WebService
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1363)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1186)
        ... 38 common frames omitted
06:07:40 INFO  [http-nio-8090-exec-5]: WebSocket context initialized                                                    (Jsr356Impl.java:80)
26-Apr-2019 06:07:40.561 GRAVE [http-nio-8090-exec-5] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
26-Apr-2019 06:07:40.562 GRAVE [http-nio-8090-exec-5] org.apache.catalina.core.StandardContext.startInternal Falló en arranque del Contexto [/bimserverwar-1.5.76] debido a errores previos
06:07:40 INFO  [http-nio-8090-exec-5]: WebSocket context destroyed

**Comment by rubendel** [comment]
Make sure you are using a Java 8 VM. The next release of BIMserver also runs on Java 11.

**Comment by davidaj90** [comment]
root@cloud03:~# java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Ubuntu-3ubuntu118.04.3)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Ubuntu-3ubuntu118.04.3, mixed mode, sharing)

So should I go back to version 8?

**Comment by davidaj90** [comment]
Finally I was able to deploy the war file. In my case, the right location to do this was /var/lib/tomcat8/webapps

**Comment by davidaj90** [comment]
Now my issue is different: I cannot go beyond this setup step:

						Installing ifcplugins...
						org.bimserver.shared.exceptions.PluginException: Implementation class 'org.bimserver.ifc.step.deserializer.Ifc4StepDeserializerPlugin' not found
						Setup aborted
