### ISSUE TITLE
getEnumAttribute  gives IfcSIUnitName cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by motjokk** [opensourceBIM/BIMserver#971]
**Description**
Using JSON calls on Bimserver 1.5.125. Trying to retrieve Name attribute of IfcSIUnit with getEnumAttribute. Returns `org.bimserver.models.ifc2x3tc1.IfcSIUnitName cannot be cast to java.lang.String`

According to _console_ this should return a string. IfcSIUnitName is an enumeration and should therefore respond to the getEnumAttribute method.  

My own output:
```
Posting: { "request": { "interface": "LowLevelInterface", "method": "getEnumAttribute", "parameters": { "attributeName": "Name", "oid": 5833106, "tid": 141 } }, "token": "84e88616c753d7144420bf75d5c80761a6e5e31d6c475f560f4c21f45f563181eb9855ca047f09e35d90d72dd3fded40" }
"{\"response\":{\"exception\":{\"__type\":\"ClassCastException\",\"message\":\"org.bimserver.models.ifc2x3tc1.IfcSIUnitName cannot be cast to java.lang.String\"}}}"
```

bimserver.log
```
2019-04-24 12:58:02,093 INFO [http-nio-8090-exec-8] o.b.JsonHandler [JsonHandler.java:84] {"request":{"interface":"LowLevelInterface","method":"getEnumAttribute","parameters":{"attributeName":"Name","oid":5833106,"tid":132}},"token":"9e9148d050646dca01184aea92d6526f0eb01d8abf5fd590a7d4b7f607071d7feb9855ca047f09e35d90d72dd3fded40"}
2019-04-24 12:58:02,093 INFO [http-nio-8090-exec-8] o.b.JsonHandler [JsonHandler.java:85] 
java.lang.ClassCastException: org.bimserver.models.ifc2x3tc1.IfcSIUnitName cannot be cast to java.lang.String
        at org.bimserver.webservices.impl.LowLevelServiceImpl.getEnumAttribute(LowLevelServiceImpl.java:588)
        at org.bimserver.generated.LowLevelInterfaceReflector1.callMethod(LowLevelInterfaceReflector1.java)
        at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
        at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:160)
        at org.bimserver.JsonHandler.execute(JsonHandler.java:76)
        at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:67)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
2019-04-24 12:58:02,093 ERROR [http-nio-8090-exec-8] o.b.JsonHandler [JsonHandler.java:193] 
java.lang.ClassCastException: org.bimserver.models.ifc2x3tc1.IfcSIUnitName cannot be cast to java.lang.String
        at org.bimserver.webservices.impl.LowLevelServiceImpl.getEnumAttribute(LowLevelServiceImpl.java:588)
        at org.bimserver.generated.LowLevelInterfaceReflector1.callMethod(LowLevelInterfaceReflector1.java)
        at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
        at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:160)
        at org.bimserver.JsonHandler.execute(JsonHandler.java:76)
        at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:67)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by motjokk** [comment]
I found the bug. I was calling the wrong method.

**Comment by rubendel** [comment]
Thanks for reporting, fixed and will be in the next release.
