### ISSUE TITLE
Installation page hanging on "Loading"

### ISSUE THREAD

**Issue by davidaj90** [opensourceBIM/BIMserver#980]
I have successfully deployed the war file of bimserver v 1.5.138. Im using Ubuntu 18.04.2, Tomcat 8 and Java 8. When I start the application for the first time, it shows the message "Loading" and then never loads. Few days ago I was able to install bimserver v 1.5.125 with bimviews and bimsurfer successfully on the same computer. The following day the application stopped working (bimviews, bimsurfer and console weren't available on the home page anymore). Since then I haven't been able to install bimserver again, and I have tried several of the latest versions, I always get stucked with the "Loading" message. Any help please? Here are the contents of the logs:

root@administrador:/opt/tomcat/webapps/bimserverwar-1.5.138/WEB-INF/logs# cat bimserver.log | tail -n 50
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
        at java.lang.String.<init>(String.java:515)
        at org.bimserver.database.Registry.readString(Registry.java:135)
        at org.bimserver.database.Database.init(Database.java:147)
        ... 38 common frames omitted
2019-05-13 11:59:06,901 INFO [http-nio-8080-exec-8] o.b.s.w.j.Jsr356Impl [Jsr356Impl.java:104] WebSocket context initialized
2019-05-13 11:59:23,909 ERROR [http-nio-8080-exec-14] o.b.s.RootServlet [RootServlet.java:214]
java.lang.NullPointerException: null
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:81)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

root@administrador:/opt/tomcat/webapps/bimserverwar-1.5.138/WEB-INF/logs# cat /opt/tomcat/logs/catalina.out | tail -n 50
        at      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at      at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
        at      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
        at      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at      at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
        at      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at      at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
        at      at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at      at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
        at      at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at      at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at      at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at      at java.lang.Thread.run(Thread.java:748)
11:58:55,251 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.eclipse.jetty] to WARN
11:58:55,251 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.eclipse.jetty] to false
11:58:55,252 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[org.eclipse.jetty]
11:58:55,252 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.cxf] to ERROR
11:58:55,252 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.apache.cxf] to false
11:58:55,252 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[org.apache.cxf]
11:58:55,252 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [nl.tue.buildingsmart] to WARN
11:58:55,252 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [nl.tue.buildingsmart] to false
11:58:55,253 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[nl.tue.buildingsmart]
11:58:55,253 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.http] to WARN
11:58:55,253 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.apache.http] to false
11:58:55,253 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[org.apache.http]
11:58:55,253 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.quartz] to WARN
11:58:55,253 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.quartz] to false
11:58:55,253 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[org.quartz]
11:58:55,253 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.jcabi.github] to WARN
11:58:55,253 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [com.jcabi.github] to false
11:58:55,254 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[com.jcabi.github]
11:58:55,254 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.eclipse.aether] to WARN
11:58:55,254 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.eclipse.aether] to false
11:58:55,254 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[org.eclipse.aether]
11:58:55,254 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.ifcopenshell] to INFO
11:58:55,254 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.ifcopenshell] to false
11:58:55,254 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[org.ifcopenshell]
11:58:55,254 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.bimserver] to INFO
11:58:55,254 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.bimserver] to false
11:58:55,254 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[org.bimserver]
11:58:55,254 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
11:58:55,254 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
11:58:55,254 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
11:58:55,255 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@6486288a - Registering current configuration as safe fallback point

Logging to /opt/tomcat/webapps/bimserverwar-1.5.138/WEB-INF/logs/bimserver.log

**Comment by rubendel** [comment]
Could it be that you are using a 1.5.125 database with a 1.5.136 release? The line it's crashing on is the line where it read the BIMserver UUID, which was not available in 1.5.125.

**Comment by davidaj90** [comment]
So how do I fix that? What should I try? Sorry, I'm not a very advanced user.

**Comment by rubendel** [comment]
Just delete the home directory

**Comment by TitouanGisle** [comment]
I have the same problem as Davidaj90, on a clean install, 1.5.125 works, but all the following releases get stuck on 'loading...'
Trying to install 1.5.147 with tomcat9 on a debian9 VM, in an empty directory, here's the bimserver log.

[bimserver_1.5.147_install_logs.txt](https://github.com/opensourceBIM/BIMserver/files/3350242/bimserver_1.5.147_install_logs.txt)

The catalina.out seems fine : 
"deployment of archive [blah/blablah/BIMserver.war] finished in 30 000 ms"
[...]
"launching the server took 30 000 ms"

**Comment by rubendel** [comment]
The problem in the log file is related to a "feature" of BerkeleyDB Java Edition which BIMserver uses as it's database. The default settings require about 6GB of free disk space to be available. This actually came to my attention about a month ago when someone was running on VirtualBox, which has a default VM size of 12GB, of which usually > 6 GB is used by the OS.

See also: https://github.com/opensourceBIM/BIMserver/issues/986#issuecomment-496631599

**Comment by TitouanGisle** [comment]
Yup ! That was it for me, I needed a bigger boat !
Thanks !

**Comment by zhengling** [comment]
Maybe your browser doesn't support WebGL technology. The support of WebGL browser is shown as below:
1.Google Chrome 9+
2.Mozilla firefox 4+
3.Safari 5.1+(Only available with MacOSX)
4.Opera 12 Alpha+
I really try with this in various kinds of system environment, It's  in accordance with the actual sitaution. Hope it works for you

**Comment by hlg** [comment]
This issue seems to have been solved.
