### ISSUE TITLE
BIMserver does not start in Ubuntu on VirtualBox

### ISSUE THREAD

**Issue by rubendel** [opensourceBIM/BIMserver#986]
**Describe the bug**
```
Caused by: com.sleepycat.je.DiskLimitException: (JE 7.5.11) Disk usage is not within je.maxDisk or je.freeDisk limits and write operations are prohibited: maxDiskLimit=0 freeDiskLimit=5,368,709,120 adjustedMaxDiskLimit=0 maxDiskOverage=0 freeDiskShortage=629,911,552 diskFreeSpace=4,738,797,568 availableLogSize=-629,911,552 totalLogSize=543,290 activeLogSize=543,290 reservedLogSize=0 protectedLogSize=0 protectedLogSizeMap={}
	at com.sleepycat.je.Cursor.checkUpdatesAllowed(Cursor.java:5337)
	at com.sleepycat.je.Cursor.checkUpdatesAllowed(Cursor.java:5314)
	at com.sleepycat.je.Cursor.putInternal(Cursor.java:2410)
	at com.sleepycat.je.Cursor.putInternal(Cursor.java:830)
	at com.sleepycat.je.Database.put(Database.java:1603)
	at com.sleepycat.je.Database.put(Database.java:1656)
	at org.bimserver.database.berkeley.BerkeleyKeyValueStore.store(BerkeleyKeyValueStore.java:520)
	at org.bimserver.database.berkeley.BerkeleyKeyValueStore.store(BerkeleyKeyValueStore.java:511)
	at org.bimserver.database.Registry.save(Registry.java:72)
	at org.bimserver.database.Database.setDatabaseVersion(Database.java:406)
	at org.bimserver.database.migrations.Schema.upgradeDatabase(Schema.java:247)
```

**To Reproduce**
1. Setup Ubuntu 19.04 on Virtual Box
2. Install BIMserver (1.5.138) as WAR on Tomcat 9 (default ubuntu package)
3. Start tomcat

**Expected behavior**
BIMserver should startup correctly.

**Additional context**
The "maxDiskLimit" setting in the stacktrace seems to indicate that 0 bytes can be used for the database, I suspect this has incorrectly been set to a wrong default, which is probably specific to VirtualBox.

**Comment by rubendel** [comment]
The "problem" here is that a default VirtualBox machine gets 12GB of disk. Of that, about 6.8GB is taken up by a default Ubuntu 19.04 installation. BerkeleyDB JE has a default setting of `5368709120L` for the FREE_DISK parameter. This requires about 5GB of disk to be available, otherwise the afformentioned exception is thrown.

So we could opt to lower this limit, but I think it's actually quite safe to have a limit like this in place.

So the solution for this specific case: Create a bigger disk in VirtualBox, it can even be the (slower) dynamically sizing disk.
