### ISSUE TITLE
BIMserver version 1.5.147 can not send mail for change password ect.

### ISSUE THREAD

**Issue by ngmdat** [opensourceBIM/BIMserver#989]
hi Guys,
I got send mail error as following log, 
thanks for any advises 

`
2019-06-06 15:16:50,004 INFO [http-nio-8080-exec-4] o.b.JsonHandler [JsonHandler.java:86]
java.lang.NoSuchMethodError: com.sun.mail.util.LineOutputStream.<init>(Ljava/io/OutputStream;Z)V
        at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1631)
        at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1889)
        at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1259)
        at org.bimserver.mail.EmailMessage.send(EmailMessage.java:94)
        at org.bimserver.database.actions.RequestPasswordChangeDatabaseAction$1.execute(RequestPasswordChangeDatabaseAction.java:96)
        at org.bimserver.database.DatabaseSession.commit(DatabaseSession.java:228)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:737)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:727)
        at org.bimserver.webservices.impl.AuthServiceImpl.requestPasswordChange(AuthServiceImpl.java:111)
        at org.bimserver.generated.AuthInterfaceReflectorZyUMioRNygKz_1.callMethod(AuthInterfaceReflectorZyUMioRNygKz_1.java)
`

**Comment by rubendel** [comment]
There was a dependency error with the java mail library, this is working now, will be in the next release.
